Repository shopsys/shopsys, pull requests merged in 2018-11, with the labels that each got.

#578 [shopsys] docs: update FAQ
  docs/introduction/faq-and-common-issues.md
Labels: Documentation :book:

#566 [project-base] Set development docker build target before production and CI targets
  UPGRADE.md
  project-base/docker/php-fpm/Dockerfile
Labels: Easy Pick :baby_chick:

#563 Open Source License Acknowledgements and Third-Party Copyrights
  CONTRIBUTING.md
  README.md
  open-source-license-acknowledgements-and-third-party-copyrights.md
Labels: Documentation :book:, Status: in implementation

#602 [shopsys] Update of installation docs for production
  docs/installation/installation-using-docker-on-production-server.md
Labels: Bug, Easy Pick :baby_chick:

#620 [shopsys] generate error pages in restart_kubernetes.sh
  .ci/restart_kubernetes.sh
Labels: Bug

#628 [framework] selectboxes rollout problem for dev env
  packages/framework/src/Resources/scripts/admin/components/autocompleteSelectbox.js
  packages/framework/src/Resources/scripts/admin/components/view.js
Labels: Bug, Design & Apperance
