Repository shopsys/shopsys, pull requests merged in 2019-09, with the labels that each got.

#1382 Removed info about not extensible admin forms in docs
  docs/extensibility/framework-extensibility.md
Labels: Documentation, Easy Pick

#1368 [framework] all phing targets that should not be run in production now ask for permission if in production environment
  .ci/restart_kubernetes.sh
  docs/cookbook/jenkins-configuration.md
  docs/upgrade/UPGRADE-v9.0.0-dev.md
  packages/framework/build.xml
  project-base/app/getEnvironment.php
  project-base/kubernetes/deployments/webserver-php-fpm.yml
Labels: Status: review

#1198 [project-base] gke-cluster.tf: remove 'google_container_engine_versions' data source
  project-base/infrastructure/google-cloud/gke-cluster.tf
  upgrade/UPGRADE-v7.3.2-dev.md
Labels: Bug
