Repository shopsys/shopsys, pull requests merged in 2019-05, with the labels that each got.

#954 [framework] Current domain router match route for POST and ajax condition
  packages/framework/src/Component/Router/CurrentDomainRouter.php
  packages/framework/src/Component/Router/DomainRouterFactory.php
  packages/framework/src/Resources/config/services.yml
  packages/framework/tests/Unit/Component/Router/DomainRouterFactoryTest.php
Labels: Bug, Easy Pick :baby_chick:

#980 [project-base] ecs-fix phing target fixes result of ecs phing target
  docs/upgrade/UPGRADE-unreleased.md
  project-base/build-dev.xml
Labels: Bug

#1070 [shopsys] framework-extensibility.md: change heading
  docs/introduction/framework-extensibility.md
Labels: Easy Pick :baby_chick:

#1074 [framework] custom extension of FlysystemVolumeDriver is loaded via files instead of classmap
  composer.json
  packages/framework/composer.json
Labels: Bug
