Repository shopsys/shopsys, pull requests merged in 2019-06, with the labels that each got.

#1109 [framework] checking of order item type is fixed by using type getters
  packages/framework/src/Resources/views/Admin/Content/Order/preview.html.twig
Labels: Bug, Easy Pick :baby_chick:

#1049 prepare DI configuration for project-base like framework
  docs/upgrade/UPGRADE-unreleased.md
  project-base/src/Shopsys/ShopBundle/Component/.gitkeep
  project-base/src/Shopsys/ShopBundle/Resources/config/services.yml
  project-base/src/Shopsys/ShopBundle/Resources/config/services/twig.yml
Labels: Status: in implementation

#1124 .travis.yml: overwriting of travis user id by group id in docker-compose is fixed
  .travis.yml
Labels: Bug, Easy Pick :baby_chick:

#1120 [framework] escaping values in emails to prevent HTML injection
  docs/upgrade/UPGRADE-unreleased.md
  packages/framework/src/Model/Customer/Mail/RegistrationMail.php
  packages/framework/src/Model/Customer/Mail/ResetPasswordMail.php
  packages/framework/src/Model/Mail/Mailer.php
  packages/framework/src/Model/Order/Mail/OrderMail.php
  packages/framework/src/Model/PersonalData/Mail/PersonalDataAccessMail.php
  packages/framework/src/Model/PersonalData/Mail/PersonalDataExportMail.php
Labels: Priority :warning:, Security :skull_and_crossbones:

#1125 [framework] generating of multidomain sitemaps
  packages/framework/src/Model/Sitemap/SitemapDumper.php
Labels: Bug, Easy Pick :baby_chick:

#1042 remove unused route "front_category_panel"
  docs/upgrade/UPGRADE-unreleased.md
  project-base/src/Shopsys/ShopBundle/Resources/config/routing_front.yml
Labels: Status: in implementation
