Repository shopsys/shopsys, pull requests merged in 2020-04, with the labels that each got.

#1761 [framework] fixed parameter name in remove item from order confirm window
  packages/framework/assets/js/admin/components/OrderItems.js
Labels: Easy Pick

#1764 [shopsys] doctrine money type now requires sql comment hint
  packages/framework/src/Component/Doctrine/MoneyType.php
  project-base/config/packages/doctrine.yaml
  upgrade/UPGRADE-v9.0.0-dev.md
Labels: Bug

#1720 [framework] used methods for providing config definition classes
  packages/framework/src/Component/Domain/Config/DomainsConfigLoader.php
Labels: DX & Refactoring, Easy Pick

#1774 [shopsys] Creating instance of data object with DataFactory::createInstance() method
  docs/cookbook/adding-new-attribute-to-an-entity.md
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlDataFactory.php
  packages/framework/src/Component/UploadedFile/UploadedFileDataFactory.php
  packages/framework/src/Model/Administrator/AdministratorDataFactory.php
  packages/framework/src/Model/Administrator/Role/AdministratorRoleDataFactory.php
  packages/framework/src/Model/Advert/AdvertDataFactory.php
  packages/framework/src/Model/Article/ArticleDataFactory.php
  packages/framework/src/Model/Category/CategoryDataFactory.php
  packages/framework/src/Model/ContactForm/ContactFormSettingsDataFactory.php
  packages/framework/src/Model/Country/CountryDataFactory.php
  packages/framework/src/Model/Customer/BillingAddressDataFactory.php
  packages/framework/src/Model/Customer/CustomerDataFactory.php
  packages/framework/src/Model/Customer/DeliveryAddressDataFactory.php
  packages/framework/src/Model/Customer/User/CustomerUserDataFactory.php
  packages/framework/src/Model/Customer/User/CustomerUserRefreshTokenChainDataFactory.php
  packages/framework/src/Model/Customer/User/CustomerUserUpdateDataFactory.php
  packages/framework/src/Model/Mail/MailTemplateDataFactory.php
  packages/framework/src/Model/Order/Item/OrderItemDataFactory.php
  packages/framework/src/Model/Order/OrderDataFactory.php
  packages/framework/src/Model/Order/PromoCode/PromoCodeDataFactory.php
  packages/framework/src/Model/Order/Status/OrderStatusDataFactory.php
  packages/framework/src/Model/Payment/PaymentDataFactory.php
  packages/framework/src/Model/PersonalData/PersonalDataAccessRequestDataFactory.php
  packages/framework/src/Model/Pricing/Currency/CurrencyDataFactory.php
  packages/framework/src/Model/Pricing/Group/PricingGroupDataFactory.php
  packages/framework/src/Model/Pricing/Vat/VatDataFactory.php
  packages/framework/src/Model/Product/Availability/AvailabilityDataFactory.php
  packages/framework/src/Model/Product/Brand/BrandDataFactory.php
  packages/framework/src/Model/Product/Flag/FlagDataFactory.php
  packages/framework/src/Model/Product/Parameter/ParameterDataFactory.php
  packages/framework/src/Model/Product/Parameter/ParameterValueDataFactory.php
  packages/framework/src/Model/Product/Parameter/ProductParameterValueDataFactory.php
  packages/framework/src/Model/Product/ProductDataFactory.php
  packages/framework/src/Model/Product/Unit/UnitDataFactory.php
  packages/framework/src/Model/Script/ScriptDataFactory.php
  packages/framework/src/Model/Slider/SliderItemDataFactory.php
  packages/framework/src/Model/Transport/TransportDataFactory.php
  packages/product-feed-google/src/Model/Product/GoogleProductDomainDataFactory.php
  packages/product-feed-heureka/src/Model/HeurekaCategory/HeurekaCategoryDataFactory.php
  packages/product-feed-heureka/src/Model/Product/HeurekaProductDomainDataFactory.php
  packages/product-feed-zbozi/src/Model/Product/ZboziProductDomainDataFactory.php
  packages/read-model/src/Product/Action/ProductActionViewFactory.php
  packages/read-model/src/Product/Listed/ListedProductViewFactory.php
  project-base/src/Model/Administrator/AdministratorDataFactory.php
  project-base/src/Model/Article/ArticleDataFactory.php
  project-base/src/Model/Category/CategoryDataFactory.php
  project-base/src/Model/Customer/User/CustomerUserDataFactory.php
  project-base/src/Model/Order/Item/OrderItemDataFactory.php
  project-base/src/Model/Order/OrderDataFactory.php
  project-base/src/Model/Payment/PaymentDataFactory.php
  project-base/src/Model/Product/Brand/BrandDataFactory.php
  project-base/src/Model/Product/ProductDataFactory.php
  project-base/src/Model/Transport/TransportDataFactory.php
Labels: DX & Refactoring, Easy Pick
