Repository shopsys/shopsys, pull requests merged in 2020-09, with the labels that each got.

#2024 [shopsys] moved npm-global directory to project so it is included in volume
  .gitignore
  project-base/.gitignore
  project-base/docker/php-fpm/Dockerfile
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Bug

#2025 [shopsys] optimized monorepo docker files
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose-win.yml.dist
  docker/conf/docker-compose.yml.dist
  docker/conf/docker-sync-win.yml.dist
  docker/conf/docker-sync.yml.dist
Labels: DX & Refactoring

#2027 [shopsys] added missing upgrade notes for 1827
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Documentation

#2029 Release of version 7.3.5
  .codeac.yml
  CHANGELOG.md
  packages/form-types-bundle/composer.json
  packages/framework/composer.json
  packages/framework/src/ShopsysFrameworkBundle.php
  packages/google-cloud-bundle/composer.json
  packages/migrations/composer.json
  packages/plugin-interface/composer.json
  packages/product-feed-google/composer.json
  packages/product-feed-heureka-delivery/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-zbozi/composer.json
  packages/read-model/composer.json
  project-base/composer.json
  project-base/src/Shopsys/ShopBundle/Resources/translations/messages.cs.po
  project-base/src/Shopsys/ShopBundle/Resources/translations/messages.en.po
  upgrade/UPGRADE-v7.3.5.md
  upgrade/UPGRADE-v7.3.6-dev.md
  upgrade/upgrading-monorepo.md
Labels: SSFW 7 LTS

#2028 [shopsys] fix upgrade notes for https://github.com/shopsys/shopsys/pull/1777
  upgrade/UPGRADE-v9.0.1.md
  upgrade/UPGRADE-v9.0.2.md
Labels: Documentation

#2020 [framework] removed SliderFormType excessive ID constraint
  packages/framework/src/Form/Admin/Slider/SliderItemFormType.php
Labels: Bug

#2031 [framework] deprecated notice is triggered when deprecated method is called
  packages/framework/src/Component/Elasticsearch/IndexDefinition.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Category/CategoryRepository.php
Labels: DX & Refactoring

#2023 [project-base] filterFormMacro.html.twig: display "+" only if counts > 0
  project-base/templates/Front/Content/Product/filterFormMacro.html.twig
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Bug

#2036 [framework] move creation of FilterQuery from facade to factory
  packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
  packages/framework/src/Model/Product/Search/FilterQueryFactory.php
  upgrade/UPGRADE-v9.0.3-dev.md
Labels: DX & Refactoring

#2037 [framework] changed default locale in test to domain locale
  docs/introduction/how-to-set-up-domains-and-locales.md
  packages/framework/src/Model/Administration/AdministrationFacade.php
  packages/framework/src/Resources/config/services_test.yaml
  packages/framework/tests/Test/TestTranslatableListener.php
  project-base/config/packages/test/prezent_doctrine_translatable.yaml
  project-base/tests/App/Functional/Model/Cart/CartFacadeTest.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Bug

#2019 [frontend-api] Made functional tests independent on domain locales
  project-base/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/tests/FrontendApiBundle/Functional/Article/GetArticleTest.php
  project-base/tests/FrontendApiBundle/Functional/Article/GetArticlesTest.php
  project-base/tests/FrontendApiBundle/Functional/Category/CategoriesTest.php
  project-base/tests/FrontendApiBundle/Functional/Customer/User/CurrentCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/AbstractOrderTestCase.php
  project-base/tests/FrontendApiBundle/Functional/Order/CompanyFieldsAreValidatedTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsAreValidatedTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/FullOrderTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/GetOrdersAsAuthenticatedCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/MinimalOrderTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/MultipleProductsInOrderTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductVariantTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: DX & Refactoring

#2038 [shopsys] required symfony/http-kernel in 4.4.13 or higher due to security issue
  packages/backend-api/composer.json
  packages/form-types-bundle/composer.json
  packages/frontend-api/composer.json
  packages/google-cloud-bundle/composer.json
  packages/migrations/composer.json
  packages/product-feed-google/composer.json
  packages/product-feed-heureka-delivery/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-zbozi/composer.json
  packages/read-model/composer.json
Labels: Security

#1999 [shopsys] ReadModel for product detail
  packages/framework/src/Component/Image/ImageFacade.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/read-model/src/Brand/BrandView.php
  packages/read-model/src/Brand/BrandViewFacade.php
  packages/read-model/src/Brand/BrandViewFacadeInterface.php
  packages/read-model/src/Brand/BrandViewFactory.php
  packages/read-model/src/Image/ImageView.php
  packages/read-model/src/Image/ImageViewFacade.php
  packages/read-model/src/Image/ImageViewFacadeInterface.php
  packages/read-model/src/Image/ImageViewFactory.php
  packages/read-model/src/Parameter/ParameterView.php
  packages/read-model/src/Parameter/ParameterViewFacade.php
  packages/read-model/src/Parameter/ParameterViewFacadeInterface.php
  packages/read-model/src/Parameter/ParameterViewFactory.php
  packages/read-model/src/Product/Action/ProductActionView.php
  packages/read-model/src/Product/Action/ProductActionViewFacade.php
  packages/read-model/src/Product/Action/ProductActionViewFacadeInterface.php
  packages/read-model/src/Product/Action/ProductActionViewFactory.php
  packages/read-model/src/Product/Detail/ProductDetailView.php
  packages/read-model/src/Product/Detail/ProductDetailViewFacade.php
  packages/read-model/src/Product/Detail/ProductDetailViewFacadeInterface.php
  packages/read-model/src/Product/Detail/ProductDetailViewFactory.php
  packages/read-model/src/Product/Listed/ListedProductVariantsViewFacade.php
  packages/read-model/src/Product/Listed/ListedProductVariantsViewFacadeInterface.php
  packages/read-model/src/Product/Listed/ListedProductView.php
  packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php
  packages/read-model/src/Product/Listed/ListedProductViewFacade.php
  packages/read-model/src/Product/Listed/ListedProductViewFacadeInterface.php
  packages/read-model/src/Product/Listed/ListedProductViewFactory.php
  packages/read-model/src/Resources/config/services.yaml
  packages/read-model/src/Twig/ImageExtension.php
  packages/read-model/tests/Unit/Brand/BrandViewFacadeTest.php
  packages/read-model/tests/Unit/Brand/BrandViewFactoryTest.php
  packages/read-model/tests/Unit/Image/ImageViewFacadeTest.php
  packages/read-model/tests/Unit/Product/Detail/ProductDetailViewFactoryTest.php
  project-base/src/Controller/Front/ProductController.php
  project-base/templates/Front/Content/Product/detail.html.twig
  project-base/tests/ReadModelBundle/Functional/Image/ImageViewFacadeTest.php
  project-base/tests/ReadModelBundle/Functional/Product/Action/ProductActionViewFacadeTest.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement

#2032 [shopsys] remove FE API only dependencies from framework
  packages/framework/src/Model/Article/ArticleFacade.php
  packages/framework/src/Model/Article/ArticleRepository.php
  packages/framework/src/Model/Order/OrderFacade.php
  packages/framework/src/Model/Order/OrderRepository.php
  packages/frontend-api/src/Model/Article/ArticleFacade.php
  packages/frontend-api/src/Model/Article/ArticleRepository.php
  packages/frontend-api/src/Model/Order/OrderFacade.php
  packages/frontend-api/src/Model/Order/OrderRepository.php
  packages/frontend-api/src/Model/Resolver/Article/ArticleResolver.php
  packages/frontend-api/src/Model/Resolver/Article/ArticlesResolver.php
  packages/frontend-api/src/Model/Resolver/Order/OrderResolver.php
  packages/frontend-api/src/Model/Resolver/Order/OrdersResolver.php
Labels: DX & Refactoring

#2045 [shopsys] frontend API tests are always run on CI in monorepo
  .ci/build_kubernetes.sh
  project-base/tests/FrontendApiBundle/Functional/Image/ProductImagesTest.php
  project-base/tests/FrontendApiBundle/Functional/Payment/PaymentsTest.php
  project-base/tests/FrontendApiBundle/Functional/Transport/TransportsTest.php
  upgrade/UPGRADE-v9.0.3-dev.md
Labels: Bug

#2046 [frontend-api] pagination now works with right number of products
  packages/frontend-api/src/Model/Product/ProductFacade.php
  packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
Labels: Bug

#2040 [shopsys] Unified using ENVs
  .env
  docs/installation/application-configuration.md
  docs/introduction/setting-environment-variables.md
  project-base/.env
  project-base/.env.prod
  project-base/.env.test
  project-base/config/parameters.yaml.dist
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Documentation

#2052 [shopsys] do not require short list syntax
  packages/framework/src/Component/Paginator/QueryPaginator.php
  project-base/easy-coding-standard.yml
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Bug
