Repository shopsys/shopsys, pull requests merged in 2020-12, with the labels that each got.

#2133 [framework] Enabled caching for DomainRouter and LocalizedRouter
  packages/framework/src/Component/Router/DomainRouterFactory.php
  packages/framework/src/Component/Router/LocalizedRouterFactory.php
  packages/framework/src/Resources/config/paths.yaml
  packages/framework/src/Resources/config/services.yaml
  packages/framework/tests/Unit/Component/Router/DomainRouterFactoryTest.php
  packages/framework/tests/Unit/Component/Router/LocalizedRouterFactoryTest.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement, Performance

#2141 [project-base] added total count to frontend API connections
  docs/frontend-api/pagination.md
  project-base/config/graphql/types/Pagination/ArticleConnection.types.yaml
  project-base/config/graphql/types/Pagination/OrderConnection.types.yaml
  project-base/config/graphql/types/Pagination/ProductConnection.types.yaml
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement

#2155 [shopsys] excluded not commited files from yaml standards checks
  yaml-standards.yaml
Labels: DX & Refactoring, Easy Pick

#2145 [project-base] add ACCEPTANCE file to .gitignore
  project-base/.gitignore
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Bug

#2120 [project-base] added email length validation in SubscriptionFormType
  project-base/src/Form/Front/Newsletter/SubscriptionFormType.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Bug

#2158 [frontend-api] fixed wrong annotations of ParameterWithValues
  packages/frontend-api/src/Model/Parameter/ParameterWithValues.php
  packages/frontend-api/src/Model/Parameter/ParameterWithValuesFactory.php
Labels: DX & Refactoring

#2148 [shopsys] use DBAL native queries for DML instead of ORM Native SQL
  docs/model/introduction-to-model-architecture.md
  packages/framework/src/Component/DataFixture/AbstractNativeFixture.php
  packages/framework/src/Component/Domain/DomainDbFunctionsFacade.php
  packages/framework/src/Component/Domain/DomainUrlReplacer.php
  packages/framework/src/Component/Domain/Multidomain/MultidomainEntityDataCreator.php
  packages/framework/src/Component/Setting/SettingValueRepository.php
  packages/framework/src/Component/Translation/TranslatableEntityDataCreator.php
  packages/framework/src/Model/Cart/CartRepository.php
  packages/framework/src/Model/Localization/DbIndexesRepository.php
  packages/framework/src/Model/Product/Pricing/ProductCalculatedPriceRepository.php
  packages/framework/src/Model/Product/ProductVisibilityRepository.php
  project-base/src/DataFixtures/Demo/ImageDataFixture.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement

#2156 [shopsys] product filter in frontend API
  packages/framework/src/Migrations/Version20201120143414.php
  packages/framework/src/Model/Product/Brand/BrandFacade.php
  packages/framework/src/Model/Product/Brand/BrandRepository.php
  packages/framework/src/Model/Product/Filter/BrandFilterChoiceRepository.php
  packages/framework/src/Model/Product/Filter/FlagFilterChoiceRepository.php
  packages/framework/src/Model/Product/Filter/PriceRangeRepository.php
  packages/framework/src/Model/Product/Filter/ProductFilterConfigFactory.php
  packages/framework/src/Model/Product/Flag/Flag.php
  packages/framework/src/Model/Product/Flag/FlagData.php
  packages/framework/src/Model/Product/Flag/FlagDataFactory.php
  packages/framework/src/Model/Product/Flag/FlagFacade.php
  packages/framework/src/Model/Product/Flag/FlagRepository.php
  packages/framework/src/Model/Product/Parameter/ParameterFacade.php
  packages/framework/src/Model/Product/Parameter/ParameterRepository.php
  packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
  packages/framework/src/Model/Product/ProductRepository.php
  packages/framework/src/Model/Product/Search/FilterQueryFactory.php
  packages/framework/tests/Unit/Model/Product/Flag/FlagFacadeTest.php
  packages/frontend-api/apiary.apib
  packages/frontend-api/apiary/components/data-structures.md
  packages/frontend-api/apiary/product/index.md
  packages/frontend-api/apiary/product/methods/list-of-products.md
  packages/frontend-api/apiary/product/methods/product-filter-options.md
  packages/frontend-api/src/Component/Arguments/PaginatorArgumentsBuilder.php
  packages/frontend-api/src/Model/Product/Connection/ProductConnection.php
  packages/frontend-api/src/Model/Product/Connection/ProductConnectionFactory.php
  packages/frontend-api/src/Model/Product/Filter/BrandFilterOption.php
  packages/frontend-api/src/Model/Product/Filter/FlagFilterOption.php
  packages/frontend-api/src/Model/Product/Filter/ParameterFilterOption.php
  packages/frontend-api/src/Model/Product/Filter/ParameterValueFilterOption.php
  packages/frontend-api/src/Model/Product/Filter/ProductFilterDataMapper.php
  packages/frontend-api/src/Model/Product/Filter/ProductFilterFacade.php
  packages/frontend-api/src/Model/Product/Filter/ProductFilterNormalizer.php
  packages/frontend-api/src/Model/Product/Filter/ProductFilterOptions.php
  packages/frontend-api/src/Model/Product/Filter/ProductFilterOptionsFactory.php
  packages/frontend-api/src/Model/Product/ProductFacade.php
  packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
  packages/frontend-api/src/Resources/config/graphql-types/FlagDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductFilter/BrandFilterOptionDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductFilter/FlagFilterOptionDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductFilter/ParameterFilterDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductFilter/ParameterFilterOptionDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductFilter/ParameterValueFilterOptionDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductFilter/ProductFilterDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductFilter/ProductFilterOptionsDecorator.types.yaml
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/config/graphql/types/Pagination/ProductConnection.types.yaml
  project-base/config/graphql/types/ParameterFilter.types.yaml
  project-base/config/graphql/types/ProductFilter.types.yaml
  project-base/config/graphql/types/ProductFilter/BrandFilterOption.types.yaml
  project-base/config/graphql/types/ProductFilter/FlagFilterOption.types.yaml
  project-base/config/graphql/types/ProductFilter/ParameterFilterOption.types.yaml
  project-base/config/graphql/types/ProductFilter/ParameterValueFilterOption.types.yaml
  project-base/config/graphql/types/ProductFilter/ProductFilterOptions.types.yaml
  project-base/easy-coding-standard.yml
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsFilteringOptionsTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsFilteringTest.php
  project-base/tests/FrontendApiBundle/Test/GraphQlTestCase.php
Labels: Enhancement

#2153 [framework] refactoring of NormalizeUrlTrailingSlashSubscriber
  packages/framework/src/Component/Router/NormalizeUrlTrailingSlashSubscriber.php
  packages/framework/src/Component/String/TransformString.php
  packages/framework/tests/Unit/Component/String/TransformStringTest.php
Labels: Easy Pick, Enhancement

#2151 [shopsys] FE API returns visible category by uuid
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/frontend-api/src/Model/Resolver/Category/CategoryResolver.php
Labels: Bug, Easy Pick

#2146 [shopsys] cache friendly url slugs for generator into redis
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlCacheKeyProvider.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGenerator.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlRouterFactory.php
  project-base/config/packages/framework.yaml
  project-base/config/packages/snc_redis.yaml
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Performance

#2159 [frontend-api] Rename Mutation to MutationDecorator
  packages/frontend-api/src/Resources/config/graphql-types/MutationDecorator.types.yaml
Labels: DX & Refactoring

#2154 [frontend-api] removed deprecated use of time as integer in IAT and EXP claims
  packages/frontend-api/src/Model/Token/TokenFacade.php
Labels: DX & Refactoring

#2161 [shopsys] added upgrade notes for adding articles support in FEAPI
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Documentation, Easy Pick

#2143 [docs] grid-rendering-customization.md tweak
  docs/administration/grid-rendering-customization.md
Labels: Documentation, Easy Pick

#2163 [shopsys] added search for products and categories in frontend API
  docs/frontend-api/pagination.md
  packages/framework/src/Model/Category/CategoryRepository.php
  packages/frontend-api/apiary/category/methods/categories-search.md
  packages/frontend-api/apiary/product/methods/list-of-products.md
  packages/frontend-api/src/Component/Arguments/PaginatorArgumentsBuilder.php
  packages/frontend-api/src/Model/Category/CategoryFacade.php
  packages/frontend-api/src/Model/Category/CategoryRepository.php
  packages/frontend-api/src/Model/Product/ProductFacade.php
  packages/frontend-api/src/Model/Resolver/Category/CategoriesSearchResolver.php
  packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
  packages/frontend-api/src/Resources/config/graphql-types/Pagination/CategoryDecoratorConnection.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
  project-base/config/graphql/types/Pagination/CategoryConnection.types.yaml
  project-base/tests/FrontendApiBundle/Functional/Category/CategoriesSearchTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsFilteringTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsGraphQlTestCase.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsSearch.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement
