Repository shopsys/shopsys, pull requests merged in 2020-11, with the labels that each got.

#2087 [project-base] fix ProductRenameRedirectPreviousUrlTest when overwrite_domain_url is https
  project-base/tests/App/Functional/Controller/ProductRenameRedirectPreviousUrlTest.php
Labels: Bug

#2079 [framework] throwable is now available in logger context when a cron fails on error
  packages/framework/src/Component/Cron/CronFacade.php
Labels: Easy Pick, Enhancement

#2086 [shopsys] allow placing scripts in administration after content
  packages/framework/assets/js/admin/components/MeasuringScript.js
  packages/framework/src/Controller/Admin/ScriptController.php
  packages/framework/src/Form/Admin/Script/ScriptFormType.php
  packages/framework/src/Form/Transformers/ScriptPlacementToBooleanTransformer.php
  packages/framework/src/Model/Script/Script.php
  packages/framework/src/Model/Script/ScriptFacade.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Script/detail.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/listGrid.html.twig
  packages/framework/src/Twig/ScriptsExtension.php
  project-base/src/Controller/Front/ScriptController.php
  project-base/templates/Front/Content/Order/sent.html.twig
  project-base/templates/Front/Layout/base.html.twig
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement

#1879 [project-base] Load javascripts after content is loaded
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose-win.yml.dist
  docker/conf/docker-compose.yml.dist
  docs/introduction/running-acceptance-tests.md
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/config/services/twig.yaml
  packages/framework/src/Twig/JsFormValidatorTwigExtension.php
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose-win.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
  project-base/kubernetes/deployments/selenium-server.yml
  project-base/templates/Front/Layout/base.html.twig
  project-base/tests/App/Acceptance/acceptance/CustomerRegistrationCest.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement, Help wanted

#2099 [project-base] Improved acceptance tests
  project-base/easy-coding-standard.yml
  project-base/tests/App/Acceptance/acceptance/CartCest.php
  project-base/tests/App/Acceptance/acceptance/CustomerLoginCest.php
  project-base/tests/App/Acceptance/acceptance/CustomerRegistrationCest.php
  project-base/tests/App/Acceptance/acceptance/LoginAsCustomerCest.php
  project-base/tests/App/Acceptance/acceptance/OrderCest.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/CartPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/LayoutPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/LoginPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/OrderPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductDetailPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductFilterPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductListPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/RegistrationPage.php
  project-base/tests/App/Acceptance/acceptance/PaymentImageUploadCest.php
  project-base/tests/App/Acceptance/acceptance/ProductImageUploadCest.php
  project-base/tests/App/Acceptance/acceptance/TransportImageUploadCest.php
  project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: DX & Refactoring, Enhancement

#2084 [framework] do not run checks for cart modifications on cart delete
  packages/framework/src/Model/Cart/CartFacade.php
Labels: Bug

#2100 [framework] added support for customer user registration to Frontend API
  packages/frontend-api/apiary.apib
  packages/frontend-api/src/Model/Customer/User/CustomerUserDataFactory.php
  packages/frontend-api/src/Model/Mutation/Customer/User/CustomerUserMutation.php
  packages/frontend-api/src/Resources/config/graphql-types/Mutation.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/RegistrationDataInputDecorator.types.yaml
  project-base/config/graphql/types/RegistrationDataInput.types.yaml
  project-base/tests/FrontendApiBundle/Functional/Customer/User/RegisterTest.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement

#2112 [project-base] fixed SEO informations in categories demo data
  project-base/src/DataFixtures/Demo/CategoryDataFixture.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Bug

#2090 [shopsys] ProductDetailView provided by elasticsearch
  docs/cookbook/extending-product-list.md
  packages/framework/easy-coding-standard.yml
  packages/framework/src/Model/Product/Accessory/ProductAccessoryFacade.php
  packages/framework/src/Model/Product/Brand/BrandCachedFacade.php
  packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
  packages/framework/src/Model/Product/ProductElasticsearchProvider.php
  packages/framework/src/Model/Product/Search/FilterQuery.php
  packages/framework/src/Model/Product/Search/FilterQueryFactory.php
  packages/framework/src/Model/Product/Search/ProductElasticsearchConverter.php
  packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
  packages/framework/tests/Unit/Model/Product/Search/ProductElasticsearchConverterTest.php
  packages/read-model/easy-coding-standard.yml
  packages/read-model/src/Brand/BrandViewFactory.php
  packages/read-model/src/Parameter/ParameterViewFactory.php
  packages/read-model/src/Product/Detail/ProductDetailView.php
  packages/read-model/src/Product/Detail/ProductDetailViewElasticsearchFacade.php
  packages/read-model/src/Product/Detail/ProductDetailViewElasticsearchFactory.php
  packages/read-model/src/Product/Detail/ProductDetailViewFactory.php
  packages/read-model/src/Product/Listed/ListedProductViewFactory.php
  packages/read-model/src/Product/PriceFactory.php
  packages/read-model/tests/Unit/Product/Detail/ProductDetailViewFactoryTest.php
  project-base/config/services.yaml
  project-base/src/Controller/Front/ProductController.php
  project-base/src/Resources/definition/product/1.json
  project-base/src/Resources/definition/product/2.json
  project-base/templates/Front/Content/Product/detail.html.twig
  project-base/tests/App/Functional/Model/Product/Elasticsearch/ProductExportRepositoryTest.php
  upgrade/UPGRADE-v9.1.0-dev.md
  upgrade/upgrading-monorepo.md
Labels: Enhancement

#2080 [framework] optimization: flush the whole identity map when an order is created
  packages/framework/src/Model/Order/OrderFacade.php
Labels: Performance

#2113 [project-base] enabled logging in tests
  project-base/config/packages/test/monolog.yaml
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: DX & Refactoring

#2070 Do not use private in constraints
  packages/framework/easy-coding-standard.yml
  packages/framework/src/Form/Constraints/CountryValidator.php
  packages/framework/src/Form/Constraints/EmailValidator.php
  packages/framework/src/Form/Constraints/FileAbstractFilesystemValidator.php
  packages/framework/src/Form/Constraints/ImageAbstractFilesystemValidator.php
  packages/framework/src/Form/Constraints/NotSelectedDomainToShowValidator.php
  packages/framework/src/Form/Constraints/UniqueCollectionValidator.php
  packages/framework/src/Form/Constraints/UniqueEmailValidator.php
  packages/framework/src/Form/Constraints/UniqueSlugsOnDomainsValidator.php
Labels: DX & Refactoring

#2116 [monorepo] add frontend_api.yaml to .gitignore for monorepo
  .gitignore
Labels: DX & Refactoring

#2103 [project-base] tail logs unbuffered
  project-base/docker/php-fpm/docker-php-entrypoint
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Bug

#2104 [project-base] disable javascript validation for product filter form
  project-base/src/Form/Front/Product/ProductFilterFormType.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Performance

#2107 [shopsys] move doctrine metadata and annotations cache to file instead of redis
  packages/framework/src/Component/Doctrine/Cache/FallbackCacheFactory.php
  packages/framework/src/Resources/config/services.yaml
  project-base/config/packages/snc_redis.yaml
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Performance

#2123 [shopsys] accessories is provided by elasticsearch for ListedProductView
  packages/framework/src/Model/Product/ProductElasticsearchProvider.php
  packages/framework/src/Model/Product/Search/FilterQuery.php
  packages/framework/src/Model/Product/Search/FilterQueryFactory.php
  packages/read-model/src/Product/Detail/ProductDetailViewElasticsearchFactory.php
  packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php
Labels: DX & Refactoring

#2126 [framework] do not call unnecessary elasticsearch queries
  packages/read-model/src/Product/Detail/ProductDetailViewElasticsearchFactory.php
Labels: DX & Refactoring

#2095 [framework] Wrong annotation of return type in getFullPathsIndexedByIdsForDomain
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Category/CategoryRepository.php
Labels: DX & Refactoring, Easy Pick
