Repository shopsys/shopsys, pull requests merged in 2020-10, with the labels that each got.

#2057 [shopsys] added missing data to Product frontend API type
  packages/framework/src/Migrations/Version20200930074334.php
  packages/framework/src/Model/Product/Parameter/Parameter.php
  packages/framework/src/Model/Product/Parameter/ParameterData.php
  packages/framework/src/Model/Product/Parameter/ParameterDataFactory.php
  packages/framework/src/Model/Product/Parameter/ParameterValue.php
  packages/framework/src/Model/Product/Parameter/ParameterValueData.php
  packages/framework/src/Model/Product/Parameter/ParameterValueDataFactory.php
  packages/frontend-api/apiary.apib
  packages/frontend-api/easy-coding-standard.yml
  packages/frontend-api/src/Model/Parameter/ParameterWithValues.php
  packages/frontend-api/src/Model/Parameter/ParameterWithValuesFactory.php
  packages/frontend-api/src/Model/Product/ProductAccessoryFacade.php
  packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php
  packages/frontend-api/src/Resources/config/graphql-types/ParameterDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ParameterValueDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductDecorator.types.yaml
  project-base/config/graphql/types/Parameter.types.yaml
  project-base/config/graphql/types/ParameterValue.types.yaml
  project-base/easy-coding-standard.yml
  project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement

#2055 [shopsys] made parameters overridable by ENV variables
  .ci/build_kubernetes.sh
  composer.json
  docs/cookbook/dumping-and-importing-the-database.md
  docs/installation/application-configuration.md
  docs/installation/installation-using-docker-on-production-server.md
  docs/introduction/running-acceptance-tests.md
  packages/framework/src/Twig/MailerSettingExtension.php
  project-base/.env
  project-base/.env.test
  project-base/build/codeception.yml
  project-base/composer.json
  project-base/config/bootstrap.php
  project-base/config/parameters.yaml.dist
  project-base/config/parameters_test.yaml.dist
  project-base/kubernetes/deployments/webserver-php-fpm.yml
  project-base/src/Kernel.php
  project-base/symfony.lock
  project-base/tests/App/Acceptance/acceptance.suite.yml
  symfony.lock
  upgrade/UPGRADE-v9.1.0-dev.md
  upgrade/upgrading-monorepo.md
Labels: Enhancement, Infrastructure

#2078 [shopsys] added documentation about CORS
  docs/frontend-api/introduction-to-frontend-api.md
Labels: Documentation

#2075 [shopsys] made frontend API tests to be currency independent
  packages/frontend-api/src/Component/Price/MoneyFormatterHelper.php
  packages/frontend-api/src/Model/ScalarType/MoneyType.php
  project-base/easy-coding-standard.yml
  project-base/tests/App/Test/FunctionalTestCase.php
  project-base/tests/FrontendApiBundle/Functional/Order/AbstractOrderTestCase.php
  project-base/tests/FrontendApiBundle/Functional/Order/CompanyFieldsAreValidatedTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsAreValidatedTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/DynamicFieldsInOrderTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/FullOrderTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/GetOrderAsAuthenticatedCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/GetOrderAsUnauthenticatedCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/GetOrdersAsAuthenticatedCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/MinimalOrderTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/MultipleProductsInOrderTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/Resources/companyFieldsAreValidated.graphql
  project-base/tests/FrontendApiBundle/Functional/Order/Resources/deliveryFieldsAreValidated.graphql
  project-base/tests/FrontendApiBundle/Functional/Order/Resources/dynamicFieldsInOrder.graphql
  project-base/tests/FrontendApiBundle/Functional/Order/Resources/fullOrder.graphql
  project-base/tests/FrontendApiBundle/Functional/Order/Resources/minimalOrder.graphql
  project-base/tests/FrontendApiBundle/Functional/Payment/PaymentsTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
  project-base/tests/FrontendApiBundle/Functional/Transport/TransportsTest.php
  project-base/tests/FrontendApiBundle/Test/GraphQlTestCase.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: DX & Refactoring

#2068 [frontend-api] added resolver for adverts into FEAPI
  packages/framework/src/Migrations/Version20201009082139.php
  packages/framework/src/Model/Advert/Advert.php
  packages/framework/src/Model/Advert/AdvertData.php
  packages/frontend-api/apiary.apib
  packages/frontend-api/src/Model/Advert/AdvertFacade.php
  packages/frontend-api/src/Model/Advert/AdvertRepository.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertPositionsResolver.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertResolverMap.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertsResolver.php
  packages/frontend-api/src/Model/Resolver/Advert/TypeNotImplementedException.php
  packages/frontend-api/src/Model/Resolver/Image/ImagesResolver.php
  packages/frontend-api/src/Resources/config/graphql-types/AdvertCodeDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/AdvertDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/AdvertImageDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/AdvertPositionDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
  project-base/config/graphql/types/Advert.types.yaml
  project-base/config/graphql/types/AdvertCode.types.yaml
  project-base/config/graphql/types/AdvertImage.types.yaml
  project-base/config/graphql/types/AdvertPosition.types.yaml
  project-base/easy-coding-standard.yml
  project-base/tests/FrontendApiBundle/Functional/Advert/GetAdvertPositionsTest.php
  project-base/tests/FrontendApiBundle/Functional/Advert/GetAdvertsTest.php
  project-base/tests/FrontendApiBundle/Functional/Advert/Resources/logo.png
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Enhancement

#2064 [framework] fixed currencies menu text
  packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
Labels: Design & Apperance

#2091 [framework] fixed rendering currency symbol in admin grid
  docs/administration/grid-rendering-customization.md
  packages/framework/src/Model/Customer/User/CustomerUserRepository.php
  packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig
Labels: Bug, Design & Apperance

#2094 [project-base] fixed standards on new release of FriendsOfPHP/PHP-CS-Fixer
  project-base/src/Controller/Front/ErrorController.php
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: DX & Refactoring
