Repository shopsys/shopsys, pull requests merged in 2020-03, with the labels that each got.

#1712 fix wrong migration on database with data
  packages/framework/src/Migrations/Version20200127085928.php
Labels: Bug

#1478 [shopsys] bad constraint message for minimum password length
  packages/framework/src/Form/Admin/Administrator/AdministratorFormType.php
  packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  project-base/src/Form/Front/Customer/Password/NewPasswordFormType.php
  project-base/src/Form/Front/Customer/User/CustomerUserFormType.php
  project-base/src/Form/Front/Registration/RegistrationFormType.php
  project-base/translations/validators.cs.po
  project-base/translations/validators.en.po
  upgrade/UPGRADE-v9.0.0-dev.md
Labels: Easy Pick

#1566 [shopsys] added note about overriding templates
  docs/cookbook/modifying-a-template-in-administration.md
Labels: Documentation, Easy Pick
