Repository shopsys/shopsys, pull requests merged in 2020-02, with the labels that each got.

#1067 [project-base] unification of URL paths
  project-base/config/shopsys-routing/routing_front_cs.yml
  project-base/config/shopsys-routing/routing_front_en.yml
  upgrade/UPGRADE-v9.0.0-dev.md
Labels: Easy Pick

#1652 [framework] Padding categories by level in advanced search
  packages/framework/src/Model/AdvancedSearch/Filter/ProductCategoryFilter.php
Labels: Easy Pick

#1373 [coding-standards] force unix line endings
  packages/coding-standards/easy-coding-standard.yml
Labels: Easy Pick

#1682 [shopsys] fixed Payment and Transport tests for single domain
  project-base/tests/App/Functional/Model/Order/OrderTransportAndPaymentTest.php
  project-base/tests/App/Functional/Model/Payment/IndependentPaymentVisibilityCalculationTest.php
  project-base/tests/App/Functional/Model/Payment/PaymentDomainTest.php
  project-base/tests/App/Functional/Model/Transport/IndependentTransportVisibilityCalculationTest.php
  project-base/tests/App/Functional/Model/Transport/TransportDomainTest.php
  upgrade/UPGRADE-v9.0.0-dev.md
Labels: Bug

#1601 [shopsys] Update to Postgres 12
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose-win.yml.dist
  docker/conf/docker-compose.yml.dist
  docs/installation/application-requirements.md
  docs/installation/installation-using-docker-on-production-server.md
  open-source-license-acknowledgements-and-third-party-copyrights.md
  project-base/config/parameters_common.yml
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose-win.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
  project-base/docker/php-fpm/Dockerfile
  project-base/kubernetes/deployments/postgres.yml
  project-base/tests/App/Test/Codeception/Module/Db.php
  upgrade/UPGRADE-v9.0.0-dev.md
  upgrade/upgrading-monorepo.md
Labels: Status: in implementation

#1673 [framework] fixed editing of SliderItem's domain id
  packages/framework/src/Model/Slider/SliderItem.php
Labels: Bug, Easy Pick

#1669 [framework] Run all recalculators during deploy only if domain is created
  packages/framework/build.xml
  packages/framework/src/Command/CreateDomainsDataCommand.php
Labels: Status: in implementation

#1407 [framework] Cron overview
  docs/introduction/cron.md
  packages/framework/src/Component/Cron/Config/CronConfig.php
  packages/framework/src/Component/Cron/Config/CronModuleConfig.php
  packages/framework/src/Component/Cron/CronFacade.php
  packages/framework/src/Component/Cron/CronModule.php
  packages/framework/src/Component/Cron/CronModuleFacade.php
  packages/framework/src/Component/Cron/CronModuleRepository.php
  packages/framework/src/Controller/Admin/DefaultController.php
  packages/framework/src/DependencyInjection/Compiler/RegisterCronModulesCompilerPass.php
  packages/framework/src/Migrations/Version20190824181350.php
  packages/framework/src/Resources/config/parameters_common.yml
  packages/framework/src/Resources/config/services/cron.yml
  packages/framework/src/Resources/svg/admin/power.svg
  packages/framework/src/Resources/svg/admin/schedule.svg
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Default/cronListGrid.html.twig
  packages/framework/src/Resources/views/Admin/Content/Default/index.html.twig
  packages/product-feed-heureka/src/Resources/config/services.yml
  project-base/config/packages/security.yml
  project-base/config/services/cron.yml
  project-base/tests/App/Smoke/Http/RouteConfigCustomization.php
Labels: Enhancement, Status: in implementation

#1666 [framework] fix multiple binding js-product-visibility
  packages/framework/assets/js/admin/components/ProductVisibility.js
Labels: Easy Pick
