Repository shopsys/shopsys, pull requests merged in 2020-07, with the labels that each got.

#1904 [framework] select2 is no longer hidden under bottom bar in administration
  packages/framework/assets/js/admin/components/initSelect2.js
  packages/framework/assets/styles/admin/libs/select2/select2-custom.less
Labels: Bug, Design & Apperance

#1902 [framework] fixed undefined property userData
  packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
Labels: Easy Pick

#1862 [coding-standards] Upgrade dependency on symplify/easy-coding-standard
  composer.json
  packages/backend-api/install/config/bundles.php.patch
  packages/coding-standards/composer.json
  packages/coding-standards/easy-coding-standard.yml
  project-base/config/bundles.php
  symfony.lock
  utils/releaser/src/ReleaseWorker/AbstractCheckUncommittedChangesReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/CheckPackagesOnPackagistReleaseWorker.php
  utils/releaser/src/ReleaseWorker/Message.php
  utils/releaser/src/ReleaseWorker/Release/CheckChangelogForTodaysDateReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckNewDoctrineReleaseReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ResolveDocsTodoReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/SetFrameworkBundleVersionReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/SetMutualDependenciesToVersionReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/TestYourBranchLocallyReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateUpgradeReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ValidateConflictsInComposerJsonReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ValidateRequireFormatInComposerJsonReleaseWorker.php
Labels: Enhancement

#1908 [framework] BestsellingProductFormType now uses constant for rendering product list
  packages/framework/src/Form/Admin/BestsellingProduct/BestsellingProductFormType.php
  packages/framework/src/Model/Product/BestsellingProduct/BestsellingProductFacade.php
Labels: DX & Refactoring

#1880 [shopsys] fixed JavaScript translations generation
  packages/backend-api/install/build.xml.patch
  packages/framework/assets/js/admin/utils/Window.js
  project-base/assets/js/frontend/utils/Window.js
  project-base/build.xml
  project-base/webpack.config.js
  upgrade/UPGRADE-v9.0.1-dev.md
Labels: Bug

#1842 [project-base] Automatically delete sessions after 7 days of user inactivity
  project-base/config/packages/snc_redis.yaml
  upgrade/UPGRADE-v9.0.1-dev.md
Labels: Enhancement

#1909 [framework] fixed error 500 during logout when the user is already logged out
  packages/framework/src/Component/Error/LogoutExceptionSubscriber.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  upgrade/UPGRADE-v9.0.1-dev.md
Labels: Bug

#1896 [docs] fixed link for checking exported product in elasticsearch
  docs/model/elasticsearch.md
Labels: Easy Pick

#1582 [project-base] CartCest now uses correct translations
  project-base/tests/App/Acceptance/acceptance/CartCest.php
  upgrade/UPGRADE-v9.0.1-dev.md
Labels: Status: in implementation

#1619 [framework] production protection phing target now returns 1 on error
  packages/framework/build.xml
Labels: Status: in implementation

#1660 [framework] unification of using form data if it is object
  packages/framework/src/Controller/Admin/ArticleController.php
  packages/framework/src/Controller/Admin/CategoryController.php
  packages/framework/src/Controller/Admin/CustomerController.php
  packages/framework/src/Controller/Admin/ProductController.php
  packages/framework/src/Controller/Admin/PromoCodeController.php
  packages/framework/src/Controller/Admin/ScriptController.php
  packages/framework/src/Controller/Admin/SliderController.php
  packages/framework/src/Controller/Admin/TransportController.php
Labels: Status: in implementation

#1644 [project-base] Order can now be completed when successful flash message exists
  project-base/src/Controller/Front/OrderController.php
  upgrade/UPGRADE-v9.0.1-dev.md
Labels: Status: in implementation

#1897 [framework] updated Currency::setRoundingType() for easier extension in project-base
  packages/framework/src/Model/Pricing/Currency/Currency.php
Labels: Easy Pick

#1874 [framework] Redirect URLs with a trailing slash (code 301)
  packages/framework/src/Component/Router/NormalizeUrlTrailingSlashSubscriber.php
  packages/framework/src/Component/String/TransformString.php
Labels: Enhancement

#1918 [project-base] generate images_id_seq in data fixtures automatically
  project-base/src/DataFixtures/Demo/ImageDataFixture.php
  upgrade/UPGRADE-v9.0.2-dev.md
Labels: Enhancement

#1750 [framework] Product::setProductCategoryDomains() fix
  packages/framework/src/Model/Product/Product.php
Labels: Bug

#1947 [releaser] fixed checking builds in after-release stage
  utils/releaser/src/ReleaseWorker/AbstractCheckPackagesTravisBuildsReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/CheckPackagesTravisBuildsReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckPackagesTravisBuildsReleaseWorker.php
Labels: Enhancement

#1952 [framework] JS validation: fix creating of prototype of compound item in collection
  packages/framework/assets/js/common/validation/customizeFpValidator.js
Labels: Bug

#1957 [shopsys] update tests to use tests container to decrease amount of services defined in `services_test.yaml`
  packages/framework/src/Resources/config/services_test.yaml
  project-base/config/services_test.yaml
  project-base/tests/App/Functional/EntityExtension/EntityExtensionTest.php
  project-base/tests/App/Performance/Feed/AllFeedsTest.php
  project-base/tests/App/Performance/Page/AllPagesTest.php
  project-base/tests/App/Smoke/Http/HttpSmokeTest.php
  project-base/tests/App/Smoke/Http/RouteConfigCustomization.php
  project-base/tests/App/Test/Codeception/Helper/SymfonyHelper.php
  project-base/tests/App/Test/FunctionalTestCase.php
  upgrade/UPGRADE-v9.0.2-dev.md
Labels: DX & Refactoring

#1963 [framework] fixed multiple binding of product picker events
  packages/framework/assets/js/admin/components/ProductsPickerWindow.js
Labels: Bug

#1956 [framework] IndexExportedEvent is called after elasticsearch export cron module finished
  packages/framework/src/Component/Elasticsearch/AbstractExportChangedCronModule.php
  packages/framework/src/Model/Product/Elasticsearch/ProductExportChangedCronModule.php
Labels: Bug

#1959 [framework] ProductAvailabilityCalculation: fix property annotation
  packages/framework/src/Model/Product/Availability/ProductAvailabilityCalculation.php
Labels: DX & Refactoring

#1324 [coding-standards] easy-coding-standard.yml: declare compliance with PSR-12
  packages/coding-standards/easy-coding-standard.yml
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: DX & Refactoring

#1949 [releaser] releaser added warning when merging RC branch
  utils/releaser/src/ReleaseWorker/Release/MergeReleaseCandidateBranchReleaseWorker.php
Labels: Enhancement

#1552 [shopsys] Upgraded yaml standards package
  packages/framework/src/Resources/config/services.yaml
  packages/frontend-api/src/Resources/config/graphql-types/OrderInput/OrderProductInputDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/OrderInput/PaymentInputDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/OrderInput/TransportInputDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductPriceDecorator.types.yaml
  packages/frontend-api/src/Resources/config/services.yaml
  packages/read-model/src/Resources/config/services.yaml
  project-base/config/routes/shopsys_front.yaml
  project-base/config/services.yaml
  project-base/config/services_test.yaml
  project-base/docker/conf/docker-compose.prod.yml.dist
  project-base/docker/conf/docker-sync.yml.dist
  project-base/yaml-standards.yaml
  upgrade/UPGRADE-v9.1.0-dev.md
  yaml-standards.yaml
Labels: DX & Refactoring
