Repository shopsys/shopsys, pull requests merged in 2020-08, with the labels that each got.

#1955 [shopsys] temporary fileupload is now uploaded to abstract filesystem
  packages/framework/assets/js/admin/components/FileUpload.js
  packages/framework/easy-coding-standard.yml
  packages/framework/src/Component/FileUpload/DeleteOldUploadedFilesCronModule.php
  packages/framework/src/Component/FileUpload/FileUpload.php
  packages/framework/src/Component/Image/Processing/ImageProcessor.php
  packages/framework/src/DependencyInjection/Compiler/AddConstraintValidatorsPass.php
  packages/framework/src/Form/Constraints/FileAbstractFilesystemValidator.php
  packages/framework/src/Form/Constraints/ImageAbstractFilesystemValidator.php
  packages/framework/src/Model/Mail/MailTemplateAttachmentFilepathProvider.php
  packages/framework/src/Resources/config/directories.yaml
  packages/framework/src/Resources/config/paths.yaml
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/config/services/cron.yaml
  packages/framework/src/ShopsysFrameworkBundle.php
  packages/framework/tests/Unit/Component/Image/ImageFactoryTest.php
  project-base/config/paths.yaml
  project-base/config/services/cron.yaml
  upgrade/UPGRADE-v9.0.2-dev.md
Labels: Bug

#1961 [symfony] added phpstan-symfony extension
  build.xml
  composer.json
  packages/framework/build.xml
  phpstan.neon
  project-base/composer.json
  project-base/phpstan.neon
  project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductVariantTest.php
  symfony.lock
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: DX & Refactoring

#1823 [framework] remove final from relevant classes
  packages/framework/src/Component/Collector/ShopsysFrameworkDataCollector.php
  packages/framework/src/Component/Doctrine/MoneyType.php
  packages/framework/src/Component/Money/Exception/InvalidNumericArgumentException.php
  packages/framework/src/Component/Money/Exception/UnsupportedTypeException.php
  packages/framework/src/Component/Money/Money.php
  packages/framework/src/Form/Transformers/CopyTotalPricesOfOrderItemTransformer.php
  packages/framework/src/Form/Transformers/NumericToMoneyTransformer.php
  packages/framework/src/Migrations/Version20181114102106.php
  packages/framework/src/Migrations/Version20181114120915.php
  packages/framework/src/Migrations/Version20181114134959.php
Labels: DX & Refactoring

#1964 [shopsys] fixed filtering of products in frontend API
  packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
  packages/framework/src/Model/Product/ProductOnCurrentDomainFacade.php
  packages/framework/src/Model/Product/ProductOnCurrentDomainFacadeInterface.php
  packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
  packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
Labels: Bug

#1960 [frontend-api] Added resolvers for orders
  packages/framework/src/Model/Order/OrderFacade.php
  packages/framework/src/Model/Order/OrderRepository.php
  packages/frontend-api/apiary.apib
  packages/frontend-api/src/Model/Resolver/Order/OrderResolver.php
  packages/frontend-api/src/Model/Resolver/Order/OrdersResolver.php
  packages/frontend-api/src/Resources/config/graphql-types/Pagination/OrderDecoratorConnection.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
  project-base/config/graphql/types/Pagination/OrderConnection.types.yaml
  project-base/tests/FrontendApiBundle/Functional/Order/GetOrderAsAuthenticatedCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/GetOrderAsUnauthenticatedCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/GetOrdersAsAuthenticatedCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/GetOrdersAsUnauthenticatedCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Test/GraphQlWithLoginTestCase.php
Labels: Enhancement

#1973 [shopsys] added cron limitation documentation
  docs/introduction/cron.md
Labels: Documentation

#1974 [project-base] fixed path to tests in phpstan.neon
  project-base/phpstan.neon
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: Bug

#1969 [shopsys] ignored phpcs-cache file for git repository
  .gitignore
Labels: DX & Refactoring

#1966 [framework] fixed clearing form options in product picker
  packages/framework/src/Controller/Admin/ProductPickerController.php
  packages/framework/src/Form/ProductType.php
  packages/framework/src/Form/ProductsType.php
Labels: Bug

#1970 [project-base] fixed displaying errors in popup window
  project-base/assets/js/frontend/utils/Window.js
  project-base/assets/js/frontend/utils/showFormErrorsWindow.js
  upgrade/UPGRADE-v9.0.2-dev.md
Labels: Bug

#1777 [shopsys] ImageConfig accepts extended entities
  packages/framework/src/Component/Image/Config/ImageConfig.php
  packages/framework/src/Component/Image/Config/ImageConfigLoader.php
  packages/framework/tests/Unit/Component/Image/Config/ImageConfigLoaderTest.php
  packages/framework/tests/Unit/Component/Image/Config/ImageConfigTest.php
  packages/framework/tests/Unit/Component/Image/DirectoryStructureCreatorTest.php
  packages/framework/tests/Unit/Component/Image/ImageLocatorTest.php
  project-base/config/services_test.yaml
  project-base/tests/App/Functional/Component/Image/Config/ImageConfigTest.php
  upgrade/UPGRADE-v9.0.1.md
Labels: DX & Refactoring, Help wanted

#1975 [shopsys] fixed cron limitation documentation for version 7.3
  docs/introduction/cron.md
Labels: Documentation

#1971 [framework] fixed joining the same table with different alias
  packages/framework/src/Component/Doctrine/Exception/DuplicatedAliasException.php
  packages/framework/src/Component/Doctrine/QueryBuilderExtender.php
  packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php
Labels: Bug

#1972 [framework] fixed removing friendly urls
  packages/framework/easy-coding-standard.yml
  packages/framework/src/Model/Article/ArticleFacade.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Product/Brand/BrandFacade.php
  packages/framework/src/Model/Product/ProductFacade.php
Labels: Bug

#1658 [shopsys] coding standards for using strict comparison operators
  packages/framework/easy-coding-standard.yml
  packages/framework/src/Command/ChangeAdminPasswordCommand.php
  packages/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php
  packages/framework/src/Form/Constraints/UniqueEmailValidator.php
  packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderCityFilter.php
  packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderEmailFilter.php
  packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderLastNameFilter.php
  packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderNameFilter.php
  packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderNumberFilter.php
  packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderPhoneNumberFilter.php
  packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderPriceFilterWithVatFilter.php
  packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderStreetFilter.php
  packages/framework/src/Model/Pricing/InputPriceRecalculator.php
  packages/framework/src/Twig/NumberFormatterExtension.php
  project-base/easy-coding-standard.yml
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: DX & Refactoring, Easy Pick

#1979 [framework] spinbox plus now works correctly with min value
  project-base/assets/js/frontend/components/spinbox.js
Labels: Bug

#1967 [framework] select distinct product for vat replace
  packages/framework/src/Model/Product/ProductRepository.php
Labels: Bug

#1987 [framework] design - admin - domain switcher for more domains
  packages/framework/assets/styles/admin/components/in/domain.less
Labels: Design & Apperance

#1986 [framework] design - admin title button wrap bar only if contains buttons
  packages/framework/src/Resources/views/Admin/Content/Administrator/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Advert/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Article/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Category/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Country/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Customer/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Product/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/PromoCode/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Slider/list.html.twig
  packages/framework/src/Resources/views/Admin/Layout/layoutWithPanel.html.twig
Labels: Design & Apperance

#1989 [shopsys] required new line at the end of files
  CHANGELOG.md
  easy-coding-standard.yml
  packages/backend-api/easy-coding-standard.yml
  packages/form-types-bundle/easy-coding-standard.yml
  packages/framework/easy-coding-standard.yml
  packages/framework/src/Model/Product/Product.php
  packages/frontend-api/easy-coding-standard.yml
  packages/frontend-api/src/Model/Resolver/Order/OrderResolver.php
  packages/frontend-api/src/Model/User/FrontendApiUserFactoryInterface.php
  packages/google-cloud-bundle/easy-coding-standard.yml
  packages/http-smoke-testing/easy-coding-standard.yml
  packages/migrations/easy-coding-standard.yml
  packages/plugin-interface/easy-coding-standard.yml
  packages/product-feed-google/easy-coding-standard.yml
  packages/product-feed-heureka-delivery/easy-coding-standard.yml
  packages/product-feed-heureka/easy-coding-standard.yml
  packages/product-feed-zbozi/easy-coding-standard.yml
  packages/read-model/easy-coding-standard.yml
  project-base/.eslintrc.json
  project-base/.stylelintrc
  project-base/assets/styles/frontend/common/components/box/login.less
  project-base/assets/styles/frontend/common/components/box/promo-code.less
  project-base/assets/styles/frontend/common/components/in/disable.less
  project-base/assets/styles/frontend/common/layout/header/menu.less
  project-base/assets/styles/frontend/domain2/main.less
  project-base/assets/styles/frontend/domain2/wysiwyg.less
  project-base/easy-coding-standard.yml
  upgrade/UPGRADE-v9.1.0-dev.md
Labels: DX & Refactoring

#1977 [framework] remove customer and his addresses with customer user
  packages/framework/src/Model/Customer/Customer.php
  packages/framework/src/Model/Customer/CustomerFacade.php
  packages/framework/src/Model/Customer/CustomerRepository.php
  packages/framework/src/Model/Customer/User/CustomerUserFacade.php
  upgrade/UPGRADE-v9.0.2-dev.md
Labels: Bug

#1988 [framework] fixed stylelint phing targets
  packages/framework/build.xml
  project-base/package.json
Labels: Bug

#1985 [shopsys] redis build-version now includes application environment
  docs/introduction/console-commands-for-application-management-phing-targets.md
  packages/backend-api/install/config/parameters_common.yaml.patch
  project-base/config/packages/snc_redis.yaml
  project-base/config/parameters_common.yaml
  project-base/config/parameters_version.yaml.dist
  upgrade/UPGRADE-v9.0.2-dev.md
Labels: Bug

#1995 design - in popup window with html conntent - call registerNewContent…
  project-base/assets/js/frontend/utils/Window.js
Labels: Design & Apperance

#1994 [framework] added link into breadcrumb item in admin if uri is not null
  packages/framework/src/Resources/views/Admin/Inline/Breadcrumb/breadcrumb.html.twig
Labels: Design & Apperance

#1998 [framewok] fixed delayed javascript validators
  packages/framework/assets/js/common/validation/customizeBundle.js
Labels: Bug

#1992 [docs] updated doc for configuring new domain
  docs/introduction/how-to-set-up-domains-and-locales.md
  mkdocs.yml
Labels: Documentation

#1996 [frontend-api] added articles resolver
  packages/framework/src/Migrations/Version20200819165818.php
  packages/framework/src/Model/Article/Article.php
  packages/framework/src/Model/Article/ArticleData.php
  packages/framework/src/Model/Article/ArticleFacade.php
  packages/framework/src/Model/Article/ArticleRepository.php
  packages/frontend-api/apiary.apib
  packages/frontend-api/src/Model/Resolver/Article/ArticleResolver.php
  packages/frontend-api/src/Model/Resolver/Article/ArticlesResolver.php
  packages/frontend-api/src/Resources/config/graphql-types/ArticleDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/Pagination/ArticleDecoratorConnection.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
  project-base/config/graphql/types/Article.types.yaml
  project-base/config/graphql/types/Pagination/ArticleConnection.types.yaml
  project-base/src/DataFixtures/Demo/ArticleDataFixture.php
  project-base/tests/FrontendApiBundle/Functional/Article/GetArticleTest.php
  project-base/tests/FrontendApiBundle/Functional/Article/GetArticlesTest.php
  project-base/translations/dataFixtures.cs.po
  project-base/translations/dataFixtures.en.po
Labels: Enhancement

#2000 [shopsys] timezone for running crons
  docs/introduction/cron.md
  docs/introduction/working-with-date-time-values.md
  packages/backend-api/install/config/parameters_common.yaml.patch
  packages/framework/src/Command/CronCommand.php
  packages/framework/src/Resources/config/parameters_common.yaml
  project-base/config/parameters_common.yaml
  upgrade/UPGRADE-v9.0.2-dev.md
Labels: Bug

#2001 [framework] AbstractFileUploadType: remove fileConstraints class property
  packages/framework/src/Form/AbstractFileUploadType.php
Labels: Bug

#2003 [frontend-api] fixed checking for key existence in articles test
  project-base/tests/FrontendApiBundle/Functional/Article/GetArticlesTest.php
Labels: Bug

#2006 [framework] sellingTo is now set with the end of day time
  packages/framework/src/Controller/Admin/ProductController.php
Labels: Bug

#2004 [framework] remove space in error page filename
  packages/framework/src/Component/Error/ErrorPagesFacade.php
Labels: Bug

#2010 [framework] cart items are now correctly deleted when cart is deleted
  packages/framework/src/Migrations/Version20200828131906.php
  packages/framework/src/Model/Cart/Cart.php
  packages/framework/src/Model/Cart/Item/CartItem.php
Labels: Bug

#1951 [framework] new phing target for changing environment
  docs/introduction/console-commands-for-application-management-phing-targets.md
  packages/framework/build.xml
Labels: DX & Refactoring

#2002 [frontend-api] Added special article resolvers
  packages/frontend-api/apiary.apib
  packages/frontend-api/src/Model/Resolver/Article/ArticleResolver.php
  packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
  project-base/tests/FrontendApiBundle/Functional/Article/GetArticleTest.php
Labels: Enhancement
