Repository shopsys/shopsys, pull requests merged in 2020-06, with the labels that each got.

#1713 [docs] Fixed installation docs for Windows 10 via Docker
  docs/installation/installation-using-docker-windows-10-pro-higher.md
Labels: Status: in implementation

#1885 [framework] fixed calculate availability for new product
  packages/framework/src/Model/Product/Availability/ProductAvailabilityCalculation.php
Labels: Bug

#1906 [project-base] windowForm: fix initialization of JS validation
  project-base/templates/Front/Content/Login/windowForm.html.twig
  upgrade/UPGRADE-v9.0.1-dev.md
Labels: Bug

#1905 [framework] new entity extensions are now registered immediately
  packages/framework/src/ShopsysFrameworkBundle.php
Labels: Bug, DX & Refactoring, Easy Pick

#1888 [docs] updated deprecated uses in a cookbook
  docs/cookbook/adding-a-new-administration-page.md
  docs/cookbook/create-advanced-grid.md
  docs/cookbook/create-basic-grid.md
Labels: Documentation

#1861 [project-base] Added extra_host for missing elasticsearch in production docker-compose.yml file
  project-base/docker/conf/docker-compose.prod.yml.dist
  upgrade/UPGRADE-v9.0.1-dev.md
Labels: Enhancement
