Repository shopsys/shopsys, pull requests merged in 2021-04, with the labels that each got.

#2287 [product-feed-heureka] ignored errors reported by new squizlabs/php_codesniffer version 3.6.0
  packages/product-feed-heureka/easy-coding-standard.yml
Labels: Bug

#2253 [docs] improved formatting in FE API introduction
  docs/frontend-api/introduction-to-frontend-api.md
Labels: Documentation, Easy Pick

#2281 [monorepo] UPGRADE.md: info about updating NPM dependencies
  UPGRADE.md
Labels: Documentation

#2288 [coding-standards] removed direct dependency symplify/package-builder
  composer.json
  packages/coding-standards/composer.json
Labels: DX & Refactoring

#2286 [framework] fixed cleaning redis in test environment
  packages/framework/build.xml
Labels: Bug

#2293 [releaser] added --resume-step option for release command
  utils/releaser/config/services.yaml
  utils/releaser/src/Command/ReleaseCommand.php
  utils/releaser/src/ReleaseWorker/ReleaseWorkerProvider.php
Labels: Enhancement

#2292 [monorepo] symplify/changelog-linker replaced by github-changelog-generator/github-changelog-generator
  .github_changelog_generator
  changelog-linker.yml
  composer.json
  docs/contributing/guidelines-for-pull-request.md
  symfony.lock
  utils/releaser/src/FileManipulator/ChangelogFileManipulator.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateChangelogReleaseWorker.php
  utils/releaser/tests/FileManipulator/ChangelogFileManipulator/ChangelogFileManipulatorTest.php
  utils/releaser/tests/FileManipulator/ChangelogFileManipulator/Source/CHANGELOG-after.md
  utils/releaser/tests/FileManipulator/ChangelogFileManipulator/Source/CHANGELOG-before.md
Labels: DX & Refactoring

#2299 [shopsys] fix incorrect deprecated annotation in ProductOnCurrentDomainElasticFacade
  packages/framework/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
  upgrade/UPGRADE-v9.0.3.md
Labels: Documentation

#2300 [framework] fixed validation of customer email edit in administration
  packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: Bug

#2301 [framework] fixed title of modal window for deleting with setting replacement
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Components/ConfirmDelete/setNewAndDelete.html.twig
Labels: Bug, Design & Appearance
