Repository shopsys/shopsys, pull requests merged in 2021-05, with the labels that each got.

#2319 [shopsys] class names are get from `::class` constant instead of FQCN string
  packages/framework/tests/Unit/Model/Security/AuthenticatorTest.php
  project-base/tests/App/Functional/Model/Administrator/AdministratorRepositoryTest.php
  project-base/tests/App/Functional/Model/Cart/CartFacadeTest.php
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: DX & Refactoring

#2320 [shopsys] excluded friendsofphp/php-cs-fixer v2.19.0 in 7.3
  composer.json
  packages/coding-standards/composer.json
Labels: SSFW 7 LTS

#2313 [shopsys] bumped version of composer dependency composer/composer
  composer.json
  packages/framework/composer.json
  project-base/composer.json
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: DX & Refactoring

#2321 [product-feed-heureka] ignored errors reported by new squizlabs/php_codesniffer version 3.6.0 in 7.3
  packages/product-feed-heureka/easy-coding-standard.yml
Labels: SSFW 7 LTS

#2314 [shopsys] bumped version of composer dependency composer/composer in 7.3
  composer.json
  packages/framework/composer.json
  project-base/composer.json
  upgrade/UPGRADE-v7.3.7-dev.md
Labels: DX & Refactoring, SSFW 7 LTS

#2323 [shopsys] prevent admin to log as customer user on a different domain than user is registered on
  packages/framework/src/Controller/Admin/CustomerController.php
Labels: Bug

#2325 [shopsys] fix calculation of transport and payment visibilities
  packages/framework/src/Model/Payment/IndependentPaymentVisibilityCalculation.php
  packages/framework/src/Model/Payment/PaymentFacade.php
  packages/framework/src/Model/Payment/PaymentRepository.php
  packages/framework/src/Model/Transport/IndependentTransportVisibilityCalculation.php
  packages/framework/src/Model/Transport/TransportFacade.php
  packages/framework/src/Model/Transport/TransportRepository.php
  packages/frontend-api/src/Component/Constraints/PaymentCanBeUsedValidator.php
  packages/frontend-api/src/Component/Constraints/TransportCanBeUsedValidator.php
  packages/frontend-api/src/Model/Order/OrderDataFactory.php
  packages/frontend-api/src/Model/Resolver/Payment/PaymentResolver.php
  packages/frontend-api/src/Model/Resolver/Transport/TransportResolver.php
  project-base/tests/App/Functional/Model/Payment/IndependentPaymentVisibilityCalculationTest.php
  project-base/tests/App/Functional/Model/Transport/IndependentTransportVisibilityCalculationTest.php
Labels: Bug
