Repository shopsys/shopsys, pull requests merged in 2021-03, with the labels that each got.

#2259 [framework] ElFinder abort exception is now muted
  packages/framework/src/Controller/ElFinder/ElfinderController.php
  packages/framework/src/Resources/config/services.yaml
Labels: Bug

#2265 [framework] improved readibility of MethodAnnotationsFactory::getMethodAnnotationLine() method
  packages/framework/src/Component/ClassExtension/MethodAnnotationsFactory.php
Labels: DX & Refactoring

#2264 [project-base] improved docker-sync reliability on MacOS
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-sync.yml.dist
  upgrade/UPGRADE-v9.1.1-dev.md
Labels: DX & Refactoring

#2262 [monorepo] fixed CI builds
  .ci/build_kubernetes.sh
  .github/workflows/docker-build.yaml
  project-base/kubernetes/deployments/webserver-php-fpm.yml
Labels: Infrastructure

#2272 [project-base] updated windows installation guide to omit docker-sync and use WSL 2 instead
  docker/conf/docker-compose-win.yml.dist
  docker/conf/docker-sync-win.yml.dist
  docs/installation/index.md
  docs/installation/installation-guide.md
  docs/installation/installation-using-docker-windows-10-pro-higher.md
  docs/installation/installation-using-docker-windows-10.md
  project-base/docker/conf/docker-compose-win.yml.dist
  project-base/docker/conf/docker-sync-win.yml.dist
  project-base/scripts/install-docker-wsl-debian.sh
  project-base/scripts/install.sh
  upgrade/UPGRADE-v9.1.1-dev.md
Labels: Documentation

#2274 [shopsys] replaced <i> tag with twig icon function
  docs/frontend/icon-function.md
  docs/frontend/index.md
  docs/frontend/navigation.yml
  packages/framework/src/Resources/views/Common/Inline/Icon/icon.html.twig
  packages/framework/src/Twig/IconExtension.php
  project-base/templates/Front/Content/Cart/index.html.twig
  project-base/templates/Front/Content/Category/panel.html.twig
  project-base/templates/Front/Content/ContactForm/index.html.twig
  project-base/templates/Front/Content/Customer/edit.html.twig
  project-base/templates/Front/Content/Customer/orders.html.twig
  project-base/templates/Front/Content/Login/loginForm.html.twig
  project-base/templates/Front/Content/Login/windowForm.html.twig
  project-base/templates/Front/Content/Order/PromoCode/index.html.twig
  project-base/templates/Front/Content/Order/step3.html.twig
  project-base/templates/Front/Content/Product/detail.html.twig
  project-base/templates/Front/Content/Product/filterFormMacro.html.twig
  project-base/templates/Front/Content/Product/filterFormTheme.html.twig
  project-base/templates/Front/Content/Product/list.html.twig
  project-base/templates/Front/Content/Product/search.html.twig
  project-base/templates/Front/Content/Registration/register.html.twig
  project-base/templates/Front/Content/Search/autocomplete.html.twig
  project-base/templates/Front/Content/Search/searchBox.html.twig
  project-base/templates/Front/Form/theme.html.twig
  project-base/templates/Front/Inline/Breadcrumb/breadcrumb.html.twig
  project-base/templates/Front/Inline/Cart/cartBox.html.twig
  project-base/templates/Front/Inline/Cart/cartBoxItemMacro.html.twig
  project-base/templates/Front/Inline/Newsletter/subscription.html.twig
  project-base/templates/Front/Layout/header.html.twig
  project-base/templates/Styleguide/styleguide.html.twig
  upgrade/UPGRADE-v9.2.0-dev.md
Labels: Design & Apperance

#2280 [monorepo] do not pull elasticsearch and php-fpm image as they can be built locally
  .github/workflows/docker-build.yaml
Labels: Infrastructure
