Repository shopsys/shopsys, pull requests merged in 2021-01, with the labels that each got.

#2170 [shopsys] add login to our docker hub account for travis in order to prevent docker pull limit errors
  .travis.yml
  project-base/.ci/docker_login.sh
  project-base/.travis.yml
Labels: Infrastructure

#2169 stalebot now ignores issues with set milestone
  .github/stale.yml
Labels: Enhancement

#2176 [framework] admin: fixed displaying remove button for urls
  packages/framework/src/Model/Product/ProductDataFactory.php
Labels: Bug

#2180 [framework] product visibility is now recalculated, when their category is removed
  packages/framework/src/Model/Category/CategoryFacade.php
Labels: Bug

#2174 [project-base] validate search text is printable
  packages/framework/src/Component/String/TransformString.php
  project-base/src/Controller/Front/ProductController.php
  project-base/src/Controller/Front/SearchController.php
  upgrade/UPGRADE-v9.1.1-dev.md
Labels: Bug

#2179 [shopsys] acceptance tests now use test prefix for css classes
  docs/automated-testing/best-practices-for-writing-acceptance-tests.md
  docs/automated-testing/index.md
  docs/automated-testing/introduction-to-automated-testing.md
  docs/automated-testing/navigation.yml
  docs/automated-testing/running-acceptance-tests.md
  docs/index.md
  docs/introduction/console-commands-for-application-management-phing-targets.md
  docs/introduction/faq-and-common-issues.md
  docs/introduction/index.md
  docs/introduction/navigation.yml
  docs/navigation.yml
  packages/framework/assets/js/admin/utils/Window.js
  packages/framework/src/Resources/views/Admin/Content/Order/AdvancedSearch/ruleForm.html.twig
  packages/framework/src/Resources/views/Admin/Content/Pricing/Groups/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Content/Product/AdvancedSearch/ruleForm.html.twig
  packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig
  packages/framework/src/Resources/views/Components/ConfirmDelete/directDelete.html.twig
  project-base/assets/js/frontend/utils/Window.js
  project-base/templates/Front/Content/Cart/index.html.twig
  project-base/templates/Front/Content/Product/detail.html.twig
  project-base/templates/Front/Content/Product/filterFormMacro.html.twig
  project-base/templates/Front/Content/Product/productListMacro.html.twig
  project-base/templates/Front/Inline/Cart/cartBox.html.twig
  project-base/templates/Front/Inline/Paginator/paginator.html.twig
  project-base/templates/Front/Layout/header.html.twig
  project-base/templates/Styleguide/styleguide.html.twig
  project-base/tests/App/Acceptance/acceptance/PageObject/Admin/InlineEditPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Admin/ProductAdvancedSearchPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/CartBoxPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/CartPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/FloatingWindowPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/LayoutPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductDetailPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductFilterPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductListComponent.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductListPage.php
  project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php
  upgrade/UPGRADE-v9.2.0-dev.md
Labels: Documentation, Enhancement

#2210 [coding-standards] hotfix: exclude version of symfony/dependency-injection which breaks ECS
  composer.json
  packages/coding-standards/composer.json
Labels: Bug

#2193 [monorepo] github actions with persisted docker images
  .github/build-elasticsearch-image.sh
  .github/build-php-fpm-image.sh
  .github/check-image-exists.sh
  .github/workflows/docker-build.yaml
  .github/workflows/rebuild-docker-images.yaml
  README.md
  docker/conf/docker-compose.github-actions.yml.dist
  project-base/config/services_acc.yaml
  project-base/docker/php-fpm/Dockerfile
  yaml-standards.yaml
Labels: Infrastructure

#2200 [shopsys] prevent to pass null to not-nullable argument to ListedProductViewFactory::createFromArray()
  packages/framework/src/Model/Pricing/Exception/NoProductPriceForPricingGroupException.php
  packages/framework/src/Model/Product/Pricing/PriceFactory.php
  packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php
  packages/read-model/src/Product/Listed/ListedProductViewFactory.php
Labels: Bug
