Repository shopsys/shopsys, pull requests merged in 2021-06, with the labels that each got.

#2331 [shopsys] fix travis for version 7.3
  .travis.yml
  project-base/.ci/docker_login.sh
Labels: Infrastructure

#2315 [shopsys] set minimal version of symfony/symfony to 3.4.48
  composer.json
  packages/framework/composer.json
  packages/product-feed-google/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-zbozi/composer.json
  project-base/composer.json
  upgrade/UPGRADE-v7.3.7-dev.md
Labels: Security

#2334 [framework] cron overview now can display duration of crons over one hour
  packages/framework/src/Controller/Admin/DefaultController.php
Labels: Bug

#2316 [docs] added upgrade note for upgrading symfony/security* packages
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: Documentation

#2261 [framework] fix entity name in FrontendCustomerUserProvider
  packages/framework/src/Model/Customer/User/FrontendCustomerUserProvider.php
Labels: DX & Refactoring

#2324 [docs] introduction-to-frontend-api.md: fix typos
  docs/frontend-api/introduction-to-frontend-api.md
Labels: Documentation, Easy Pick

#2322 [framework] admin: dashboard: deleted orders are no longer included in statistics
  packages/framework/src/Model/Statistics/StatisticsRepository.php
Labels: Bug

#2312 [docs] updated apiary.apib to be up to date
  packages/frontend-api/apiary.apib
Labels: Documentation

#2306 [project-base] removed unused multipleProductsInOrder.graphql file
  project-base/tests/FrontendApiBundle/Functional/Order/Resources/multipleProductsInOrder.graphql
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: DX & Refactoring

#2304 [framework] destroy intervention image after it is saved in filesystem in order to prevent memory leaks
  packages/framework/src/Component/Image/Processing/ImageProcessor.php
Labels: Performance

#2335 [monorepo] added release candidate step for generating Apiary.io blueprint
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/GenerateApiaryBlueprintReleaseWorker.php
Labels: DX & Refactoring

#2330 [project-base] ProductFilterPage now uses mb_stripos instead of stripos
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/ProductFilterPage.php
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: Bug

#2327 [framework] fixed rendering of DisplayOnlyType in inline data grid
  packages/framework/src/Form/DisplayOnlyType.php
Labels: Bug

#2346 [framework] javascript email validation works now same as server side validation
  packages/framework/assets/js/common/validation/ConstraintEmail.js
  packages/framework/assets/js/common/validation/ShopsysFrameworkBundleFormConstraintsEmail.js
Labels: Bug

#2344 [shopsys] allowed install new version of symfony/dependency-injection
  composer.json
  packages/coding-standards/composer.json
  packages/coding-standards/easy-coding-standard.yml
  packages/coding-standards/src/Yaml/CheckerServiceParametersShifter.php
  project-base/symfony.lock
  symfony.lock
Labels: DX & Refactoring

#2339 [frontend-api] removed deprecated use of `Token::getClaim` in FrontendApiUserFactory
  packages/frontend-api/src/Model/User/FrontendApiUserFactory.php
Labels: DX & Refactoring

#2338 [framework] company name is return when is not null
  packages/framework/src/Model/Customer/User/CustomerUser.php
Labels: Bug

#2329 [framework] fixed order validation of company customers
  project-base/assets/js/frontend/validation/form/orderValidator.js
Labels: Bug

#2328 [framework] optimized category sorting in admin
  docs/cookbook/import-categories.md
  docs/cookbook/index.md
  docs/cookbook/navigation.yml
  docs/model/how-to-sort-categories.md
  docs/model/img/category-tree.png
  docs/model/index.md
  docs/model/navigation.yml
  packages/framework/assets/js/admin/components/CategoryTreeSorting.js
  packages/framework/easy-coding-standard.yml
  packages/framework/src/Command/RecalculateCategoryTreeCommand.php
  packages/framework/src/Controller/Admin/CategoryController.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Category/CategoryNestedSetCalculator.php
  packages/framework/src/Resources/views/Admin/Content/Category/list.html.twig
  packages/framework/tests/Unit/Model/Category/CategoryNestedSetCalculatorTest.php
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: DX & Refactoring, Performance

#2342 [framework] handled FileNotFoundException on main filesystem
  packages/framework/src/Component/Image/ImageFacade.php
  packages/framework/src/Form/Constraints/FileAbstractFilesystemValidator.php
  packages/framework/src/Form/Constraints/ImageAbstractFilesystemValidator.php
  packages/framework/src/Model/Mail/Mailer.php
Labels: Bug

#2354 [project-base] fixed wrong price converting in datafixtures
  project-base/src/DataFixtures/Demo/PaymentDataFixture.php
  project-base/src/DataFixtures/Demo/TransportDataFixture.php
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: Bug

#2349 [shopsys] trigger deprecations wrapped to helper class
  packages/framework/src/Command/CronCommand.php
  packages/framework/src/Command/Elasticsearch/ElasticsearchIndexesCreateCommand.php
  packages/framework/src/Component/DataFixture/AbstractNativeFixture.php
  packages/framework/src/Component/Deprecations/DeprecationHelper.php
  packages/framework/src/Component/Elasticsearch/AbstractExportChangedCronModule.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchIndexException.php
  packages/framework/src/Component/Elasticsearch/IndexDefinition.php
  packages/framework/src/Component/Elasticsearch/IndexFacade.php
  packages/framework/src/Component/Environment/EnvironmentFileSetting.php
  packages/framework/src/Component/FileUpload/FileUpload.php
  packages/framework/src/Component/Image/Config/ImageConfig.php
  packages/framework/src/Component/Image/Config/ImageConfigLoader.php
  packages/framework/src/Component/Router/DomainRouterFactory.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGenerator.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlRouterFactory.php
  packages/framework/src/Component/Router/LocalizedRouterFactory.php
  packages/framework/src/Controller/Admin/CustomerController.php
  packages/framework/src/Model/AdvancedSearch/Filter/ProductCategoryFilter.php
  packages/framework/src/Model/Breadcrumb/ErrorPageBreadcrumbGenerator.php
  packages/framework/src/Model/Breadcrumb/SimpleBreadcrumbGenerator.php
  packages/framework/src/Model/Cart/Watcher/CartWatcherFacade.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Category/CategoryRepository.php
  packages/framework/src/Model/Customer/User/CustomerUserPasswordFacade.php
  packages/framework/src/Model/Feed/FeedExportFactory.php
  packages/framework/src/Model/LegalConditions/LegalConditionsFacade.php
  packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
  packages/framework/src/Model/Product/Listing/ProductListOrderingModeForBrandFacade.php
  packages/framework/src/Model/Product/Listing/ProductListOrderingModeForListFacade.php
  packages/framework/src/Model/Product/Listing/ProductListOrderingModeForSearchFacade.php
  packages/framework/src/Model/Product/Pricing/PriceFactory.php
  packages/framework/src/Model/Product/ProductDataFactory.php
  packages/framework/src/Model/Product/ProductFacade.php
  packages/framework/src/Model/Product/ProductRepository.php
  packages/framework/src/Model/Script/ScriptFacade.php
  packages/framework/src/Twig/UploadedFileExtension.php
  packages/frontend-api/src/Component/Constraints/ProductCanBeOrderedValidator.php
  packages/frontend-api/src/Controller/FrontendApiController.php
  packages/frontend-api/src/Model/Article/ArticleRepository.php
  packages/frontend-api/src/Model/Product/ProductFacade.php
  packages/frontend-api/src/Model/Resolver/Category/CategoryResolver.php
  packages/frontend-api/src/Model/Resolver/Image/ImagesResolver.php
  packages/frontend-api/src/Model/Resolver/Price/PriceResolver.php
  packages/frontend-api/src/Model/Resolver/Products/ProductResolver.php
  packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php
  packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
  packages/read-model/src/Image/ImageViewFacade.php
  packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php
  packages/read-model/src/Product/Listed/ListedProductViewFacade.php
  packages/read-model/src/Product/Listed/ListedProductViewFactory.php
  project-base/src/Controller/Front/CartController.php
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: DX & Refactoring

#2351 [shopsys] extract setter injection methods into trait
  packages/framework/src/Command/CronCommand.php
  packages/framework/src/Component/Elasticsearch/AbstractExportChangedCronModule.php
  packages/framework/src/Component/FileUpload/FileUpload.php
  packages/framework/src/Component/Image/Config/ImageConfig.php
  packages/framework/src/Component/Image/Config/ImageConfigLoader.php
  packages/framework/src/Component/Router/DomainRouterFactory.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGenerator.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlRouterFactory.php
  packages/framework/src/Component/Router/LocalizedRouterFactory.php
  packages/framework/src/Controller/Admin/CustomerController.php
  packages/framework/src/DependencyInjection/SetterInjectionTrait.php
  packages/framework/src/Model/AdvancedSearch/Filter/ProductCategoryFilter.php
  packages/framework/src/Model/Customer/User/CustomerUserPasswordFacade.php
  packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
  packages/framework/src/Model/Product/ProductDataFactory.php
  packages/framework/src/Twig/UploadedFileExtension.php
  packages/frontend-api/src/Component/Constraints/ProductCanBeOrderedValidator.php
  packages/frontend-api/src/Controller/FrontendApiController.php
  packages/frontend-api/src/Model/Resolver/Category/CategoryResolver.php
  packages/frontend-api/src/Model/Resolver/Image/ImagesResolver.php
  packages/frontend-api/src/Model/Resolver/Price/PriceResolver.php
  packages/frontend-api/src/Model/Resolver/Products/ProductResolverMap.php
  packages/frontend-api/src/Model/Resolver/Products/ProductsResolver.php
  packages/read-model/src/Product/Listed/ListedProductViewElasticFacade.php
  packages/read-model/src/Product/Listed/ListedProductViewFactory.php
Labels: DX & Refactoring

#2332 [framework] exchange rate recalculation after changing default currency
  packages/framework/src/Model/Pricing/Currency/CurrencyFacade.php
  packages/framework/src/Model/Pricing/Currency/CurrencyRepository.php
  packages/framework/src/Model/Pricing/PriceConverter.php
  packages/framework/src/Model/Pricing/PricingSetting.php
  project-base/src/DataFixtures/Demo/CurrencyDataFixture.php
  project-base/src/DataFixtures/Demo/PaymentDataFixture.php
  project-base/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/src/DataFixtures/Demo/TransportDataFixture.php
  project-base/tests/App/Functional/Model/Product/ProductOnCurrentDomainFacadeCountDataTest.php
  project-base/tests/App/Functional/Model/Product/ProductOnCurrentDomainFacadeTest.php
  project-base/tests/App/Functional/Model/Product/Search/FilterQueryTest.php
  project-base/tests/App/Test/Codeception/Helper/NumberFormatHelper.php
  project-base/tests/FrontendApiBundle/Test/GraphQlTestCase.php
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: Bug

#2355 [docs] introduction-to-frontend-api.md: fix graphiql links
  docs/frontend-api/introduction-to-frontend-api.md
Labels: Documentation

#2298 [docs] linked post-installation steps for linux installation
  docs/installation/installation-using-docker-linux.md
Labels: Documentation

#2356 [project-base] data fixtures always create same prices independently on input price setting
  packages/framework/src/Model/Pricing/PriceConverter.php
  project-base/src/DataFixtures/Demo/PaymentDataFixture.php
  project-base/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/src/DataFixtures/Demo/TransportDataFixture.php
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: Bug

#2359 [shopsys] increase minimal supported version of symfony/proxy-manager-bridge
  composer.json
  packages/framework/composer.json
  project-base/composer.json
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: Bug

#2352 [docs] fix basic-data-import.md
  docs/cookbook/basic-data-import.md
Labels: Documentation

#2336 [shopsys] updated node and npm packages
  build.xml
  package-lock.json
  packages/framework/assets/package.json
  packages/framework/assets/styles/admin/core/variables.less
  project-base/assets/js/bin/copyAssets.js
  project-base/assets/js/bin/generateWebfonts.js
  project-base/assets/js/commands/svg/generateWebFont.js
  project-base/assets/js/frontend/cart/CartBoxItemRemover.js
  project-base/assets/styles/frontend/common/core/variables.less
  project-base/assets/styles/styleguide/structure.css
  project-base/babel.config.js
  project-base/docker/php-fpm/Dockerfile
  project-base/package.json
  project-base/webpack.config.js
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: DX & Refactoring

#2357 [framework] free text in order is now correctly translated to orders language
  packages/framework/src/Twig/PriceExtension.php
Labels: Bug

#2360 [shopsys] bump minimal version of doctrine/dbal package
  composer.json
  packages/backend-api/composer.json
  packages/framework/composer.json
  packages/migrations/composer.json
  packages/product-feed-google/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-zbozi/composer.json
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: Bug

#2361 [framework] bump minimal version of litipk/php-bignumbers package
  composer.json
  packages/framework/composer.json
Labels: Bug

#2348 [framework] admin: fix label alignment in multidomain fields
  packages/framework/assets/styles/admin/components/form/line.less
  packages/framework/assets/styles/admin/components/in/ckeditor.less
  packages/framework/assets/styles/admin/components/in/image.less
  packages/framework/assets/styles/admin/core/form/input.less
  packages/framework/src/Resources/views/Admin/Form/theme.html.twig
Labels: Bug, Design & Appearance

#2363 [docs] typo in database-migrations.md
  docs/introduction/database-migrations.md
Labels: Documentation

#2365 [shopsys] increased the minimal version of `league/flysystem`
  composer.json
  packages/framework/composer.json
  project-base/composer.json
  upgrade/UPGRADE-v9.1.2-dev.md
Labels: Security
