Repository shopsys/shopsys, pull requests merged in 2021-02, with the labels that each got.

#2206 [framework] empty strings are stored as null if possible
  packages/framework/src/Component/String/TransformString.php
  packages/framework/src/Migrations/Version20210127085903.php
  packages/framework/src/Model/Category/CategoryTranslation.php
  packages/framework/src/Model/Payment/PaymentTranslation.php
  packages/framework/src/Model/Product/Brand/BrandTranslation.php
  packages/framework/src/Model/Product/Parameter/ParameterTranslation.php
  packages/framework/src/Model/Product/ProductTranslation.php
  packages/framework/src/Model/Transport/TransportTranslation.php
  packages/framework/tests/Unit/Component/String/TransformStringTest.php
Labels: Bug

#2093 [framework] fixed box-upload white line overlapping box
  packages/framework/assets/styles/admin/components/box/upload.less
Labels: Bug, Design & Apperance

#2191 [framework] set CountryDomain as multi domain entity
  packages/framework/src/Model/MultidomainEntityClassProvider.php
Labels: Bug

#2178 [framework] admin: customer user form: customer user with not existing email can be saved
  packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
Labels: Bug

#2201 [frontend-api] Payment price is required
  packages/frontend-api/src/Resources/config/graphql-types/PaymentDecorator.types.yaml
Labels: Bug, Easy Pick

#2195 [frontend-api] product decorators inherit all fields from product type
  packages/frontend-api/src/Resources/config/graphql-types/MainVariantDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/RegularProductDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/VariantDecorator.types.yaml
  upgrade/UPGRADE-v9.1.1-dev.md
Labels: DX & Refactoring, Easy Pick

#2196 [docs] use `CategoryResolverMap` as an example of `ResolverMap` in FE API introduction
  docs/frontend-api/introduction-to-frontend-api.md
Labels: Documentation, Easy Pick

#2202 [shopsys] entites are refreshed after product visibility recalculations
  packages/framework/src/Component/EntityExtension/EntityManagerDecorator.php
  packages/framework/src/Model/Product/ProductVisibilityRepository.php
  project-base/tests/App/Functional/Model/Order/OrderFacadeTest.php
  upgrade/UPGRADE-v9.1.1-dev.md
Labels: Bug

#2183 [coding-standards] added support for symfony5
  packages/coding-standards/.travis.yml
  packages/coding-standards/composer.json
Labels: Enhancement

#2221 [frontend-api] fixed creating order with no products
  packages/frontend-api/src/Resources/config/graphql-types/OrderInput/OrderInputDecorator.types.yaml
  project-base/tests/FrontendApiBundle/Functional/Order/MinimalOrderTest.php
  upgrade/UPGRADE-v9.1.1-dev.md
Labels: Bug

#2218 [framework] CsvReader class is now deprecated
  packages/framework/src/Component/Csv/CsvReader.php
  upgrade/UPGRADE-v9.2.0-dev.md
Labels: DX & Refactoring

#2229 [framework] elFinder: thumbnail is only removed when some thumbnail exists
  packages/framework/src/Component/Filesystem/Flysystem/VolumeDriver.php
Labels: Bug

#2225 [monorepo] added github actions configs for all packages
  packages/backend-api/.github/workflows/run-checks-tests.yaml
  packages/coding-standards/.github/workflows/run-checks-tests.yaml
  packages/form-types-bundle/.github/workflows/run-checks-tests.yaml
  packages/framework/.github/workflows/run-checks-tests.yaml
  packages/frontend-api/.github/workflows/run-checks-tests.yaml
  packages/google-cloud-bundle/.github/workflows/run-checks-tests.yaml
  packages/http-smoke-testing/.github/workflows/run-checks-tests.yaml
  packages/migrations/.github/workflows/run-checks-tests.yaml
  packages/plugin-interface/.github/workflows/run-checks-tests.yaml
  packages/product-feed-google/.github/workflows/run-checks-tests.yaml
  packages/product-feed-heureka-delivery/.github/workflows/run-checks-tests.yaml
  packages/product-feed-heureka/.github/workflows/run-checks-tests.yaml
  packages/product-feed-zbozi/.github/workflows/run-checks-tests.yaml
  packages/read-model/.github/workflows/run-checks-tests.yaml
  project-base/.github/workflows/docker-build.yaml
Labels: Infrastructure

#2048 [project-base] logo on homepage is link and is not wrapped in H1
  project-base/templates/Front/Content/Default/index.html.twig
  upgrade/UPGRADE-v9.1.1-dev.md
Labels: Design & Apperance
