Repository shopsys/shopsys, pull requests merged in 2022-02, with the labels that each got.

#2398 [project-base] fixed memory limit for phpunit
  project-base/phpunit.xml
  upgrade/UPGRADE-v9.1.3-dev.md
Labels: Bug, Easy Pick

#2397 composer updates
  build.xml
  composer.json
  easy-coding-standard.yml
  packages/backend-api/composer.json
  packages/coding-standards/composer.json
  packages/form-types-bundle/composer.json
  packages/framework/composer.json
  packages/framework/easy-coding-standard.yml
  packages/framework/phpstan.neon
  packages/framework/tests/Test/Codeception/ActorInterface.php
  packages/frontend-api/composer.json
  packages/google-cloud-bundle/composer.json
  packages/http-smoke-testing/composer.json
  packages/migrations/composer.json
  packages/plugin-interface/composer.json
  packages/product-feed-google/composer.json
  packages/product-feed-heureka-delivery/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-zbozi/composer.json
  packages/read-model/composer.json
  phpstan.neon
  project-base/composer.json
  project-base/phpstan.neon
  project-base/src/DataFixtures/Demo/CustomerUserDataFixture.php
  project-base/symfony.lock
  project-base/tests/App/Test/Codeception/AcceptanceTester.php
  project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php
  symfony.lock
  upgrade/UPGRADE-v9.1.3-dev.md
Labels: Security

#2394 [framework] fixed duplicated extra section in composer
  packages/framework/composer.json
Labels: Bug

#2395 [shopsys] updated year in license files
  LICENSE
  packages/backend-api/LICENSE
  packages/coding-standards/LICENSE
  packages/form-types-bundle/LICENSE
  packages/framework/LICENSE
  packages/frontend-api/LICENSE
  packages/google-cloud-bundle/LICENSE
  packages/http-smoke-testing/LICENSE
  packages/migrations/LICENSE
  packages/monorepo-tools/LICENSE
  packages/plugin-interface/LICENSE
  packages/product-feed-google/LICENSE
  packages/product-feed-heureka-delivery/LICENSE
  packages/product-feed-heureka/LICENSE
  packages/product-feed-zbozi/LICENSE
  packages/read-model/LICENSE
  project-base/LICENSE
Labels: Easy Pick, Documentation
