Repository shopsys/shopsys, pull requests merged in 2023-05, with the labels that each got.

#2606 [docs] changed bc promise link to supported version
  docs/contributing/backward-compatibility-promise.md
Labels: Documentation

#2610 [shopsys] updated acceptance tests because they were no longer working locally
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose.github-actions.yml.dist
  docker/conf/docker-compose.yml.dist
  docs/automated-testing/running-acceptance-tests.md
  open-source-license-acknowledgements-and-third-party-copyrights.md
  packages/framework/build.xml
  packages/framework/tests/Test/Codeception/AbstractCheckbox.php
  packages/framework/tests/Test/Codeception/ActorInterface.php
  phpstan.neon
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
  project-base/kubernetes/deployments/selenium-server.yml
  project-base/tests/App/Acceptance/acceptance.suite.yml
  project-base/tests/App/Acceptance/acceptance/PageObject/Admin/ProductAdvancedSearchPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/CartPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/OrderPage.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/RegistrationPage.php
  project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php
  upgrade/UPGRADE-v11.0.1-dev.md
Labels: Bug

#2611 [shopsys] updated codeception to version 5
  composer.json
  packages/framework/tests/Test/Codeception/ActorInterface.php
  project-base/build/codeception.yml
  project-base/phpstan.neon
  project-base/tests/App/Acceptance/acceptance.suite.yml
  project-base/tests/App/Test/Codeception/Module/Db.php
  project-base/tests/App/Test/Codeception/Module/StrictWebDriver.php
  symfony.lock
Labels: DX & Refactoring

#1935 [framework] add typehints and return types in ImageFacade
  packages/framework/src/Component/Image/ImageFacade.php
  upgrade/UPGRADE-v12.0.0-dev.md
Labels: DX & Refactoring

#2605 [framework] RegisterProjectFrameworkClassExtensionCompilerPass now ensures that both class and interface alias are registered in Symfony services
  packages/framework/ecs.php
  packages/framework/src/Component/ClassExtension/ClassExtensionRegistry.php
  packages/framework/src/DependencyInjection/Compiler/RegisterProjectFrameworkClassExtensionsCompilerPass.php
  project-base/src/Controller/Front/CartController.php
  project-base/src/Controller/Front/CustomerController.php
  project-base/src/Controller/Front/HomepageController.php
  project-base/src/Controller/Front/PersonalDataController.php
  project-base/src/Controller/Front/ProductController.php
  project-base/src/Controller/Front/SearchController.php
  project-base/src/DataFixtures/Demo/AdvertDataFixture.php
  project-base/src/DataFixtures/Demo/AvailabilityDataFixture.php
  project-base/src/DataFixtures/Demo/CountryDataFixture.php
  project-base/src/DataFixtures/Demo/CurrencyDataFixture.php
  project-base/src/DataFixtures/Demo/CustomerUserDataFixture.php
  project-base/src/DataFixtures/Demo/FlagDataFixture.php
  project-base/src/DataFixtures/Demo/MailTemplateDataFixture.php
  project-base/src/DataFixtures/Demo/OrderStatusDataFixture.php
  project-base/src/DataFixtures/Demo/PricingGroupDataFixture.php
  project-base/src/DataFixtures/Demo/PromoCodeDataFixture.php
  project-base/src/DataFixtures/Demo/ScriptDataFixture.php
  project-base/src/DataFixtures/Demo/SliderItemDataFixture.php
  project-base/src/DataFixtures/Demo/UnitDataFixture.php
  project-base/src/DataFixtures/Demo/VatDataFixture.php
  project-base/src/DataFixtures/Performance/CustomerUserDataFixture.php
  project-base/src/Form/Front/Customer/User/CustomerUserUpdateFormType.php
  project-base/src/Model/Administrator/AdministratorDataFactory.php
  project-base/src/Model/Article/ArticleDataFactory.php
  project-base/src/Model/Category/CategoryDataFactory.php
  project-base/src/Model/Customer/User/CustomerUserDataFactory.php
  project-base/src/Model/Order/Item/OrderItemDataFactory.php
  project-base/src/Model/Order/OrderDataFactory.php
  project-base/src/Model/Payment/PaymentDataFactory.php
  project-base/src/Model/Product/Brand/BrandDataFactory.php
  project-base/src/Model/Product/ProductDataFactory.php
  project-base/src/Model/Transport/TransportDataFactory.php
Labels: DX & Refactoring
