Repository shopsys/shopsys, pull requests merged in 2023-08, with the labels that each got.

#2673 errors on SF can now have different verbosity
  project-base/storefront/helpers/errors/applicationErrors.ts
  project-base/storefront/helpers/errors/errorMessageMapper.ts
  project-base/storefront/helpers/errors/friendlyErrorMessageParser.ts
  project-base/storefront/helpers/errors/ignoredErrors.ts
  project-base/storefront/urql/errorExchange.ts
Labels: Enhancement, Design & Appearance

#2686 storefront unit tests config and initial examples
  .github/workflows/docker-build.yaml
  project-base/storefront/docs/unit-tests.md
  project-base/storefront/helpers/filterOptions/seoCategories.ts
  project-base/storefront/hooks/useQueryParams.ts
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  project-base/storefront/tsconfig.json
  project-base/storefront/vitest.config.js
  project-base/storefront/vitest/components/ExtendedNextLink/ExtendedNextLink.test.tsx
  project-base/storefront/vitest/components/ExtendedNextLink/snap-1.test.tsx.snap
  project-base/storefront/vitest/components/ExtendedNextLink/snap-2.test.tsx.snap
  project-base/storefront/vitest/components/ExtendedNextLink/snap-3.test.tsx.snap
  project-base/storefront/vitest/components/ExtendedNextLink/snap-4.test.tsx.snap
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.resetAllFilters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterBrands.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterFlags.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterInStock.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterParameters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMaximum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMinimum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPrices.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updatePagination.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateSort.test.ts
Labels: DX & Refactoring

#2690 images are not downloadable from the product gallery
  project-base/storefront/components/Basic/Gallery/Gallery.tsx
Labels: Easy Pick

#2697 wishlist and comparison for product variant cards
  project-base/storefront/components/Blocks/Product/ButtonsAction/ProductCompareButton.tsx
  project-base/storefront/components/Blocks/Product/ButtonsAction/ProductWishlistButton.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductItem.tsx
  project-base/storefront/components/Blocks/Product/SliderProductItem.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
Labels: Enhancement, Easy Pick, Design & Appearance

#2698 changed images and icons to free variants
  project-base/storefront/components/Basic/Icon/IconsSvgMap.tsx
  project-base/storefront/components/Blocks/Popup/Login/Login.tsx
  project-base/storefront/components/Layout/Header/Cart/Cart.tsx
  project-base/storefront/components/Pages/Registration/RegistrationContent.tsx
  project-base/storefront/public/images/empty-cart-small.png
  project-base/storefront/public/images/qmark.png
  project-base/storefront/public/svg/IconsSvg.tsx
Labels: Easy Pick, Design & Appearance

#2688 fixed incorrect button margin in newsletter form
  project-base/storefront/components/Layout/Footer/NewsletterForm.tsx
Labels: Bug, Design & Appearance

#2689 router.push and router.replace now navigate correctly between dynamic…
  project-base/storefront/components/Blocks/Product/ProductAction.tsx
  project-base/storefront/helpers/filterOptions/seoCategories.ts
  project-base/storefront/hooks/useQueryParams.ts
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.resetAllFilters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterBrands.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterFlags.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterInStock.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterParameters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMaximum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMinimum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPrices.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updatePagination.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateSort.test.ts
Labels: Bug

#2700 error popup is now shown after the first invalid form submission
  project-base/storefront/hooks/forms/useErrorPopupVisibility.ts
Labels: Bug, Easy Pick

#2685 added closing days to be set for stores to inform customers that store is closed
  packages/framework/src/Component/Domain/Domain.php
  project-base/app/src/Controller/Admin/ClosedDayController.php
  project-base/app/src/Controller/Admin/SideMenuConfigurationSubscriber.php
  project-base/app/src/DataFixtures/Demo/ClosedDayDataFixture.php
  project-base/app/src/Form/Admin/BlogArticleFormType.php
  project-base/app/src/Form/Admin/ClosedDayFormType.php
  project-base/app/src/Form/Admin/Transformer/StoreIdToStoreTransformer.php
  project-base/app/src/FrontendApi/Resolver/Store/OpeningHours/OpeningHoursResolverMap.php
  project-base/app/src/Migrations/Version20230524064748.php
  project-base/app/src/Model/Store/ClosedDay/ClosedDay.php
  project-base/app/src/Model/Store/ClosedDay/ClosedDayData.php
  project-base/app/src/Model/Store/ClosedDay/ClosedDayDataFactory.php
  project-base/app/src/Model/Store/ClosedDay/ClosedDayFacade.php
  project-base/app/src/Model/Store/ClosedDay/ClosedDayRepository.php
  project-base/app/src/Model/Store/ClosedDay/Exception/ClosedDayNotFoundException.php
  project-base/app/src/Model/Store/ClosedDay/Grid/ClosedDayGridFactory.php
  project-base/app/src/Model/Store/Store.php
  project-base/app/src/Model/Store/StoreFacade.php
  project-base/app/src/Model/Store/StoreIdsToStoresTransformer.php
  project-base/app/templates/Admin/Content/ClosedDay/detail.html.twig
  project-base/app/templates/Admin/Content/ClosedDay/edit.html.twig
  project-base/app/templates/Admin/Content/ClosedDay/list.html.twig
  project-base/app/templates/Admin/Content/ClosedDay/listGrid.html.twig
  project-base/app/templates/Admin/Content/ClosedDay/new.html.twig
  project-base/app/tests/FrontendApiBundle/Functional/Store/GetStoreTest.php
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/query/StoreQuery.graphql
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  project-base/app/translations/validators.cs.po
  project-base/app/translations/validators.en.po
Labels: Enhancement

#2702 added total price to order detail
  project-base/storefront/components/Basic/Table/Table.tsx
  project-base/storefront/components/Pages/Customer/OrderDetailContent.tsx
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailFragment.graphql
Labels: Design & Appearance

#2687 refactored menu iconic for a better DX
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconic.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemLogin.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemUser.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemUserAuthenticated.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemUserUnauthenticated.tsx
Labels: Bug, DX & Refactoring

#2696 logged-in user wishlist and comparison fix
  project-base/storefront/hooks/auth/useAuth.tsx
  project-base/storefront/hooks/comparison/useComparison.tsx
  project-base/storefront/hooks/useWishlist.tsx
  project-base/storefront/store/zustand/slices/createWishlistSlice.ts
  project-base/storefront/urql/cacheExchange.ts
Labels: Bug

#2708 [project-base] removed product images entity caching
  project-base/app/src/Component/Image/ImageFacade.php
  project-base/app/src/Model/Product/Transfer/Akeneo/TransferredProductProcessor.php
  project-base/app/src/Model/ProductFeed/Mergado/FeedItem/MergadoFeedItem.php
Labels: Bug

#2705 [github-actions] no source code is in the base php-fpm image now
  .github/build-php-fpm-image.sh
  .github/workflows/docker-build.yaml
Labels: Infrastructure

#2706 [github-actions] added link to review to PR description
  .github/workflows/docker-build.yaml
Labels: Infrastructure

#2695 load more feature
  project-base/storefront/components/Blocks/Pagination/Pagination.tsx
  project-base/storefront/components/Blocks/Product/Filter/helpers/getEndCursor.ts
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItemSkeleton.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductsList.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductsListContent.tsx
  project-base/storefront/components/Pages/BlogCategory/BlogCategoryArticlesWrapper.tsx
  project-base/storefront/components/Pages/BlogCategory/BlogCategoryPageSkeleton.tsx
  project-base/storefront/components/Pages/BrandDetail/BrandDetailProductsWrapper.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailProductsWrapper.tsx
  project-base/storefront/components/Pages/CategoryDetail/helpers.ts
  project-base/storefront/components/Pages/FlagDetail/FlagDetailProductsWrapper.tsx
  project-base/storefront/components/Pages/Search/ProductsSearch.tsx
  project-base/storefront/components/Pages/Search/ResultProducts.tsx
  project-base/storefront/components/Pages/Search/SearchProductsWrapper.tsx
  project-base/storefront/components/Pages/Search/helpers.ts
  project-base/storefront/config/constants.ts
  project-base/storefront/docs/gtm/hooks.md
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/pageInfo/fragments/PageInfoFragment.graphql
  project-base/storefront/graphql/requests/products/fragments/ListedProductConnectionFragment.graphql
  project-base/storefront/graphql/requests/products/queries/SearchProductsQuery.graphql
  project-base/storefront/graphql/requests/search/queries/AutocompleteSearchQuery.graphql
  project-base/storefront/helpers/gtm/eventFactories.ts
  project-base/storefront/helpers/pagination/loadMore.ts
  project-base/storefront/helpers/pagination/parseLoadMoreFromQuery.ts
  project-base/storefront/helpers/parsing/getDynamicPageQueryKey.ts
  project-base/storefront/helpers/queryParams/queryParamNames.ts
  project-base/storefront/hooks/gtm/productList/useGtmPaginatedProductListViewEvent.ts
  project-base/storefront/hooks/seo/useSeoTitleWithPagination.ts
  project-base/storefront/hooks/useQueryParams.ts
  project-base/storefront/next.config.js
  project-base/storefront/pages/blogCategories/[blogCategorySlug].tsx
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/customer/orders.tsx
  project-base/storefront/pages/flags/[flagSlug].tsx
  project-base/storefront/pages/search.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/vitest/helpers/pagination/loadMore.test.ts
  project-base/storefront/vitest/helpers/parsing/getDynamicPageQueryKey.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.loadMore.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.resetAllFilters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterBrands.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterFlags.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterInStock.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterParameters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMaximum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMinimum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPrices.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateSort.test.ts
Labels: Enhancement, Easy Pick, Design & Appearance

#2714 [project-base] changed robots.txt datafixture to avoid encouraging inappropriate practices
  project-base/app/src/DataFixtures/Demo/SettingValueDataFixture.php
Labels: Easy Pick, DX & Refactoring

#2712 [project-base] fixed en url to personal data export in admin
  project-base/app/config/shopsys-routing/routing_front_en.yaml
Labels: Bug

#2715 [project-base] fixed category blog delete confirm
  project-base/app/templates/Admin/Content/Blog/Category/list.html.twig
Labels: Bug

#2720 fixed dynamic robots.txt on storefront
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/robotsTxt/RobotsTxtQuery.graphql
  project-base/storefront/middleware.ts
  project-base/storefront/pages/robots.txt.tsx
Labels: Bug, Enhancement, Easy Pick

#2709 [shopsys] updated open source license acknowledgements
  open-source-license-acknowledgements-and-third-party-copyrights.md
  utils/license-acknowledgements-generator/.gitignore
  utils/license-acknowledgements-generator/composer.json
  utils/license-acknowledgements-generator/composer.lock
  utils/license-acknowledgements-generator/generate-acknowledgements.php
  utils/license-acknowledgements-generator/license-report-config.json
  utils/license-acknowledgements-generator/template.md
  utils/license-acknowledgements-generator/vendor/.gitkeep
  utils/releaser/config/release-candidate.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateLicenseAcknowledgementsReleaseWorker.php
Labels: Documentation

#2719 [shopsys] removed deprecations before release 12.0
  docs/installation/application-configuration.md
  packages/framework/src/Command/CronCommand.php
  packages/framework/src/Component/Cron/Config/CronConfig.php
  packages/framework/src/Component/Cron/CronModuleExecutor.php
  packages/framework/src/Component/Cron/CronModuleFacade.php
  packages/framework/src/Controller/Admin/DefaultController.php
  packages/framework/src/Controller/Admin/SuperadminController.php
  packages/framework/src/Model/Advert/AdvertRepository.php
  packages/framework/src/Model/Mail/EventListener/EnvelopeListener.php
  packages/framework/src/Model/Mail/Exception/MasterMailNotSetException.php
  packages/framework/src/Model/Mail/Mailer.php
  packages/framework/src/Model/Mail/MailerSettingProvider.php
  packages/framework/src/Model/Product/Search/AggregationResultToProductFilterCountDataTransformer.php
  packages/framework/src/Model/Product/Search/ProductFilterCountDataElasticsearchRepository.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Superadmin/mailWhitelist.html.twig
  packages/framework/src/Twig/MailerSettingExtension.php
  packages/framework/tests/Unit/Component/Cron/CronFacadeTest.php
  packages/framework/tests/Unit/Component/Cron/CronModuleExecutorTest.php
  packages/framework/tests/Unit/Model/Mail/EnvelopeListenerTest.php
  packages/frontend-api/src/Model/Mutation/Login/LoginMutation.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertPositionWithoutCategoryUserError.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertsQuery.php
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/.env
  project-base/src/Controller/Front/AdvertController.php
  project-base/src/Controller/Front/RobotsController.php
  upgrade/UPGRADE-v12.0.0-dev.md
Labels: DX & Refactoring

#2738 registration after order now uses data from URL
  project-base/storefront/components/Pages/OrderConfirmation/RegistrationAfterOrder.tsx
  project-base/storefront/pages/order-confirmation.tsx
  project-base/storefront/pages/order/contact-information.tsx
Labels: Bug

#2707 cart can now be prefilled based on a previous order
  packages/framework/src/Model/Cart/Cart.php
  project-base/app/config/graphql/types/ModelType/Cart/CartInput/AddOrderItemsToCartInput.types.yaml
  project-base/app/config/graphql/types/ModelType/Cart/CartModificationsResult.types.yaml
  project-base/app/config/graphql/types/ModelType/Cart/CartMultipleAddedProductModificationsResult.types.yaml
  project-base/app/config/graphql/types/Mutation/Cart/CartMutation.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/FrontendApi/Model/Cart/CartFacade.php
  project-base/app/src/FrontendApi/Model/Cart/CartWithModificationsResult.php
  project-base/app/src/FrontendApi/Mutation/Cart/CartMutation.php
  project-base/app/src/Model/Cart/Cart.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/AddOrderItemsToCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/AnonymousAddOrderItemsToCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/CartWithPromoCodeTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/RemainingToFreeTransportCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/graphql/AddOrderItemsToCart.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Cart/graphql/GetCart.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Order/CompanyFieldsAreValidatedTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsAreValidatedTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/DynamicFieldsInOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/FullOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/GetOrderSentPageContentTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/GetOrdersAsAuthenticatedCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/MinimalOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/MultipleProductsInOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/OrderTestTrait.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/OrderWithPersonalPickupStoreTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/OrderWithPromoCodeTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/PaymentInOrderValidationTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/ProductInOrderValidationTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/RequiredFieldsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/TransportInOrderValidationTest.php
  project-base/storefront/components/Pages/Customer/MergeCartsPopup.tsx
  project-base/storefront/components/Pages/Customer/NotAddedProductsPopup.tsx
  project-base/storefront/components/Pages/Customer/OrderDetailContent.tsx
  project-base/storefront/components/Pages/Customer/OrdersContent.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/cart/fragments/CartModificationsFragment.graphql
  project-base/storefront/graphql/requests/cart/mutations/AddOrderItemsToCartMutation.graphql
  project-base/storefront/hooks/cart/useAddOrderItemsToCart.ts
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/schema.graphql.json
  project-base/storefront/urql/cacheExchange.ts
Labels: Enhancement, Easy Pick, Design & Appearance

#2727 added iframe and image to grapejs
  project-base/app/assets/js/admin/grapesjs/initGrapesJs.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-blocks-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-iframe-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-image-file-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-image-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-link-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-text-with-image-plugin.js
  project-base/storefront/components/Basic/UserText/GrapeJsParser.tsx
  project-base/storefront/components/Basic/UserText/GrapesJsParser.tsx
  project-base/storefront/components/Pages/Article/ArticleDetailContent.tsx
  project-base/storefront/components/Pages/BlogArticle/BlogArticleDetailContent.tsx
  project-base/storefront/gtm/types/enums.ts
Labels: Enhancement, Easy Pick

#2730 added block with bestsellers to category detail
  project-base/storefront/components/Blocks/Product/ProductAvailableStoresCount.tsx
  project-base/storefront/components/Blocks/Product/ProductExposedStoresCount.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItem.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryBestsellers/CategoryBestsellers.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryBestsellers/CategoryBestsellersListItem.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductVariantsTable/Variant.tsx
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/categories/fragments/CategoryDetailFragment.graphql
  project-base/storefront/gtm/types/enums.ts
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
Labels: Enhancement, Easy Pick, Design & Appearance

#2744 [google-feed] fixed google feed availability constants
  packages/product-feed-google/src/Model/FeedItem/GoogleFeedItem.php
  packages/product-feed-google/tests/Unit/GoogleFeedItemTest.php
Labels: Bug

#2746 [project-base] product videos UX fixes
  project-base/app/src/Form/Admin/VideoTokenType.php
  project-base/app/templates/Admin/Form/productVideoValue.html.twig
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  upgrade/UPGRADE-v13.0.0-dev.md
Labels: Design & Appearance

#2743 [docs] updated infrastructure schema
  docs/img/shopsys-platform-infrastructure.png
Labels: Documentation

#2747 [project-base] filtering in ready category seo mix is now working with provided filters by API
  project-base/app/src/FrontendApi/Resolver/Products/ProductsQuery.php
  project-base/app/src/Model/Product/Filter/ProductFilterDataFactory.php
  upgrade/UPGRADE-v13.0.0-dev.md
Labels: Bug

#2757 [project-base] fixed elasticsearch definition to have correct languages set by default domain languages
  project-base/app/src/Resources/definition/article/1.json
  project-base/app/src/Resources/definition/article/2.json
  project-base/app/src/Resources/definition/blog_article/1.json
  project-base/app/src/Resources/definition/blog_article/2.json
  project-base/app/src/Resources/definition/product/1.json
Labels: Bug

#2759 [docs] added coding standards upgrade notes
  upgrade/UPGRADE-v12.0.0-dev.md
Labels: Documentation
