Repository shopsys/shopsys, pull requests merged in 2023-07, with the labels that each got.

#2651 images are now rebuilt only for currently supported versions
  .github/workflows/docker-build.yaml
  .github/workflows/rebuild-docker-images.yaml
Labels: Infrastructure

#2658 build will no longer be successful if the storefront standards or review will fail
  .github/get-build-exit-code.sh
  .github/workflows/docker-build.yaml
Labels: Infrastructure

#2652 fix console warnings
  .github/workflows/docker-build.yaml
  Makefile
  project-base/storefront/.eslintrc.js
  project-base/storefront/components/Basic/RangeSlider/RangeSlider.tsx
  project-base/storefront/components/Blocks/Pagination/Pagination.tsx
  project-base/storefront/components/Blocks/Product/ButtonsAction/ProductCompareButton.tsx
  project-base/storefront/components/Blocks/Product/Filter/FilterGroupParameters.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductItem.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductsList.tsx
  project-base/storefront/components/Forms/Button/Button.tsx
  project-base/storefront/components/Layout/Header/AutocompleteSearch/Autocomplete.tsx
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSearch.tsx
  project-base/storefront/components/Layout/Header/Cart/Cart.tsx
  project-base/storefront/components/Layout/Header/DropdownMenu/DropdownItem.tsx
  project-base/storefront/components/Layout/Header/DropdownMenu/DropdownMenu.tsx
  project-base/storefront/components/Layout/Header/Header.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconic.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicElements.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemLogin.tsx
  project-base/storefront/components/Layout/LoadingHandler.tsx
  project-base/storefront/components/Pages/Cart/EmptyCartWrapper.tsx
  project-base/storefront/components/Pages/NewPassword/NewPasswordContent.tsx
  project-base/storefront/components/Pages/Order/PaymentConfirmation/Gateways/GoPayGateway.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelect.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailAvailability.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  project-base/storefront/components/Pages/ProductsComparison/ButtonRemoveAll.tsx
  project-base/storefront/components/Pages/ProductsComparison/Content.tsx
  project-base/storefront/components/Pages/ProductsComparison/Head.tsx
  project-base/storefront/components/Pages/ProductsComparison/HeadItem.tsx
  project-base/storefront/components/Pages/ProductsComparison/HeadSticky.tsx
  project-base/storefront/components/Pages/ProductsComparison/ProductsComparison.tsx
  project-base/storefront/connectors/cart/Cart.ts
  project-base/storefront/connectors/customer/CurrentCustomer.ts
  project-base/storefront/cypress/integration/Functions/header.js
  project-base/storefront/docker/Dockerfile
  project-base/storefront/docker/ci.Dockerfile
  project-base/storefront/docker/dev.Dockerfile
  project-base/storefront/docs/gtm/gtm.md
  project-base/storefront/helpers/gtm/gtm.ts
  project-base/storefront/hooks/auth/useAuth.tsx
  project-base/storefront/hooks/cart/useAddToCart.ts
  project-base/storefront/hooks/cart/useReloadCart.ts
  project-base/storefront/hooks/comparison/useComparison.tsx
  project-base/storefront/hooks/comparison/useComparisonTable.tsx
  project-base/storefront/hooks/helpers/useComponentUpdate.ts
  project-base/storefront/hooks/ui/useEffectOnce.ts
  project-base/storefront/package.json
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/flags/[flagSlug].tsx
  project-base/storefront/pages/order-payment-confirmation.tsx
  project-base/storefront/pages/order/contact-information.tsx
  project-base/storefront/pages/order/payment-status-notify.tsx
  project-base/storefront/pnpm-lock.yaml
  project-base/storefront/store/zustand/slices/createGeneralSlice.ts
  project-base/storefront/store/zustand/slices/createUserSlice.ts
  project-base/storefront/types/cart.ts
Labels: DX & Refactoring

#2648 [shopsys] deployment
  .github/workflows/docker-build.yaml
  .gitignore
  composer.json
  docker/conf/docker-compose.github-actions.review.yml.dist
  docs/frontend-api/introduction-to-frontend-api.md
  docs/installation/installation-using-docker-on-production-server.md
  packages/s3-bridge/src/ShopsysS3BridgeBundle.php
  project-base/.gitlab-ci.yml
  project-base/app/app/preload.php
  project-base/app/composer.json
  project-base/app/config/bundles.php
  project-base/app/config/packages/frontend_api.yaml
  project-base/app/deploy/basicHttpAuth
  project-base/app/deploy/deploy-project.sh
  project-base/app/deploy/parts/whitelist-ip.sh
  project-base/app/docker/php-fpm/Dockerfile
  project-base/gitlab/docker-compose-ci.yml
  project-base/gitlab/mirror-repository/gitlab-stage.yml
  project-base/gitlab/mirror-repository/mirror.sh
  project-base/scripts/install.sh
  upgrade/UPGRADE-v13.0.0-dev.md
Labels: Infrastructure

#2674 ensure only project classes are updated via annotation fixer
  packages/framework/src/Command/ExtendedClassesAnnotationsCommand.php
Labels: Bug

#2654 Implemented SEO category functionality on storefront
  packages/frontend-api/src/Component/Arguments/PaginatorArgumentsBuilder.php
  project-base/app/config/graphql/types/ModelType/Product/Filter/ParameterFilter.types.yaml
  project-base/app/config/graphql/types/ModelType/Product/Filter/ParameterSliderFilterOption.types.yaml
  project-base/app/config/graphql/types/Query/Category/CategoryQuery.types.yaml
  project-base/app/config/graphql/types/Query/Product/ProductQuery.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
  project-base/app/src/FrontendApi/Component/SessionChecker/SessionChecker.php
  project-base/app/src/FrontendApi/Model/Product/Filter/ParameterFilterOption.php
  project-base/app/src/FrontendApi/Model/Product/Filter/ProductFilterOptionsFactory.php
  project-base/app/src/FrontendApi/Resolver/Category/CategoryQuery.php
  project-base/app/src/FrontendApi/Resolver/Products/ProductsQuery.php
  project-base/app/src/FrontendApi/Resolver/Slug/SlugQuery.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringOptionsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/graphql/SliderFilterInCategory.graphql
  project-base/storefront/components/Basic/Head/BreadcrumbsMetadata.tsx
  project-base/storefront/components/Basic/RangeSlider/RangeSlider.tsx
  project-base/storefront/components/Blocks/Product/Filter/FilterGroupGeneric.tsx
  project-base/storefront/components/Blocks/Product/Filter/FilterGroupParameters.tsx
  project-base/storefront/components/Blocks/Product/Filter/SelectedParameters.tsx
  project-base/storefront/components/Blocks/SortingBar/SortingBar.tsx
  project-base/storefront/components/Pages/BrandDetail/BrandDetailProductsWrapper.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailProductsWrapper.tsx
  project-base/storefront/components/Pages/FlagDetail/FlagDetailProductsWrapper.tsx
  project-base/storefront/docs/gtm/gtm.md
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/brands/fragments/BrandDetailFragment.graphql
  project-base/storefront/graphql/requests/categories/fragments/CategoryDetailFragment.graphql
  project-base/storefront/graphql/requests/categories/fragments/NavigationSubCategoriesLinkFragment.graphql
  project-base/storefront/graphql/requests/categories/fragments/SimpleCategoryFragment.graphql
  project-base/storefront/graphql/requests/categories/queries/CategoryDetailQuery.graphql
  project-base/storefront/graphql/requests/flags/fragments/FlagDetailFragment.graphql
  project-base/storefront/graphql/requests/navigation/fragments/ColumnCategoryFragment.graphql
  project-base/storefront/graphql/requests/productFilterOptions/fragments/ProductFilterOptionsParametersSliderFragment.graphql
  project-base/storefront/graphql/requests/products/fragments/ListedProductsPreviewFragment.graphql
  project-base/storefront/graphql/requests/products/queries/BrandProductsQuery.graphql
  project-base/storefront/graphql/requests/products/queries/CategoryProductsQuery.graphql
  project-base/storefront/graphql/requests/products/queries/FlagProductsQuery.graphql
  project-base/storefront/helpers/filterOptions/mapParametersFilter.ts
  project-base/storefront/helpers/filterOptions/seoCategories.ts
  project-base/storefront/helpers/gtm/gtm.ts
  project-base/storefront/helpers/gtm/mappers.ts
  project-base/storefront/helpers/misc/getLoginUrlWithRedirect.ts
  project-base/storefront/helpers/parsing/stringWIthoutSlash.ts
  project-base/storefront/helpers/seo/generateCanonicalUrl.ts
  project-base/storefront/hooks/graphQl/useQueryError.ts
  project-base/storefront/hooks/useQueryParams.ts
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/flags/[flagSlug].tsx
  project-base/storefront/schema.graphql.json
  project-base/storefront/store/zustand/slices/createSeoCategorySlice.ts
  project-base/storefront/store/zustand/useSessionStore.ts
  project-base/storefront/types/friendlyUrl.ts
Labels: Enhancement, Frontend API
