Repository shopsys/shopsys, pull requests merged in 2023-12, with the labels that each got.

#2923 [SSP-1962] package.json fix to minors
  UPGRADE-14.0.md
  project-base/storefront/components/Basic/RangeSlider/RangeSlider.tsx
  project-base/storefront/components/Forms/TextInput/SearchInput.tsx
  project-base/storefront/components/Forms/TextInput/TextInput.tsx
  project-base/storefront/components/Forms/Textarea/Textarea.tsx
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
Labels: dependencies

#2943 docker-compose: remove img proxy container name for CI review
  docker/conf/docker-compose.github-actions.review.simplified.yml.dist
  docker/conf/docker-compose.github-actions.review.yml.dist
  project-base/gitlab/docker-compose-ci-review.yml
Labels: Infrastructure

#2938 monorepo coding standards: ensure all packages use the same cyclomatic complexity setting
  ecs.php
  packages/coding-standards/ecs.php
  packages/coding-standards/src/Helper/CyclomaticComplexitySniffSetting.php
  packages/framework/composer.json
  packages/framework/ecs.php
  project-base/app/ecs.php
Labels: coding standards

#2936 order info is now asynchronously sent to Heureka after order is created
  UPGRADE-14.0.md
  packages/framework/src/Model/Heureka/HeurekaFacade.php
  packages/framework/src/Model/Order/Messenger/HeurekaPlacedOrderMessageHandler.php
  packages/framework/src/Model/Order/Messenger/PlacedOrderMessage.php
  packages/framework/src/Model/Order/Messenger/PlacedOrderMessageDispatcher.php
  packages/framework/src/Model/Order/OrderFacade.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/tests/Unit/Model/Order/OrderFacadeHeurekaTest.php
  packages/frontend-api/src/Model/Order/PlaceOrderFacade.php
  project-base/app/.env.test
  project-base/app/config/packages/messenger.yaml
  project-base/app/config/packages/monolog.yaml
  project-base/app/deploy/deploy-project.sh
  project-base/app/docker/php-fpm/consumer-entrypoint.sh
  project-base/app/src/FrontendApi/Model/Order/PlaceOrderFacade.php
  project-base/app/src/Model/Order/OrderFacade.php
Labels: Enhancement

#2945 [shospys] improved feed memory usage, iterated crons are now able to sleep before memory overflow and improved feed generation logging
  UPGRADE-14.0.md
  docs/introduction/cron.md
  packages/framework/src/Component/Bytes/BytesHelper.php
  packages/framework/src/Component/Cron/CronModuleExecutor.php
  packages/framework/src/Model/Feed/FeedCronModule.php
  packages/framework/src/Model/Feed/FeedExport.php
  packages/framework/src/Model/Feed/FeedExportFactory.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/tests/Unit/Component/Bytes/BytesHelperTest.php
  packages/framework/tests/Unit/Component/Cron/CronFacadeTest.php
  packages/framework/tests/Unit/Component/Cron/CronModuleExecutorTest.php
  project-base/app/config/services.yaml
  project-base/app/src/Model/Feed/FeedExportFactory.php
Labels: DX & Refactoring

#2950 docker-compose: add rabbitMQ container for cypress tests on gitlab CI
  UPGRADE-14.0.md
  project-base/gitlab/docker-compose-ci.yml
Labels: Infrastructure

#2951 [project-base] stores tests enhancements
  UPGRADE-14.0.md
  project-base/app/tests/FrontendApiBundle/Functional/Store/GetStoreTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Store/GetStoresTest.php
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/query/StoreOpeningHoursQuery.graphql
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/query/StoreQuery.graphql
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/query/StoresQuery.graphql
Labels: DX & Refactoring

#2948 [project-base] more file types are now allowed to upload in wysiwyg editor
  UPGRADE-14.0.md
  project-base/app/config/packages/fm_elfinder.yaml
Labels: Enhancement, Easy Pick

#2947 [shopsys] improved upgrade instructions for read-model removal
  UPGRADE-14.0.md
Labels: Documentation

#2955 [documentation] added upgrade note for product recalculations via queue
  UPGRADE-14.0.md
  upgrade-product-recalculations.md
Labels: Documentation

#2953 [project-base] messages are now consumed on gitlab ci review
  .github/set-urls-for-review.sh
  .github/workflows/docker-build.yaml
  UPGRADE-14.0.md
  project-base/.gitlab-ci.yml
  project-base/gitlab/docker-compose-ci-review.yml
  project-base/gitlab/scripts/rabbitmq-vhost.sh
  project-base/gitlab/scripts/set-urls-for-review.sh
Labels: Infrastructure

#2949 [shopsys] improved storefront translations cache invalidation
  .github/cancel-review.sh
  UPGRADE-14.0.md
  composer.json
  packages/framework/build.xml
  project-base/app/composer.json
  project-base/storefront/i18n-translator.js
  project-base/storefront/i18n.js
Labels: Bug

#2495 [shopsys] Elasticsearch: defined structure for ID
  UPGRADE-14.0.md
  packages/framework/src/Model/Product/Search/ProductElasticsearchConverter.php
  packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
  packages/framework/tests/Unit/Model/Product/Search/ProductElasticsearchConverterTest.php
  project-base/app/src/Resources/definition/product/1.json
  project-base/app/src/Resources/definition/product/2.json
Labels: DX & Refactoring, In Backlog
