Repository shopsys/shopsys, pull requests merged in 2023-11, with the labels that each got.

#2887 added USPs to product detail page
  UPGRADE-14.0.md
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailUsps.tsx
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/products/fragments/ProductDetailFragment.graphql
Labels: Enhancement, Easy Pick

#2908 [project-base] fixed ProductsQuery Gatling simulation to wait for http response
  project-base/gatling/gatling/simulations/graphql/ProductsQuery.scala
Labels: Bug

#2895 [FW-1678] search on search page is now not called if search query is empty
  UPGRADE-14.0.md
  project-base/storefront/components/Pages/Search/SearchContent.tsx
  project-base/storefront/pages/search.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
Labels: Bug

#2912 [shopsys] all commands are now named via attribute
  packages/framework/src/Command/ChangeAdminPasswordCommand.php
  packages/framework/src/Command/ChangeEnvironmentCommand.php
  packages/framework/src/Command/CheckRedisCommand.php
  packages/framework/src/Command/CheckTimezonesCommand.php
  packages/framework/src/Command/CleanOpcacheCommand.php
  packages/framework/src/Command/ConfigureDomainsUrlsCommand.php
  packages/framework/src/Command/CreateApplicationDirectoriesCommand.php
  packages/framework/src/Command/CreateDatabaseCommand.php
  packages/framework/src/Command/CreateDatabaseSchemaCommand.php
  packages/framework/src/Command/CreateDomainsDataCommand.php
  packages/framework/src/Command/CreateDomainsDbFunctionsCommand.php
  packages/framework/src/Command/CronCommand.php
  packages/framework/src/Command/CronLockCommand.php
  packages/framework/src/Command/CronWatchCommand.php
  packages/framework/src/Command/DatabaseDumpCommand.php
  packages/framework/src/Command/DomainInfoCommand.php
  packages/framework/src/Command/DropDatabaseSchemaCommand.php
  packages/framework/src/Command/ElFinderInstallerCommand.php
  packages/framework/src/Command/Elasticsearch/ElasticsearchChangedDataExportCommand.php
  packages/framework/src/Command/Elasticsearch/ElasticsearchDataExportCommand.php
  packages/framework/src/Command/Elasticsearch/ElasticsearchIndexesDeleteCommand.php
  packages/framework/src/Command/Elasticsearch/ElasticsearchIndexesMigrateCommand.php
  packages/framework/src/Command/EntitiesDumpCommand.php
  packages/framework/src/Command/ExtendedClassesAnnotationsCommand.php
  packages/framework/src/Command/GenerateErrorPagesCommand.php
  packages/framework/src/Command/GenerateFriendlyUrlCommand.php
  packages/framework/src/Command/ImportDefaultDatabaseSchemaCommand.php
  packages/framework/src/Command/LoadPluginDataFixturesCommand.php
  packages/framework/src/Command/MaintenanceModeCommand.php
  packages/framework/src/Command/PhingConfigFixerCommand.php
  packages/framework/src/Command/RecalculateCategoryTreeCommand.php
  packages/framework/src/Command/RecalculationsCommand.php
  packages/framework/src/Command/RedisCleanCacheCommand.php
  packages/framework/src/Command/RedisCleanCacheOldCommand.php
  packages/framework/src/Command/ReplaceDomainsUrlsCommand.php
  packages/framework/src/Command/RouterDebugCommandForDomain.php
  packages/framework/src/Command/RouterMatchCommandForDomain.php
  packages/framework/src/Command/TranslationReplaceSourceCommand.php
  packages/framework/src/Command/YamlLintCommand.php
  packages/migrations/src/Command/CheckDatabaseSchemaCommand.php
  packages/migrations/src/Command/CheckOrmMappingCommand.php
  packages/migrations/src/Command/GenerateMigrationCommand.php
  packages/migrations/src/Command/GetCountOfMigrationsToExecuteCommand.php
  packages/migrations/src/Command/MigrateCommand.php
  project-base/app/src/Command/CheckUnusedFriendlyUrlRouteNameListCommand.php
  project-base/app/src/Command/CleanStorefrontQueryCacheCommand.php
  project-base/app/src/Command/ImportPoFilesCommand.php
  project-base/app/src/Command/PerformanceDataCommand.php
  project-base/app/src/Command/ReplaceCdnDomainUrlCommand.php
Labels: DX & Refactoring

#2915 [framework] RedisClientFacade::contains() now throws exception when Redis is in multimode
  packages/framework/src/Component/Redis/Exception/RedisMultiModeNotSupportedException.php
  packages/framework/src/Component/Redis/RedisClientFacade.php
Labels: Bug

#2914 [shopsys] replaced custom application bootstraping with symfony/runtime
  UPGRADE-14.0.md
  composer.json
  project-base/app/app/autoload.php
  project-base/app/app/getEnvironment.php
  project-base/app/bin/console
  project-base/app/composer.json
  project-base/app/config/bootstrap.php
  project-base/app/config/packages/framework.yaml
  project-base/app/phpunit.xml
  project-base/app/src/Kernel.php
  project-base/app/tests/bootstrap.php
  project-base/app/web/index.php
  project-base/app/web/resolveFriendlyUrl.php
Labels: DX & Refactoring

#2920 [SSP-1902] removed error logging for GTM safe push
  UPGRADE-14.0.md
  docs/storefront/gtm/intro.md
  project-base/storefront/gtm/helpers/gtm.ts
Labels: Easy Pick

#2921 [SSP-1960] added logic for orgering GTM events
  UPGRADE-14.0.md
  docs/storefront/gtm/context.md
  docs/storefront/gtm/index.md
  docs/storefront/gtm/navigation.yml
  project-base/storefront/components/Pages/App/AppPageContent.tsx
  project-base/storefront/gtm/context/GtmProvider.tsx
  project-base/storefront/gtm/context/useGtmContext.ts
  project-base/storefront/gtm/hooks/productList/useGtmPaginatedProductListViewEvent.ts
  project-base/storefront/gtm/hooks/productList/useGtmSliderProductListViewEvent.ts
  project-base/storefront/gtm/hooks/useGtmAutocompleteResultsViewEvent.ts
  project-base/storefront/gtm/hooks/useGtmCartViewEvent.ts
  project-base/storefront/gtm/hooks/useGtmContactInformationPageViewEvent.ts
  project-base/storefront/gtm/hooks/useGtmPageViewEvent.ts
  project-base/storefront/gtm/hooks/useGtmPaymentAndTransportPageViewEvent.ts
  project-base/storefront/gtm/hooks/useGtmProductDetailViewEvent.ts
Labels: Enhancement, Easy Pick

#2891 [FW-1848] SEO categories with ignored filters
  UPGRADE-14.0.md
  docs/storefront/unit-tests.md
  project-base/app/src/DataFixtures/Demo/ReadyCategorySeoDataFixture.php
  project-base/app/src/Model/Product/Parameter/ParameterRepository.php
  project-base/app/tests/FrontendApiBundle/Functional/Category/ReadyCategorySeoMix/ReadyCategorySeoMixTest.php
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/query/ReadyCategorySeoMixQuery.graphql
  project-base/storefront/components/Blocks/SortingBar/SortingBar.tsx
  project-base/storefront/components/Pages/CategoryDetail/helpers.ts
  project-base/storefront/config/constants.ts
  project-base/storefront/helpers/arrayUtils.ts
  project-base/storefront/helpers/filterOptions/buildNewQueryAfterFilterChange.ts
  project-base/storefront/helpers/filterOptions/getFilterWithoutEmpty.ts
  project-base/storefront/helpers/filterOptions/seoCategories.ts
  project-base/storefront/helpers/parsing/urlParsing.ts
  project-base/storefront/hooks/seoCategories/useHandleDefaultFiltersUpdate.ts
  project-base/storefront/hooks/useQueryParams.ts
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/vitest/helpers/filterOptions/buildNewQueryAfterFilterChange.test.ts
  project-base/storefront/vitest/helpers/filterOptions/getFilterWithoutEmpty.test.ts
  project-base/storefront/vitest/helpers/filterOptions/seoCategories.getFilterWithoutSeoSensitiveFilters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.resetAllFilters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterBrands.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterFlags.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterInStock.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterParameters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMaximum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMinimum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPrices.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateSort.test.ts
Labels: Enhancement

#2922 [shopsys] added ability to schedule each cron for specific time same way as crons
  UPGRADE-14.0.md
  docs/cookbook/basic-data-import.md
  docs/cookbook/working-with-multiple-cron-instances.md
  docs/model/product-feeds.md
  packages/framework/src/Command/CronCommand.php
  packages/framework/src/Command/ScheduleFeedsCommand.php
  packages/framework/src/Component/Cron/Config/CronConfig.php
  packages/framework/src/Component/Cron/CronTimeInterface.php
  packages/framework/src/Component/Cron/CronTimeResolver.php
  packages/framework/src/Component/DateTimeHelper/DateTimeHelper.php
  packages/framework/src/Component/Domain/Domain.php
  packages/framework/src/Controller/Admin/FeedController.php
  packages/framework/src/DependencyInjection/Compiler/RegisterProductFeedConfigsCompilerPass.php
  packages/framework/src/Migrations/Version20231114121946.php
  packages/framework/src/Model/Feed/Exception/FeedNotFoundException.php
  packages/framework/src/Model/Feed/FeedConfig.php
  packages/framework/src/Model/Feed/FeedCronModule.php
  packages/framework/src/Model/Feed/FeedExportCreationDataQueue.php
  packages/framework/src/Model/Feed/FeedFacade.php
  packages/framework/src/Model/Feed/FeedModule.php
  packages/framework/src/Model/Feed/FeedModuleFactory.php
  packages/framework/src/Model/Feed/FeedModuleFactoryInterface.php
  packages/framework/src/Model/Feed/FeedModuleRepository.php
  packages/framework/src/Model/Feed/FeedRegistry.php
  packages/framework/src/Model/Feed/HourlyFeedCronModule.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/config/services_test.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Feed/listGrid.html.twig
  packages/framework/tests/Unit/Component/Domain/DomainTest.php
  packages/framework/tests/Unit/Model/Feed/FeedCronModuleTest.php
  packages/product-feed-google/src/Resources/config/services.yaml
  packages/product-feed-heureka-delivery/src/Resources/config/services.yaml
  packages/product-feed-heureka/src/Resources/config/services.yaml
  packages/product-feed-zbozi/src/Resources/config/services.yaml
  project-base/app/config/cron.yaml
  project-base/app/config/feed.yaml
  project-base/app/config/services.yaml
  project-base/app/src/Model/Feed/FeedFacade.php
  project-base/app/tests/App/Performance/Feed/AllFeedsTest.php
  project-base/app/tests/App/Smoke/Http/RouteConfigCustomization.php
Labels: Enhancement
