Repository shopsys/shopsys, pull requests merged in 2023-10, with the labels that each got.

#2830 [shopsys] graphql-bundle classes are now dumped so they can use composer autoload
  composer.json
  project-base/app/composer.json
  project-base/app/config/directories.yaml
  project-base/app/config/packages/overblog_dataloader.yaml
  project-base/app/config/packages/overblog_graphql.yaml
  upgrade/UPGRADE-v13.0.0-dev.md
Labels: DX & Refactoring

#2842 [project-base] fixed argument passing to productsByCatnum query
  project-base/app/config/graphql/types/Query/Product/ProductQuery.types.yaml
  project-base/app/src/FrontendApi/Resolver/Products/ProductsQuery.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsByCatnumsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/graphql/productsByCatnums.graphql
Labels: Bug

#2841 [project-base] fixed closed day edit
  project-base/app/src/Form/Admin/ClosedDayFormType.php
Labels: Bug

#2845 [project-base] fixed edit language constant
  project-base/app/config/packages/snc_redis.yaml
Labels: Bug

#2843 [project-base] added validation to suppliers delivery time
  project-base/app/src/Form/Admin/ProductFormTypeExtension.php
  project-base/app/translations/validators.cs.po
  project-base/app/translations/validators.en.po
Labels: Bug

#2846 [project-base] fixed sentry logging on production
  project-base/app/config/packages/prod/monolog.yaml
Labels: Bug

#2834 database, redis, and elastic is now cleaned after PR merge
  .github/cancel-review.sh
  project-base/app/config/packages/snc_redis.yaml
  project-base/app/src/Command/CleanStorefrontQueryCacheCommand.php
  project-base/app/src/Component/Redis/CleanStorefrontCacheFacade.php
  project-base/app/tests/App/Functional/Component/Redis/RedisVersionsFacadeTest.php
Labels: Infrastructure

#2837 moved login popup outside of the contact information form
  project-base/storefront/components/Pages/Order/ContactInformation/ContactInformationContent.tsx
  project-base/storefront/pages/order/contact-information.tsx
Labels: Bug

#2794 brands SEO sensitive config
  project-base/storefront/helpers/filterOptions/seoCategories.ts
  project-base/storefront/hooks/useQueryParams.ts
  project-base/storefront/store/slices/createSeoCategorySlice.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.resetAllFilters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterBrands.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterFlags.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterInStock.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterParameters.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMaximum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPriceMinimum.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateFilterPrices.test.ts
  project-base/storefront/vitest/hooks/useQueryParams/useQueryParams.updateSort.test.ts
Labels: Enhancement

#2844 [project-base] admin with limited permissions now can use domain filter
  project-base/app/config/packages/security.yaml
  upgrade/UPGRADE-v13.0.0-dev.md
Labels: Bug

#2847 [shopsys] improved permissions handling in admin
  packages/framework/assets/js/admin/components/GridDragAndDrop.js
  packages/framework/assets/js/common/utils/Ajax.js
  packages/framework/src/Controller/Admin/AccessController.php
  project-base/app/config/packages/security.yaml
  project-base/app/src/Form/Admin/AdministratorFormTypeExtension.php
  project-base/app/tests/App/Smoke/Http/RouteConfigCustomization.php
Labels: Security

#2838 [project-base] seo category mix slug now includes trailing slash and is consistent with other slugs
  project-base/app/src/FrontendApi/Model/Category/ReadyCategorySeoMixBatchLoader.php
  project-base/app/tests/FrontendApiBundle/Functional/Category/CategoryTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Category/ReadyCategorySeoMix/ReadyCategorySeoMixTest.php
Labels: Bug

#2860 [infrastructure] added information about GitHub limits and increased verbosity of composer install on CI servers
  project-base/app/docker/php-fpm/Dockerfile
Labels: DX & Refactoring

#2840 fixed redis cache on storefront
  docs/storefront/caching.md
  docs/storefront/unit-tests.md
  project-base/storefront/.eslintrc.js
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/articlesInterface/articles/queries/ArticlesQuery.graphql
  project-base/storefront/graphql/requests/articlesInterface/blogArticles/queries/BlogArticlesQuery.graphql
  project-base/storefront/graphql/requests/directives.graphql
  project-base/storefront/graphql/requests/navigation/queries/NavigationQuery.graphql
  project-base/storefront/graphql/requests/notificationBars/queries/NotificationBarsQuery.graphql
  project-base/storefront/graphql/requests/settings/queries/SettingsQuery.graphql
  project-base/storefront/helpers/serverSide/initServerSideProps.ts
  project-base/storefront/urql/createClient.ts
  project-base/storefront/urql/fetcher.ts
  project-base/storefront/vitest.config.js
  project-base/storefront/vitest/helpers/urql/createClient.test.tsx
  project-base/storefront/vitest/helpers/urql/fetcher.test.ts
Labels: Bug

#2850 [infrastructure] fixed cancelling of reviews after seven days
  .github/cancel-old-reviews.sh
  .github/workflows/cancel-old-reviews.yaml
Labels: Infrastructure

#2854 [framework] added optional manual readable frequency to crons.yaml
  docs/introduction/cron.md
  packages/framework/src/Component/Cron/Config/CronConfig.php
  packages/framework/src/Component/Cron/Config/CronModuleConfig.php
  packages/framework/src/DependencyInjection/Compiler/RegisterCronModulesCompilerPass.php
  packages/framework/tests/Unit/Component/Cron/CronFacadeTest.php
  packages/framework/tests/Unit/Component/Cron/CronModuleExecutorTest.php
  upgrade/UPGRADE-v13.0.0-dev.md
Labels: DX & Refactoring

#2862 [github-actions] improved removing the branches from packages
  .github/monorepo/remove_branch.sh
Labels: Infrastructure

#2849 [shopsys] updated our LICENSE by new one for version 13.0
  LICENSE
  open-source-license-acknowledgements-and-third-party-copyrights.md
  packages/backend-api/LICENSE
  packages/framework/LICENSE
  packages/frontend-api/LICENSE
  packages/read-model/LICENSE
  packages/s3-bridge/LICENSE
  project-base/LICENSE
  upgrade/UPGRADE-v13.0.0-dev.md
  utils/license-acknowledgements-generator/template.md
Labels: Documentation

#2852 [project-base] personal pickup transport is now a type instead of a separate field
  project-base/app/src/DataFixtures/Demo/TransportDataFixture.php
  project-base/app/src/Form/Admin/TransportFormTypeExtension.php
  project-base/app/src/Migrations/Version20231004072533.php
  project-base/app/src/Model/Transport/Transport.php
  project-base/app/src/Model/Transport/TransportData.php
  project-base/app/src/Model/Transport/TransportDataFactory.php
  project-base/app/src/Model/Transport/Type/TransportType.php
  project-base/app/src/Model/Transport/Type/TransportTypeEnum.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/CartTransportTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Transport/TransportsTest.php
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentContent.tsx
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/transports/fragments/SimpleTransportFragment.graphql
  project-base/storefront/pages/order/transport-and-payment.tsx
Labels: Enhancement

#2861 [monorepo] updated releaser with changes in the new version
  utils/releaser/config/after-release.php
  utils/releaser/config/release-candidate.php
  utils/releaser/src/GithubActions/GithubActionsStatusReporter.php
  utils/releaser/src/ReleaseWorker/AfterRelease/CheckHeimdallBuildReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/EnableMergingReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/MergeBranchToTheHigherBranchesReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/RemoveLockFilesReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/SetMutualDependenciesToDevelopmentVersionReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/UpdateDemoProjectBaseReleaseWorker.php
  utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagReleaseWorker.php
  utils/releaser/src/ReleaseWorker/Release/MergeReleaseCandidateBranchReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckBranchSplitReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckLatestVersionOfReleaserReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckProjectBaseBuild.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckShopsysInstallReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ForceYourBranchSplitReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/SendBranchForReviewAndTestsReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/VerifyMinorUpgradeReleaseWorker.php
Labels: Enhancement

#2839 [infrastructure] added composer security check to GitHub Actions
  .github/workflows/security-check.yaml
Labels: Infrastructure

#2807 Transport and payment page fetching state refactoring
  .github/workflows/docker-build.yaml
  docker/conf/docker-compose.github-actions.review.simplified.yml.dist
  docker/conf/docker-compose.github-actions.review.yml.dist
  project-base/storefront/components/Layout/OrderLayout/OrderLayout.tsx
  project-base/storefront/components/Layout/OrderLayout/OrderLayoutContentSkeleton.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentContent.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelect.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelectItemLabel.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/helpers.ts
  project-base/storefront/gtm/helpers/mappers.ts
  project-base/storefront/pages/order/contact-information.tsx
  project-base/storefront/pages/order/transport-and-payment.tsx
Labels: Bug, Enhancement, DX & Refactoring

#2869 [infrastructure] Packetery and GoPay are now enabled on review server
  .github/workflows/docker-build.yaml
  docker/conf/docker-compose.github-actions.review.simplified.yml.dist
  docker/conf/docker-compose.github-actions.review.yml.dist
Labels: Infrastructure

#2870 [shopsys] moved migration from Google feed to framework as it was placed incorrectly
  UPGRADE-13.0.md
  packages/framework/src/Migrations/Version20230220115918.php
  packages/product-feed-google/src/Migrations/Version20230220115918.php
Labels: Bug

#2868 [infrastructure] added translations dump check
  .github/get-build-exit-code.sh
  .github/workflows/docker-build.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
Labels: Infrastructure

#2873 [shopsys] ported fixes from release 13.0.0
  project-base/app/check-composer-json.sh
  project-base/app/composer.json
  project-base/check-composer-json.sh
  project-base/composer.json
  project-base/storefront/components/Blocks/Product/ButtonsAction/ProductCompareButton.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  utils/releaser/src/ReleaseWorker/Release/CreateAndCommitLockFilesReleaseWorker.php
  utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagsExceptProjectBaseReleaseWorker.php
Labels: Bug

#2880 [shopsys] added test to keep elasticsearch converter and mapping in sync
  UPGRADE-14.0.md
  packages/framework/src/Model/Product/Search/ProductElasticsearchConverter.php
  packages/framework/tests/Unit/Model/Product/Search/ProductElasticsearchConverterTest.php
  project-base/app/ecs.php
  project-base/app/src/Model/Product/Search/ProductElasticsearchConverter.php
  project-base/app/src/Resources/definition/product/1.json
  project-base/app/src/Resources/definition/product/2.json
  project-base/app/tests/App/Unit/Model/Product/Search/ProductElasticsearchConverterTest.php
Labels: DX & Refactoring

#2370 [framework] fixed access to nullable country
  packages/framework/src/Resources/views/Admin/Form/deliveryAddressListFields.html.twig
Labels: Bug, In Backlog

#2587 [framework] set products for export to elastic after changing quantity after completing, editing, or deleting order
  UPGRADE-14.0.md
  packages/framework/src/Model/Order/Item/OrderProductFacade.php
  packages/framework/tests/Unit/Model/Order/Item/OrderProductFacadeTest.php
Labels: In Backlog

#2888 [FW-1879] removed unnecessary default value for domainConfig
  UPGRADE-14.0.md
  project-base/storefront/hooks/useDomainConfig.ts
  project-base/storefront/store/slices/createDomainSlice.ts
Labels: Easy Pick, DX & Refactoring

#2882 [FW-1875] fixed undefined window error
  UPGRADE-14.0.md
  docs/storefront/gtm/intro.md
  project-base/storefront/components/Pages/Wishlist/Wishlist.tsx
  project-base/storefront/gtm/GtmHeadScript.tsx
  project-base/storefront/gtm/helpers/gtm.ts
  project-base/storefront/gtm/helpers/helpers.ts
  project-base/storefront/helpers/isClient.ts
  project-base/storefront/helpers/isRedirectedFromSsr.ts
  project-base/storefront/helpers/isServer.ts
  project-base/storefront/helpers/toasts.tsx
  project-base/storefront/pages/articles/[articleSlug].tsx
  project-base/storefront/pages/blogArticles/[blogArticleSlug].tsx
  project-base/storefront/pages/blogCategories/[blogCategorySlug].tsx
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/flags/[flagSlug].tsx
  project-base/storefront/pages/products/[productSlug].tsx
  project-base/storefront/pages/stores/[storeSlug].tsx
  project-base/storefront/urql/fetcher.ts
  project-base/storefront/vitest/helpers/urql/createClient.test.tsx
  project-base/storefront/vitest/helpers/urql/fetcher.test.ts
Labels: Bug

#2877 [infrastructure] test project-base with only one domain on GitHub actions
  .github/workflows/rebuild-docker-images.yaml
  UPGRADE-14.0.md
  packages/backend-api/.github/workflows/run-checks-tests.yaml
  packages/form-types-bundle/.github/workflows/run-checks-tests.yaml
  packages/framework/.github/workflows/run-checks-tests.yaml
  packages/frontend-api/.github/workflows/run-checks-tests.yaml
  packages/google-cloud-bundle/.github/workflows/run-checks-tests.yaml
  packages/migrations/.github/workflows/run-checks-tests.yaml
  packages/plugin-interface/.github/workflows/run-checks-tests.yaml
  packages/product-feed-google/.github/workflows/run-checks-tests.yaml
  packages/product-feed-heureka-delivery/.github/workflows/run-checks-tests.yaml
  packages/product-feed-heureka/.github/workflows/run-checks-tests.yaml
  packages/product-feed-zbozi/.github/workflows/run-checks-tests.yaml
  packages/read-model/.github/workflows/run-checks-tests.yaml
  packages/s3-bridge/.github/workflows/run-checks-tests.yaml
  project-base/.github/workflows/run-checks-tests.yaml
  project-base/app/src/DataFixtures/Demo/ParameterDataFixture.php
  project-base/app/src/DataFixtures/Demo/ReadyCategorySeoDataFixture.php
  project-base/app/src/DataFixtures/Demo/StoreDataFixture.php
  project-base/app/src/Model/Transport/TransportData.php
  project-base/app/tests/App/Functional/Model/Order/Mail/OrderMailTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Store/GetStoreTest.php
Labels: Infrastructure

#2885 add Related Products tab section
  UPGRADE-14.0.md
  project-base/storefront/components/Basic/Tabs/Tabs.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailMainVariantContent.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailTabs.tsx
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/products/fragments/ProductDetailInterfaceFragment.graphql
  project-base/storefront/gtm/types/enums.ts
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
Labels: Enhancement

#2879 [project-base] improvements of product list in grapesjs
  UPGRADE-14.0.md
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-products-plugin.js
  project-base/app/src/Component/GrapesJs/GrapesJsParser.php
  project-base/app/src/Controller/Admin/ProductController.php
  project-base/app/src/DataFixtures/Demo/BlogArticleDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Blog/Article/BlogArticleTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/storefront/components/Basic/UserText/GrapesJsProducts.tsx
  project-base/storefront/helpers/parsing/grapesJsParser.ts
  project-base/storefront/helpers/serverSide/initServerSideProps.ts
Labels: Bug

#2886 [infrastructure] project-base now checks also Storefront checks and runs Storefront with one domain in one domain check
  packages/backend-api/.github/workflows/run-checks-tests.yaml
  packages/coding-standards/.github/workflows/run-checks-tests.yaml
  packages/form-types-bundle/.github/workflows/run-checks-tests.yaml
  packages/framework/.github/workflows/run-checks-tests.yaml
  packages/frontend-api/.github/workflows/run-checks-tests.yaml
  packages/google-cloud-bundle/.github/workflows/run-checks-tests.yaml
  packages/http-smoke-testing/.github/workflows/run-checks-tests.yaml
  packages/migrations/.github/workflows/run-checks-tests.yaml
  packages/plugin-interface/.github/workflows/run-checks-tests.yaml
  packages/product-feed-google/.github/workflows/run-checks-tests.yaml
  packages/product-feed-heureka-delivery/.github/workflows/run-checks-tests.yaml
  packages/product-feed-heureka/.github/workflows/run-checks-tests.yaml
  packages/product-feed-zbozi/.github/workflows/run-checks-tests.yaml
  packages/read-model/.github/workflows/run-checks-tests.yaml
  packages/s3-bridge/.github/workflows/run-checks-tests.yaml
  project-base/.github/keep-only-first-domain.js
  project-base/.github/workflows/run-checks-tests.yaml
  project-base/docker/conf/docker-compose.yml.dist
Labels: Infrastructure

#2889 [shopsys] graphql validation errors now contain violation list in the additional data and allow change the log level
  UPGRADE-14.0.md
  packages/frontend-api/src/Model/Logger/FrontendApiLogger.php
  packages/frontend-api/src/Resources/config/parameters.yaml
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/app/config/packages/overblog_graphql.yaml
  project-base/app/config/parameters_common.yaml
Labels: DX & Refactoring

#2871 [FW-1706] Refactoring of various error-related matters on SF
  UPGRADE-14.0.md
  docs/storefront/error-handling.md
  docs/storefront/navigation.yml
  project-base/storefront/components/Pages/App/AppPageContent.tsx
  project-base/storefront/components/Pages/ErrorPage/Error500Content.tsx
  project-base/storefront/helpers/serverSide/initServerSideProps.ts
  project-base/storefront/middleware.ts
  project-base/storefront/pages/_app.tsx
  project-base/storefront/pages/_error.tsx
Labels: DX & Refactoring

#2903 [shopsys] increase speed of Product creation
  UPGRADE-14.0.md
  packages/framework/build.xml
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
  packages/framework/src/Model/Product/Pricing/ProductManualInputPriceFacade.php
  packages/framework/src/Model/Product/ProductFacade.php
  packages/product-feed-google/src/Model/Product/GoogleProductDomainFacade.php
  packages/product-feed-heureka/src/DataFixtures/HeurekaProductDataFixture.php
  packages/product-feed-heureka/src/Model/Product/HeurekaProductDomainFacade.php
  packages/product-feed-zbozi/src/DataFixtures/ZboziPluginDataFixture.php
  packages/product-feed-zbozi/src/Model/Product/ZboziProductDomainFacade.php
  project-base/app/src/Component/Router/FriendlyUrl/FriendlyUrlFacade.php
  project-base/app/src/DataFixtures/Performance/ProductDataFixture.php
  project-base/app/src/Model/Product/ProductFacade.php
  project-base/app/src/Model/Stock/ProductStockFacade.php
  project-base/app/tests/App/Functional/Model/Cart/Watcher/CartWatcherTest.php
Labels: Performance, DX & Refactoring

#2897 [FW-1788] auth (loading) improvements
  UPGRADE-14.0.md
  project-base/storefront/components/Layout/Header/Cart/Cart.tsx
  project-base/storefront/components/Pages/App/AppPageContent.tsx
  project-base/storefront/components/Pages/Cart/EmptyCartWrapper.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/helpers.ts
  project-base/storefront/components/Pages/OrderConfirmation/RegistrationAfterOrder.tsx
  project-base/storefront/components/Pages/Registration/RegistrationContent.tsx
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/registration/mutations/RegistrationMutation.graphql
  project-base/storefront/hooks/app/useAuthLoader.ts
  project-base/storefront/hooks/app/useLoginLoader.ts
  project-base/storefront/hooks/auth/useAuth.tsx
  project-base/storefront/hooks/auth/useRegistration.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/store/slices/createAuthLoadingSlice.ts
  project-base/storefront/store/slices/createLoginLoadingSlice.ts
  project-base/storefront/store/usePersistStore.ts
Labels: Bug, Enhancement, Easy Pick, DX & Refactoring

#2904 [project-base] added messenger configuration to deployed application
  UPGRADE-14.0.md
  composer.json
  project-base/app/composer.json
  project-base/app/deploy/deploy-project.sh
Labels: Infrastructure
