Repository shopsys/shopsys, pull requests merged in 2023-02, with the labels that each got.

#2546 Fix editing created at of article
  packages/framework/src/Form/Admin/Article/ArticleFormType.php
  packages/framework/src/Model/Article/Article.php
  packages/framework/src/Model/Article/ArticleData.php
  packages/framework/src/Model/Article/ArticleDataFactory.php
  project-base/src/Form/Admin/ArticleFormTypeExtension.php
  project-base/src/Model/Article/Article.php
  project-base/src/Model/Article/ArticleData.php
  project-base/src/Model/Article/ArticleDataFactory.php
  symfony.lock
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: Bug

#2550 [framework] New Redis Commander
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose.yml.dist
  docs/installation/installation-using-docker-application-setup.md
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
  project-base/kubernetes/deployments/redis-admin.yml
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: Infrastructure

#2543 [framework] shutdown kernel after generating error page
  packages/framework/src/Component/Error/ErrorPagesFacade.php
Labels: In Backlog

#2520 [framework] introduced new phing target demo-data that wipes and completely installs demo data including export to Elasticsearch
  docs/introduction/console-commands-for-application-management-phing-targets.md
  packages/framework/build.xml
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: DX & Refactoring

#2553 [releaser] many improvements of releaser
  .ci/monorepo_functions.sh
  CHANGELOG.md
  UPGRADE.md
  composer.json
  docs/introduction/monorepo.md
  packages/coding-standards/composer.json
  symfony.lock
  utils/releaser/config/after-release.php
  utils/releaser/config/release-candidate.php
  utils/releaser/config/release.php
  utils/releaser/src/FileManipulator/GeneralUpgradeFileManipulator.php
  utils/releaser/src/FilesProvider/ComposerJsonFilesProvider.php
  utils/releaser/src/GithubActions/GithubActionsStatusReporter.php
  utils/releaser/src/Packagist/PackageProvider.php
  utils/releaser/src/ReleaseWorker/AbstractShopsysReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/CheckHeimdallBuildReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/CheckPackagesOnPackagistReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/CheckShopsysInstallReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/MeasurePerformanceReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/UpdateDemoProjectBaseReleaseWorker.php
  utils/releaser/src/ReleaseWorker/CheckCorrectReleaseVersionReleaseWorker.php
  utils/releaser/src/ReleaseWorker/Release/CreateAndPushGitTagsExceptProjectBaseReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckBranchSplitReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckLatestVersionOfReleaserReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckNewDoctrineReleaseReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckShopsysInstallReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CreateBranchReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ReleaseNewNodeModulePackageVersion.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/SetMutualDependenciesToVersionReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateChangelogReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateListOfSupportedVersionsReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateUpgradeReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ValidateConflictsInComposerJsonReleaseWorker.php
  utils/releaser/tests/FileManipulator/UpgradeFileManipulator/Source/UPGRADE-general-after.md
  utils/releaser/tests/FileManipulator/UpgradeFileManipulator/Source/UPGRADE-general-before.md
Labels: DX & Refactoring

#2551 [shopsys] Sitemap updates
  packages/framework/src/Model/ImageSitemap/ImageSitemapCronModule.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapDumper.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapDumperFactory.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapFacade.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapFilePrefixer.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapItem.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapItemImage.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapListener.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapPopulateEvent.php
  packages/framework/src/Model/Sitemap/SitemapListener.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/views/Common/robots.txt.twig
  project-base/config/services/cron.yaml
  project-base/src/Controller/Front/RobotsController.php
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: Enhancement

#2558 [shopsys] locked version of jquery-ui to 1.12.1 in order to fix category ordering in admin
  packages/framework/assets/package.json
  project-base/package.json
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: Bug

#2555 [shopsys] Product sorting by availability
  packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
  packages/framework/src/Model/Product/ProductRepository.php
  packages/framework/src/Model/Product/Search/FilterQuery.php
  project-base/src/Resources/definition/product/1.json
  project-base/src/Resources/definition/product/2.json
  project-base/tests/App/Functional/Model/Product/Elasticsearch/ProductExportRepositoryTest.php
  project-base/tests/App/Functional/Model/Product/Search/FilterQueryTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/PaginatedProductsTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsFilteringTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: Enhancement

#2556 [framework] Symfony profiler shows query or mutation name for API requests
  packages/framework/src/Component/HttpKernel/Profiler/FileProfilerStorage.php
Labels: Bug, DX & Refactoring

#2561 [framework] fixed dumping translations by adding support for translation domain constants
  packages/framework/src/Component/Translation/PhpParserNodeHelper.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  project-base/translations/validators.cs.po
  project-base/translations/validators.en.po
Labels: Bug, DX & Refactoring

#2565 [shopsys] added Translator constant for validators
  packages/framework/src/Component/Translation/ConfigConstraintMessageExtractor.php
  packages/framework/src/Component/Translation/ConstraintMessageExtractor.php
  packages/framework/src/Component/Translation/ConstraintMessagePropertyExtractor.php
  packages/framework/src/Component/Translation/ConstraintViolationExtractor.php
  packages/framework/src/Component/Translation/Translator.php
  project-base/tests/App/Acceptance/acceptance/PageObject/Front/RegistrationPage.php
  project-base/tests/FrontendApiBundle/Functional/Customer/User/CurrentCustomerUserTest.php
  project-base/tests/FrontendApiBundle/Functional/Customer/User/RegisterTest.php
  project-base/tests/FrontendApiBundle/Functional/Newsletter/NewsletterTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/CompanyFieldsAreValidatedTest.php
  project-base/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsAreValidatedTest.php
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: DX & Refactoring

#2563 [frontent-api] GQL resolvers refactoring
  docs/frontend-api/introduction-to-frontend-api.md
  packages/framework/src/Model/Localization/IntlCurrencyRepository.php
  packages/frontend-api/src/Model/Mutation/AbstractMutation.php
  packages/frontend-api/src/Model/Mutation/BaseTokenMutation.php
  packages/frontend-api/src/Model/Mutation/Customer/User/CustomerUserMutation.php
  packages/frontend-api/src/Model/Mutation/Login/LoginMutation.php
  packages/frontend-api/src/Model/Mutation/Login/RefreshTokensMutation.php
  packages/frontend-api/src/Model/Mutation/Logout/LogoutMutation.php
  packages/frontend-api/src/Model/Mutation/Newsletter/NewsletterMutation.php
  packages/frontend-api/src/Model/Mutation/Order/CreateOrderMutation.php
  packages/frontend-api/src/Model/Resolver/AbstractQuery.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertPositionsQuery.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertPositionsResolver.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertsQuery.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertsResolver.php
  packages/frontend-api/src/Model/Resolver/Article/ArticleQuery.php
  packages/frontend-api/src/Model/Resolver/Article/ArticlesQuery.php
  packages/frontend-api/src/Model/Resolver/Brand/BrandQuery.php
  packages/frontend-api/src/Model/Resolver/Brand/BrandsQuery.php
  packages/frontend-api/src/Model/Resolver/Brand/BrandsResolver.php
  packages/frontend-api/src/Model/Resolver/Category/CategoriesQuery.php
  packages/frontend-api/src/Model/Resolver/Category/CategoriesResolver.php
  packages/frontend-api/src/Model/Resolver/Category/CategoriesSearchQuery.php
  packages/frontend-api/src/Model/Resolver/Category/CategoryQuery.php
  packages/frontend-api/src/Model/Resolver/Customer/User/CurrentCustomerUserQuery.php
  packages/frontend-api/src/Model/Resolver/Image/ImagesQuery.php
  packages/frontend-api/src/Model/Resolver/Order/OrderQuery.php
  packages/frontend-api/src/Model/Resolver/Order/OrdersQuery.php
  packages/frontend-api/src/Model/Resolver/Payment/PaymentQuery.php
  packages/frontend-api/src/Model/Resolver/Payment/PaymentsQuery.php
  packages/frontend-api/src/Model/Resolver/Payment/PaymentsResolver.php
  packages/frontend-api/src/Model/Resolver/Price/PriceQuery.php
  packages/frontend-api/src/Model/Resolver/Products/ProductDetailQuery.php
  packages/frontend-api/src/Model/Resolver/Products/ProductsQuery.php
  packages/frontend-api/src/Model/Resolver/Products/PromotedProductsQuery.php
  packages/frontend-api/src/Model/Resolver/Products/PromotedProductsResolver.php
  packages/frontend-api/src/Model/Resolver/Transport/TransportQuery.php
  packages/frontend-api/src/Model/Resolver/Transport/TransportsQuery.php
  packages/frontend-api/src/Model/Resolver/Transport/TransportsResolver.php
  packages/frontend-api/src/Resources/config/graphql-types/AdvertImageDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/BrandDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/CategoryDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/MutationDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/PaymentDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ProductDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/TransportDecorator.types.yaml
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/tests/FrontendApiBundle/Functional/Advert/GetAdvertsTest.php
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: DX & Refactoring

#2569 [shopsys] updated Elasticsearch image to newest version in order to support arm processors
  project-base/docker/elasticsearch/Dockerfile
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: DX & Refactoring

#2566 [shopsys] added name to images
  packages/framework/assets/js/admin/components/FileUpload.js
  packages/framework/assets/styles/admin/todo.less
  packages/framework/ecs.php
  packages/framework/src/Component/FileUpload/ImageUploadData.php
  packages/framework/src/Component/FileUpload/ImageUploadDataFactory.php
  packages/framework/src/Component/Image/Image.php
  packages/framework/src/Component/Image/ImageFacade.php
  packages/framework/src/Component/Image/ImageFactory.php
  packages/framework/src/Component/Image/ImageFactoryInterface.php
  packages/framework/src/Component/Image/ImageRepository.php
  packages/framework/src/Component/Image/ImageTranslation.php
  packages/framework/src/Form/ImageUploadType.php
  packages/framework/src/Model/Advert/AdvertData.php
  packages/framework/src/Model/Advert/AdvertDataFactory.php
  packages/framework/src/Model/Category/CategoryData.php
  packages/framework/src/Model/Category/CategoryDataFactory.php
  packages/framework/src/Model/Payment/PaymentData.php
  packages/framework/src/Model/Payment/PaymentDataFactory.php
  packages/framework/src/Model/Product/Brand/BrandData.php
  packages/framework/src/Model/Product/Brand/BrandDataFactory.php
  packages/framework/src/Model/Product/ProductData.php
  packages/framework/src/Model/Product/ProductDataFactory.php
  packages/framework/src/Model/Slider/SliderItemData.php
  packages/framework/src/Model/Slider/SliderItemDataFactory.php
  packages/framework/src/Model/Transport/TransportData.php
  packages/framework/src/Model/Transport/TransportDataFactory.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Form/imageuploadFields.html.twig
  packages/framework/src/Twig/ImageExtension.php
  packages/framework/tests/Unit/Component/Image/ImageFactoryTest.php
  packages/frontend-api/src/Model/Resolver/Image/ImagesQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/ImageDecorator.types.yaml
  packages/product-feed-google/src/Migrations/Version20230220115918.php
  packages/read-model/src/Image/ImageView.php
  packages/read-model/src/Image/ImageViewFactory.php
  packages/read-model/src/Twig/ImageExtension.php
  project-base/src/DataFixtures/Demo/ImageDataFixture.php
  project-base/src/Model/Category/CategoryDataFactory.php
  project-base/src/Model/Payment/PaymentDataFactory.php
  project-base/src/Model/Product/Brand/BrandDataFactory.php
  project-base/src/Model/Product/ProductDataFactory.php
  project-base/src/Model/Transport/TransportDataFactory.php
  project-base/tests/App/Functional/Twig/ImageExtensionTest.php
  project-base/tests/App/Functional/Twig/Resources/picture.twig
  project-base/tests/FrontendApiBundle/Functional/Advert/GetAdvertsTest.php
  project-base/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/tests/ReadModelBundle/Functional/Image/ImageViewFacadeTest.php
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: Enhancement

#2571 [frontend-api] UserEntityNotFoundError has been renamed to EntityNotFoundUserError
  packages/frontend-api/src/Model/Error/EntityNotFoundUserError.php
  packages/frontend-api/src/Model/Resolver/Article/Exception/ArticleNotFoundUserError.php
  packages/frontend-api/src/Model/Resolver/Brand/Exception/BrandNotFoundUserError.php
  packages/frontend-api/src/Model/Resolver/Category/Exception/CategoryNotFoundUserError.php
  packages/frontend-api/src/Model/Resolver/Order/Exception/OrderNotFoundUserError.php
  packages/frontend-api/src/Model/Resolver/Payment/Exception/PaymentNotFoundUserError.php
  packages/frontend-api/src/Model/Resolver/Products/Exception/ProductNotFoundUserError.php
  packages/frontend-api/src/Model/Resolver/Transport/Exception/TransportNotFoundUserError.php
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: DX & Refactoring

#2572 [releaser] switched from old changelog to Github Releases
  .github/release.yml
  utils/releaser/config/release.php
  utils/releaser/src/ReleaseWorker/AbstractCheckPackagesGithubActionsBuildsReleaseWorker.php
  utils/releaser/src/ReleaseWorker/Release/CheckReleaseDraftAndReleaseItReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateChangelogReleaseWorker.php
Labels: DX & Refactoring
