Repository shopsys/shopsys, pull requests merged in 2023-01, with the labels that each got.

#2522 [framework] category tree in administration is now hideable
  packages/framework/assets/styles/admin/components/form/tree.less
  packages/framework/src/Resources/views/Admin/Content/Category/list.html.twig
Labels: Enhancement, Design & Appearance

#2527 [shopsys] update twig/twig to v2.15.4
  composer.json
  packages/framework/composer.json
  packages/product-feed-google/composer.json
  packages/product-feed-heureka-delivery/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-zbozi/composer.json
  project-base/composer.json
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: Security

#2528 [framework] upgrade elfinder cache system to prevent cache errors
  composer.json
  packages/framework/composer.json
Labels: Bug

#2523 [framework] remove LoggingMiddleware from connection in data fixtures for faster demodata generation
  packages/framework/src/Component/DataFixture/AbstractReferenceFixture.php
Labels: Performance

#2530 [framework] remove product variant urls from sitemap
  packages/framework/src/Model/Sitemap/SitemapFacade.php
  packages/framework/src/Model/Sitemap/SitemapListener.php
  packages/framework/src/Model/Sitemap/SitemapRepository.php
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: Enhancement

#2536 [framework] Remove var dumps from API response
  docs/cookbook/dump-variables.md
  docs/cookbook/index.md
  project-base/config/packages/dev/debug.yaml
Labels: DX & Refactoring

#2537 [shopsys] update session and cart lifetime
  packages/framework/src/Model/Cart/CartFacade.php
  project-base/config/packages/framework.yaml
  project-base/tests/App/Functional/Model/Cart/CartFacadeDeleteOldCartsTest.php
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: Enhancement

#2547 [framework] Cache current customer user
  docs/automated-testing/introduction-to-automated-testing.md
  packages/framework/build.xml
  packages/framework/src/Model/Customer/User/CurrentCustomerUser.php
  packages/framework/tests/Unit/Model/Customer/CurrentCustomerUserTest.php
  packages/framework/tests/Unit/Model/Customer/Mock/TokenMock.php
Labels: Enhancement

#2513 [releaser] improve information in after-release stage
  utils/releaser/src/ReleaseWorker/AbstractCheckShopsysInstallReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/CheckShopsysInstallReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/SetMutualDependenciesToDevelopmentVersionReleaseWorker.php
Labels: In Backlog

#2525 [framework] fix annotations for CategoryTranslation::$name
  packages/framework/src/Model/Category/Category.php
  packages/framework/src/Model/Category/CategoryTranslation.php
Labels: In Backlog

#2524 [project-base] fix tests for product searching
  project-base/tests/FrontendApiBundle/Functional/Product/ProductsSearchTest.php
  upgrade/UPGRADE-v11.0.0-dev.md
Labels: DX & Refactoring, In Backlog
