Repository shopsys/shopsys, pull requests merged in 2023-09, with the labels that each got.

#2760 [docs] updated PHPStorm settings to use absolute paths for TypeScript
  project-base/app/config/phpstorm/phpstorm.xml
Labels: Documentation

#2762 [shopsys] introduced php-fpm base image
  .ci/monorepo_functions.sh
  .github/build-php-fpm-image.sh
  .github/workflows/docker-build.yaml
  .github/workflows/rebuild-docker-images.yaml
  CHANGELOG.md
  docs/introduction/monorepo.md
  packages/php-image/.github/workflows/build-tagged-version.yaml
  packages/php-image/.github/workflows/rebuild-dev-image.yaml
  packages/php-image/CONTRIBUTING.md
  packages/php-image/Dockerfile
  packages/php-image/LICENSE
  packages/php-image/README.md
  packages/php-image/docker-install-composer
  packages/php-image/docker-php-entrypoint
  packages/php-image/phing-completion
  project-base/app/docker/php-fpm/Dockerfile
  upgrade/UPGRADE-v13.0.0-dev.md
  utils/releaser/config/after-release.php
  utils/releaser/config/release.php
  utils/releaser/src/FileManipulator/DockerfileVersionFileManipulator.php
  utils/releaser/src/ReleaseWorker/AbstractShopsysReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/SetPhpImageVersionInDockerfileReleaseWorker.php
  utils/releaser/src/ReleaseWorker/Release/TagPhpImageReleaseWorker.php
Labels: DX & Refactoring

#2761 [project-base] reduced image url redis cache size
  project-base/app/src/Component/Image/ImageFacade.php
Labels: DX & Refactoring

#2756 [project-base] SEO categories are now returned even when ignored filters are set
  project-base/app/src/DataFixtures/Demo/ReadyCategorySeoDataFixture.php
  project-base/app/src/FrontendApi/Resolver/Category/CategoryQuery.php
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMixFacade.php
  project-base/app/tests/FrontendApiBundle/Functional/Category/ReadyCategorySeoMix/ReadyCategorySeoMixTest.php
Labels: Enhancement

#2774 [framework] upgraded doctrine/orm to latest version
  composer.json
  packages/framework/composer.json
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Model/Order/OrderFacade.php
Labels: DX & Refactoring

#2775 [shopsys] upgraded doctrine/orm to latest version
  composer.json
  packages/framework/composer.json
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Model/Order/OrderFacade.php
  project-base/app/src/Model/Order/OrderFacade.php
Labels: DX & Refactoring

#2787 [shopsys] updated overblog/graphql-bundle to stable version 1.0.0 with dependencies
  composer.json
  packages/frontend-api/composer.json
  packages/frontend-api/src/Model/Error/ErrorCodeSubscriber.php
  packages/frontend-api/src/Model/ScalarType/StringType.php
  packages/frontend-api/src/Model/Token/Exception/TokenUserMessageException.php
  project-base/app/config/graphql/types/Query/Product/ProductQuery.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/FrontendApi/Exception/ValidationError.php
  project-base/app/tests/FrontendApiBundle/Functional/Login/LoginTest.php
  project-base/app/tests/FrontendApiBundle/Functional/SeoPage/SeoPageTest.php
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/schema.graphql.json
Labels: DX & Refactoring, dependencies

#2788 [shopsys] updated overblog/graphql-bundle to stable version 1.0.0 with dependencies
  composer.json
  packages/frontend-api/composer.json
  packages/frontend-api/src/Model/Error/ErrorCodeSubscriber.php
  packages/frontend-api/src/Model/ScalarType/StringType.php
  packages/frontend-api/src/Model/Token/Exception/TokenUserMessageException.php
  project-base/tests/FrontendApiBundle/Functional/Login/LoginTest.php
  upgrade/UPGRADE-v12.0.0-dev.md
Labels: DX & Refactoring

#2780 [framework] added optional option to export data to Elasticsearch only for the specified domain
  docs/introduction/console-commands-for-application-management-phing-targets.md
  packages/framework/src/Command/Elasticsearch/AbstractElasticsearchIndexCommand.php
  packages/framework/src/Command/Elasticsearch/ElasticsearchDataExportCommand.php
  upgrade/UPGRADE-v13.0.0-dev.md
Labels: DX & Refactoring

#2753 added more info about error types to SF middleware
  project-base/storefront/middleware.ts
  project-base/storefront/pages/_error.tsx
Labels: Bug

#2790 [php-image] added cron package to base image
  packages/php-image/Dockerfile
Labels: Infrastructure

#2783 [github-actions] cancel review now use lowercased branch name to check directory
  .github/cancel-review.sh
Labels: Infrastructure

#2792 [shopsys] updated Dockerfile to update installation of NodeJS and Postgres in PHP-FPM Dockerfile
  docs/contributing/releasing-a-new-version-of-shopsys-framework.md
  project-base/docker/php-fpm/Dockerfile
  upgrade/UPGRADE-v12.0.0-dev.md
  utils/releaser/src/ReleaseWorker/AfterRelease/EnableMergingReleaseWorker.php
  utils/releaser/src/ReleaseWorker/AfterRelease/PostInfoToSlackReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/StopMergingReleaseWorker.php
Labels: Documentation, DX & Refactoring

#2797 [infrastructure] added running the crons to the review server
  .github/workflows/docker-build.yaml
  docker/conf/docker-compose.github-actions.review.simplified.yml.dist
  docker/conf/docker-compose.github-actions.review.yml.dist
Labels: Infrastructure, Use PHP Dockerfile instead of built image

#2801 [framework] fixed variant creation
  packages/framework/src/Component/Image/ImageFacade.php
  project-base/tests/App/Functional/Model/Product/ProductVariantCreationTest.php
  upgrade/UPGRADE-v12.0.0-dev.md
Labels: Bug

#2799 [framework] fixed bestsellers edit in admin
  packages/framework/src/Controller/Admin/BestsellingProductController.php
Labels: Bug

#2516 [shopsys] graphql query is not in transaction
  packages/framework/src/Component/HttpFoundation/TransactionalMasterRequestListener.php
  project-base/app/config/services.yaml
  project-base/app/src/Component/HttpFoundation/TransactionalMasterRequestListener.php
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMixFacade.php
Labels: In Backlog, Frontend API

#2800 fixed order editation error due to invalid type in vat object
  packages/framework/src/Form/Admin/Order/OrderItemFormType.php
  packages/framework/src/Form/Admin/Order/OrderPaymentFormType.php
  packages/framework/src/Form/Admin/Order/OrderTransportFormType.php
Labels: Bug

#2805 [project-base] fixed GetOrdersAsAuthenticatedCustomerUserTest
  project-base/app/tests/FrontendApiBundle/Functional/Order/GetOrdersAsAuthenticatedCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/GetOrdersAsUnauthenticatedCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/graphql/getOrders.graphql
  upgrade/UPGRADE-v13.0.0-dev.md
Labels: Bug

#2810 [shopsys] fixed split packages builds
  ecs.php
  packages/coding-standards/.github/workflows/run-checks-tests.yaml
  packages/coding-standards/composer.json
  packages/coding-standards/ecs.php
  packages/coding-standards/examples/ValidClass.php
  packages/form-types-bundle/ecs.php
  packages/framework/.github/workflows/run-checks-tests.yaml
  packages/framework/ecs.php
  packages/framework/tests/Test/Provider/TestCurrencyProvider.php
  packages/framework/tests/Test/Provider/TestOrderProvider.php
  packages/framework/tests/Unit/Model/Customer/CustomerUserUpdateDataFactoryTest.php
  packages/framework/tests/Unit/Model/Order/OrderTest.php
  packages/frontend-api/ecs.php
  packages/google-cloud-bundle/ecs.php
  packages/http-smoke-testing/.github/workflows/run-checks-tests.yaml
  packages/http-smoke-testing/composer.json
  packages/http-smoke-testing/ecs.php
  packages/migrations/ecs.php
  packages/plugin-interface/ecs.php
  packages/product-feed-google/ecs.php
  packages/product-feed-heureka-delivery/ecs.php
  packages/product-feed-heureka/ecs.php
  packages/product-feed-zbozi/ecs.php
  packages/read-model/ecs.php
  project-base/tests/App/Functional/Model/Order/Preview/OrderPreviewCalculationTest.php
  project-base/tests/App/Functional/PersonalData/PersonalDataExportXmlTest.php
  upgrade/UPGRADE-v12.0.0-dev.md
Labels: Bug

#2806 [project-base] order is updated in GoPay only if configuration is set
  project-base/app/.env.test
  project-base/app/src/Model/GoPay/GoPayClientFactory.php
  project-base/app/src/Model/Payment/Service/PaymentServiceFacade.php
Labels: Bug

#2822 [infrastructure] upgrade Kubernetes Buildpack version
  project-base/.gitlab-ci.yml
Labels: Infrastructure

#2828 comparison popup is now visible after adding a product from product detail
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
Labels: Bug

#2829 Fixes regarding default delivery address
  project-base/storefront/components/Pages/Customer/AddressList.tsx
  project-base/storefront/hooks/user/useCurrentUserContactInformation.ts
Labels: Bug
