Repository shopsys/shopsys, pull requests merged in 2023-04, with the labels that each got.

#2584 [shopsys] added ability to change periodicity and length of cron runs
  docs/introduction/cron.md
  packages/framework/assets/js/admin/components/Statistics.js
  packages/framework/assets/js/admin/utils/constant.js
  packages/framework/src/Command/CronCommand.php
  packages/framework/src/Component/Cron/Config/CronConfig.php
  packages/framework/src/Component/Cron/Config/CronModuleConfig.php
  packages/framework/src/Component/Cron/CronFacade.php
  packages/framework/src/Component/Cron/CronModuleExecutor.php
  packages/framework/src/Component/Cron/CronModuleFacade.php
  packages/framework/src/Component/Cron/CronModuleRepository.php
  packages/framework/src/Controller/Admin/DefaultController.php
  packages/framework/src/DependencyInjection/Compiler/RegisterCronModulesCompilerPass.php
  packages/framework/src/Resources/views/Admin/Content/Default/cronDetail.html.twig
  packages/framework/src/Resources/views/Admin/Content/Default/cronListGrid.html.twig
  packages/framework/src/Resources/views/Admin/Content/Default/cronModuleRunsListGrid.html.twig
  packages/framework/src/Twig/DateTimeFormatterExtension.php
  packages/framework/tests/Unit/Component/Cron/CronFacadeTest.php
  packages/framework/tests/Unit/Component/Cron/CronModuleExecutorTest.php
  project-base/config/services/cron.yaml
  upgrade/UPGRADE-v11.0.1-dev.md
Labels: Enhancement

#2507 [framework] bin/console base phing targets are now more verbose
  packages/framework/build.xml
  project-base/translations/dataFixtures.cs.po
  project-base/translations/dataFixtures.en.po
  upgrade/UPGRADE-v11.0.1-dev.md
Labels: DX & Refactoring, In Backlog

#2506 [framework] Transport::getPrice() - fix error message
  packages/framework/src/Model/Transport/Transport.php
Labels: DX & Refactoring, In Backlog

#2425 [framework] Do not show loader element in load order preview
  packages/framework/assets/js/admin/components/OrderPreview.js
Labels: Design & Appearance

#2588 [shopsys] checking if order status update email should be sent is done directly in OrderMailFacade instead in multiple places
  packages/framework/src/Model/Order/Mail/OrderMailFacade.php
  packages/framework/src/Model/Order/OrderFacade.php
  packages/frontend-api/src/Model/Mutation/Order/CreateOrderMutation.php
  project-base/src/Controller/Front/OrderController.php
  upgrade/UPGRADE-v11.0.1-dev.md
Labels: DX & Refactoring

#2564 [framework] columns in grid can now be reordered
  docs/administration/grid.md
  packages/framework/src/Component/Grid/Grid.php
  packages/framework/tests/Unit/Component/Grid/GridTest.php
Labels: Enhancement, In Backlog

#2596 [framework] fixed bc-breaks of cron module runs
  packages/framework/src/Command/CronCommand.php
  packages/framework/src/Component/Cron/Config/CronConfig.php
  packages/framework/src/Component/Cron/CronModuleExecutor.php
  packages/framework/src/Component/Deprecations/DeprecationHelper.php
  upgrade/UPGRADE-v11.0.1-dev.md
Labels: Bug

#2597 [framework] admin: order items table sizes are now fixed
  packages/framework/assets/styles/admin/components/table/col.less
  packages/framework/assets/styles/admin/todo.less
  packages/framework/src/Resources/views/Admin/Content/Order/orderItem.html.twig
  packages/framework/src/Resources/views/Admin/Form/orderItems.html.twig
Labels: Design & Appearance

#2595 [project-base] returned symfony.lock to project-base as it caused problems with symfony flex installing packages again
  project-base/symfony.lock
  utils/releaser/src/ReleaseWorker/AfterRelease/RemoveLockFilesReleaseWorker.php
  utils/releaser/src/ReleaseWorker/Release/CreateAndCommitLockFilesReleaseWorker.php
Labels: Bug

#2598 [framework] fixed upgrade notes and resolved possible BC-break
  packages/framework/src/Resources/config/services.yaml
  upgrade/UPGRADE-v11.0.1-dev.md
Labels: DX & Refactoring

#2593 [shopsys] updated installation docs for macOS using Mutagen
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-sync.yml.dist
  docs/installation/application-requirements.md
  docs/installation/index.md
  docs/installation/installation-guide.md
  docs/installation/installation-using-docker-application-setup.md
  docs/installation/installation-using-docker-linux.md
  docs/installation/installation-using-docker-macos.md
  docs/introduction/monorepo.md
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-sync.yml.dist
  project-base/scripts/configure.sh
  upgrade/UPGRADE-v11.0.1-dev.md
Labels: DX & Refactoring

#2599 [shopsys] users and admins now have only five tries to log in in one minute
  composer.json
  packages/framework/composer.json
  packages/framework/src/Controller/Admin/LoginController.php
  packages/framework/src/Model/Security/CustomerLoginHandler.php
  packages/frontend-api/src/Model/Mutation/Customer/User/Exception/TooManyLoginAttemptsUserError.php
  packages/frontend-api/src/Model/Mutation/Login/LoginMutation.php
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/assets/js/frontend/components/Login.js
  project-base/config/packages/security.yaml
  project-base/src/Controller/Front/LoginController.php
  project-base/symfony.lock
  symfony.lock
  upgrade/UPGRADE-v11.0.1-dev.md
Labels: Enhancement

#2600 [framework] cron overview is now available for admin in the default state
  packages/framework/src/Controller/Admin/DefaultController.php
  packages/framework/src/Resources/config/parameters_common.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Default/index.html.twig
  project-base/config/packages/security.yaml
  project-base/tests/App/Smoke/Http/RouteConfigCustomization.php
Labels: Enhancement
