Repository shopsys/shopsys, pull requests merged in 2024-12, with the labels that each got.

#3631 [project-base] added cookies store to error page to avoid undefined userIdentifier
  project-base/storefront/pages/_error.tsx
  upgrade-notes/storefront_20241202_094542.md
Labels: Bug

#3606 [shopsys] Removing administrator password settings from administration
  packages/framework/assets/styles/admin/components/box/reset-password.less
  packages/framework/assets/styles/admin/main.less
  packages/framework/src/Command/ChangeAdminPasswordCommand.php
  packages/framework/src/Controller/Admin/AdministratorController.php
  packages/framework/src/Form/Admin/Administrator/AdministratorFormType.php
  packages/framework/src/Form/Admin/Administrator/AdministratorResetPasswordFormType.php
  packages/framework/src/Form/DisplayOnlyUrlType.php
  packages/framework/src/Migrations/Version20241114124339.php
  packages/framework/src/Model/Administrator/Administrator.php
  packages/framework/src/Model/Administrator/AdministratorFacade.php
  packages/framework/src/Model/Administrator/AdministratorPasswordFacade.php
  packages/framework/src/Model/Administrator/Exception/InvalidResetPasswordHashAdministratorException.php
  packages/framework/src/Model/Administrator/Mail/ResetPasswordMail.php
  packages/framework/src/Model/Administrator/Mail/ResetPasswordMailFacade.php
  packages/framework/src/Model/Mail/MailTemplateConfiguration.php
  packages/framework/src/Model/Security/Authenticator.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  packages/framework/src/Resources/views/Admin/Content/Administrator/invalidResetPasswordHash.html.twig
  packages/framework/src/Resources/views/Admin/Content/Administrator/resetPassword.html.twig
  packages/framework/src/Resources/views/Admin/Form/displayOnlyUrl.html.twig
  project-base/app/config/forms.yaml
  project-base/app/config/packages/security.yaml
  project-base/app/src/Controller/Admin/AdministratorController.php
  project-base/app/src/DataFixtures/Demo/MailTemplateDataFixture.php
  project-base/app/src/Form/Admin/AdministratorFormTypeExtension.php
  project-base/app/src/Model/Administrator/AdministratorFacade.php
  project-base/app/tests/App/Smoke/Http/RouteConfigCustomization.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  project-base/app/translations/validators.cs.po
  project-base/app/translations/validators.en.po
  upgrade-notes/backend_20241119_074634.md
Labels: Enhancement

#3630 [Shopsys] Add parallel and regenerate to Gitlab pipelines
  project-base/.gitlab-ci.yml
  project-base/gitlab/docker-compose-ci.yml
  upgrade-notes/backend_20241205_071409.md
Labels: Enhancement

#3647 [shopsys] Hotfix - add regenerate stage to gitlab ci
  project-base/.gitlab-ci.yml
Labels: Bug

#3642 [framework] functional tests are now run per folder to prevent memory limits
  packages/framework/build.xml
Labels: DX & Refactoring

#3644 [project-base] added dynamic tab index to product detail page
  project-base/storefront/components/Pages/ProductDetail/ProductDetailTabs/ProductDetailTabs.tsx
  upgrade-notes/storefront_20241209_123845.md
Labels: Bug

#3652 [Luigi's Box] fix filtering products by stock
  packages/luigis-box/src/Component/LuigisBox/Filter/ProductFilterToLuigisBoxFilterMapper.php
  packages/luigis-box/src/Model/Product/Filter/LuigisBoxFacetsToProductFilterOptionsMapper.php
Labels: Bug

#3662 [frontend-api] fixed wrong type for logger in SocialNetworkFacade
  packages/frontend-api/src/Model/SocialNetwork/SocialNetworkFacade.php
Labels: Bug

#3660 [project-base] fixed single banner overflowing
  project-base/storefront/components/Blocks/Banners/Banner.tsx
  upgrade-notes/storefront_20241213_085120.md
Labels: Bug, Design & Appearance

#3636 [framework] Admin dropdown UI & UX improvement
  packages/framework/assets/js/admin/components/SelectAdminDomains.js
  packages/framework/assets/styles/admin/components/list/domain.less
  packages/framework/assets/styles/admin/core/form/custom-inputs.less
  packages/framework/assets/styles/admin/todo.less
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Form/adminDomainsForm.html.twig
  packages/framework/src/Resources/views/Admin/Inline/Domain/filter.html.twig
  packages/framework/src/Resources/views/Admin/Inline/Menu/menu.html.twig
Labels: Design & Appearance

#3650 [shopsys] fixed not working ChangePaymentMethodMutation
  packages/framework/src/Component/EntityLog/Model/EntityLogFacade.php
  packages/frontend-api/src/Resources/config/routing.yaml
  project-base/app/config/services_frontend_api.yaml
  project-base/app/src/FrontendApi/Component/SessionChecker/SessionChecker.php
  upgrade-notes/backend_20241211_140117.md
Labels: Bug

#3646 [project-base] updated dependencies
  project-base/storefront/config/i18next-parser.config.js
  project-base/storefront/next-env.d.ts
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  upgrade-notes/storefront_20241216_110417.md
Labels: dependencies

#3632 [project-base] removed neccesary space in product box
  project-base/storefront/components/Blocks/Product/LastVisitedProducts/LastVisitedProductsContent.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItem.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItemPlaceholder.tsx
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSearchProductsResult.tsx
  project-base/storefront/cypress/snapshots/e2e/matrix/matrixTest.cy.ts/[Matrix] (matrix page) matrix page visit with screenshot.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Homepage] (homepage) homepage visit with screenshot.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Product Detail] (product detail) product detail visit with screenshot.png
  upgrade-notes/storefront_20241202_100249.md
Labels: Bug

#3656 [framework] fixed slider on banner edit in czech language
  packages/framework/assets/js/admin/components/NumberSlider.js
  packages/framework/src/Form/Admin/Slider/SliderItemFormType.php
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
Labels: Bug

#3668 [project-base] removed repeat order button when product is type inquiry
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailBasicInfo.tsx
  project-base/storefront/components/Pages/Customer/Orders/OrderItem.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/adverts/queries/AdvertsQuery.generated.tsx
  project-base/storefront/graphql/requests/articles/queries/ArticleDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/articlesInterface/articles/queries/ArticlesQuery.generated.tsx
  project-base/storefront/graphql/requests/articlesInterface/blogArticles/queries/BlogArticleDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/articlesInterface/blogArticles/queries/BlogArticlesQuery.generated.tsx
  project-base/storefront/graphql/requests/auth/mutations/LoginMutation.generated.tsx
  project-base/storefront/graphql/requests/blogCategories/queries/BlogCategoryArticlesQuery.generated.tsx
  project-base/storefront/graphql/requests/blogCategories/queries/BlogCategoryQuery.generated.tsx
  project-base/storefront/graphql/requests/brands/queries/BrandDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/cart/queries/CartQuery.generated.tsx
  project-base/storefront/graphql/requests/cart/queries/MinimalCartQuery.generated.tsx
  project-base/storefront/graphql/requests/categories/queries/CategoryDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintItemFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/CreateComplaintFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/mutations/CreateComplaintMutation.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintsQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/OrderedItemsQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/SearchOrderedItemsQuery.generated.tsx
  project-base/storefront/graphql/requests/customer/queries/CouldBeCustomerRegisteredQuery.generated.tsx
  project-base/storefront/graphql/requests/flags/queries/FlagDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/ListedOrderFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/ListedOrderFragment.graphql
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailItemFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailItemFragment.graphql
  project-base/storefront/graphql/requests/orders/fragments/OrderListFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/mutations/CreateOrderMutation.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrderDetailByHashQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrderDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrdersCountQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrdersQuery.generated.tsx
  project-base/storefront/graphql/requests/personalData/mutations/PersonalDataRequestMutation.generated.tsx
  project-base/storefront/graphql/requests/personalData/queries/PersonalDataDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/BrandProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/CategoryProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/FlagProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/ProductDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/RecommendedProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/AutocompleteSearchQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/SearchProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/SearchQuery.generated.tsx
  project-base/storefront/graphql/requests/stores/queries/StoreDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/stores/queries/StoreQuery.generated.tsx
  project-base/storefront/graphql/requests/transports/queries/TransportsFullQuery.generated.tsx
  project-base/storefront/graphql/requests/transports/queries/TransportsQuery.generated.tsx
  upgrade-notes/storefront_20241216_121157.md
Labels: Bug, Design & Appearance

#3593 [SSP-2867] - disable link click on product list item text select text
  packages/framework/src/Resources/config/services.yaml
  project-base/storefront/components/Basic/ExtendedNextLink/ExtendedNextLink.tsx
  project-base/storefront/components/Blocks/Banners/BannersSlider.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItem.tsx
  project-base/storefront/components/Blocks/Product/ProductsSlider.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryBestsellers/CategoryBestsellersListItem.tsx
  project-base/storefront/utils/ui/disableClickWhenTextSelected.ts
  upgrade-notes/storefront_20241112_215631.md
Labels: regenerate screenshots

#3653 [docs] added documentation about domain limiting
  docs/model/domain-limiting.md
  docs/model/index.md
  docs/model/navigation.yml
Labels: Documentation

#3654 [framework] added missing migration to create admin reset password mail template
  packages/framework/src/Migrations/Version20241212064226.php
  packages/framework/src/Resources/translations/dataFixtures.cs.po
  packages/framework/src/Resources/translations/dataFixtures.en.po
  project-base/app/translations/dataFixtures.cs.po
Labels: Bug

#3667 [project-base] removed stock availability info for products excluded from sale
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItem.tsx
  project-base/storefront/components/Pages/ProductComparison/ProductComparisonBody.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  upgrade-notes/storefront_20241216_115626.md
Labels: Design & Appearance

#3664 [framework] ensure manually sent mail templates are wrapped with the GrapesJS body
  docs/cookbook/adding-a-new-email-template.md
  packages/framework/src/Model/Administrator/Mail/ResetPasswordMailFacade.php
  packages/framework/src/Model/Administrator/Mail/TwoFactorAuthenticationMailFacade.php
  packages/framework/src/Model/Complaint/Mail/ComplaintMailFacade.php
  packages/framework/src/Model/Customer/Mail/CustomerMailFacade.php
  packages/framework/src/Model/Customer/Mail/ResetPasswordMailFacade.php
  packages/framework/src/Model/Inquiry/Mail/InquiryMailFacade.php
  packages/framework/src/Model/Mail/MailTemplateFacade.php
  packages/framework/src/Model/Mail/MailTemplateSender/MailTemplateSenderFacade.php
  packages/framework/src/Model/Order/Mail/OrderMailFacade.php
  packages/framework/src/Model/PersonalData/Mail/PersonalDataAccessMailFacade.php
  project-base/app/src/Model/Mail/MailTemplateFacade.php
  upgrade-notes/backend_20241213_153619.md
Labels: Bug, Documentation

#3673 [shopsys] Upgrade Redis to the newest version
  composer.json
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose.github-actions.cypress.yml.dist
  docker/conf/docker-compose.github-actions.review.yml.dist
  docker/conf/docker-compose.github-actions.yml.dist
  docker/conf/docker-compose.yml.dist
  open-source-license-acknowledgements-and-third-party-copyrights.md
  packages/framework/composer.json
  packages/php-image/Dockerfile
  project-base/app/composer.json
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
  project-base/gitlab/docker-compose-ci.yml
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  upgrade-notes/backend_20241217_051020.md
  upgrade-notes/storefront_20241217_051020.md
  utils/license-acknowledgements-generator/template.md
Labels: Use PHP Dockerfile instead of built image

#3678 [shopsys] ensure graphql schema is always rendered same
  project-base/app/package.json
  upgrade-notes/backend_20241218_101900.md
  upgrade-notes/storefront_20241218_101900.md
Labels: DX & Refactoring, coderabbit

#3674 [project-base] fixed product slider on article page
  project-base/storefront/components/Basic/UserText/GrapesJsProducts.tsx
  project-base/storefront/components/Blocks/Product/ProductsSlider.tsx
  project-base/storefront/components/Pages/Article/ArticleDetailContent.tsx
  upgrade-notes/storefront_20241217_082658.md
Labels: Bug

#3663 [projcet-base] Fix preselecting packetery with empty pickup point
  project-base/storefront/components/Pages/Order/TransportAndPayment/transportAndPaymentUtils.tsx
  upgrade-notes/storefront_20241213_151348.md
Labels: Bug, Design & Appearance

#3658 [framework] improved rendering information about eshop required settings
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlMatcher.php
  packages/framework/src/Controller/Admin/DefaultController.php
  packages/framework/src/Model/Country/CountryFacade.php
  packages/framework/src/Model/Country/CountryRepository.php
  packages/framework/src/Model/Product/Unit/UnitFacade.php
  packages/framework/src/Model/Product/Unit/UnitRepository.php
  packages/framework/src/Model/Security/MenuItemsGrantedRolesSetting.php
  packages/framework/src/Model/Stock/StockFacade.php
  packages/framework/src/Model/Stock/StockRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Product/list.html.twig
  packages/framework/src/Resources/views/Admin/Layout/layoutWithPanel.html.twig
  packages/framework/src/Resources/views/Components/RequiredSettings/requiredSettings.html.twig
  packages/framework/src/Twig/RequiredSettingExtension.php
  upgrade-notes/backend_20241216_095022.md
Labels: Enhancement

#3677 [administration] Hide warning about not secured CKEditor
  composer.json
  project-base/app/assets/extra/bundles/fosckeditor/plugins/strinsert/plugin.js
  project-base/app/assets/js/admin/grapesjs/initGrapesJs.js
  project-base/app/composer.json
  project-base/app/config/packages/fos_ck_editor.yaml
  upgrade-notes/backend_20241217_121826.md
Labels: Easy Pick, Design & Appearance

#3684 [framework] fixed rendering main blog category in blog article assign to category tree
  packages/framework/src/Model/Blog/Category/BlogCategoryRepository.php
Labels: Bug

#3682 [framework] trans function now support named arguments
  packages/framework/src/Component/Translation/PhpFileExtractor.php
  packages/framework/src/Component/Translation/functions.php
  packages/framework/tests/Unit/Component/Translation/PhpFileExtractorTest.php
  packages/framework/tests/Unit/Component/Translation/Resources/Controller.php
Labels: DX & Refactoring

#3686 [framework] administrator email now must be unique
  packages/framework/src/Controller/Admin/AdministratorController.php
  packages/framework/src/Form/Admin/Administrator/AdministratorFormType.php
  packages/framework/src/Form/Constraints/UniqueEntityField.php
  packages/framework/src/Form/Constraints/UniqueEntityFieldValidator.php
  packages/framework/src/Migrations/Version20180702111015.php
  packages/framework/src/Migrations/Version20241220094923.php
  packages/framework/src/Model/Administrator/Administrator.php
  packages/framework/src/Model/Administrator/AdministratorFacade.php
  packages/framework/src/Model/Administrator/Exception/DuplicateUserNameException.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  project-base/app/src/Model/Administrator/AdministratorFacade.php
  upgrade-notes/backend_20241220_113322.md
Labels: Security

#3688 [shopsys] Upgrade some composer dependencies
  composer.json
  packages/framework/composer.json
  packages/framework/src/Model/Administrator/AdministratorTwoFactorAuthenticationFacade.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapDumper.php
  packages/framework/src/Model/Sitemap/SitemapDumper.php
  packages/frontend-api/composer.json
  packages/frontend-api/phpstan.neon
  packages/frontend-api/src/Model/Token/TokenFacade.php
  packages/frontend-api/tests/Unit/Model/Token/TokenFacadeTest.php
  packages/luigis-box/composer.json
  packages/migrations/composer.json
  phpstan.neon
  project-base/app/composer.json
  project-base/app/config/packages/scheb_2fa.yaml
  symfony.lock
  upgrade-notes/backend_20241222_074439.md
Labels: dependencies

#3694 [shopsys] add missing symfony/doctrine-messenger dependency
  composer.json
  packages/framework/composer.json
  packages/framework/src/Migrations/Version20241223020558.php
  project-base/app/composer.json
  upgrade-notes/backend_20241223_145857.md
Labels: dependencies

#3689 [shopsys] Fix zero downtime deployment
  packages/framework/build.xml
  project-base/app/config/packages/monolog.yaml
  upgrade-notes/backend_20241222_130921.md
Labels: Infrastructure

#3697 [coding-standards] fix composer version for coding-standards
  packages/coding-standards/composer.json
Labels: Bug

#3691 [project-base] updated sentry to version 8.x.x
  project-base/storefront/.env
  project-base/storefront/instrumentation.ts
  project-base/storefront/next.config.js
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  project-base/storefront/sentry.server.config.ts
  upgrade-notes/storefront_20241223_083319.md
Labels: dependencies

#3698 [shopsys] fix build of project-base after updating overblog/dataloader-bundle
  packages/framework/src/Component/EntityLog/Detection/DetectionFacade.php
  packages/framework/src/Form/Admin/Administrator/AdministratorFormType.php
  packages/framework/src/Model/AdminNavigation/MenuItemsGrantedRolesSubscriber.php
  packages/framework/src/Model/Customer/User/Role/CustomerUserRoleResolver.php
  packages/framework/src/Model/Security/CustomerLoginHandler.php
  packages/framework/tests/Unit/Model/Customer/Mock/TokenMock.php
  packages/frontend-api/src/Component/Constraints/CustomerUserRoleGroupAllowEditValidator.php
  packages/frontend-api/src/Model/Complaint/ComplaintApiFacade.php
  packages/frontend-api/src/Model/Resolver/Complaint/ComplaintQuery.php
  packages/frontend-api/src/Model/Resolver/Complaint/ComplaintsQuery.php
  packages/frontend-api/src/Model/Resolver/Order/OrderItemsQuery.php
  packages/frontend-api/src/Model/Resolver/Order/OrderItemsSearchQuery.php
  packages/frontend-api/src/Model/Resolver/Order/OrderQuery.php
  packages/frontend-api/src/Model/Resolver/Order/OrdersQuery.php
  packages/frontend-api/src/Model/Resolver/Query/MoneyResolverMap.php
  packages/frontend-api/src/Voter/CompanyOwnerVoter.php
  packages/frontend-api/src/Voter/CustomerUserVoter.php
  project-base/app/phpstan.neon
  project-base/app/src/FrontendApi/Resolver/Order/OrderQuery.php
  project-base/app/src/FrontendApi/Resolver/Order/OrdersQuery.php
  project-base/app/tests/FrontendApiBundle/Unit/Complaint/ComplaintApiFacadeTest.php
  upgrade-notes/backend_20241222_074439.md
Labels: dependencies

#3661 [shopsys] docs: fix tag name for feeds
  docs/model/product-feeds.md
Labels: Documentation

#3560 [shopsys] SF security check now runs only for supported versions
  .github/workflows/storefront-security-check.yaml
Labels: Infrastructure
