Repository shopsys/shopsys, pull requests merged in 2024-07, with the labels that each got.

#3232 [shopsys] easier mail template extending
  docs/cookbook/adding-a-new-email-template.md
  packages/framework/src/Model/Mail/MailTemplateConfiguration.php
  project-base/app/src/Model/Mail/MailTemplateConfiguration.php
  upgrade-notes/backend_20240628_110358.md
Labels: DX & Refactoring

#3216 [infrastructure] dropped rebuilding Docker images for no longer supported versions of Shopsys Framework
  .github/workflows/rebuild-docker-images.yaml
Labels: Infrastructure

#3233 [luigis-box] parameter filters are now ordered by theirs ordering priority
  packages/luigis-box/src/Model/Product/Filter/LuigisBoxFacetsToProductFilterOptionsMapper.php
Labels: Enhancement

#3238 [project-base][SSP-1565] added functionality for notImplementedYet
  project-base/storefront/components/Basic/Icon/NotImplementedYetIcon.tsx
  project-base/storefront/components/Basic/NotImplementedYet/NotImplementedYet.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideContent.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideNotImplementedYet.tsx
  upgrade-notes/storefront_20240625_102333.md
Labels: DX & Refactoring

#3230 [framework] annotation fixer now works for all Shopsys packages
  .github/monorepo/monorepo_functions.sh
  docs/introduction/console-commands-for-application-management-phing-targets.md
  packages/framework/src/Command/ExtendedClassesAnnotationsCommand.php
  packages/framework/src/Component/ClassExtension/AnnotationsReplacementsMap.php
  packages/framework/src/Component/ClassExtension/ClassExtensionRegistry.php
  packages/framework/src/DependencyInjection/Compiler/RegisterProjectShopsysClassExtensionsCompilerPass.php
  packages/framework/src/Resources/config/packages_registry.yaml
  packages/framework/src/Resources/config/services_dev.yaml
  packages/framework/src/ShopsysFrameworkBundle.php
  packages/framework/tests/Unit/Component/ClassExtension/AnnotationsReplacerTest.php
  packages/framework/tests/Unit/Component/ClassExtension/DocBlockParserTest.php
  packages/framework/tests/Unit/Component/ClassExtension/Source/DummyClassForAnnotationsReplacer.php
  project-base/app/src/Controller/Admin/MailController.php
  project-base/app/src/Controller/Admin/ProductController.php
  project-base/app/src/Form/Constraints/UniqueEmailValidator.php
  project-base/app/src/Model/Cart/AddProductResult.php
  project-base/app/src/Model/Cart/CartFacade.php
  project-base/app/src/Model/Mail/Grid/MailTemplateGridFactory.php
  project-base/app/src/Model/Order/Processing/OrderProcessorMiddleware/AddProductsMiddleware.php
  project-base/app/src/Twig/ProductExtension.php
  upgrade-notes/backend_20240529_084428.md
  utils/releaser/src/ReleaseWorker/AbstractShopsysReleaseWorker.php
Labels: DX & Refactoring

#3231 [shopsys] new cart items are added to the end of cart item list
  packages/framework/src/Model/Cart/Cart.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/AddOrderItemsToCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/MergeCartsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/MultipleProductsInOrderTest.php
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/should remove products from cart using cart in header and then display empty cart message (after first remove).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should repeatedly merge carts when logged in (starting with an empty cart for the registered customer) (cart page after second login).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, check it, remove promo code from cart, and then add a different one (cart page after applying first promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, check it, remove promo code from cart, and then add a different one (cart page after removing first promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, check it, remove promo code from cart, and then add a different one (cart page after removing second promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, check it, remove promo code from cart, and then add a different one (transport and payment page after applying first promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, remove product that allows it, and see the promo code removed (after applying promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should increase and decrease product quantity using spinbox in cart (multiple times if clicked slowly) (after decrease).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should increase and decrease product quantity using spinbox in cart (multiple times if clicked slowly) (after increase).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should increase and decrease product quantity using spinbox in cart (once if clicked fast) (after decrease).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should increase and decrease product quantity using spinbox in cart (once if clicked fast) (after increase).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/transport should not be free if price minus promo code discount is below the free transport limit (cart page with non-free transport after applying promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/transport should not be free if price minus promo code discount is below the free transport limit (transport and payment page with non-free options after applying promocode).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for logged-in user with initially empty cart (after repeat).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for logged-in user with initially filled cart and allowed merging (after repeat).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for logged-in user with initially filled cart and disallowed merging (after repeat).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for unlogged user with initially filled cart and allowed merging (after repeat).png
  upgrade-notes/backend_20240627_101853.md
Labels: Easy Pick

#3247 [shopsys] remove delete button from banner slider image when editing
  packages/framework/src/Form/Admin/Slider/SliderItemFormType.php
  packages/framework/src/Form/ImageUploadType.php
  packages/framework/src/Resources/views/Admin/Form/imageuploadFields.html.twig
  project-base/app/src/Form/Admin/SliderItemFormTypeExtension.php
  upgrade-notes/backend_20240704_065627.md
Labels: Easy Pick

#3256 [project-base] fix build on split package
  project-base/.github/workflows/run-checks-tests.yaml
  project-base/app/tests/App/Functional/Twig/PriceExtensionTest.php
  project-base/app/tests/App/Performance/Page/AllPagesTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Hreflang/HreflangLinksTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Payment/OrderPaymentsTest.php
  upgrade-notes/backend_20240710_121329.md
Labels: Infrastructure

#3255 [framework] fix calculation of transport price
  packages/framework/src/Model/Cart/Payment/CartPaymentDataFactory.php
  packages/framework/src/Model/Cart/Transport/CartTransportDataFactory.php
  packages/framework/src/Model/Order/Processing/OrderInput.php
  packages/framework/src/Model/Payment/PaymentPriceProvider.php
  packages/framework/src/Model/Transport/TransportPriceProvider.php
  packages/frontend-api/src/Model/Payment/PaymentValidationFacade.php
  packages/frontend-api/src/Model/Resolver/Price/PriceQuery.php
  packages/frontend-api/src/Model/Transport/TransportValidationFacade.php
  upgrade-order-processing.md
Labels: Bug

#3259 [project-base][SSP-2393] Fixed unknown error in navigation
  project-base/storefront/components/Layout/Header/MobileMenu/MobileMenuListItem.tsx
  project-base/storefront/components/Layout/Header/Navigation/NavigationItem.tsx
  project-base/storefront/components/Layout/Header/Navigation/NavigationItemColumn.tsx
  project-base/storefront/components/Layout/Header/Navigation/NavigationPlaceholder.tsx
  upgrade-notes/storefront_20240710_105357.md
Labels: Bug

#3264 [framework] replaced unsupported currency SLL with new SLE
  packages/framework/src/Model/Localization/IntlCurrencyRepository.php
Labels: Bug

#3237 [shopsys] blog article now displays blog category tree
  packages/framework/src/Component/Redis/CleanStorefrontCacheFacade.php
  packages/framework/src/Controller/Admin/BlogCategoryController.php
  packages/framework/src/Model/Blog/Article/Elasticsearch/BlogArticleExportRepository.php
  packages/framework/src/Model/Blog/Category/BlogCategoryRepository.php
  packages/frontend-api/src/Model/Blog/Article/BlogArticleResolverMap.php
  packages/frontend-api/src/Resources/config/graphql-types/BlogArticleDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/Resources/definition/blog_article/1.json
  project-base/app/src/Resources/definition/blog_article/2.json
  project-base/storefront/components/Basic/UserText/GrapesJsProducts.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonManager.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleProductListItem.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageBlogArticle.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageBlogCategory.tsx
  project-base/storefront/components/Layout/BlogLayout.tsx
  project-base/storefront/components/Pages/BlogArticle/BlogArticleDetailContent.tsx
  project-base/storefront/components/Pages/BlogCategory/BlogCategoryContent.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/articlesInterface/blogArticles/fragments/BlogArticleDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/articlesInterface/blogArticles/fragments/BlogArticleDetailFragment.graphql
  project-base/storefront/graphql/requests/articlesInterface/blogArticles/queries/BlogArticleDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/blogCategories/fragments/BlogCategoryDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/blogCategories/fragments/BlogCategoryDetailFragment.graphql
  project-base/storefront/graphql/requests/blogCategories/queries/BlogCategoriesQuery.generated.tsx
  project-base/storefront/graphql/requests/blogCategories/queries/BlogCategoriesQuery.graphql
  project-base/storefront/graphql/requests/blogCategories/queries/BlogCategoryQuery.generated.tsx
  project-base/storefront/graphql/requests/slugs/queries/slugQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/pages/blogArticles/[blogArticleSlug].tsx
  project-base/storefront/pages/blogCategories/[blogCategorySlug].tsx
  project-base/storefront/schema-compressed.graphql.json
  upgrade-notes/backend_20240626_162649.md
  upgrade-notes/storefront_20240703_114024.md
Labels: Enhancement

#3266 [project-base][SSP-2475] updated product detail open gallery image size
  project-base/storefront/components/Basic/ModalGallery/ModalGallery.tsx
  upgrade-notes/storefront_20240715_120117.md
Labels: Design & Appearance

#3265 [shopsys] FE API delivery address mutations
  packages/framework/src/Model/Customer/DeliveryAddressFacade.php
  packages/framework/src/Model/Customer/User/CustomerUser.php
  packages/framework/src/Model/Customer/User/CustomerUserFacade.php
  packages/frontend-api/src/Model/Mutation/Customer/DeliveryAddress/DeliveryAddressDataApiFactory.php
  packages/frontend-api/src/Model/Mutation/Customer/DeliveryAddress/DeliveryAddressMutation.php
  packages/frontend-api/src/Model/Mutation/Customer/DeliveryAddress/Exception/DeliveryAddressNotFoundUserError.php
  packages/frontend-api/src/Resources/config/graphql-types/Customer/DeliveryAddress/DeliveryAddressDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/Customer/DeliveryAddress/DeliveryAddressInputObjectDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/Customer/DeliveryAddress/DeliveryAddressMutationDecorator.types.yaml
  packages/frontend-api/src/Resources/translations/validators.cs.po
  packages/frontend-api/src/Resources/translations/validators.en.po
  project-base/app/config/graphql/types/ModelType/Customer/CustomerInput/DeliveryAddressInput.types.yaml
  project-base/app/config/graphql/types/ModelType/Customer/DeliveryAddress.types.yaml
  project-base/app/config/graphql/types/ModelType/PersonalData/PersonalDataInput/TelephoneInputObjectDecorator.types.yaml
  project-base/app/config/graphql/types/Mutation/Customer/CustomerMutation.types.yaml
  project-base/app/config/services.yaml
  project-base/app/schema.graphql
  project-base/app/src/FrontendApi/Mutation/Customer/DeliveryAddressMutation.php
  project-base/app/src/Model/Customer/DeliveryAddressDataFactory.php
  project-base/app/src/Model/Customer/User/CustomerUser.php
  project-base/app/src/Model/Customer/User/CustomerUserFacade.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/CreateDeliveryAddressTest.php
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/mutation/CreateDeliveryAddressMutation.graphql
  project-base/app/translations/validators.cs.po
  project-base/app/translations/validators.en.po
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
  upgrade-notes/backend_20240715_094630.md
Labels: Enhancement, Frontend API

#3267 [project-base][SSP-1606] added info message to main product variant
  project-base/storefront/components/Pages/ProductDetail/ProductDetailVariantsTable.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  upgrade-notes/storefront_20240715_121121.md
Labels: Design & Appearance

#3229 [shopsys] related order items
  ecs.php
  packages/framework/src/Migrations/Version20240617204710.php
  packages/framework/src/Model/Order/Item/OrderItem.php
  packages/framework/src/Model/Order/Item/OrderItemData.php
  packages/framework/src/Model/Order/Item/OrderItemTypeEnum.php
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Model/Order/PlaceOrderFacade.php
  packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/AbstractPromoCodeMiddleware.php
  packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/ApplyNominalPromoCodeMiddleware.php
  packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/ApplyPercentagePromoCodeMiddleware.php
  packages/framework/src/Resources/views/Mail/Order/products.html.twig
  packages/frontend-api/src/Model/Order/OrderItemFacade.php
  packages/frontend-api/src/Model/Order/OrderItemRepository.php
  packages/frontend-api/src/Model/Order/OrderItemsBatchLoader.php
  packages/frontend-api/src/Model/Resolver/Order/OrderResolverMap.php
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/app/config/packages/overblog_dataloader.yaml
  project-base/app/src/Migrations/Version20200624103557.php
  project-base/app/src/Model/Order/Item/OrderItem.php
  project-base/app/src/Model/Order/Item/OrderItemData.php
  project-base/app/src/Model/Order/Item/OrderItemFactory.php
  project-base/app/src/Model/Order/Mail/OrderMail.php
  project-base/app/src/Model/Order/Order.php
  project-base/app/src/Model/Order/PlaceOrderFacade.php
  project-base/app/src/Model/Product/ProductDomain.php
  project-base/app/src/Model/Product/ProductOnCurrentDomainElasticFacade.php
  project-base/app/src/Model/ProductVideo/ProductVideoTranslations.php
  project-base/app/tests/App/Functional/Component/EntityLog/EntityLogTest.php
  project-base/app/tests/App/Functional/Model/Order/OrderFacadeEditTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/OrderWithPromoCodeTest.php
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/should create order with promo code and check it in order detail (order detail).png
  upgrade-notes/backend_20240529_084428.md
  upgrade-notes/backend_20240626_082704.md
Labels: Enhancement

#3242 [shopsys] top products are now in elasticsearch
  packages/frontend-api/src/Model/Product/ProductFacade.php
  packages/frontend-api/src/Model/Resolver/Products/PromotedProductsQuery.php
  project-base/app/config/services_frontend_api.yaml
  project-base/app/src/FrontendApi/Model/Product/ProductFacade.php
  project-base/app/src/FrontendApi/Resolver/Products/ProductsQuery.php
  project-base/app/src/FrontendApi/Resolver/Products/PromotedProductsQuery.php
  upgrade-notes/backend_20240628_060247.md
Labels: Performance

#3257 [shopsys] Twig templates cleanup
  packages/framework/src/Form/Constraints/DeliveryAddressOfCurrentCustomer.php
  packages/framework/src/Form/Constraints/DeliveryAddressOfCurrentCustomerValidator.php
  packages/framework/src/Form/DeliveryAddressChoiceType.php
  packages/framework/src/Resources/config/services_dev.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  packages/framework/src/Resources/views/Admin/Content/Article/new.html.twig
  packages/framework/src/Resources/views/Admin/Content/Blog/Article/detail.html.twig
  packages/framework/src/Resources/views/Admin/Content/Blog/Article/new.html.twig
  packages/framework/src/Resources/views/Admin/Content/Blog/Category/detail.html.twig
  packages/framework/src/Resources/views/Admin/Content/Blog/Category/new.html.twig
  packages/framework/src/Resources/views/Admin/Content/Brand/edit.html.twig
  packages/framework/src/Resources/views/Admin/Content/Brand/new.html.twig
  packages/framework/src/Resources/views/Admin/Content/Category/new.html.twig
  packages/framework/src/Resources/views/Admin/Content/Currency/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Content/Order/AdvancedSearch/ruleForm.html.twig
  packages/framework/src/Resources/views/Admin/Content/Order/addProduct.html.twig
  packages/framework/src/Resources/views/Admin/Content/Product/AdvancedSearch/ruleForm.html.twig
  packages/framework/src/Resources/views/Admin/Content/Vat/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig
  packages/framework/src/Resources/views/Common/Form/theme.html.twig
  packages/framework/src/Resources/views/Common/robots.txt.twig
  packages/framework/src/Resources/views/Components/Collector/elasticSearch.html.twig
  packages/framework/src/Resources/views/Components/Icon/icon.html.twig
  packages/framework/src/Resources/views/Components/MailerSettingInfo/mailerSettingInfo.html.twig
  packages/framework/src/Resources/views/Front/Form/deliveryAddressChoiceFields.html.twig
  packages/framework/src/Twig/FormThemeExtension.php
  packages/framework/src/Twig/IconExtension.php
  packages/framework/src/Twig/MailerSettingExtension.php
  project-base/app/config/packages/twig.yaml
  project-base/app/templates/Admin/Content/LanguageConstant/edit.html.twig
  upgrade-notes/backend_20240709_145948.md
Labels: DX & Refactoring

#3246 [shopsys] few administration optimizations
  packages/framework/src/Component/Cron/CronModuleFacade.php
  packages/framework/src/Component/Grid/ArrayDataSource.php
  packages/framework/src/Component/Grid/ArrayWithPaginationDataSource.php
  packages/framework/src/Component/Grid/DataSourceInterface.php
  packages/framework/src/Component/Grid/Exception/RowNotFoundInGridByIdException.php
  packages/framework/src/Component/Grid/Grid.php
  packages/framework/src/Component/Grid/MoneyConvertingDataSourceDecorator.php
  packages/framework/src/Component/Grid/QueryBuilderDataSource.php
  packages/framework/src/Component/Grid/QueryBuilderWithRowManipulatorDataSource.php
  packages/framework/src/Component/Paginator/PaginatorInterface.php
  packages/framework/src/Component/Paginator/QueryPaginator.php
  packages/framework/src/Controller/Admin/DefaultController.php
  packages/framework/src/Controller/Admin/ProductController.php
  packages/framework/src/Model/Product/Parameter/ParameterRepository.php
  packages/framework/src/Model/Product/Unit/UnitFacade.php
  packages/framework/src/Model/Product/Unit/UnitRepository.php
  project-base/app/config/services.yaml
  upgrade-notes/backend_20240529_084428.md
  upgrade-notes/backend_20240703_131550.md
Labels: Performance

#3280 [framework] domains in admin now have colors up to 40 domains
  packages/framework/assets/styles/admin/components/in/image.less
Labels: Design & Appearance

#3283 [project-base] closed day data fixture now works for domains without store
  project-base/app/src/DataFixtures/Demo/ClosedDayDataFixture.php
  upgrade-notes/backend_20240724_143006.md
Labels: Bug

#3284 [project-base] fixed datafixtures for more than two domains
  project-base/app/src/DataFixtures/Demo/CustomerUserDataFixture.php
  project-base/app/src/DataFixtures/Demo/OrderDataFixture.php
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/GetOrderAsAuthenticatedCustomerUserTest.php
  upgrade-notes/backend_20240724_150311.md
Labels: Bug

#3278 [luigis-box] added additional information to LuigisBoxClient failed requests
  packages/luigis-box/src/Component/LuigisBox/LuigisBoxClient.php
Labels: DX & Refactoring

#3211 [project-base][SSP-2246] adverts query optimisation
  packages/framework/src/Model/Advert/AdvertRepository.php
  packages/frontend-api/src/Model/Advert/AdvertFacade.php
  packages/frontend-api/src/Model/Advert/AdvertRepository.php
  packages/frontend-api/src/Model/Resolver/Advert/AdvertsQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/Query/QueryDecorator.types.yaml
  project-base/app/config/services.yaml
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/AdvertDataFixture.php
  project-base/app/src/FrontendApi/Model/Resolver/AdvertsQuery.php
  project-base/app/src/Model/Advert/Advert.php
  project-base/app/src/Model/Advert/AdvertData.php
  project-base/app/src/Model/Advert/AdvertDataFactory.php
  project-base/app/src/Model/Advert/AdvertFacade.php
  project-base/app/src/Model/Advert/AdvertPositionRegistry.php
  project-base/app/src/Model/Advert/AdvertRepository.php
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMixFacade.php
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMixRepository.php
  project-base/app/tests/FrontendApiBundle/Functional/Advert/GetAdvertsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Advert/graphql/GetAdvertsQuery.graphql
  project-base/storefront/components/Blocks/Adverts/AdvertImage.tsx
  project-base/storefront/components/Blocks/Adverts/Adverts.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/adverts/queries/AdvertsQuery.generated.tsx
  project-base/storefront/graphql/requests/adverts/queries/AdvertsQuery.graphql
  project-base/storefront/graphql/types.ts
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/order/contact-information.tsx
  project-base/storefront/pages/order/transport-and-payment.tsx
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/utils/serverSide/initServerSideProps.ts
  upgrade-notes/backend_20240529_084428.md
Labels: Performance
