Repository shopsys/shopsys, pull requests merged in 2024-05, with the labels that each got.

#3134 [framework] fix issues reported by phpstan
  UPGRADE-15.0.md
  packages/coding-standards/extension.neon
  packages/framework/composer.json
  packages/framework/phpstan.neon
  packages/framework/src/Model/Cart/Cart.php
  packages/framework/src/Model/Cart/Payment/CartPaymentData.php
  packages/framework/src/Model/Cart/Payment/CartPaymentDataFactory.php
  packages/framework/src/Model/Cart/Payment/CartPaymentFacade.php
  packages/framework/src/Model/Cart/Transport/CartTransportData.php
  packages/framework/src/Model/Cart/Transport/CartTransportDataFactory.php
  packages/framework/src/Model/Cart/Transport/CartTransportFacade.php
  packages/frontend-api/src/Model/Cart/TransportAndPaymentWatcherFacade.php
  packages/frontend-api/src/Model/Mutation/Cart/PaymentInCartMutation.php
  packages/frontend-api/src/Model/Mutation/Cart/TransportInCartMutation.php
  phpstan.neon
  project-base/app/composer.json
  project-base/app/tests/FrontendApiBundle/Functional/Order/TransportInOrderValidationTest.php
Labels: Bug

#3149 [frontend-api] applied promo code is now taken into account in priceByTransportQuery and priceByPaymentQuery (v15.0)
  packages/frontend-api/src/Model/Resolver/Price/PriceQuery.php
Labels: Bug

#3146 [framework] fix sending emails with attachments
  UPGRADE-14.0.md
  docs/introduction/faq-and-common-issues.md
  packages/framework/src/Component/UploadedFile/UploadedFile.php
  packages/framework/src/Model/Mail/Mailer.php
  project-base/app/src/DataFixtures/Demo/MailTemplateDataFixture.php
  project-base/app/src/Model/Mail/MailTemplateConfiguration.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
Labels: Bug

#3151 [framework] fix sending emails with attachments (v15.0)
  docs/introduction/faq-and-common-issues.md
  packages/framework/src/Component/UploadedFile/UploadedFile.php
  packages/framework/src/Model/Mail/Mailer.php
  project-base/app/src/DataFixtures/Demo/MailTemplateDataFixture.php
  project-base/app/src/Model/Mail/MailTemplateConfiguration.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
Labels: Bug

#3152 [framework] fixed money type with null value in entity log
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/MoneyDataTypeFormatter.php
Labels: Bug

#3150 [project-base] [SSP-2292] removed duplicated price display on product detail page
  UPGRADE-15.0.md
  project-base/storefront/components/Pages/ProductDetail/ProductDetailAddToCart/ProductDetailAddToCart.tsx
Labels: Bug, Design & Appearance

#3133 [shopsys] removed no longer used operator info
  UPGRADE-15.0.md
  packages/framework/src/Controller/Admin/ShopInfoController.php
  packages/framework/src/Form/Admin/ShopInfo/ShopInfoSettingFormType.php
  packages/framework/src/Migrations/Version20240426045700.php
  packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
  packages/framework/src/Model/ShopInfo/ShopInfoSettingFacade.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Twig/ShopInfoExtension.php
  project-base/app/src/DataFixtures/Demo/SettingValueShopInfoDataFixture.php
  project-base/app/templates/Admin/Content/Error/error500.html.twig
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
Labels: DX & Refactoring

#3145 [project-base] [SSP-2290] cookies store smarter init
  UPGRADE-15.0.md
  project-base/storefront/components/Pages/App/AppPageContent.tsx
  project-base/storefront/components/providers/CookiesStoreProvider.tsx
  project-base/storefront/store/createCookieStore.ts
  project-base/storefront/store/useCookiesStore.ts
  project-base/storefront/utils/cookies/cookieStoreUtils.ts
  project-base/storefront/utils/cookies/cookiesStore.ts
  project-base/storefront/utils/serverSide/getServerSidePropsWrapper.ts
  project-base/storefront/utils/serverSide/initServerSideProps.ts
Labels: Bug, Enhancement

#3124 [framework] changed email from which contact form is sent so emails are not catched by spam filters
  packages/framework/src/Model/ContactForm/ContactFormFacade.php
Labels: Bug

#3128 [shopsys] display error messages in admin if legal conditions articles are not set
  UPGRADE-15.0.md
  packages/framework/src/Controller/Admin/DefaultController.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  project-base/app/src/Controller/Admin/DefaultController.php
Labels: Enhancement

#3163 [project-base][SSP-2303] minor improvements to cypress tests
  UPGRADE-15.0.md
  docs/storefront/cypress.md
  project-base/storefront/components/Layout/Header/Contact/HeaderContact.tsx
  project-base/storefront/cypress/e2e/order/createOrder.cy.ts
  project-base/storefront/cypress/e2e/order/orderSupport.ts
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should discard user's previous cart after logging in in order 3rd step (third step after second login).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should discard user's previous cart after logging in in order 3rd step (third step before second login).png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/should add product to cart from search results page (add to cart popup).png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/should try to add more products to cart than allowed from category page using spinbox input, and the spinbox quantity should correct itself (add to cart popup).png
  project-base/storefront/cypress/support/index.ts
  project-base/storefront/cypress/tids.ts
Labels: DX & Refactoring

#3144 [framework] load products iteratively while generating image sitemaps
  UPGRADE-15.0.md
  packages/framework/src/Model/ImageSitemap/ImageSitemapFacade.php
  packages/framework/src/Model/Product/ProductRepository.php
Labels: Enhancement

#3161 [shopsys] rename variable differentDeliveryAddress into isDeliveryAddressDifferentFromBilling
  UPGRADE-15.0.md
  packages/frontend-api/apiary.apib
  packages/frontend-api/apiary/order/methods/create-order-with-errors.md
  packages/frontend-api/apiary/order/methods/create-order.md
  packages/frontend-api/apiary/order/methods/list-of-customer-user-orders.md
  packages/frontend-api/apiary/order/methods/order-detail-authorized.md
  packages/frontend-api/apiary/order/methods/order-detail-unauthorized.md
  packages/frontend-api/src/Model/Mutation/Order/CreateOrderMutation.php
  packages/frontend-api/src/Model/Order/OrderDataFactory.php
  packages/frontend-api/src/Model/Resolver/Order/OrderResolverMap.php
  packages/frontend-api/src/Resources/config/graphql-types/OrderDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/OrderInput/OrderInputDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Cart/AddOrderItemsToCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Newsletter/NewsletterSubscribeFromOrderAnonymousTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Newsletter/NewsletterSubscribeFromOrderLoggedInTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/CompanyFieldsAreValidatedTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/DeliveryAddressIsNotDuplicatedTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsValidationTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/DynamicFieldsInOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/FullOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/GetOrderSentPageContentTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/MinimalOrderAsAuthenticatedCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/MinimalOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/MultipleProductsInOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/OrderTestTrait.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/OrderWithPersonalPickupStoreTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/OrderWithPromoCodeTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/ProductInOrderValidationTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/RequiredFieldsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/graphql/CreateFullOrderMutation.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Order/graphql/CreateMinimalOrderMutation.graphql
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/mutation/CreateOrderMutation.graphql
  project-base/storefront/components/Pages/Order/ContactInformation/ContactInformationContent.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationDeliveryAddress.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/contactInformationFormMeta.ts
  project-base/storefront/cypress/e2e/order/contactInformation.cy.ts
  project-base/storefront/cypress/e2e/order/createOrderWithDeliveryAddress.cy.ts
  project-base/storefront/cypress/e2e/order/orderSupport.ts
  project-base/storefront/cypress/fixtures/demodata.ts
  project-base/storefront/cypress/fixtures/generators.ts
  project-base/storefront/cypress/support/api.ts
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailFragment.graphql
  project-base/storefront/graphql/requests/orders/mutations/CreateOrderMutation.generated.tsx
  project-base/storefront/graphql/requests/orders/mutations/CreateOrderMutation.graphql
  project-base/storefront/graphql/requests/orders/queries/OrderDetailByHashQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrderDetailQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/store/slices/createContactInformationSlice.ts
Labels: DX & Refactoring

#3141 [shopsys] include domain sale exclusion in product querying more appropriately
  UPGRADE-15.0.md
  packages/framework/src/Form/Admin/Product/ProductFormType.php
  packages/framework/src/Model/Product/ProductRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/product-feed-luigis-box/src/Model/Product/LuigisBoxProductRepository.php
  project-base/app/src/Form/Admin/ProductFormTypeExtension.php
  project-base/app/src/Model/Product/ProductRepository.php
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
Labels: Enhancement

#3175 [docs] updated the infrastructure schema
  docs/img/shopsys-platform-infrastructure.png
Labels: Documentation

#3168 [shopsys] added blackfire profiling configuration and instructions
  UPGRADE-15.0.md
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose.yml.dist
  docs/introduction/blackfire-profiling.md
  docs/introduction/index.md
  docs/introduction/navigation.yml
  project-base/app/docker/php-fpm/Dockerfile
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
Labels: DX & Refactoring

#3177 [infrastructure] monorepo force split now sets all packages to same branch so it easily testable
  .github/monorepo/split-repositories.sh
Labels: Infrastructure

#3170 [project-base] parameter data fixture refactoring
  UPGRADE-15.0.md
  project-base/app/src/DataFixtures/Demo/CategoryParameterDataFixture.php
  project-base/app/src/DataFixtures/Demo/DataObject/ParameterDataFixtureData.php
  project-base/app/src/DataFixtures/Demo/ParameterColorValueDataFixture.php
  project-base/app/src/DataFixtures/Demo/ParameterDataFixture.php
  project-base/app/src/DataFixtures/Demo/ParameterGroupDataFixture.php
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/app/src/DataFixtures/Demo/ReadyCategorySeoDataFixture.php
  project-base/app/src/Model/Product/Parameter/ParameterGroupFacade.php
  project-base/app/src/Model/Product/Parameter/ParameterRepository.php
  project-base/app/tests/App/Functional/Model/Product/Filter/ParameterFilterChoiceRepositoryTest.php
  project-base/app/tests/App/Functional/Model/Product/ProductOnCurrentDomainElasticFacadeCountDataTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Category/ReadyCategorySeoMix/ReadyCategorySeoMixTest.php
  project-base/app/tests/FrontendApiBundle/Functional/ParameterFilter/ParameterFilterValidationTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringOptionsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
Labels: DX & Refactoring

#3172 [project-base][SSP-2167] removed invalid cache invalidation when adding to product list
  UPGRADE-15.0.md
  project-base/storefront/urql/cache/updates.ts
Labels: Bug
