Repository shopsys/shopsys, pull requests merged in 2024-06, with the labels that each got.

#3182 [project-base] fixed blogarticle demo data
  UPGRADE-15.0.md
  project-base/app/src/DataFixtures/Demo/BlogArticleDataFixture.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
Labels: Bug

#3169 [framework] images are no longer processed by PHP to avoid quality decrease
  UPGRADE-15.0.md
  composer.json
  open-source-license-acknowledgements-and-third-party-copyrights.md
  packages/framework/assets/styles/admin/components/list/files.less
  packages/framework/composer.json
  packages/framework/src/Component/Domain/DomainFacade.php
  packages/framework/src/Component/Domain/DomainIconProcessor.php
  packages/framework/src/Component/Image/Processing/Exception/OriginalSizeImageCannotBeGeneratedException.php
  packages/framework/src/Component/Image/Processing/ImageProcessor.php
  packages/framework/src/Component/Image/Processing/ImageThumbnailFactory.php
  packages/framework/src/Form/Admin/Domain/DomainFormType.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  packages/framework/src/Resources/views/Admin/Content/Advert/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Form/imageuploadFields.html.twig
  packages/framework/src/Twig/FileThumbnail/FileThumbnailExtension.php
  packages/framework/src/Twig/ImageExtension.php
  packages/framework/tests/Unit/Twig/FileThumbnail/FileThumbnailExtensionTest.php
  packages/php-image/Dockerfile
  project-base/app/composer.json
  project-base/app/config/packages/twig.yaml
  project-base/app/symfony.lock
  project-base/app/templates/Admin/Form/imageuploadFields.html.twig
  project-base/app/templates/bundles/ShopsysFrameworkBundle/Admin/Content/Advert/listGrid.html.twig
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  symfony.lock
Labels: Enhancement, Performance, Use PHP Dockerfile instead of built image

#3176 [project-base][SSP-1614] useContext refactoring
  UPGRADE-15.0.md
  project-base/storefront/components/Pages/App/AppPageContent.tsx
  project-base/storefront/gtm/GtmHeadScript.tsx
  project-base/storefront/gtm/context/GtmProvider.tsx
  project-base/storefront/gtm/context/useGtmContext.ts
  project-base/storefront/gtm/utils/pageViewEvents/productList/useGtmPaginatedProductListViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/productList/useGtmSliderProductListViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmAutocompleteResultsViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmCartViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmContactInformationPageViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmPageViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmPaymentAndTransportPageViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmProductDetailViewEvent.ts
  project-base/storefront/pages/_app.tsx
Labels: DX & Refactoring

#3178 [project-base] minor array keys fix
  UPGRADE-15.0.md
  project-base/storefront/components/Basic/SymfonyDebugToolbar/SymfonyDebugToolbarRequestsTable.tsx
  project-base/storefront/components/Basic/UserText/GrapesJsParser.tsx
Labels: DX & Refactoring

#3179 [project-base][SSP-2268] fixed translation on customer's edit profile page
  UPGRADE-15.0.md
  project-base/storefront/public/locales/cs/common.json
Labels: Bug

#3171 [project-base][SSP-2326] added option to migrate persist store
  UPGRADE-15.0.md
  docs/storefront/cypress.md
  docs/storefront/store-management.md
  project-base/storefront/cypress/e2e/authentication/login.cy.ts
  project-base/storefront/cypress/e2e/authentication/registration.cy.ts
  project-base/storefront/cypress/e2e/cart/cartInHeader.cy.ts
  project-base/storefront/cypress/e2e/cart/cartLogin.cy.ts
  project-base/storefront/cypress/e2e/cart/cartPage.cy.ts
  project-base/storefront/cypress/e2e/cart/cartSupport.ts
  project-base/storefront/cypress/e2e/cart/productAddToCart.cy.ts
  project-base/storefront/cypress/e2e/order/contactInformation.cy.ts
  project-base/storefront/cypress/e2e/order/createOrder.cy.ts
  project-base/storefront/cypress/e2e/order/createOrderWithDeliveryAddress.cy.ts
  project-base/storefront/cypress/e2e/order/orderRepeat.cy.ts
  project-base/storefront/cypress/e2e/order/orderSupport.ts
  project-base/storefront/cypress/e2e/transportAndPayment/lastOrderTransportAndPayment.cy.ts
  project-base/storefront/cypress/e2e/transportAndPayment/paymentSelect.cy.ts
  project-base/storefront/cypress/e2e/transportAndPayment/transportSelect.cy.ts
  project-base/storefront/cypress/e2e/visits/repeatedVisits.cy.ts
  project-base/storefront/cypress/fixtures/demodata.ts
  project-base/storefront/cypress/support/api.ts
  project-base/storefront/cypress/support/index.ts
  project-base/storefront/store/slices/createAuthLoadingSlice.ts
  project-base/storefront/store/slices/createContactInformationSlice.ts
  project-base/storefront/store/slices/createPacketerySlice.ts
  project-base/storefront/store/slices/createUserSlice.ts
  project-base/storefront/store/usePersistStore.ts
Labels: Enhancement, Easy Pick, Documentation

#3195 [framework] fix VatDeletionCronModule
  UPGRADE-15.0.md
  packages/framework/src/Model/Product/Pricing/ProductInputPriceFacade.php
  packages/framework/src/Model/Product/Pricing/ProductInputPriceRecalculator.php
  packages/framework/src/Model/Product/Product.php
  project-base/app/src/Model/Product/Pricing/ProductInputPriceFacade.php
  project-base/app/src/Model/Product/Product.php
  project-base/app/tests/App/Functional/Model/Pricing/ProductInputPriceRecalculatorTest.php
Labels: Bug

#3197 [project-base] add nominal promo code to demo data
  UPGRADE-15.0.md
  project-base/app/src/DataFixtures/Demo/PromoCodeDataFixture.php
Labels: Easy Pick

#3187 [project-base] product data fixture refactoring
  UPGRADE-15.0.md
  project-base/app/config/services.yaml
  project-base/app/src/DataFixtures/Demo/DataSetter/ProductDemoDataSetter.php
  project-base/app/src/DataFixtures/Demo/DemoDataFactory/ProductDemoDataFactory.php
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
Labels: DX & Refactoring

#3215 [GitHub Actions] added missing checks for builds to build successful
  .github/get-build-exit-code.sh
  .github/workflows/docker-build.yaml
Labels: Infrastructure

#3217 [project-base] Luigi's Box search relations fix
  Makefile
  UPGRADE-15.0.md
  project-base/Makefile
  project-base/storefront/components/Pages/Search/SearchPageContent.tsx
  project-base/storefront/components/Pages/Search/SearchProductsContent.tsx
  project-base/storefront/components/Pages/Search/searchUtils.ts
  project-base/storefront/graphql/requests/products/queries/SearchProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/SearchQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/SearchQuery.graphql
  project-base/storefront/pages/search.tsx
Labels: Bug, Enhancement, DX & Refactoring

#3212 [framework] don't add manually added order item into repeat order cart
  packages/frontend-api/src/Model/Mutation/Cart/CartMutation.php
Labels: Bug

#3223 [framework] cleanup DB schema
  composer.json
  packages/article-feed-luigis-box/composer.json
  packages/brand-feed-luigis-box/composer.json
  packages/category-feed-luigis-box/composer.json
  packages/framework/composer.json
  packages/framework/src/Migrations/Version20240613231000.php
  packages/framework/src/Migrations/Version20240613235059.php
  packages/migrations/composer.json
  packages/product-feed-google/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-luigis-box/composer.json
  packages/product-feed-zbozi/composer.json
Labels: Bug, Performance

#3198 [project-base] add packeta type transport to demo data
  UPGRADE-15.0.md
  project-base/app/src/DataFixtures/Demo/PaymentDataFixture.php
  project-base/app/src/DataFixtures/Demo/TransportDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Payment/PaymentsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Transport/TransportsTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, check it, remove promo code from cart, and then add a different one (transport and payment page after applying first promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/should add product to cart from search results page (add to cart popup).png
  project-base/storefront/cypress/snapshots/e2e/order/contactInformation.cy.ts/should redirect to transport and payment select page and not display contact information form if transport and payment are not selected and user is logged in (transport and payment page).png
  project-base/storefront/cypress/snapshots/e2e/order/contactInformation.cy.ts/should redirect to transport and payment select page and not display contact information form if transport and payment are not selected and user is not logged in (transport and payment page).png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/paymentSelect.cy.ts/removing transport should remove payment as well, and then allow to select transport incompatible with previous payment (after removing transport).png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/should be able to remove transport using repeated clicks (after removing).png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/should be able to remove transport using reset button (after removing).png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/should change price for transport when cart is large enough for transport to be free (transport and payment page with too few products).png
Labels: Easy Pick

#3214 [project-base] refactoring of SEO categories - removed ReadyCategorySeoMixDataForForm
  UPGRADE-15.0.md
  project-base/app/src/Controller/Admin/CategorySeoController.php
  project-base/app/src/DataFixtures/Demo/ReadyCategorySeoDataFixture.php
  project-base/app/src/Form/Admin/ReadyCategorySeoCombinationFormType.php
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMix.php
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMixData.php
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMixDataFactory.php
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMixDataForForm.php
Labels: DX & Refactoring

#3194 [shopsys] split upgrade notes
  build.xml
  upgrade-notes/_layout.md
  upgrade-notes/_template.md
  upgrade-notes/backend_20240529_084428.md
  upgrade-notes/storefront_20240529_084431.md
  upgrade-notes/upgrade_notes.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateUpgradeReleaseWorker.php
Labels: DX & Refactoring

#3227 [shopsys] nominal promo code discount is limited by applicable products
  packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/ApplyNominalPromoCodeMiddleware.php
Labels: Bug

#3222 [SSP-2110] SF optimizations based on projects
  packages/frontend-api/src/Model/Resolver/Article/ArticleQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/SettingsDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Article/GetArticleTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Settings/GetSettingsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Settings/graphql/SettingsQuery.graphql
  project-base/storefront/components/Basic/Loader/Loader.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreview.tsx
  project-base/storefront/components/Blocks/BlogPreview/DeferredBlogPreview.tsx
  project-base/storefront/components/Blocks/UserConsent/DeferredUserConsent.tsx
  project-base/storefront/components/Blocks/UserConsent/UserConsentForm.tsx
  project-base/storefront/components/Blocks/UserConsent/userConsentUtils.ts
  project-base/storefront/components/Layout/Footer/Footer.tsx
  project-base/storefront/components/Layout/Footer/NewsletterForm/newsletterFormMeta.tsx
  project-base/storefront/components/Layout/Header/Cart/Cart.tsx
  project-base/storefront/components/Pages/Contact/contactFormMeta.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationSendOrderButton.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelect.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/transportAndPaymentUtils.tsx
  project-base/storefront/components/Pages/OrderConfirmation/registrationAfterOrderFormMeta.tsx
  project-base/storefront/components/Pages/Registration/registrationFormMeta.tsx
  project-base/storefront/components/PaymentsInOrderSelect/PaymentsInOrderSelectItem.tsx
  project-base/storefront/cypress/support/index.ts
  project-base/storefront/cypress/tids.ts
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/articles/queries/PrivacyPolicyArticleUrlQuery.generated.tsx
  project-base/storefront/graphql/requests/articles/queries/PrivacyPolicyArticleUrlQuery.graphql
  project-base/storefront/graphql/requests/articles/queries/TermsAndConditionsArticleUrlQuery.generated.tsx
  project-base/storefront/graphql/requests/articles/queries/TermsAndConditionsArticleUrlQuery.graphql
  project-base/storefront/graphql/requests/articles/queries/UserConsentPolicyArticleUrlQuery.generated.tsx
  project-base/storefront/graphql/requests/articles/queries/UserConsentPolicyArticleUrlQuery.graphql
  project-base/storefront/graphql/requests/blogCategories/queries/BlogUrlQuery.generated.tsx
  project-base/storefront/graphql/requests/blogCategories/queries/BlogUrlQuery.graphql
  project-base/storefront/graphql/requests/categories/queries/PromotedCategoriesQuery.generated.tsx
  project-base/storefront/graphql/requests/categories/queries/PromotedCategoriesQuery.graphql
  project-base/storefront/graphql/requests/orders/queries/OrdersCountQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/PromotedProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/PromotedProductsQuery.graphql
  project-base/storefront/graphql/requests/settings/queries/SettingsQuery.generated.tsx
  project-base/storefront/graphql/requests/settings/queries/SettingsQuery.graphql
  project-base/storefront/graphql/requests/sliderItems/queries/SliderItemsQuery.generated.tsx
  project-base/storefront/graphql/requests/sliderItems/queries/SliderItemsQuery.graphql
  project-base/storefront/graphql/types.ts
  project-base/storefront/pages/index.tsx
  project-base/storefront/pages/user-consent.tsx
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/urql/authExchange.ts
  project-base/storefront/utils/serverSide/initServerSideProps.ts
  upgrade-notes/backend_20240621_072038.md
  upgrade-notes/storefront_20240621_072038.md
Labels: Enhancement, DX & Refactoring

#3240 [project-base][SSP-2243] implemented new banners slider
  project-base/app/config/graphql/types/ModelType/Slider/SliderItem.types.yaml
  project-base/app/schema.graphql
  project-base/storefront/components/Blocks/Banners/BannerImage.tsx
  project-base/storefront/components/Blocks/Banners/BannersSlider.tsx
  project-base/storefront/components/Blocks/Banners/BannersSliderItem.tsx
  project-base/storefront/components/Blocks/Banners/BannersSliderPlaceholder.tsx
  project-base/storefront/components/Blocks/Banners/bannersUtils.ts
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/sliderItems/fragments/SliderItemFragment.generated.tsx
  project-base/storefront/graphql/requests/sliderItems/queries/SliderItemsQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  project-base/storefront/schema-compressed.graphql.json
  upgrade-notes/storefront_20240626_175916.md
Labels: Enhancement, Design & Appearance, DX & Refactoring, dependencies

#3241 [releaser] added update roadmap release step
  utils/releaser/config/after-release.php
  utils/releaser/src/ReleaseWorker/AfterRelease/EnsureRoadmapIsUpdatedReleaseWorker.php
Labels: Enhancement
