Repository shopsys/shopsys, pull requests merged in 2024-11, with the labels that each got.

#3532 [shopsys] Do not log out the user after changing the password
  packages/framework/src/Model/Customer/User/CustomerUserFacade.php
  packages/framework/src/Model/Customer/User/CustomerUserPasswordFacade.php
  packages/framework/src/Model/Customer/User/CustomerUserRefreshTokenChainFacade.php
  packages/framework/src/Model/Customer/User/CustomerUserRefreshTokenChainRepository.php
  packages/frontend-api/src/Model/Mutation/Customer/User/CustomerUserMutation.php
  project-base/app/src/Model/Customer/User/CustomerUserFacade.php
  project-base/app/src/Model/Customer/User/CustomerUserPasswordFacade.php
  project-base/app/src/Model/Customer/User/CustomerUserRefreshTokenChainFacade.php
  project-base/app/src/Model/Customer/User/CustomerUserRefreshTokenChainRepository.php
Labels: Enhancement

#3557 [Framework] Fix parameters groups migrations
  packages/framework/src/Migrations/Version20241007064158.php
  packages/framework/src/Migrations/Version20241101073720.php
  packages/framework/src/Migrations/Version20241101081004.php
  packages/framework/src/Migrations/Version20241101083720.php
  packages/framework/src/Model/Product/Parameter/ParameterRepository.php
  project-base/app/src/Migrations/Version20240702065648.php
  upgrade-notes/backend_20241009_135052.md
Labels: Bug

#3534 [shopsys] Role ROLE_ALL_API sees all company complaints
  packages/framework/src/Migrations/Version20241023142037.php
  packages/framework/src/Model/Complaint/Complaint.php
  packages/frontend-api/src/Model/Complaint/ComplaintApiFacade.php
  packages/frontend-api/src/Model/Complaint/ComplaintRepository.php
  packages/frontend-api/src/Model/Resolver/Complaint/ComplaintQuery.php
  packages/frontend-api/src/Model/Resolver/Complaint/ComplaintsQuery.php
  project-base/app/src/DataFixtures/Demo/CompanyComplaintDataFixture.php
  project-base/app/src/DataFixtures/Demo/ComplaintDataFixture.php
  project-base/app/src/DataFixtures/Demo/Helper/ComplaintHelper.php
  project-base/app/src/DataFixtures/resources/images/complaint/404.jpg
  project-base/app/src/DataFixtures/resources/images/complaint/405.jpg
  upgrade-notes/backend_20241025_060719.md
Labels: Enhancement

#3535 [project-base] hidden repeat order button
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailBasicInfo.tsx
  project-base/storefront/components/Pages/Customer/Orders/OrderItem.tsx
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintItemFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/CreateComplaintFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/mutations/CreateComplaintMutation.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintsQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/OrderedItemsQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/SearchOrderedItemsQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/ListedOrderFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/ListedOrderFragment.graphql
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailItemFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailItemFragment.graphql
  project-base/storefront/graphql/requests/orders/fragments/OrderListFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrderDetailByHashQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrderDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrdersQuery.generated.tsx
  project-base/storefront/graphql/requests/personalData/queries/PersonalDataDetailQuery.generated.tsx
  upgrade-notes/storefront_20241025_075505.md
Labels: Design & Appearance

#3543 [project-base] added new email validation regex
  project-base/storefront/components/Forms/validationRules.ts
  upgrade-notes/storefront_20241030_064410.md
Labels: Enhancement

#3544 [project-base] fixed product edit in development environment
  packages/framework/assets/js/admin/validation/form/index.js
  packages/framework/assets/js/admin/validation/form/validationUniqueProductCatnum.js
  packages/framework/src/Form/Admin/Product/ProductFormType.php
  packages/framework/src/Form/Constraints/UniqueProductCatnum.php
  packages/framework/src/Form/Constraints/UniqueProductCatnumValidator.php
  packages/framework/src/Model/Product/ProductFacade.php
  packages/framework/src/Model/Product/ProductRepository.php
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  project-base/app/assets/js/admin/validation/index.js
  project-base/app/src/Form/Admin/ProductFormTypeExtension.php
  project-base/app/src/Model/Product/ProductFacade.php
  project-base/app/src/Model/Product/ProductRepository.php
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  project-base/app/translations/validators.cs.po
  project-base/app/translations/validators.en.po
  upgrade-notes/backend_20241030_090019.md
Labels: Bug

#3562 [project-base] Stabilise cypress tests locally
  Makefile
  project-base/Makefile
  upgrade-notes/storefront_20241101_153857.md
Labels: DX & Refactoring

#3538 [project-base] Refactored animations for order transport and payment
  project-base/storefront/components/Blocks/Popup/PickupPlacePopup.tsx
  project-base/storefront/components/Layout/OrderLayout/OrderLayout.tsx
  project-base/storefront/components/Layout/Popup/Popup.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/StoreSelect.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelect.tsx
  upgrade-notes/storefront_20241030_111703.md
Labels: Bug

#3523 [project-base] reset form state after logout
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/[Discard Cart] (third step after second login) discard user's previous cart after logging in in order 3rd step.png
  project-base/storefront/cypress/snapshots/e2e/order/contactInformation.cy.ts/[Logged Preserve Contact Form] (contact information page after reload) keep changed contact information after page refresh for logged-in user.png
  project-base/storefront/cypress/snapshots/e2e/order/contactInformation.cy.ts/[Logout Clear Form] (filled contact information form before logout) remove contact information after logout.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/[Logged Home Cash] (filled contact information form) create order as logged-in user (transport to home, cash on delivery) and check it in order detail.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/[Logged Preserve Form On Checkbox Change] (contact information form after checking again) keep filled delivery address for logged-in user after unchecking the checkbox for different delivery address and then checking it again.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/[Logged Preserve Form On Checkbox Change] (contact information form before filling) keep filled delivery address for logged-in user after unchecking the checkbox for different delivery address and then checking it again.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/[Logged Preserve Form On Refresh] (contact information form after refresh) keep filled delivery address for logged-in user after page refresh.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/[Logged Preserve Form On Refresh] (contact information form before filling) keep filled delivery address for logged-in user after page refresh.png
  project-base/storefront/utils/auth/useLogout.tsx
  project-base/storefront/utils/user/useCurrentUserContactInformation.ts
  upgrade-notes/storefront_20241021_123404.md
Labels: Bug, Design & Appearance

#3508 [shopsys] frontend API testing on b2b domain
  packages/framework/build.xml
  packages/framework/src/Component/Domain/Domain.php
  packages/framework/tests/Test/TestTranslatableListener.php
  packages/frontend-api/src/Component/Constraints/UniqueBillingAddressApiValidator.php
  packages/frontend-api/src/Model/Order/OrderRepository.php
  packages/frontend-api/src/Resources/config/graphql-types/Mutation/MutationDecorator.types.yaml
  project-base/app/config/graphql/types/Mutation/PersonalData/PersonalDataMutation.types.yaml
  project-base/app/phpunit.xml
  project-base/app/src/DataFixtures/Demo/CompanyComplaintDataFixture.php
  project-base/app/src/DataFixtures/Demo/CompanyDataFixture.php
  project-base/app/src/DataFixtures/Demo/CompanyOrderDataFixture.php
  project-base/app/src/DataFixtures/Demo/CustomerUserDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Advert/GetAdvertsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/User/CurrentCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/User/RegisterTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/GetNullAsLastOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/MinimalOrderAsAuthenticatedCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductList/ProductListLoggedCustomerWithoutListTest.php
  project-base/app/tests/FrontendApiBundle/Functional/SliderItem/GetSliderItemsTest.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/CustomerUserOwnerTest.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/CustomerUserSelfManageTest.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/Helper/ChangePersonalDataInputProvider.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/RegisterTest.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/AddNewCustomerUserMutation.graphql
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/CustomerUsersQuery.graphql
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/EditCustomerUserPersonalDataMutation.graphql
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/OrderQuery.graphql
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/OrdersQuery.graphql
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/RemoveCustomerUserMutation.graphql
  project-base/app/tests/FrontendApiBundle/Test/CommonGraphQlWithLoginTestCase.php
  project-base/app/tests/FrontendApiBundle/Test/GraphQlB2bDomainTestCase.php
  project-base/app/tests/FrontendApiBundle/Test/GraphQlB2bDomainWithLoginTestCase.php
  project-base/app/tests/FrontendApiBundle/Test/GraphQlTestCase.php
  project-base/app/tests/FrontendApiBundle/Test/GraphQlWithLoginTestCase.php
  upgrade-notes/backend_20241104_103744.md
Labels: DX & Refactoring

#3507 [project-base] added brand and flag page filtration
  project-base/storefront/components/Blocks/CollapsibleDescriptionWithImage/CollapsibleDescriptionWithImage.tsx
  project-base/storefront/components/Blocks/FilteredProductsWrapper/FilteredProductsWrapper.tsx
  project-base/storefront/components/Blocks/Product/Filter/DeferredFilterPanel.tsx
  project-base/storefront/components/Blocks/Product/Filter/FilterPanel.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonManager.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleProductListItem.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleProductsList.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageBrand.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageFlag.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageProductsListSimple.tsx
  project-base/storefront/components/Blocks/SortingBar/DeferredFilterAndSortingBar.tsx
  project-base/storefront/components/Pages/BrandDetail/BrandDetailContent.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
  project-base/storefront/components/Pages/FlagDetail/FlagDetailContent.tsx
  project-base/storefront/components/Pages/Search/SearchProducts.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Brand Page Add] (add to cart popup) add product to cart from brand page.png
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/store/slices/createFilterPanelSlice.ts
  project-base/storefront/store/useSessionStore.ts
  project-base/storefront/types/friendlyUrl.ts
  project-base/storefront/utils/useDeferredRender.ts
  upgrade-notes/storefront_20241015_131136.md
Labels: Design & Appearance

#3515 [shopsys] tweak docs about social login settings
  docs/integration/social-networks.md
Labels: Documentation

#3483 [shopsys] CI is now built as production
  .github/workflows/docker-build.yaml
  project-base/app/docker/php-fpm/Dockerfile
Labels: Infrastructure

#3565 [project-base] fixed category image responsive
  project-base/storefront/components/Blocks/CollapsibleDescriptionWithImage/CollapsibleDescriptionWithImage.tsx
  upgrade-notes/storefront_20241104_073836.md
Labels: Bug, Design & Appearance

#3546 [shopsys] register company after order is more user friendly on b2b domain
  packages/frontend-api/src/Model/Customer/Exception/CompanyAlreadyRegisteredUserError.php
  packages/frontend-api/src/Model/Customer/User/RegistrationFacade.php
  packages/frontend-api/src/Model/Resolver/Customer/CustomerRegisteredQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/Query/QueryDecorator.types.yaml
  project-base/app/config/graphql/types/Query/Customer/User/CustomerUserQuery.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/FrontendApi/Resolver/Customer/User/CustomerUserRegisteredQuery.php
  project-base/storefront/components/Pages/Order/ContactInformation/contactInformationUtils.ts
  project-base/storefront/components/Pages/OrderConfirmation/RegistrationAfterOrder.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/customer/queries/CouldBeCustomerRegisteredQuery.generated.tsx
  project-base/storefront/graphql/requests/customer/queries/CouldBeCustomerRegisteredQuery.graphql
  project-base/storefront/graphql/types.ts
  project-base/storefront/pages/order-confirmation.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/utils/errors/applicationErrors.ts
  project-base/storefront/utils/errors/errorMessageMapper.ts
  upgrade-notes/backend_20241101_140019.md
  upgrade-notes/storefront_20241101_140019.md
Labels: Enhancement

#3576 [project-base] fixed change password page for users without password
  project-base/storefront/components/Blocks/UserNavigation/UserNavigation.tsx
  project-base/storefront/components/Pages/Customer/ChangePassword/ChangePassword.tsx
  project-base/storefront/components/Pages/Customer/ChangePassword/ChangePasswordContent.tsx
  project-base/storefront/components/Pages/Customer/ChangePassword/ResetPassword.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/ChangePassword.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/[Register B2C] (customer edit page) register as a B2C customer.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/[Register After Order] (customer edit page) register after order completion, and check that the just created order is in customer orders.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/[Register After Order] (order detail) register after order completion, and check that the just created order is in customer orders.png
  upgrade-notes/storefront_20241106_144452.md
Labels: Bug

#3579 [project-base] removed initial tab animation on product detail page
  project-base/storefront/components/Basic/Tabs/Tabs.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItemPlaceholder.tsx
  project-base/storefront/components/Blocks/Product/ProductsSliderPlaceholder.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleComparisonAndWishlistButtons.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleProductDetailAddToCart.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailTabs/ProductDetailTabs.tsx
  upgrade-notes/storefront_20241107_075309.md
Labels: Bug, Design & Appearance

#3541 [project-base] fixed cart delivery address validation
  project-base/storefront/components/Pages/Customer/EditProfile/AddressList.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/ContactInformationContent.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationDeliveryAddress.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/contactInformationFormMeta.ts
  upgrade-notes/storefront_20241029_121335.md
Labels: Bug

#3433 [shopsys] list of complaints in personal data
  packages/framework/src/Controller/Front/PersonalDataController.php
  packages/framework/src/Model/Complaint/Complaint.php
  packages/framework/src/Model/Complaint/ComplaintData.php
  packages/framework/src/Model/Complaint/ComplaintFacade.php
  packages/framework/src/Model/Complaint/ComplaintRepository.php
  packages/framework/src/Resources/views/Front/Content/PersonalData/complaints.xml.twig
  packages/framework/src/Resources/views/Front/Content/PersonalData/export.xml.twig
  project-base/app/config/graphql/types/ModelType/PersonalData/PersonalData.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/Controller/Front/PersonalDataController.php
  project-base/app/src/FrontendApi/Resolver/PersonalData/PersonalDataQuery.php
  project-base/app/tests/App/Functional/PersonalData/PersonalDataExportXmlTest.php
  project-base/app/tests/App/Functional/PersonalData/Resources/test.xml
  project-base/storefront/components/Pages/PersonalData/Detail/PersonalDataDetailContent.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/personalData/queries/PersonalDataDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/personalData/queries/PersonalDataDetailQuery.graphql
  project-base/storefront/graphql/types.ts
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/schema-compressed.graphql.json
  upgrade-notes/backend_20240913_092812.md
  upgrade-notes/storefront_20240913_092812.md
Labels: Enhancement

#3569 [project-base] Add animations for mobile navigation menu
  project-base/storefront/components/Layout/Header/MobileMenu/MobileMenu.tsx
  project-base/storefront/components/Layout/Header/MobileMenu/MobileMenuContent.tsx
  project-base/storefront/components/Layout/Header/MobileMenu/MobileMenuListItem.tsx
  project-base/storefront/components/Layout/Header/MobileMenu/MobileMenuSubItems.tsx
  upgrade-notes/storefront_20241104_172822.md
Labels: Design & Appearance

#3578 [Framework] Rename tv products for main and variants
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/RetrieveCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/CategorySeo/CategorySeoTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/Flag/FlagTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductVariantTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsByCatnumsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringOptionsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/PromotedProductsTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/storefront/cypress/fixtures/demodata.ts
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Brand Page Add] (add to cart popup) add product to cart from brand page.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Product Variant Add] (add to cart popup) add variant product to cart from product detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Homepage] (homepage) homepage visit with screenshot.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Product Detail] (product detail) product detail visit with screenshot.png
Labels: DX & Refactoring

#3581 [Framework] Preselected country in the delivery address creating by billing address
  packages/framework/src/Model/Customer/DeliveryAddressDataFactory.php
Labels: Bug

#3421 [framework] getting position for new image is now more robust
  packages/framework/src/Component/FileUpload/FileUpload.php
  packages/framework/src/Component/Image/ImageRepository.php
  upgrade-notes/backend_20240909_132416.md
Labels: DX & Refactoring, In Backlog

#3580 [project-base] polished menu animations
  project-base/storefront/components/Basic/Animations/AnimateNavigationMenu.tsx
  project-base/storefront/components/Layout/Header/Navigation/Navigation.tsx
  project-base/storefront/components/Layout/Header/Navigation/NavigationItem.tsx
  upgrade-notes/storefront_20241107_094214.md
Labels: Bug, Design & Appearance

#3598 [project-base] fixed failing MainBlogCategoryDataSettingsTest because of incorrect domain url
  project-base/app/tests/FrontendApiBundle/Functional/Settings/MainBlogCategoryDataSettingsTest.php
  upgrade-notes/backend_20241114_094625.md
Labels: DX & Refactoring

#3599 [framework]CustomerFileNotFoundException now checks existence of App\Environment so it is working correctly on splited packages
  packages/framework/src/Component/CustomerUploadedFile/Exception/CustomerFileNotFoundException.php
Labels: Bug

#3600 [project-base] category without image is now rendered correctly
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
  upgrade-notes/storefront_20241114_101951.md
Labels: Bug

#3596 [project-base] fixed product detail code and brand
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailElements.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailMainVariantContent.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Product Detail Add] (add to cart popup) add product to cart from product detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Product Detail] (product detail) product detail visit with screenshot.png
  upgrade-notes/storefront_20241114_065144.md
Labels: Bug, Design & Appearance

#3592 [project-base] Remove active filters when switching pages
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/pages/flags/[flagSlug].tsx
  project-base/storefront/pages/search.tsx
  project-base/storefront/utils/seo/useResetOriginalCategorySlug.ts
  upgrade-notes/storefront_20241112_155546.md
Labels: Bug

#3601 [shopsys] separated edit personal data mutation to allow change data for self-managed user on b2b domain
  packages/frontend-api/src/Model/Customer/User/CustomerUserUpdateDataFactory.php
  packages/frontend-api/src/Model/Mutation/Customer/User/CustomerUserMutation.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Customer/CustomerUser/Input/ChangeCompanyDataInputDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Customer/CustomerUser/Input/ChangePersonalDataInputDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/Mutation/MutationDecorator.types.yaml
  project-base/app/config/graphql/types/ModelType/PersonalData/PersonalDataInput/ChangeCompanyDataInput.types.yaml
  project-base/app/config/graphql/types/ModelType/PersonalData/PersonalDataInput/ChangePersonalDataInput.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/CompanyDataFixture.php
  project-base/app/src/FrontendApi/Model/Customer/User/CustomerUserUpdateDataFactory.php
  project-base/app/src/FrontendApi/Mutation/Customer/User/CustomerUserMutation.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/User/CurrentCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/User/graphql/ChangePersonalDataMutation.graphql
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/CustomerUserOwnerTest.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/AddNewCustomerUserMutation.graphql
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/EditCustomerUserPersonalDataMutation.graphql
  project-base/storefront/components/Blocks/Popup/ManageCustomerUserPopup.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/EditProfileContent.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/customer/mutations/ChangeCompanyDataMutation.generated.tsx
  project-base/storefront/graphql/requests/customer/mutations/ChangeCompanyDataMutation.graphql
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
  upgrade-notes/backend_20241114_135955.md
  upgrade-notes/storefront_20241114_135955.md
Labels: Bug

#3574 [Shopsys] Sliders extension
  packages/framework/assets/js/admin/components/NumberSlider.js
  packages/framework/assets/js/admin/components/index.js
  packages/framework/assets/styles/admin/libs/number-slider/number-slider-custom.less
  packages/framework/assets/styles/admin/main.less
  packages/framework/src/Form/Admin/Slider/SliderItemFormType.php
  packages/framework/src/Form/NumberSliderType.php
  packages/framework/src/Migrations/Version20241031100638.php
  packages/framework/src/Model/Slider/SliderItem.php
  packages/framework/src/Model/Slider/SliderItemData.php
  packages/framework/src/Model/Slider/SliderItemDataFactory.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  packages/framework/src/Resources/views/Admin/Form/numberSlider.html.twig
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Slider/SliderItemDecorator.types.yaml
  project-base/app/config/graphql/types/ModelType/Slider/SliderItem.types.yaml
  project-base/app/config/packages/twig.yaml
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/SliderItemDataFixture.php
  project-base/app/src/Form/Admin/SliderItemFormTypeExtension.php
  project-base/app/src/FrontendApi/Resolver/SliderItem/SliderItemResolverMap.php
  project-base/app/src/Migrations/Version20241114072907.php
  project-base/app/src/Model/Slider/SliderItem.php
  project-base/app/src/Model/Slider/SliderItemData.php
  project-base/app/src/Model/Slider/SliderItemDataFactory.php
  project-base/app/tests/FrontendApiBundle/Functional/SliderItem/GetSliderItemsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/SliderItem/graphql/SliderItemsQuery.graphql
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  project-base/storefront/components/Blocks/Banners/Banner.tsx
  project-base/storefront/components/Blocks/Banners/BannerImage.tsx
  project-base/storefront/components/Blocks/Banners/BannersSlider.tsx
  project-base/storefront/components/Blocks/Banners/bannersUtils.ts
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/sliderItems/fragments/SliderItemFragment.generated.tsx
  project-base/storefront/graphql/requests/sliderItems/fragments/SliderItemFragment.graphql
  project-base/storefront/graphql/requests/sliderItems/queries/SliderItemsQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
  upgrade-notes/backend_20241119_072753.md
  upgrade-notes/storefront_20241111_124125.md
Labels: Design & Appearance

#3464 [project-base] GrapesJS new plugins
  project-base/app/assets/js/admin/grapesjs/initGrapesJs.js
  project-base/app/assets/js/admin/grapesjs/locales/cs.js
  project-base/app/assets/js/admin/grapesjs/locales/en.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-blocks-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-buttons-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-iframe-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-image-file-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-image-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-custom-link-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-mail-template-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-products-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-table-custom-plugin.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-text-with-image-plugin.js
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  project-base/storefront/styles/user-text.css
  upgrade-notes/backend_20241105_133044.md
Labels: Enhancement

#3609 [framework] improve appearence of datagrid
  packages/framework/assets/styles/admin/components/table/grid.less
  packages/framework/assets/styles/admin/core/variables.less
Labels: Design & Appearance

#3618 [project-base] Fix Gitlab tests
  packages/php-image/Dockerfile
  project-base/.gitlab-ci.yml
  project-base/app/docker/php-fpm/Dockerfile
  upgrade-notes/backend_20241121_143218.md
Labels: Bug

#3619 [project-base] fixed running jest on alpine on gitlab
  project-base/.gitlab-ci.yml
  upgrade-notes/backend_20241121_143218.md
Labels: Bug

#3607 [project-base] Enable deleting Spinbox's value
  project-base/storefront/components/Forms/Spinbox/Spinbox.tsx
  project-base/storefront/components/Pages/Cart/CartList/CartListItem.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideIcons.tsx
  project-base/storefront/cypress/e2e/cart/cartPage.cy.ts
  upgrade-notes/storefront_20241119_170756.md
Labels: Design & Appearance

#3613 [project-base] Remove duplicate Webline for RecommendedProducts
  project-base/storefront/components/Blocks/Product/DeferredRecommendedProducts.tsx
  project-base/storefront/components/Pages/HomePage/HomePageContent.tsx
  upgrade-notes/storefront_20241122_102620.md
Labels: Bug

#3604 [framework] added missing weight attribute to Packeta
  docs/integration/index.md
  docs/integration/navigation.yml
  docs/integration/packeta.md
  packages/framework/src/Component/Packetery/Packet/PacketAttributes.php
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Resources/views/Packetery/createPacket.xml.twig
  project-base/app/src/DataFixtures/Demo/DemoDataFactory/ProductDemoDataFactory.php
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/[Add Remove Promo] (transport and payment page after applying first promocode) add promo code to cart, check it, remove promo code from cart, and then add a different one.png
  upgrade-notes/backend_20241118_111219.md
Labels: Enhancement

#3621 [project-base] updated fetcher condition
  project-base/storefront/urql/fetcher.ts
  upgrade-notes/storefront_20241126_104229.md
Labels: Bug

#3617 [project-base] added users table role column
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemUserAuthenticatedContent.tsx
  project-base/storefront/components/Pages/Customer/Users/CustomerUsersTable.tsx
  upgrade-notes/storefront_20241125_123725.md
Labels: Design & Appearance

#3610 [project-base] updated user navigation alignments
  project-base/storefront/components/Blocks/UserNavigation/UserNavigation.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/[Register B2C] (customer edit page) register as a B2C customer.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/[Register After Order] (customer edit page) register after order completion, and check that the just created order is in customer orders.png
  upgrade-notes/storefront_20241121_105351.md
Labels: Bug

#3568 [project-base] fixed tablet account popups
  project-base/storefront/components/Basic/Drawer/Drawer.tsx
  project-base/storefront/components/Forms/Lib/LabelWrapper.tsx
  project-base/storefront/components/Layout/Header/Cart/CartInHeader.tsx
  project-base/storefront/components/Layout/Header/Cart/CartInHeaderPopover.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicElements.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemUserAuthenticated.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemUserUnauthenticated.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemUserUnauthenticatedContent.tsx
  project-base/storefront/cypress/e2e/authentication/authenticationSupport.ts
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/[Cart Header Remove] (after second remove) remove products from cart using cart in header and then display empty cart message.png
  upgrade-notes/storefront_20241104_120204.md
Labels: Bug, Design & Appearance

#3616 [frontend-api] JwtConfiguration is now created on demand
  packages/frontend-api/src/Model/Token/JwtConfigurationProvider.php
  packages/frontend-api/src/Model/Token/TokenFacade.php
  packages/frontend-api/src/Resources/config/services.yaml
  packages/frontend-api/tests/Unit/Model/Token/TokenFacadeTest.php
  project-base/app/src/FrontendApi/Model/Token/TokenFacade.php
  upgrade-notes/backend_20241126_124621.md
Labels: DX & Refactoring

#3608 [shopsys] Slug of Seo page is now saved as text instead of FriendlyUrl
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGridFactory.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlRepository.php
  packages/framework/src/Form/Admin/Seo/SeoPageFormType.php
  packages/framework/src/Form/Constraints/UniqueSeoPageSlug.php
  packages/framework/src/Form/Constraints/UniqueSeoPageSlugValidator.php
  packages/framework/src/Migrations/Version20241119123503.php
  packages/framework/src/Model/Seo/HreflangLinksFacade.php
  packages/framework/src/Model/Seo/Page/SeoPage.php
  packages/framework/src/Model/Seo/Page/SeoPageDataFactory.php
  packages/framework/src/Model/Seo/Page/SeoPageDomain.php
  packages/framework/src/Model/Seo/Page/SeoPageFacade.php
  packages/framework/src/Model/Seo/Page/SeoPageFriendlyUrlDataProvider.php
  packages/framework/src/Model/Seo/Page/SeoPageGridFactory.php
  packages/framework/src/Model/Seo/Page/SeoPageRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  packages/framework/src/Resources/views/Admin/Content/Seo/Page/listGrid.html.twig
  project-base/app/config/shopsys-routing/routing_friendly_url.yaml
  project-base/app/src/DataFixtures/Demo/SeoPageDataFixture.php
  project-base/app/tests/App/Functional/Model/SeoPage/SeoPageTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Hreflang/HreflangLinksTest.php
  project-base/storefront/urql/errorExchange.ts
  upgrade-notes/backend_20241127_115108.md
  upgrade-notes/storefront_20241127_115108.md
Labels: Enhancement

#3558 [shopsys] releaser: replace BitWarden mentions with 1Password
  utils/releaser/src/ReleaseWorker/AfterRelease/CheckDocsReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ReleaseNewNodeModulePackageVersion.php
Labels: Easy Pick
