Repository shopsys/shopsys, pull requests merged in 2024-01, with the labels that each got.

#2963 [shopsys] Persoo feed fixes
  packages/category-feed-persoo/src/Model/FeedItem/PersooCategoryFeedItemFactory.php
  packages/product-feed-persoo/src/Model/FeedItem/PersooFeedItemFactory.php
  packages/product-feed-persoo/src/Resources/views/feed.xml.twig
  packages/product-feed-persoo/tests/Unit/PersooFeedItemTest.php
Labels: Bug

#2966 [SSP-2021] fix broken drag and drop in GrapesJS in Safari
  UPGRADE-14.0.md
  project-base/app/assets/js/admin/grapesjs/initGrapesJs.js
  project-base/app/package.json
Labels: Bug

#2962 [frontend-api] add Category ID to CategoryHierarchyItem
  UPGRADE-14.0.md
  packages/frontend-api/src/Resources/config/graphql-types/CategoryDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/CategoryHierarchyItemDecorator.types.yaml
  project-base/app/config/graphql/types/ModelType/Category/Category.types.yaml
  project-base/app/config/graphql/types/ModelType/Category/CategoryHierarchyItem.types.yaml
  project-base/app/schema.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Category/CategoryHierarchyTest.php
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/query/CategoryHierarchy/CategoryListQuery.graphql
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/query/CategoryHierarchy/ChildrenQuery.graphql
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/query/CategoryHierarchy/SingleCategoryQuery.graphql
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/categories/fragments/CategoryDetailFragment.graphql
  project-base/storefront/gtm/helpers/gtm.ts
  project-base/storefront/schema.graphql.json
Labels: Enhancement

#2973 [SSP-2034] improve error handling for friendly URL pages based on API status codes
  UPGRADE-14.0.md
  packages/frontend-api/src/Model/Error/ErrorCodeSubscriber.php
  project-base/storefront/helpers/errors/handleServerSideErrorResponseForFriendlyUrls.ts
  project-base/storefront/pages/articles/[articleSlug].tsx
  project-base/storefront/pages/blogArticles/[blogArticleSlug].tsx
  project-base/storefront/pages/blogCategories/[blogCategorySlug].tsx
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/flags/[flagSlug].tsx
  project-base/storefront/pages/products/[productSlug].tsx
  project-base/storefront/pages/stores/[storeSlug].tsx
Labels: Enhancement, Easy Pick, Frontend API

#2981 [framework] product recalculations priority queue
  UPGRADE-14.0.md
  docs/asynchronous-processing/handling-failed-product-recalculations.md
  packages/framework/src/Command/DispatchRecalculationMessageCommand.php
  packages/framework/src/Controller/Admin/ProductController.php
  packages/framework/src/Model/Product/ProductFacade.php
  packages/framework/src/Model/Product/Recalculation/AbstractProductRecalculationMessage.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationMessageHandler.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationPriorityEnum.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationPriorityEnumInterface.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationPriorityHighMessage.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationPriorityRegularMessage.php
  project-base/app/config/packages/messenger.yaml
  project-base/app/deploy/deploy-project.sh
  project-base/app/docker/php-fpm/consumer-entrypoint.sh
  project-base/app/src/Controller/Admin/ProductController.php
  project-base/app/src/Model/Product/ProductFacade.php
  project-base/app/tests/App/Test/WebTestCase.php
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
Labels: Enhancement

#2985 [infrastructure] GitHub actions now use default_branch set in repository instead of variable
  .github/cancel-old-reviews.sh
  .github/workflows/cancel-old-reviews.yaml
  .github/workflows/clean-up-after-branch-merge.yaml
  .github/workflows/manually-cancel-review.yaml
Labels: Infrastructure

#2989 [framework] admin: fixed flag filter in product advanced search
  packages/framework/src/Model/AdvancedSearch/Filter/ProductFlagFilter.php
Labels: Bug

#2991 [infrastructure] fixed path to codeception logs in project-base
  project-base/.github/workflows/run-checks-tests.yaml
Labels: Infrastructure

#2988 [docs] added documentation about asynchronous processing
  docs/asynchronous-processing/index.md
  docs/asynchronous-processing/introduction-to-asynchronous-processing.md
  docs/asynchronous-processing/navigation.yml
  docs/asynchronous-processing/product-recalculations.md
  docs/cookbook/create-asynchronous-notifier.md
  docs/cookbook/index.md
  docs/cookbook/navigation.yml
Labels: Documentation

#2998 [shopsys] emails are now sent via queue
  UPGRADE-14.0.md
  packages/framework/src/Model/Mail/Email.php
  project-base/app/config/packages/messenger.yaml
  project-base/app/deploy/deploy-project.sh
  project-base/app/docker/php-fpm/consumer-entrypoint.sh
Labels: Enhancement

#2994 [project-base] grapesjs product catnums field is now text input
  UPGRADE-14.0.md
  packages/framework/src/Component/GrapesJs/GrapesJsParser.php
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-products-plugin.js
Labels: Bug

#3000 [shopsys] fixed type annotation on collections
  UPGRADE-14.0.md
  packages/framework/src/Component/Image/Image.php
  packages/framework/src/Model/Administrator/Administrator.php
  packages/framework/src/Model/Blog/Article/BlogArticle.php
  packages/framework/src/Model/Blog/Category/BlogCategory.php
  packages/framework/src/Model/Cart/Cart.php
  packages/framework/src/Model/Category/Category.php
  packages/framework/src/Model/Country/Country.php
  packages/framework/src/Model/Customer/Customer.php
  packages/framework/src/Model/Customer/User/CustomerUser.php
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Model/Order/Status/OrderStatus.php
  packages/framework/src/Model/Payment/Payment.php
  packages/framework/src/Model/Product/Availability/Availability.php
  packages/framework/src/Model/Product/Brand/Brand.php
  packages/framework/src/Model/Product/Flag/Flag.php
  packages/framework/src/Model/Product/Parameter/Parameter.php
  packages/framework/src/Model/Product/Product.php
  packages/framework/src/Model/Product/ProductDomain.php
  packages/framework/src/Model/Product/Unit/Unit.php
  packages/framework/src/Model/Store/Store.php
  packages/framework/src/Model/Transport/Transport.php
  packages/product-feed-heureka/src/Model/HeurekaCategory/HeurekaCategory.php
  project-base/app/src/Model/Cart/Cart.php
  project-base/app/src/Model/Category/Category.php
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMix.php
  project-base/app/src/Model/Customer/User/CustomerUser.php
  project-base/app/src/Model/LanguageConstant/LanguageConstant.php
  project-base/app/src/Model/Order/Order.php
  project-base/app/src/Model/Payment/Payment.php
  project-base/app/src/Model/Product/Parameter/ParameterGroup.php
  project-base/app/src/Model/Product/Product.php
  project-base/app/src/Model/Product/ProductDataFactory.php
  project-base/app/src/Model/Product/ProductDomain.php
  project-base/app/src/Model/ProductFeed/Mergado/MergadoFeedItemFacade.php
  project-base/app/src/Model/ProductFeed/Mergado/MergadoProductRepository.php
  project-base/app/src/Model/Transport/Transport.php
  project-base/app/src/ProductFeed/Google/Model/Product/GoogleProductRepository.php
  project-base/app/tests/App/Functional/EntityExtension/Model/CategoryManyToManyBidirectionalEntity.php
  project-base/app/tests/App/Functional/EntityExtension/Model/DummyEntity.php
  project-base/app/tests/App/Functional/EntityExtension/Model/ExtendedCategory.php
  project-base/app/tests/App/Functional/EntityExtension/Model/ExtendedDummyEntity.php
  project-base/app/tests/App/Functional/EntityExtension/Model/ExtendedProduct.php
  project-base/app/tests/App/Functional/EntityExtension/Model/ProductManyToManyBidirectionalEntity.php
Labels: DX & Refactoring
