Repository shopsys/shopsys, pull requests merged in 2024-04, with the labels that each got.

#3090 [SSP-2231] Cypress make command fix
  Makefile
  UPGRADE-15.0.md
  project-base/Makefile
Labels: Bug

#3093 [SSP-2233] cypress stability fixes
  UPGRADE-15.0.md
  docs/storefront/cypress.md
  project-base/storefront/components/Basic/Link/Link.tsx
  project-base/storefront/components/Layout/Footer/newsletterFormMeta.tsx
  project-base/storefront/components/Pages/Contact/ContactContent.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationSendOrderButton.tsx
  project-base/storefront/components/Pages/OrderConfirmation/registrationAfterOrderFormMeta.tsx
  project-base/storefront/components/Pages/Registration/registrationFormMeta.tsx
  project-base/storefront/cypress/cypress.d.ts
  project-base/storefront/cypress/e2e/order/contactInformation.cy.ts
  project-base/storefront/cypress/e2e/order/createOrderWithDeliveryAddress.cy.ts
  project-base/storefront/cypress/e2e/transportAndPayment/lastOrderTransportAndPayment.cy.ts
  project-base/storefront/cypress/support/api.ts
  project-base/storefront/cypress/support/index.ts
Labels: Bug, DX & Refactoring

#3094 [SSP-2234] fixed incorrect keys in cache exchange config
  UPGRADE-15.0.md
  project-base/storefront/urql/cache/cacheExchange.ts
Labels: Bug

#2494 Not null data in delivery address
  UPGRADE-15.0.md
  packages/framework/assets/js/admin/validation/form/validationCustomer.js
  packages/framework/src/Form/Admin/Customer/BillingAddressFormType.php
  packages/framework/src/Form/Admin/Customer/DeliveryAddressFormType.php
  packages/framework/src/Migrations/Version20220725104726.php
  packages/framework/src/Model/Customer/DeliveryAddress.php
  project-base/app/config/forms.yaml
  project-base/app/src/DataFixtures/Demo/CustomerUserDataFixture.php
  project-base/app/src/Form/Admin/Customer/DeliveryAddressFormTypeExtension.php
Labels: DX & Refactoring, In Backlog

#2567 Elasticsearch structure vol 2.0
  UPGRADE-15.0.md
  packages/framework/assets/package.json
  packages/framework/tests/Unit/Component/Elasticsearch/__fixtures/definitions/invalidJson/product/1.json
  packages/framework/tests/Unit/Component/Elasticsearch/__fixtures/definitions/valid/product/1.json
  packages/framework/tests/Unit/Component/Translation/Resources/translationsDump.json
  project-base/app/src/Model/Product/Elasticsearch/ProductExportRepository.php
  project-base/app/src/Model/Product/Search/ProductElasticsearchConverter.php
  project-base/app/src/Resources/definition/article/1.json
  project-base/app/src/Resources/definition/article/2.json
  project-base/app/src/Resources/definition/blog_article/1.json
  project-base/app/src/Resources/definition/blog_article/2.json
  project-base/app/src/Resources/definition/product/1.json
  project-base/app/src/Resources/definition/product/2.json
  project-base/app/tests/App/Functional/Model/Product/Elasticsearch/ProductExportRepositoryTest.php
  utils/license-acknowledgements-generator/license-report-config.json
Labels: In Backlog

#2820 restrict limit of requests how many can robot ask from eshop
  UPGRADE-15.0.md
  packages/framework/src/Migrations/Version20230919173422.php
  project-base/app/src/DataFixtures/Demo/SettingValueDataFixture.php
Labels: In Backlog

#3087 [frontend-api] main blog category URL is now available via settings query
  packages/framework/src/Model/Blog/Category/BlogCategoryFacade.php
  packages/framework/src/Model/Blog/Category/BlogCategoryRepository.php
  packages/frontend-api/src/Model/Resolver/Settings/MainBlogCategoryUrlQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/SettingsDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Settings/MainBlogCategoryUrlSettingsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Settings/graphql/MainBlogCategoryUrlSettingsQuery.graphql
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
Labels: Performance

#3083 add developer styleguide
  UPGRADE-15.0.md
  project-base/storefront/components/Basic/IconImage/IconImage.tsx
  project-base/storefront/components/Forms/Lib/LabelWrapper.tsx
  project-base/storefront/components/Layout/Footer/FooterContact.tsx
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSearchPopup.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideButtons.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideCheckboxes.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideColors.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideContent.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideElements.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideForms.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideIcons.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguidePopups.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideRadiogroup.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideSelects.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideSpinboxes.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideTables.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideToasts.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideTooltips.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideTypography.tsx
  project-base/storefront/config/staticRewritePaths.ts
  project-base/storefront/pages/styleguide.tsx
  project-base/storefront/utils/serverSide/initServerSideProps.ts
Labels: Design & Appearance

#3106 [SSP-2206] cart and product lists are not refetched while auth loading is active
  project-base/storefront/utils/cart/useCurrentCart.ts
  project-base/storefront/utils/productLists/useProductList.ts
Labels: Bug

#3096 [SSP-2206] cart and product lists are not refetched while auth loading is active
  UPGRADE-14.0.md
  packages/framework/src/Component/ClassExtension/DocBlockParser.php
  project-base/storefront/hooks/cart/useCurrentCart.ts
  project-base/storefront/hooks/productLists/useProductList.ts
Labels: Bug

#3111 [frontend-api] fixed ordering of search results
  packages/frontend-api/src/Model/Resolver/Products/ProductOrderingModeProvider.php
  packages/frontend-api/src/Model/Resolver/Products/Search/ProductSearchResultsProvider.php
Labels: Bug

#3113 [shopsys] fixed saving empty article
  packages/framework/src/Component/GrapesJs/GrapesJsParser.php
Labels: Bug

#3098 [shopsys] add customer option for Verified by Customers Heureka
  UPGRADE-14.0.md
  packages/framework/src/Form/Admin/Order/OrderFormType.php
  packages/framework/src/Migrations/Version20240415095045.php
  packages/framework/src/Model/Heureka/HeurekaSetting.php
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Model/Order/OrderData.php
  packages/framework/src/Model/Order/OrderDataFactory.php
  packages/framework/src/Model/Order/OrderFacade.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/tests/Unit/Model/Order/OrderFacadeHeurekaTest.php
  packages/frontend-api/src/Model/Resolver/Settings/HeurekaQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/OrderDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/OrderInput/OrderInputDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/SettingsDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/SettingValueDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/FullOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/graphql/CreateFullOrderMutation.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Settings/HeurekaEnabledSettingTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Settings/graphql/HeurekaEnabledSettingsQuery.graphql
  project-base/storefront/components/Pages/Order/ContactInformation/ContactInformationFormWrapper.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/contactInformationFormMeta.ts
  project-base/storefront/connectors/customer/CurrentCustomerUser.ts
  project-base/storefront/cypress/fixtures/demodata.ts
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/orders/mutations/CreateOrderMutation.graphql
  project-base/storefront/graphql/requests/settings/queries/SettingsQuery.graphql
  project-base/storefront/hooks/forms/useHandleContactInformationNonTextChanges.ts
  project-base/storefront/pages/order/contact-information.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/schema.graphql.json
  project-base/storefront/store/slices/createContactInformationSlice.ts
Labels: Enhancement

#3116 open cypress tests is now possible on WSL
  Makefile
  UPGRADE-15.0.md
  project-base/Makefile
Labels: DX & Refactoring

#3115 [project-base] friendly url fixes
  UPGRADE-15.0.md
  project-base/app/src/Component/Router/FriendlyUrl/FriendlyUrlMatcher.php
  project-base/app/src/FrontendApi/Component/Breadcrumb/Exception/UnableToGenerateBreadcrumbItemsUserError.php
  project-base/app/src/FrontendApi/Resolver/Breadcrumb/BreadcrumbQuery.php
  project-base/app/src/Model/Product/Flag/FlagRepository.php
  project-base/app/web/resolveFriendlyUrl.php
  project-base/storefront/utils/errors/applicationErrors.ts
Labels: Bug

#3127 [framework] messenger: prevent errors when MESSENGER_TRANSPORT_DSN is empty (v15.0)
  packages/framework/src/Component/Messenger/AbstractMessageDispatcher.php
  packages/framework/src/Component/Messenger/MessageBusDecorator.php
  packages/framework/src/Component/Messenger/NullMessageBus.php
  packages/framework/src/Resources/config/services.yaml
Labels: Bug

#3126 [frontend-api] addProductToListMutation: ensure new product list is created with non-conflicting uuid
  UPGRADE-14.0.md
  packages/framework/src/Model/Product/List/ProductListFacade.php
  packages/framework/src/Model/Product/List/ProductListRepository.php
  packages/frontend-api/src/Model/Mutation/ProductList/ProductListMutation.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductList/ProductListLoggedCustomerTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductList/ProductListNotLoggedCustomerTest.php
Labels: Bug

#3105 [frontend-api] create order with preselected delivery address
  UPGRADE-15.0.md
  packages/frontend-api/src/Component/Constraints/DeliveryAddressUuid.php
  packages/frontend-api/src/Component/Constraints/DeliveryAddressUuidValidator.php
  packages/frontend-api/src/Model/Mutation/Order/CreateOrderMutation.php
  packages/frontend-api/src/Model/Order/OrderDataFactory.php
  packages/frontend-api/src/Model/Order/PlaceOrderFacade.php
  packages/frontend-api/src/Resources/config/graphql-types/OrderInput/OrderInputDecorator.types.yaml
  packages/frontend-api/src/Resources/translations/validators.cs.po
  packages/frontend-api/src/Resources/translations/validators.en.po
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/CartDataFixture.php
  project-base/app/src/DataFixtures/Demo/CustomerUserDataFixture.php
  project-base/app/src/FrontendApi/Model/Order/PlaceOrderFacade.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsAreValidatedTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsValidationTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/MinimalOrderAsAuthenticatedCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/MinimalOrderTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/graphql/CreateMinimalOrderMutation.graphql
  project-base/storefront/components/Pages/Order/ContactInformation/ContactInformationContent.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/types.ts
Labels: Enhancement, DX & Refactoring

#3104 [framework] dispatch product stocks export after Setting::TRANSFER_DAYS_BETWEEN_STOCKS is set
  UPGRADE-15.0.md
  packages/framework/src/Model/Stock/StockSettingsDataFacade.php
Labels: Enhancement

#3110 [luigis-box] added parameter filter to Luigi's Box search
  docs/integration/luigis-box.md
  packages/frontend-api/src/Model/Product/Filter/ProductFilterOptionsFactory.php
  packages/frontend-api/src/Model/Resolver/Products/Search/ProductSearchQuery.php
  packages/frontend-api/src/Model/Resolver/Products/Search/ProductSearchResultsProvider.php
  packages/frontend-api/src/Model/Resolver/Products/Search/ProductSearchResultsProviderInterface.php
  packages/luigis-box/src/Component/LuigisBox/Filter/ProductFilterToLuigisBoxFilterMapper.php
  packages/luigis-box/src/Component/LuigisBox/LuigisBoxClient.php
  packages/luigis-box/src/Model/Product/Filter/LuigisBoxFacetsToProductFilterOptionsMapper.php
  packages/luigis-box/src/Model/Product/Parameter/Value/ParameterValueRepository.php
  packages/luigis-box/src/Model/Product/ProductSearchResultsProvider.php
  packages/product-feed-luigis-box/src/Model/FeedItem/LuigisBoxProductFeedItemFacade.php
  project-base/app/src/DataFixtures/Demo/ParameterDataFixture.php
  project-base/app/src/DataFixtures/Demo/ReadyCategorySeoDataFixture.php
  project-base/app/src/FrontendApi/Model/Product/Filter/ProductFilterOptionsFactory.php
  project-base/app/tests/App/Functional/Model/Product/ProductOnCurrentDomainElasticFacadeCountDataTest.php
  project-base/storefront/components/Blocks/Product/Filter/FilterSelectedParameters.tsx
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSearchPopup.tsx
  project-base/storefront/pages/products/[productSlug].tsx
Labels: Enhancement

#3112 [frontend-api] cart is now correctly created for current customer user when carts are merged
  UPGRADE-14.0.md
  project-base/app/src/FrontendApi/Mutation/Cart/CartMutation.php
Labels: Bug

#3122 [shopsys] removed no longer used functionality of measuring scripts
  UPGRADE-14.0.md
  docs/integration/index.md
  docs/integration/third-party-scripts.md
  packages/framework/assets/js/admin/components/MeasuringScript.js
  packages/framework/assets/js/admin/components/index.js
  packages/framework/src/Controller/Admin/ScriptController.php
  packages/framework/src/Form/Admin/Script/GoogleAnalyticsScriptFormType.php
  packages/framework/src/Form/Admin/Script/ScriptFormType.php
  packages/framework/src/Migrations/Version20240416105031.php
  packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
  packages/framework/src/Model/Script/Exception/ScriptException.php
  packages/framework/src/Model/Script/Exception/ScriptNotFoundException.php
  packages/framework/src/Model/Script/Script.php
  packages/framework/src/Model/Script/ScriptData.php
  packages/framework/src/Model/Script/ScriptDataFactory.php
  packages/framework/src/Model/Script/ScriptDataFactoryInterface.php
  packages/framework/src/Model/Script/ScriptFacade.php
  packages/framework/src/Model/Script/ScriptFactory.php
  packages/framework/src/Model/Script/ScriptFactoryInterface.php
  packages/framework/src/Model/Script/ScriptRepository.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  packages/framework/src/Resources/views/Admin/Content/Script/detail.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/edit.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/googleAnalytics.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/new.html.twig
  packages/framework/src/Twig/ScriptsExtension.php
  project-base/app/config/packages/security.yaml
  project-base/app/src/Controller/Admin/SideMenuConfigurationSubscriber.php
  project-base/app/src/DataFixtures/Demo/ScriptDataFixture.php
  project-base/app/src/Model/Security/MenuItemsGrantedRolesSetting.php
  project-base/app/src/Model/Security/Roles.php
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
Labels: DX & Refactoring

#3137 [shopsys] removed no longer used functionality of measuring scripts
  docs/integration/index.md
  docs/integration/third-party-scripts.md
  packages/framework/assets/js/admin/components/MeasuringScript.js
  packages/framework/assets/js/admin/components/index.js
  packages/framework/src/Controller/Admin/ScriptController.php
  packages/framework/src/Form/Admin/Script/GoogleAnalyticsScriptFormType.php
  packages/framework/src/Form/Admin/Script/ScriptFormType.php
  packages/framework/src/Migrations/Version20240416105031.php
  packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
  packages/framework/src/Model/Script/Exception/ScriptException.php
  packages/framework/src/Model/Script/Exception/ScriptNotFoundException.php
  packages/framework/src/Model/Script/Script.php
  packages/framework/src/Model/Script/ScriptData.php
  packages/framework/src/Model/Script/ScriptDataFactory.php
  packages/framework/src/Model/Script/ScriptDataFactoryInterface.php
  packages/framework/src/Model/Script/ScriptFacade.php
  packages/framework/src/Model/Script/ScriptFactory.php
  packages/framework/src/Model/Script/ScriptFactoryInterface.php
  packages/framework/src/Model/Script/ScriptRepository.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  packages/framework/src/Resources/views/Admin/Content/Script/detail.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/edit.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/googleAnalytics.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Content/Script/new.html.twig
  packages/framework/src/Twig/ScriptsExtension.php
  project-base/app/config/packages/security.yaml
  project-base/app/src/Controller/Admin/SideMenuConfigurationSubscriber.php
  project-base/app/src/DataFixtures/Demo/ScriptDataFixture.php
  project-base/app/src/Model/Security/MenuItemsGrantedRolesSetting.php
  project-base/app/src/Model/Security/Roles.php
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
Labels: DX & Refactoring

#3139 [project-base] fix main variants in last visited products
  UPGRADE-14.0.md
  project-base/storefront/components/Pages/ProductDetail/ProductDetailMainVariantContent.tsx
Labels: Bug

#3140 [project-base] fix main variants in last visited products (v15.0)
  project-base/storefront/components/Pages/ProductDetail/ProductDetailMainVariantContent.tsx
Labels: Bug

#3142 [SSP-2289] cart hydration fix
  project-base/storefront/hooks/cart/useCurrentCart.ts
  project-base/storefront/store/slices/createPageLoadingStateSlice.ts
Labels: Bug

#3138 [SSP-2285] recommended products skeleton
  UPGRADE-14.0.md
  project-base/storefront/components/Blocks/Product/RecommendedProducts.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleProductListItem.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleProductSlider.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageCart.tsx
  project-base/storefront/components/Pages/Cart/CartContent.tsx
Labels: Design & Appearance

#3143 Port of cart hydration fix to v15
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailMainVariantContent.tsx
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/index.tsx
  project-base/storefront/pages/products/[productSlug].tsx
  project-base/storefront/store/slices/createPageLoadingStateSlice.ts
  project-base/storefront/utils/cart/useCurrentCart.ts
Labels: Bug
