Repository shopsys/shopsys, pull requests merged in 2024-08, with the labels that each got.

#3285 [framework] address, name and some other user data is now nullable
  packages/framework/src/Migrations/Version20240724062626.php
  packages/framework/src/Migrations/Version20240729072354.php
  packages/framework/src/Migrations/Version20240730070101.php
  packages/framework/src/Model/Customer/BillingAddress.php
  packages/framework/src/Model/Customer/DeliveryAddress.php
  packages/framework/src/Model/Customer/User/CustomerUser.php
  packages/framework/src/Model/Customer/User/CustomerUserUpdateDataFactory.php
  packages/framework/tests/Unit/Model/Customer/CustomerUserUpdateDataFactoryTest.php
  packages/framework/tests/Unit/Model/Customer/TestCustomerProvider.php
  packages/frontend-api/src/Model/Customer/User/RegistrationDataFactory.php
  upgrade-notes/backend_20240725_061952.md
Labels: Easy Pick, In Backlog

#3279 [shopsys] refactored product price form type
  docs/cookbook/basic-data-import.md
  packages/form-types-bundle/src/MultidomainType.php
  packages/framework/src/Form/Admin/Product/Price/MoneyWithCalculatedPriceType.php
  packages/framework/src/Form/Admin/Product/Price/PricesWithCalculatedSellingPricesType.php
  packages/framework/src/Form/Admin/Product/Price/ProductPricesWithVatSelectType.php
  packages/framework/src/Form/Admin/Product/ProductFormType.php
  packages/framework/src/Form/ProductCalculatedPricesType.php
  packages/framework/src/Model/Product/Pricing/ProductInputPriceFacade.php
  packages/framework/src/Model/Product/Pricing/ProductManualInputPriceFacade.php
  packages/framework/src/Model/Product/Product.php
  packages/framework/src/Model/Product/ProductData.php
  packages/framework/src/Model/Product/ProductDataFactory.php
  packages/framework/src/Model/Product/ProductFacade.php
  packages/framework/src/Model/Product/ProductInputPriceData.php
  packages/framework/src/Model/Product/ProductInputPriceDataFactory.php
  packages/framework/src/Resources/views/Admin/Form/Product/Price/pricesWithCalculatedSellingPricesType.html.twig
  packages/framework/src/Resources/views/Admin/Form/Product/Price/productPricesWithVatSelectType.html.twig
  packages/framework/src/Resources/views/Admin/Form/productCalculatedPrices.html.twig
  packages/framework/tests/Unit/Model/Order/Processing/OrderProcessorMiddleware/AddProductsMiddlewareTest.php
  project-base/app/config/packages/twig.yaml
  project-base/app/config/services.yaml
  project-base/app/src/DataFixtures/Demo/DataSetter/ProductDemoDataSetter.php
  project-base/app/src/DataFixtures/Demo/DemoDataFactory/ProductDemoDataFactory.php
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/app/src/Model/Product/Pricing/ProductInputPriceFacade.php
  project-base/app/src/Model/Product/ProductDataFactory.php
  project-base/app/tests/App/Functional/Model/Cart/CartItemTest.php
  project-base/app/tests/App/Functional/Model/Cart/CartTest.php
  project-base/app/tests/App/Functional/Model/Cart/Watcher/CartWatcherTest.php
  project-base/app/tests/App/Functional/Model/Product/ProductDomainTest.php
  project-base/app/tests/App/Functional/Model/Product/ProductFacadeTest.php
  project-base/app/tests/App/Functional/Model/Product/ProductVisibilityRepositoryTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/AuthenticatedCartModificationsResultTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/CartModificationsResultTest.php
  upgrade-notes/backend_20240724_092914.md
Labels: DX & Refactoring

#3300 [project-base][SSP-2508] updated filter slider apperance
  project-base/storefront/components/Blocks/Product/Filter/FilterSelectedParameters.tsx
  upgrade-notes/storefront_20240802_100126.md
Labels: Bug

#3287 [project-base][SSP-2513] Fixed skeleton loaders while navigating through main navigation
  project-base/storefront/components/Basic/ExtendedNextLink/ExtendedNextLink.tsx
  project-base/storefront/components/Layout/Header/Navigation/DeferredNavigation.tsx
  project-base/storefront/components/Layout/Header/Navigation/Navigation.tsx
  project-base/storefront/components/Layout/Header/Navigation/NavigationItem.tsx
  project-base/storefront/components/Layout/Header/Navigation/NavigationItemColumn.tsx
  project-base/storefront/components/Layout/Header/Navigation/NavigationPlaceholder.tsx
  project-base/storefront/vitest/components/ExtendedNextLink/ExtendedNextLink.test.tsx
  upgrade-notes/storefront_20240805_101042.md
Labels: Bug

#3305 [shopsys] add missing upgrade note for google maps
  upgrade-notes/storefront_20240722_104600.md
Labels: Documentation

#3299 [project-base][SSP-2505] added unification company user form validation
  project-base/storefront/components/Pages/Customer/EditProfileContent.tsx
  project-base/storefront/components/Pages/Customer/customerChangeProfileFormMeta.ts
  upgrade-notes/storefront_20240802_100451.md
Labels: Bug

#3290 [project-base][SSP-2488] added create and edit customer delivery address
  project-base/storefront/components/Basic/Icon/EditIcon.tsx
  project-base/storefront/components/Blocks/Popup/DeliveryAddressPopup.tsx
  project-base/storefront/components/Pages/Customer/AddressList.tsx
  project-base/storefront/components/Pages/Customer/EditProfileContent.tsx
  project-base/storefront/components/Pages/Customer/customerChangeProfileFormMeta.ts
  project-base/storefront/components/Pages/Customer/deliveryAddressFormMeta.ts
  project-base/storefront/components/Pages/NewPassword/NewPasswordContent.tsx
  project-base/storefront/components/Pages/NewPassword/recoveryPasswordFormMeta.ts
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationDeliveryAddress.tsx
  project-base/storefront/connectors/customer/CurrentCustomer.ts
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/should register as a B2C customer (customer edit page).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/should register after order completion, and check that the just created order is in customer orders (customer edit page).png
  project-base/storefront/graphql/requests/customer/mutations/CreateDeliveryAddressMutation.generated.tsx
  project-base/storefront/graphql/requests/customer/mutations/CreateDeliveryAddressMutation.graphql
  project-base/storefront/graphql/requests/customer/mutations/EditDeliveryAddressMutation.generated.tsx
  project-base/storefront/graphql/requests/customer/mutations/EditDeliveryAddressMutation.graphql
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/types/customer.ts
  project-base/storefront/types/form.ts
  project-base/storefront/urql/cache/updates.ts
  upgrade-notes/storefront_20240731_062725.md
Labels: Enhancement

#3313 [framework] refactoring: OrderStatus::$type is now string
  packages/framework/src/Migrations/Version20240614144002.php
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Model/Order/Status/Exception/InvalidOrderStatusTypeException.php
  packages/framework/src/Model/Order/Status/Grid/OrderStatusGridFactory.php
  packages/framework/src/Model/Order/Status/OrderStatus.php
  packages/framework/src/Model/Order/Status/OrderStatusFacade.php
  packages/framework/src/Model/Order/Status/OrderStatusFactory.php
  packages/framework/src/Model/Order/Status/OrderStatusFactoryInterface.php
  packages/framework/src/Model/Order/Status/OrderStatusRepository.php
  packages/framework/src/Model/Order/Status/OrderStatusTypeEnum.php
  packages/framework/src/Model/Product/BestsellingProduct/AutomaticBestsellingProductRepository.php
  packages/framework/src/Model/Statistics/StatisticsRepository.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/tests/Test/Provider/TestOrderProvider.php
  packages/framework/tests/Unit/Model/Order/Status/OrderStatusTest.php
  upgrade-notes/backend_20240806_093105.md
Labels: DX & Refactoring

#3315 [project-base] deploy-project.sh: add missing SEZNAM_CLIENT_SECRET to fix Seznam social login
  project-base/app/deploy/deploy-project.sh
  upgrade-notes/backend_20240529_084428.md
Labels: Infrastructure

#3309 [project-base][SSP-2552] updated product detail responsive
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailGallery.tsx
  upgrade-notes/storefront_20240805_114940.md
Labels: Design & Appearance

#3292 [framework] fix blog category without articles
  packages/framework/src/Component/GrapesJs/GrapesJsParser.php
  packages/framework/src/Controller/Admin/ArticleController.php
  packages/framework/src/Controller/Admin/BlogCategoryController.php
  packages/framework/src/Model/Article/ArticleFacade.php
  packages/framework/src/Model/Blog/BlogVisibilityRecalculationListener.php
  packages/framework/src/Model/Blog/Category/BlogCategoryFacade.php
  project-base/storefront/components/Pages/BlogCategory/BlogCategoryArticlesWrapper.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  upgrade-notes/backend_20240529_084428.md
  upgrade-notes/backend_20240626_162649.md
  upgrade-notes/backend_20240802_113516.md
  upgrade-notes/storefront_20240806_090405.md
Labels: Bug

#3307 [project-base][SSP-2551] updated contact info merge logic to handle empty object
  project-base/storefront/utils/user/useCurrentUserContactInformation.ts
  upgrade-notes/storefront_20240805_105651.md
Labels: Bug

#3296 [shopsys] role `ROLE_ALL_API` sees all customer user orders from common customer
  packages/framework/src/Controller/Admin/CustomerController.php
  packages/framework/src/Form/Admin/Order/OrderFormType.php
  packages/framework/src/Form/DisplayOnlyCompanyNameType.php
  packages/framework/src/Migrations/Version20240731150432.php
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Resources/views/Admin/Form/displayOnlyCompanyName.html.twig
  packages/frontend-api/src/Model/Order/OrderApiFacade.php
  packages/frontend-api/src/Model/Order/OrderRepository.php
  packages/frontend-api/src/Model/Resolver/Order/OrderQuery.php
  packages/frontend-api/src/Model/Resolver/Order/OrdersQuery.php
  project-base/app/config/packages/twig.yaml
  project-base/app/src/DataFixtures/Demo/CompanyOrderDataFixture.php
  project-base/app/src/FrontendApi/Model/Order/OrderApiFacade.php
  project-base/app/src/FrontendApi/Model/Order/OrderRepository.php
  project-base/app/src/FrontendApi/Resolver/Order/OrderQuery.php
  project-base/app/src/FrontendApi/Resolver/Order/OrdersQuery.php
  upgrade-notes/backend_20240731_200701.md
Labels: Enhancement, Frontend API

#3269 releaser: add instruction about social networks
  utils/releaser/src/ReleaseWorker/AfterRelease/EnsureReleaseHighlightsPostIsReleasedReleaseWorker.php
Labels: Documentation

#3326 fix generating upgrade notes
  build.xml
Labels: Bug, Easy Pick

#3291 [shopsys] Send mail adding new customer user to customer
  packages/framework/assets/styles/admin/todo.less
  packages/framework/src/Component/Grid/ActionColumn.php
  packages/framework/src/Controller/Admin/CustomerController.php
  packages/framework/src/Form/Admin/Customer/User/CustomerUserFormType.php
  packages/framework/src/Form/Admin/Customer/User/CustomerUserUpdateFormType.php
  packages/framework/src/Model/Customer/Mail/CustomerActivationMail.php
  packages/framework/src/Model/Customer/Mail/ResetPasswordMail.php
  packages/framework/src/Model/Customer/User/CustomerUserData.php
  packages/framework/src/Model/Customer/User/CustomerUserFacade.php
  packages/framework/src/Model/Customer/User/CustomerUserUpdateData.php
  packages/framework/src/Model/Mail/Exception/ResetPasswordHashNotValidException.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Customer/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Customer/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Form/customerUserListFields.html.twig
  packages/framework/src/Resources/views/Admin/Grid/Grid.html.twig
  packages/frontend-api/src/Model/Customer/User/CustomerUserDataFactory.php
  packages/frontend-api/src/Model/Customer/User/CustomerUserUpdateDataFactory.php
  packages/frontend-api/src/Model/Mutation/Customer/User/CustomerUserMutation.php
  project-base/app/config/packages/security.yaml
  project-base/app/src/Controller/Admin/CustomerController.php
  project-base/app/src/DataFixtures/Demo/CompanyDataFixture.php
  project-base/app/src/Model/Customer/User/CustomerUserFacade.php
  project-base/app/tests/App/Smoke/Http/RouteConfigCustomization.php
  project-base/storefront/components/Pages/NewPassword/NewPasswordContent.tsx
  upgrade-notes/backend_20240731_134528.md
Labels: Enhancement, Frontend API

#3298 [project-base][SSP-2465] Add search parameters to queries
  project-base/storefront/components/Pages/Search/searchUtils.ts
  project-base/storefront/graphql/requests/search/queries/AutocompleteSearchQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/SearchProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/SearchProductsQuery.graphql
  project-base/storefront/graphql/requests/search/queries/SearchQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/SearchQuery.graphql
  upgrade-notes/storefront_20240801_162202.md
Labels: Enhancement

#3325 [project-base] Disable middleware prefetch
  project-base/storefront/next.config.js
  upgrade-notes/storefront_20240809_075813.md
Labels: Easy Pick, Performance

#3324 [project-base] [SSP-2564] fixed responsive design in mobile menu and on cart page
  project-base/storefront/components/Blocks/PromoCode/PromoCode.tsx
  project-base/storefront/components/Layout/Header/HamburgerMenu/HamburgerMenu.tsx
  project-base/storefront/components/Pages/Cart/CartSummary.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should discard user's previous cart after logging in in order 3rd step (cart page after first login).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should log in, add product to an empty cart, and empty cart after log out (cart page after adding product to cart).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should log in, add product to cart to an already prefilled cart, and empty cart after log out (cart page after adding product to cart).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should log in, add product to cart to an already prefilled cart, and empty cart after log out (cart page after login).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should repeatedly merge carts when logged in (starting with an empty cart for the registered customer) (cart page after adding product to cart).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should repeatedly merge carts when logged in (starting with an empty cart for the registered customer) (cart page after adding second product to cart).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/should repeatedly merge carts when logged in (starting with an empty cart for the registered customer) (cart page after second login).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, check it, remove promo code from cart, and then add a different one (cart page after applying first promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, check it, remove promo code from cart, and then add a different one (cart page after removing first promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, check it, remove promo code from cart, and then add a different one (cart page after removing second promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, remove product that allows it, and see the promo code removed (after applying promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should add promo code to cart, remove product that allows it, and see the promo code removed (after removing product that allows promocode).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should increase and decrease product quantity using spinbox in cart (multiple times if clicked slowly) (after decrease).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should increase and decrease product quantity using spinbox in cart (multiple times if clicked slowly) (after increase).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should increase and decrease product quantity using spinbox in cart (once if clicked fast) (after decrease).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should increase and decrease product quantity using spinbox in cart (once if clicked fast) (after increase).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/should remove products from cart (after first removal).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/transport should not be free if price minus promo code discount is below the free transport limit (cart page with non-free transport after applying promocode).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for logged-in user with initially empty cart (after repeat).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for logged-in user with initially filled cart and allowed merging (after repeat).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for logged-in user with initially filled cart and disallowed merging (after repeat).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for unlogged user with initially empty cart (after repeat).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for unlogged user with initially filled cart and allowed merging (after repeat).png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/should repeat order (pre-fill cart) for unlogged user with initially filled cart and disallowed merging (after repeat).png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/should change price for transport when cart is large enough for transport to be free (cart page with enough products).png
  upgrade-notes/storefront_20240808_164334.md
Labels: Bug, Design & Appearance

#3339 [project-base] storefront cypress is now removed after cypress tests finish
  Makefile
  project-base/Makefile
Labels: Bug, DX & Refactoring

#3317 [framework] admin parameter form now validates parameter name uniqueness within a given locale
  packages/framework/assets/js/admin/validation/form/index.js
  packages/framework/assets/js/admin/validation/form/validationParameterName.js
  packages/framework/src/Form/Admin/Product/Parameter/ParameterFormType.php
  packages/framework/src/Model/Product/Parameter/ParameterFacade.php
  packages/framework/src/Model/Product/Parameter/ParameterRepository.php
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  project-base/app/src/Model/Product/Parameter/ParameterFacade.php
  project-base/app/src/Model/Product/Parameter/ParameterRepository.php
  upgrade-notes/backend_20240807_095718.md
Labels: Enhancement

#3331 [project-base] [SSP-2571, SSP-2572, SSP-2573] design fixes
  project-base/storefront/components/Basic/Table/Table.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonManager.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageContact.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicPlaceholder.tsx
  project-base/storefront/components/Pages/BlogArticle/BlogArticleDetailContent.tsx
  project-base/storefront/components/Pages/Customer/OrderDetailContent.tsx
  project-base/storefront/components/Pages/Customer/Orders/OrderItem.tsx
  project-base/storefront/components/Pages/StoreDetail/StoreDetailContent.tsx
  project-base/storefront/cypress/e2e/visits/simpleVisitsWithScreenshots.cy.ts
  project-base/storefront/cypress/e2e/visits/visitsSupport.ts
  project-base/storefront/cypress/fixtures/demodata.ts
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/should create order as logged-in user (transport to home, cash on delivery) and check it in order detail (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/should create order as unlogged user (PPL, credit cart) and check it in order detail (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/should create order as unlogged user (personal collection, cash) and check it in order detail (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/should create order as unlogged user (transport to home, cash on delivery) and check it in order detail (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/should create order as unlogged user with a registered email (transport to home, cash on delivery) and check it in order detail (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/should create order with promo code and check it in order detail (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/should register after order completion, and check that the just created order is in customer orders (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should first select saved default delivery address for logged-in user, but then fill and keep new delivery address after refresh (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should first select saved default delivery address for logged-in user, then fill new delivery address, then change it to a saved one and back to the new address which should stay filled (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should keep filled delivery address after page refresh (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should keep filled delivery address after unchecking the checkbox for different delivery address and then checking it again (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should keep filled delivery address for logged-in user after page refresh (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should keep filled delivery address for logged-in user after unchecking the checkbox for different delivery address and then checking it again (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should not prefill delivery contact for logged-in user with saved address and pickup point, but keep filled delivery information after unchecking and checking checkbox for different delivery address (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should not prefill delivery contact for logged-in user with saved address and with selected pickup point, and then keep the filled delivery information after refresh (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should prefill delivery address from selected pickup point and keep delivery contact after refresh (order detail).png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/should prefill delivery address from selected pickup point and keep delivery contact after unchecking the checkbox for different delivery contact and then checking it again (order detail).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/blog article detail visit with screenshot (blog article detail).png
  project-base/storefront/cypress/tids.ts
  project-base/storefront/store/slices/createPageLoadingStateSlice.ts
  upgrade-notes/storefront_20240812_114154.md
Labels: Bug, Design & Appearance

#2878 Generate command has a new option with generate empty migrations
  docs/introduction/console-commands-for-application-management-phing-targets.md
  packages/framework/build.xml
  packages/migrations/src/Command/GenerateMigrationCommand.php
  upgrade-notes/backend_20240814_134056.md
Labels: DX & Refactoring, In Backlog

#3332 [project-base] [SSP-2570] added opening hours to packetery selected transport label
  project-base/storefront/components/Blocks/OpeningHours/OpeningHours.tsx
  project-base/storefront/components/Blocks/Popup/PickupPlacePopup.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/contactInformationUtils.ts
  project-base/storefront/components/Pages/Order/ContactInformation/deliveryAddressUtils.ts
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/StoreSelect.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelect.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelectItemLabel.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/transportAndPaymentUtils.tsx
  project-base/storefront/components/Pages/Stores/StoreInfoBox.tsx
  project-base/storefront/components/Pages/Stores/StoresContent.tsx
  project-base/storefront/gtm/factories/getGtmTransportChangeEvent.ts
  project-base/storefront/gtm/handlers/onGtmTransportChangeEventHandler.ts
  project-base/storefront/gtm/mappers/getGtmPickupPlaceFromLastOrder.ts
  project-base/storefront/gtm/mappers/getGtmPickupPlaceFromStore.ts
  project-base/storefront/gtm/mappers/mapGtmShippingInfo.ts
  project-base/storefront/store/slices/createPacketerySlice.ts
  project-base/storefront/types/cart.ts
  project-base/storefront/utils/cart/useChangeTransportInCart.ts
  project-base/storefront/utils/cart/useCurrentCart.ts
  project-base/storefront/utils/packetery/index.ts
  project-base/storefront/utils/packetery/types.ts
  upgrade-notes/storefront_20240813_192717.md
Labels: Design & Appearance

#3342 [project-base][SSP-2578] added skeleton for registration page
  project-base/storefront/components/Blocks/Popup/LoginPopup.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonManager.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageRegistration.tsx
  project-base/storefront/components/Layout/Breadcrumbs/Breadcrumbs.tsx
  project-base/storefront/store/slices/createPageLoadingStateSlice.ts
  upgrade-notes/storefront_20240814_121427.md
Labels: Bug, Design & Appearance

#3323 [framework] admin can manage customer user group roles
  packages/framework/src/Controller/Admin/CustomerUserRoleGroupController.php
  packages/framework/src/Form/Admin/Customer/RoleGroup/CustomerUserRoleGroupFormType.php
  packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
  packages/framework/src/Model/Customer/User/Role/CustomerUserRole.php
  packages/framework/src/Model/Customer/User/Role/CustomerUserRoleGroup.php
  packages/framework/src/Model/Customer/User/Role/CustomerUserRoleGroupDataFactory.php
  packages/framework/src/Model/Customer/User/Role/CustomerUserRoleGroupFacade.php
  packages/framework/src/Model/Customer/User/Role/CustomerUserRoleGroupGridFactory.php
  packages/framework/src/Model/Customer/User/Role/CustomerUserRoleGroupRepository.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  packages/framework/src/Resources/views/Admin/Content/Customer/RoleGroup/detail.html.twig
  packages/framework/src/Resources/views/Admin/Content/Customer/RoleGroup/edit.html.twig
  packages/framework/src/Resources/views/Admin/Content/Customer/RoleGroup/list.html.twig
  packages/framework/src/Resources/views/Admin/Content/Customer/RoleGroup/new.html.twig
  project-base/app/tests/App/Smoke/Http/RouteConfigCustomization.php
  upgrade-notes/backend_20240808_161547.md
Labels: Enhancement

#3361 [framework] the price filter now takes into account the pricing group
  packages/framework/src/Model/Product/Search/FilterQuery.php
  project-base/app/src/Model/Product/Search/FilterQuery.php
  upgrade-notes/backend_20240820_124554.md
Labels: Bug

#3333 [shopsys] packetery delivery address is no longer saved as delivery address for customer user
  packages/framework/src/Model/Customer/User/CustomerUserFacade.php
  packages/framework/src/Model/Customer/User/CustomerUserUpdateDataFactory.php
  project-base/app/src/Model/Customer/User/CustomerUserFacade.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/DeliveryAddressIsNotStoredForPacketeryOrPersonalPickupTest.php
  upgrade-notes/backend_20240812_134156.md
Labels: Bug

#3320 [shopsys] moved two attributes of ProductFormType from project-base to framework
  UPGRADE-14.0.md
  packages/framework/src/Form/Admin/Product/ProductFormType.php
  packages/framework/src/Model/Product/ProductDataFactory.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  project-base/app/src/Form/Admin/ProductFormTypeExtension.php
  project-base/app/src/Model/Product/ProductDataFactory.php
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
Labels: Bug

#3318 [shopsys] Moved CSRFExtension from project-base to framework
  UPGRADE-14.0.md
  packages/framework/src/Twig/CsrfExtension.php
Labels: Bug

#3350 [shopsys] removed dependency on App from frontend-api package
  packages/frontend-api/src/Model/Resolver/Products/BestsellingProductsQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Customer/BillingAddress/Input/BillingAddressInputObjectDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Customer/BillingAddress/Input/CompanyInputObjectDecorator.types.yaml
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/app/config/graphql/types/ModelType/Category/Category.types.yaml
  project-base/app/config/services_frontend_api.yaml
  project-base/app/src/FrontendApi/Resolver/Products/BestsellingProductsQuery.php
  project-base/app/src/FrontendApi/Resolver/Store/StoreAvailabilityResolverMap.php
  upgrade-notes/backend_20240717_111911.md
  upgrade-notes/backend_20240822_114800.md
Labels: Bug

#3316 [shopsys] fixed image resolving for transport in FrontendAPI
  UPGRADE-14.0.md
  packages/frontend-api/src/Resources/config/graphql-types/TransportDecorator.types.yaml
  project-base/app/config/graphql/types/ModelType/Transport/Transport.types.yaml
Labels: Bug

#3312 [framework] fixed price range query
  packages/framework/src/Model/Product/Filter/PriceRangeRepository.php
Labels: Bug

#3345 [project-base][SSP-2135] updated artcle product slider arrows
  project-base/storefront/components/Basic/UserText/GrapesJsParser.tsx
  project-base/storefront/components/Basic/UserText/GrapesJsProducts.tsx
  project-base/storefront/components/Blocks/Product/ProductsSlider.tsx
  project-base/storefront/components/Pages/Article/ArticleDetailContent.tsx
  project-base/storefront/components/Pages/BlogArticle/BlogArticleDetailContent.tsx
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/blog article detail visit with screenshot (blog article detail).png
  upgrade-notes/storefront_20240815_080220.md
Labels: Bug, Design & Appearance

#3310 [framework] fixed query wrongly loading flags from Product instead of ProductDomain
  packages/framework/src/Model/Product/Filter/FlagFilterChoiceRepository.php
Labels: Bug

#3376 [shopsys] moved two attributes of ProductFormType from project-base to framework
  packages/framework/src/Form/Admin/Product/ProductFormType.php
  packages/framework/src/Model/Product/ProductDataFactory.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  project-base/app/src/Form/Admin/ProductFormTypeExtension.php
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  upgrade-notes/backend_20240827_085319.md
Labels: DX & Refactoring

#3377 [shopsys] fixed image resolving for transport in FrontendAPI
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Transport/TransportDecorator.types.yaml
  project-base/app/config/graphql/types/ModelType/Transport/Transport.types.yaml
  upgrade-notes/backend_20240827_090633.md
Labels: Bug

#3347 [shopsys] upgraded nginx to version 1.27
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose.github-actions.cypress.yml.dist
  docker/conf/docker-compose.github-actions.review.simplified.yml.dist
  docker/conf/docker-compose.github-actions.review.yml.dist
  docker/conf/docker-compose.github-actions.yml.dist
  docker/conf/docker-compose.yml.dist
  docs/introduction/cdn.md
  open-source-license-acknowledgements-and-third-party-copyrights.md
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
  project-base/gitlab/docker-compose-ci-review.yml
  project-base/gitlab/docker-compose-ci.yml
  upgrade-notes/backend_20240827_151048.md
  utils/license-acknowledgements-generator/template.md
Labels: Infrastructure

#3370 [project-base] fix product count in autocomplete
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSearchProductsResult.tsx
  upgrade-notes/storefront_20240826_134856.md
Labels: Bug

#3338 [shopsys] fixed duplicate addDomain to query builder
  UPGRADE-14.0.md
  packages/framework/src/Model/Product/ProductRepository.php
  project-base/app/src/Model/Product/ProductRepository.php
Labels: Bug

#3365 [shopsys] administrator now can see list of last ten orders on customer edit page
  packages/framework/assets/js/admin/components/AdvancedSearch.js
  packages/framework/src/Form/Admin/AdvancedSearch/AdvancedSearchOperatorTranslation.php
  packages/framework/src/Form/Admin/AdvancedSearch/AdvancedSearchOrderFilterTranslation.php
  packages/framework/src/Form/Admin/Customer/BillingAddressAndRelatedInfoFormType.php
  packages/framework/src/Form/Admin/Customer/User/CustomerUserUpdateFormType.php
  packages/framework/src/Form/OrderListType.php
  packages/framework/src/Model/AdvancedSearch/AdvancedSearchFilterInterface.php
  packages/framework/src/Model/AdvancedSearch/OrderAdvancedSearchConfig.php
  packages/framework/src/Model/AdvancedSearchOrder/Filter/OrderCustomerIdFilter.php
  packages/framework/src/Model/Order/OrderFacade.php
  packages/framework/src/Model/Order/OrderRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Form/orderlistFields.html.twig
  project-base/app/src/Model/Order/OrderFacade.php
  project-base/app/src/Model/Order/OrderRepository.php
  upgrade-notes/backend_20240821_092126.md
Labels: Enhancement

#3357 [framework] Annotations fixer access of nullable does not break fixer
  packages/framework/src/Component/ClassExtension/MethodAnnotationsFactory.php
Labels: Bug

#3384 [shopsys] fixed duplicate addDomain to query builder
  packages/framework/src/Model/Product/ProductRepository.php
  project-base/app/src/Model/Product/ProductRepository.php
  upgrade-notes/backend_20240828_102210.md
Labels: Bug

#3358 [project-base][SSP-2560] redesigned radio and inverted button hover
  project-base/storefront/components/Blocks/Pagination/Pagination.tsx
  project-base/storefront/components/Blocks/Product/ButtonsAction/ProductCompareButton.tsx
  project-base/storefront/components/Blocks/Product/ButtonsAction/ProductWishlistButton.tsx
  project-base/storefront/components/Forms/Spinbox/Spinbox.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconic.tsx
  project-base/storefront/components/Pages/Wishlist/Wishlist.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/should remove products from cart using cart in header and then display empty cart message (after first remove).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/should remove products from cart using cart in header and then display empty cart message (after second remove).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/blog article detail visit with screenshot (blog article detail).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/category detail visit with screenshot (category detail).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/homepage visit with screenshot (homepage).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/product detail visit with screenshot (product detail).png
  project-base/storefront/tailwind.config.js
  upgrade-notes/storefront_20240819_121320.md
Labels: Bug, Design & Appearance

#3381 [framework] FileUpload: set position for the new images only
  packages/framework/src/Component/FileUpload/EntityFileUploadInterface.php
  packages/framework/src/Component/FileUpload/FileUpload.php
  packages/framework/src/Component/Image/Image.php
  packages/framework/src/Component/UploadedFile/UploadedFile.php
Labels: Bug
