Repository shopsys/shopsys, pull requests merged in 2024-09, with the labels that each got.

#3336 [shopsys] moved category parameters to framework package
  UPGRADE-14.0.md
  packages/framework/src/Form/Admin/Category/CategoryFormType.php
  packages/framework/src/Model/Category/CategoryData.php
  packages/framework/src/Model/Category/CategoryDataFactory.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Product/Parameter/ParameterRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  project-base/app/src/Form/Admin/CategoryFormTypeExtension.php
  project-base/app/src/Model/Category/CategoryData.php
  project-base/app/src/Model/Category/CategoryDataFactory.php
  project-base/app/src/Model/Category/CategoryFacade.php
  project-base/app/src/Model/Product/Parameter/ParameterRepository.php
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
Labels: DX & Refactoring

#3385 [framework] files picker fix and tweak
  packages/framework/assets/js/admin/components/FileUpload.js
  packages/framework/assets/js/admin/components/MultiplePicker.js
  packages/framework/src/Form/Admin/UploadedFile/UploadedFileFormType.php
  packages/framework/src/Form/MultiLocaleBasicFileUploadType.php
  packages/framework/src/Form/MultiLocaleFileUploadType.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Form/fileuploadFields.html.twig
  packages/framework/src/Resources/views/Admin/Form/multiLocaleFileuploadFields.html.twig
  packages/framework/src/Resources/views/Admin/Form/theme.html.twig
Labels: Bug, Design & Appearance, DX & Refactoring

#3391 [project-base] data fixtures: load translations for all locales where required
  project-base/app/src/DataFixtures/Demo/CountryDataFixture.php
  project-base/app/src/DataFixtures/Demo/UnitDataFixture.php
  upgrade-notes/backend_20240802_220053.md
Labels: Bug

#3387 [shopsys] moved category parameters to framework package
  packages/framework/src/Form/Admin/Category/CategoryFormType.php
  packages/framework/src/Model/Category/CategoryData.php
  packages/framework/src/Model/Category/CategoryDataFactory.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Product/Parameter/ParameterRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  project-base/app/src/Form/Admin/CategoryFormTypeExtension.php
  project-base/app/src/Model/Category/CategoryData.php
  project-base/app/src/Model/Category/CategoryDataFactory.php
  project-base/app/src/Model/Category/CategoryFacade.php
  project-base/app/src/Model/Product/Parameter/ParameterRepository.php
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  upgrade-notes/backend_20240828_162100.md
Labels: DX & Refactoring

#3334 [framework] Fix create ImageTypeNotFoundException with null imageType attr
  packages/framework/src/Component/Image/Config/ImageEntityConfig.php
Labels: Bug

#3374 [framework] EntityLogEventListener now handles PersistentCollection directly instead of catching Exception
  packages/framework/src/Component/EntityLog/EventListener/EntityLogEventListener.php
Labels: DX & Refactoring

#3166 [framework] admin can remove an image and upload a new one
  packages/framework/src/Component/Image/ImageFacade.php
  packages/framework/src/Component/Image/ImageFactory.php
  packages/framework/src/Component/Image/ImageFactoryInterface.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/tests/Unit/Component/Image/ImageFactoryTest.php
  project-base/app/src/Component/Image/ImageFacade.php
  upgrade-notes/backend_20240819_133415.md
Labels: Bug

#3341 [project-base][SSP-1974] updated procuts list sync with open tabs
  project-base/storefront/components/Pages/App/Loaders.tsx
  project-base/storefront/components/Pages/ProductDetail/ComparisonAndWishlistButtons/ComparisonAndWishlistButtons.tsx
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/category detail visit with screenshot (category detail).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/product detail visit with screenshot (product detail).png
  project-base/storefront/utils/productLists/comparison/useComparison.tsx
  project-base/storefront/utils/productLists/comparison/useRefetchComparedProducts.tsx
  project-base/storefront/utils/productLists/useProductList.ts
  project-base/storefront/utils/productLists/wishlist/useRefetchWishedProducts.tsx
  project-base/storefront/utils/productLists/wishlist/useWishlist.tsx
  project-base/storefront/utils/useBroadcastChannel.ts
  upgrade-notes/storefront_20240814_110159.md
Labels: Bug, Design & Appearance

#3393 [framework] Enable pagination and quick search in blog articles in the admin
  packages/framework/src/Controller/Admin/BlogArticleController.php
  packages/framework/src/Model/Blog/Article/BlogArticleFacade.php
  packages/framework/src/Model/Blog/Article/BlogArticleGridFactory.php
  packages/framework/src/Model/Blog/Article/BlogArticleRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Blog/Article/list.html.twig
  upgrade-notes/backend_20240830_100754.md
Labels: Enhancement, Easy Pick

#3224 Say goodbye to Yennefer of Vengerberg
  project-base/app/src/DataFixtures/resources/images/productSeries/106.jpg
  upgrade-notes/backend_20240906_090025.md
Labels: Easy Pick, DX & Refactoring

#3402 [framework] fixed wrong columns used in migration Version20240102112523
  UPGRADE-14.0.md
  packages/framework/src/Migrations/Version20240102112523.php
Labels: Bug

#3404 [framework] flags are no longer all deleted and then recreated but are properly managed
  packages/framework/src/Model/Product/ProductDomain.php
Labels: DX & Refactoring

#3415 [framework] fixed wrong columns used in migration Version20240102112523
  packages/framework/src/Migrations/Version20240102112523.php
  upgrade-notes/backend_20240909_091053.md
Labels: Bug

#3406 [framework] fixed EntityLogger to no longer empty collection that is cleared and filled on every update
  UPGRADE-14.0.md
  packages/framework/src/Component/EntityLog/EventListener/EntityLogEventListener.php
  packages/framework/src/Resources/config/services.yaml
Labels: Bug

#3416 [framework] moved FlagDetailFriendlyUrlDataProvider from project-base to framework
  packages/framework/src/Model/Product/Flag/FlagDetailFriendlyUrlDataProvider.php
  upgrade-notes/backend_20240909_105040.md
Labels: DX & Refactoring

#3418 [framework] fixed EntityLogger to no longer empty collection that is cleared and filled on every update
  packages/framework/src/Component/EntityLog/EventListener/EntityLogEventListener.php
  packages/framework/src/Resources/config/services.yaml
  upgrade-notes/backend_20240909_114838.md
Labels: DX & Refactoring

#3410 [framework] improved formatting of Entity logs
  UPGRADE-14.0.md
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/BooleanDataTypeFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/CollectionChangesFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/DateTimeDataTypeFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/MoneyDataTypeFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/ResolvedChangesFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/ScalarDataTypeFormatter.php
Labels: Enhancement

#3420 [framework] fixed redundant log for the Money type if the scale of compared object was different
  packages/framework/src/Component/EntityLog/ChangeSet/DataTypeResolver/MoneyDataTypeResolver.php
  packages/framework/src/Component/EntityLog/ChangeSet/ResolvedChanges.php
  upgrade-notes/backend_20240909_131346.md
Labels: Bug

#3423 [framework] improved formatting of Entity logs
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/BooleanDataTypeFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/CollectionChangesFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/DateTimeDataTypeFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/MoneyDataTypeFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/ResolvedChangesFormatter.php
  packages/framework/src/Component/EntityLog/ChangeSet/Formatter/ScalarDataTypeFormatter.php
  upgrade-notes/backend_20240909_135505.md
Labels: DX & Refactoring

#3388 [framework] edit complaint items in admin
  packages/framework/assets/js/admin/validation/form/index.js
  packages/framework/assets/js/admin/validation/form/validationComplaintItem.js
  packages/framework/assets/styles/admin/todo.less
  packages/framework/src/Component/CustomerUploadedFile/CustomerUploadedFileFacade.php
  packages/framework/src/Controller/Front/CustomerUploadedFileController.php
  packages/framework/src/Form/Admin/Complaint/ComplaintFormType.php
  packages/framework/src/Form/Admin/Complaint/ComplaintItemFormType.php
  packages/framework/src/Form/Admin/Complaint/Status/ComplaintItemsType.php
  packages/framework/src/Model/Complaint/Complaint.php
  packages/framework/src/Model/Complaint/ComplaintDataFactory.php
  packages/framework/src/Model/Complaint/ComplaintFacade.php
  packages/framework/src/Model/Complaint/ComplaintItem.php
  packages/framework/src/Model/Complaint/ComplaintItemDataFactory.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/translations/validators.cs.po
  packages/framework/src/Resources/translations/validators.en.po
  packages/framework/src/Resources/views/Admin/Form/complaintItems.html.twig
  packages/framework/src/Twig/UploadedFileExtension.php
  project-base/app/config/packages/twig.yaml
  project-base/app/src/DataFixtures/Demo/ComplaintDataFixture.php
  upgrade-notes/backend_20240828_191228.md
Labels: Enhancement

#3425 Release of version 14.0.1
  CHANGELOG-14.0.md
  UPGRADE-14.0.md
  docs/contributing/releasing-a-new-version-of-shopsys-platform.md
  open-source-license-acknowledgements-and-third-party-copyrights.md
  packages/article-feed-luigis-box/composer.json
  packages/brand-feed-luigis-box/composer.json
  packages/category-feed-luigis-box/composer.json
  packages/form-types-bundle/composer.json
  packages/framework/assets/package.json
  packages/framework/composer.json
  packages/framework/src/Form/Admin/Category/CategoryFormType.php
  packages/framework/src/ShopsysFrameworkBundle.php
  packages/frontend-api/composer.json
  packages/google-cloud-bundle/composer.json
  packages/http-smoke-testing/composer.json
  packages/luigis-box/composer.json
  packages/migrations/composer.json
  packages/plugin-interface/composer.json
  packages/product-feed-google/composer.json
  packages/product-feed-heureka-delivery/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-luigis-box/composer.json
  packages/product-feed-zbozi/composer.json
  packages/s3-bridge/composer.json
  project-base/app/composer.json
  project-base/app/package.json
  utils/releaser/config/release-candidate.php
  utils/releaser/config/release.php
  utils/releaser/src/ReleaseWorker/AbstractSetMutualDependenciesToVersionReleaseWorker.php
  utils/releaser/src/ReleaseWorker/Release/SetMutualDependenciesToVersionReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckPackagesGithubActionsBuildsAfterSplitReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckProjectBaseBuild.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/CheckShopsysInstallReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ForceYourBranchSplitReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ReleaseNewNodeModulePackageVersion.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateChangelogReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/UpdateLicenseAcknowledgementsReleaseWorker.php
Labels: Priority

#3417 [shopsys] immediate access token revocation
  packages/framework/src/Component/EntityLog/Detection/DetectionFacade.php
  packages/framework/src/Migrations/Version20240906201521.php
  packages/framework/src/Model/Customer/User/CustomerUser.php
  packages/framework/src/Model/Customer/User/CustomerUserFacade.php
  packages/framework/src/Model/Customer/User/CustomerUserFactory.php
  packages/framework/src/Model/Customer/User/CustomerUserPasswordFacade.php
  packages/framework/src/Model/Customer/User/CustomerUserRefreshTokenChainRepository.php
  packages/framework/src/Model/Customer/User/CustomerUserRepository.php
  packages/frontend-api/src/Model/Token/TokenAuthenticator.php
  packages/frontend-api/src/Model/Token/TokenFacade.php
  project-base/app/src/FrontendApi/Model/Token/TokenAuthenticator.php
  project-base/app/src/Model/Customer/User/CustomerUserPasswordFacade.php
  project-base/app/tests/FrontendApiBundle/Functional/Login/LoginTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Login/LoginTokenInvalidationTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Login/graphql/ChangePasswordMutation.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Login/graphql/LoginMutation.graphql
  upgrade-notes/backend_20240909_110703.md
Labels: Security

#3428 [monorepo] Fix cancel old reviews script
  .github/cancel-old-reviews.sh
  .github/workflows/cancel-old-reviews.yaml
Labels: Bug, Infrastructure

#3432 [framework] tweak complaint status migration
  packages/framework/src/Migrations/Version20240816221930.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
Labels: DX & Refactoring

#3386 [project-base] fixed handling of 401 errors on dynamic page
  project-base/storefront/pages/articles/[articleSlug].tsx
  project-base/storefront/pages/blogArticles/[blogArticleSlug].tsx
  project-base/storefront/pages/blogCategories/[blogCategorySlug].tsx
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/flags/[flagSlug].tsx
  project-base/storefront/pages/products/[productSlug].tsx
  project-base/storefront/pages/stores/[storeSlug].tsx
  project-base/storefront/urql/authExchange.ts
  project-base/storefront/utils/auth/getTokensFromCookies.ts
  project-base/storefront/utils/errors/handleServerSideErrorResponseForFriendlyUrls.ts
Labels: Bug

#3355 [framework] limited user can't user free transport and gateway payments
  ecs.php
  packages/framework/src/Model/Customer/User/Role/CustomerUserRoleProvider.php
  packages/framework/src/Model/Payment/IndependentPaymentVisibilityCalculation.php
  packages/framework/src/Model/Payment/Payment.php
  packages/framework/src/Model/Payment/PaymentFacade.php
  packages/framework/src/Model/Payment/PaymentPriceCalculation.php
  packages/framework/src/Model/Payment/PaymentVisibilityCalculation.php
  packages/framework/src/Model/Transport/TransportPriceCalculation.php
  packages/framework/src/Model/TransportAndPayment/FreeTransportAndPaymentFacade.php
  packages/framework/src/Twig/HiddenPriceExtension.php
  packages/framework/tests/Unit/Model/Payment/IndependentPaymentVisibilityCalculationTest.php
  packages/framework/tests/Unit/Model/Payment/PaymentPriceCalculationTest.php
  packages/framework/tests/Unit/Model/Transport/TransportPriceCalculationTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Price/HiddenPricesTest.php
  upgrade-notes/backend_20240818_204612.md
Labels: Enhancement

#3438 [project-base][SSP-2708] updated store opening hours alignment
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelectItemLabel.tsx
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/should select personal pickup transport (after selecting).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/stores page visit with screenshot (stores page).png
  upgrade-notes/storefront_20240916_112700.md
Labels: Bug, Design & Appearance

#3437 [project-base][SSP-2701] updated responsive toast
  project-base/storefront/styles/globals.css
  upgrade-notes/storefront_20240916_110156.md
Labels: Bug, Design & Appearance

#3443 [shopsys] updated twig to latest version in order to resolve security issues
  composer.json
  packages/administration/composer.json
  packages/article-feed-luigis-box/composer.json
  packages/brand-feed-luigis-box/composer.json
  packages/category-feed-luigis-box/composer.json
  packages/framework/composer.json
  packages/framework/src/Twig/TranslationExtension.php
  packages/product-feed-google/composer.json
  packages/product-feed-heureka-delivery/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-luigis-box/composer.json
  packages/product-feed-zbozi/composer.json
  project-base/app/composer.json
  upgrade-notes/backend_20240917_095529.md
Labels: Security

#3407 [framework] Heureka: send order number instead of order id
  packages/framework/src/Model/Heureka/HeurekaShopCertificationFactory.php
Labels: Enhancement

#3447 [framework] fixed GoPay no longer failing on missing key of enabledSwifts
  packages/framework/src/Model/GoPay/PaymentMethod/GoPayPaymentMethodFacade.php
Labels: Bug

#3448 [project-base][SSP-2618] added condition for unsupported broadcast channel
  project-base/storefront/store/broadcast.ts
  project-base/storefront/utils/useBroadcastChannel.ts
  project-base/storefront/vitest/utils/urql/createClient.test.tsx
  upgrade-notes/storefront_20240919_122906.md
Labels: Bug

#3422 fixed duplicate video forms in administration product
  packages/framework/assets/js/admin/components/HreflangSetting.js
  packages/framework/assets/js/admin/components/MailWhitelist.js
  packages/framework/assets/js/admin/components/OpeningHoursCollection.js
  packages/framework/assets/js/admin/components/OrderItems.js
  packages/framework/assets/js/admin/components/Parameters.js
  packages/framework/assets/js/admin/components/PromoCodeFlags.js
  packages/framework/assets/js/admin/components/PromoCodeLimits.js
  project-base/app/assets/js/admin/product/product.js
  project-base/app/templates/Admin/Form/productVideoValue.html.twig
  upgrade-notes/backend_20240909_135228.md
Labels: Bug

#3031 [framework] InMemoryCache for easier managing of caches
  docs/asynchronous-processing/introduction-to-asynchronous-processing.md
  docs/introduction/index.md
  docs/introduction/memory-cache.md
  docs/introduction/navigation.yml
  packages/framework/src/Component/Cache/Exception/InMemoryCacheException.php
  packages/framework/src/Component/Cache/Exception/NamespaceCacheKeyNotFoundException.php
  packages/framework/src/Component/Cache/Exception/ValueCacheKeyNotFoundException.php
  packages/framework/src/Component/Cache/InMemoryCache.php
  packages/framework/src/Component/Cache/InMemoryCacheResetListener.php
  packages/framework/src/Component/Cron/CronModuleFacade.php
  packages/framework/src/Component/FileUpload/FileUpload.php
  packages/framework/src/Model/Customer/User/CurrentCustomerUser.php
  packages/framework/src/Model/Product/Availability/ProductAvailabilityFacade.php
  packages/framework/src/Model/Product/Brand/BrandCachedFacade.php
  packages/framework/src/Model/Product/Collection/ProductParametersBatchLoader.php
  packages/framework/src/Model/Product/Collection/ProductUrlsBatchLoader.php
  packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
  packages/framework/src/Model/Product/ProductCachedAttributesFacade.php
  packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
  packages/framework/src/Model/Store/OpeningHours/StoreOpeningHoursProvider.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/tests/Unit/Component/Cache/InMemoryCacheTest.php
  packages/framework/tests/Unit/Component/Image/ImageFactoryTest.php
  packages/framework/tests/Unit/Model/Customer/CurrentCustomerUserTest.php
  packages/product-feed-heureka/src/Model/FeedItem/HeurekaFeedItemFactory.php
  packages/product-feed-heureka/tests/Unit/HeurekaFeedItemTest.php
  project-base/app/config/services.yaml
  project-base/app/src/Model/CategorySeo/ReadyCategorySeoMixRepository.php
  project-base/app/src/Model/Customer/User/ClearCurrentCustomerUserCacheDoctrineSubscriber.php
  project-base/app/src/Model/Customer/User/CurrentCustomerUser.php
  project-base/app/src/Model/Product/Elasticsearch/ProductExportRepository.php
  project-base/app/src/Model/Product/Search/ProductElasticsearchRepository.php
  project-base/app/src/ProductFeed/Heureka/Model/FeedItem/HeurekaFeedItemFactory.php
  upgrade-notes/backend_20240914_085905.md
Labels: DX & Refactoring

#3445 [shopsys] added complaint detail url to mail templates
  packages/framework/src/Migrations/Version20240910054629.php
  packages/framework/src/Model/Complaint/Mail/ComplaintMail.php
  packages/framework/src/Model/Mail/MailTemplateConfiguration.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  project-base/app/config/shopsys-routing/routing_front_cs.yaml
  project-base/app/config/shopsys-routing/routing_front_en.yaml
  project-base/app/config/shopsys-routing/routing_front_sk.yaml
  upgrade-notes/backend_20240917_130712.md
Labels: Enhancement

#3436 [project-base][SSP-2682] removed hp headlines when no data available
  project-base/app/src/FrontendApi/Resolver/Category/PromotedCategory/PromotedCategoryRepository.php
  project-base/storefront/components/Blocks/Banners/Banners.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreview.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewPlaceholder.tsx
  project-base/storefront/components/Blocks/BlogPreview/DeferredBlogPreview.tsx
  project-base/storefront/components/Blocks/Categories/PromotedCategories.tsx
  project-base/storefront/components/Blocks/Product/DeferredPromotedProducts.tsx
  project-base/storefront/components/Blocks/Product/DeferredRecommendedProducts.tsx
  project-base/storefront/components/Pages/HomePage/HomePageContent.tsx
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/homepage visit with screenshot (homepage).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/product detail visit with screenshot (product detail).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/stores page visit with screenshot (stores page).png
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  upgrade-notes/storefront_20240915_184818.md
Labels: Bug, Design & Appearance

#3449 [project-base][SSP-2729] added error message for edit profile duplicate company number
  project-base/storefront/components/Pages/Customer/EditProfileContent.tsx
  upgrade-notes/storefront_20240920_112138.md
Labels: Bug

#3452 [project-base] Fixed hiding prices for limited user
  project-base/storefront/components/Blocks/OrderSummary/TransportAndPayment.tsx
  project-base/storefront/components/Layout/Header/Cart/CartInHeader.tsx
  project-base/storefront/components/Layout/Header/Cart/CartInHeaderListItem.tsx
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailBasicInfo.tsx
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailOrderItem.tsx
  project-base/storefront/components/Pages/Customer/OrderedItems/OrderedItem.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/should remove products from cart using cart in header and then display empty cart message (after first remove).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/stores page visit with screenshot (stores page).png
  upgrade-notes/storefront_20240925_075509.md
Labels: Bug

#3458 [framework] user is logged out after role change
  packages/framework/src/Model/Customer/User/CustomerUserFacade.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/User/CustomerUserWithLimitedRoleGroupTest.php
Labels: Enhancement
