Repository shopsys/shopsys, pull requests merged in 2024-03, with the labels that each got.

#2993 Check vulnerabilities for storefront
  .github/workflows/storefront-security-check.yaml
  UPGRADE-15.0.md
  project-base/.gitlab-ci.yml
Labels: In Backlog

#3033 [SSP-2143] added more verbose error messages for mutations
  UPGRADE-15.0.md
  docs/storefront/error-handling.md
  project-base/storefront/.env
  project-base/storefront/.env.development
  project-base/storefront/components/Pages/ErrorPage/Error500Content.tsx
  project-base/storefront/helpers/errors/isWithErrorDebugging.ts
  project-base/storefront/helpers/errors/logException.ts
  project-base/storefront/helpers/toasts.tsx
  project-base/storefront/middleware.ts
  project-base/storefront/next.config.js
  project-base/storefront/pages/_error.tsx
  project-base/storefront/urql/errorExchange.ts
  project-base/storefront/vitest/helpers/urql/createClient.test.tsx
Labels: Enhancement, Easy Pick

#3055 [project-base] added doctrine backtrace collecting in dev mode
  UPGRADE-15.0.md
  project-base/app/config/packages/dev/doctrine.yaml
Labels: DX & Refactoring

#3060 [framework] fixed situation when placeholder was not set for selected locale
  packages/framework/src/Component/DataFixture/AbstractReferenceFixture.php
  packages/framework/src/Form/Admin/Product/Brand/BrandFormType.php
  packages/framework/src/Form/Admin/Product/ProductFormType.php
Labels: Bug

#3057 changed link URL for Catalog navigation element
  UPGRADE-15.0.md
  project-base/app/src/DataFixtures/Demo/NavigationItemDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Navigation/NavigationTest.php
Labels: DX & Refactoring

#3050 added security headers for more safety
  UPGRADE-15.0.md
  docker/nginx/nginx.conf
  project-base/docker/nginx/nginx.conf
Labels: Security

#2350 Fix persist on null object in create delivery address
  UPGRADE-15.0.md
  packages/framework/src/Model/Customer/DeliveryAddressFacade.php
  packages/framework/src/Model/Customer/User/CustomerUserFacade.php
  project-base/app/src/Model/Customer/DeliveryAddressFacade.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/SetDefaultDeliveryAddressTest.php
Labels: In Backlog

#3068 [framework] ensure proper entity name is used within getClassMetadata call
  UPGRADE-14.0.md
  packages/framework/src/Component/EntityExtension/EntityManagerDecorator.php
  packages/framework/src/Model/Category/CategoryRepository.php
  project-base/app/src/Model/Category/CategoryRepository.php
Labels: Bug

#3071 [SSP-2204] added visitAndWaitForStableDOM for visiting pages in cypress
  UPGRADE-15.0.md
  docs/storefront/cypress.md
  project-base/storefront/cypress/cypress.d.ts
  project-base/storefront/cypress/e2e/authentication/authentication.cy.ts
  project-base/storefront/cypress/e2e/cart/cartPage.cy.ts
  project-base/storefront/cypress/e2e/cart/productAddToCart.cy.ts
  project-base/storefront/cypress/e2e/order/createOrder.cy.ts
  project-base/storefront/cypress/e2e/transportAndPayment/paymentSelect.cy.ts
  project-base/storefront/cypress/e2e/transportAndPayment/transportSelect.cy.ts
  project-base/storefront/cypress/package-lock.json
  project-base/storefront/cypress/package.json
  project-base/storefront/cypress/support/index.ts
Labels: Easy Pick, DX & Refactoring

#3061 [project-base] deploy is now not dependent only on commit but also on pipeline id
  UPGRADE-15.0.md
  project-base/.gitlab-ci.yml
Labels: Bug, Infrastructure

#3065 [shopsys] adverts restricted by theirs display dates are now correctly displayed at specified dates
  UPGRADE-14.0.md
  packages/framework/src/Controller/Admin/AdvertController.php
  packages/framework/src/Model/Advert/AdvertFacade.php
  packages/framework/src/Model/Advert/AdvertRepository.php
  packages/frontend-api/src/Model/Advert/AdvertRepository.php
  project-base/app/src/Controller/Admin/AdvertController.php
  project-base/app/src/Model/Advert/AdvertRepository.php
Labels: Bug

#3062 [project-base] fixed wrong PageType for articles in search
  UPGRADE-14.0.md
  project-base/storefront/components/Blocks/Categories/PromotedCategories.tsx
  project-base/storefront/components/Blocks/SimpleNavigation/SimpleNavigation.tsx
  project-base/storefront/components/Blocks/SimpleNavigation/SimpleNavigationListItem.tsx
  project-base/storefront/components/Blocks/SimpleNavigation/helpers.ts
  project-base/storefront/components/Blocks/Skeleton/SkeletonManager.tsx
  project-base/storefront/components/Pages/Brands/BrandsContent.tsx
  project-base/storefront/components/Pages/CategoryDetail/AdvancedSeoCategories.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
  project-base/storefront/components/Pages/Search/SearchContent.tsx
  project-base/storefront/types/simpleNavigation.ts
Labels: Bug

#2975 move migration 20200219145345
  .github/workflows/docker-build.yaml
  UPGRADE-14.0.md
  packages/framework/src/Migrations/Version20200219145345.php
Labels: Bug

#3077 [SSP-2211] SF bundle size reduction changes
  UPGRADE-15.0.md
  project-base/storefront/.eslintrc.js
  project-base/storefront/.gitignore
  project-base/storefront/.prettierignore
  project-base/storefront/components/Basic/Icon/IconsSvg.tsx
  project-base/storefront/components/Basic/SeznamMap/SeznamMapMarkerIcon.tsx
  project-base/storefront/components/Basic/SeznamMap/SeznamMapMarkerLayer.tsx
  project-base/storefront/components/Layout/UrqlWrapper.tsx
  project-base/storefront/i18n.js
  project-base/storefront/next.config.js
  project-base/storefront/package.json
  project-base/storefront/pages/_app.tsx
  project-base/storefront/pages/api/log-exception.ts
  project-base/storefront/pnpm-lock.yaml
  project-base/storefront/schema-compress.js
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/schema.graphql.json
  project-base/storefront/urql/cache/cacheExchange.ts
Labels: Easy Pick, DX & Refactoring

#3075 [project-base] replaced UUID pools by generation from entities data
  UPGRADE-15.0.md
  project-base/app/src/DataFixtures/Demo/AdvertDataFixture.php
  project-base/app/src/DataFixtures/Demo/ArticleDataFixture.php
  project-base/app/src/DataFixtures/Demo/BlogArticleDataFixture.php
  project-base/app/src/DataFixtures/Demo/BrandDataFixture.php
  project-base/app/src/DataFixtures/Demo/CategoryDataFixture.php
  project-base/app/src/DataFixtures/Demo/CategoryParameterDataFixture.php
  project-base/app/src/DataFixtures/Demo/OrderDataFixture.php
  project-base/app/src/DataFixtures/Demo/ParameterDataFixture.php
  project-base/app/src/DataFixtures/Demo/PaymentDataFixture.php
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/app/src/DataFixtures/Demo/SliderItemDataFixture.php
  project-base/app/src/DataFixtures/Demo/StoreDataFixture.php
  project-base/app/src/DataFixtures/Demo/TransportDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Article/GetArticlesTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/GetOrderAsAuthenticatedCustomerUserTest.php
  project-base/storefront/cypress/fixtures/demodata.ts
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/order-detail-unlogged-user-personal-collection-cash.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/order-detail-unlogged-user-ppl-credit-card.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/order-detail-unlogged-user-transport-to-home-cash-on-delivery.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/order-detail-unlogged-user-with-registerd-email-transport-to-home-cash-on-delivery.png
Labels: DX & Refactoring

#3082 [shopsys] unified composer conflicts
  UPGRADE-14.0.md
  composer.json
  packages/http-smoke-testing/composer.json
  project-base/app/composer.json
Labels: Bug

#3051 [shopsys] product recalculations scoping
  .github/workflows/docker-build.yaml
  UPGRADE-15.0.md
  docs/asynchronous-processing/product-recalculations.md
  packages/framework/ecs.php
  packages/framework/src/Command/DispatchRecalculationMessageCommand.php
  packages/framework/src/Command/ListExportScopesCommand.php
  packages/framework/src/Component/Elasticsearch/AbstractIndex.php
  packages/framework/src/Component/Elasticsearch/Exception/UnsupportedFeatureException.php
  packages/framework/src/Component/Elasticsearch/IndexFacade.php
  packages/framework/src/Component/Reflection/ReflectionHelper.php
  packages/framework/src/Model/Article/Elasticsearch/ArticleIndex.php
  packages/framework/src/Model/Blog/Article/Elasticsearch/BlogArticleIndex.php
  packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
  packages/framework/src/Model/Product/Elasticsearch/ProductIndex.php
  packages/framework/src/Model/Product/Elasticsearch/Scope/Exception/InvalidScopeException.php
  packages/framework/src/Model/Product/Elasticsearch/Scope/Exception/ScopeRuleAlreadyExistsException.php
  packages/framework/src/Model/Product/Elasticsearch/Scope/Exception/ScopeRuleDoesNotExistException.php
  packages/framework/src/Model/Product/Elasticsearch/Scope/ProductExportFieldProvider.php
  packages/framework/src/Model/Product/Elasticsearch/Scope/ProductExportScopeConfig.php
  packages/framework/src/Model/Product/Elasticsearch/Scope/ProductExportScopeConfigFacade.php
  packages/framework/src/Model/Product/Elasticsearch/Scope/ProductExportScopeRule.php
  packages/framework/src/Model/Product/MassAction/ProductMassActionFacade.php
  packages/framework/src/Model/Product/ProductElasticsearchProvider.php
  packages/framework/src/Model/Product/Recalculation/AbstractProductRecalculationMessage.php
  packages/framework/src/Model/Product/Recalculation/DispatchAffectedProductsSubscriber.php
  packages/framework/src/Model/Product/Recalculation/DispatchAllProductsMessage.php
  packages/framework/src/Model/Product/Recalculation/DispatchAllProductsMessageHandler.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationFacade.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationMessageHandler.php
  packages/framework/src/Model/Product/Search/FilterQuery.php
  packages/framework/src/Model/Product/Search/FilterQueryFactory.php
  packages/framework/src/Model/Product/Search/ProductElasticsearchRepository.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/tests/Unit/Component/Elasticsearch/__fixtures/CategoryIndex.php
  project-base/app/config/services.yaml
  project-base/app/ecs.php
  project-base/app/src/Model/Product/Elasticsearch/ProductExportRepository.php
  project-base/app/src/Model/Product/Elasticsearch/Scope/ProductExportFieldProvider.php
  project-base/app/src/Model/Product/Elasticsearch/Scope/ProductExportScopeConfig.php
  project-base/app/src/Model/Product/Search/FilterQuery.php
  project-base/app/src/Model/Product/Search/FilterQueryFactory.php
  project-base/app/src/Model/Product/Search/ProductElasticsearchConverter.php
  project-base/app/src/Resources/definition/product/1.json
  project-base/app/src/Resources/definition/product/2.json
  project-base/app/tests/App/Functional/Model/Product/Elasticsearch/ProductExportRepositoryTest.php
Labels: Enhancement, DX & Refactoring
