Repository shopsys/shopsys, pull requests merged in 2024-02, with the labels that each got.

#3003 [shopsys] split ElasticsearchIndexException into separate ones
  UPGRADE-14.0.md
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchAliasNotFoundException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchBulkUpdateException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchCannotReadDefinitionFileException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchCreateAliasException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchCreateIndexException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchDeleteIndexException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchIndexAliasAlreadyExistsException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchIndexAliasNotFoundException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchIndexException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchIndexNotFoundException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchInvalidJsonInDefinitionFileException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchMoreThanOneIndexFoundForAliasException.php
  packages/framework/src/Component/Elasticsearch/Exception/ElasticsearchNoAliasException.php
  packages/framework/src/Component/Elasticsearch/IndexDefinition.php
  packages/framework/src/Component/Elasticsearch/IndexFacade.php
  packages/framework/src/Component/Elasticsearch/IndexRegistry.php
  packages/framework/src/Component/Elasticsearch/IndexRepository.php
  packages/framework/tests/Test/ProductIndexBackupFacade.php
  packages/framework/tests/Unit/Component/Elasticsearch/IndexDefinitionTest.php
  packages/framework/tests/Unit/Component/Elasticsearch/IndexRegistryTest.php
  project-base/app/src/Component/Elasticsearch/IndexRepository.php
Labels: DX & Refactoring

#2990 [SSP-2071] add possibility to change SF error verbosity for development
  UPGRADE-14.0.md
  docs/storefront/error-handling.md
  project-base/storefront/.env
  project-base/storefront/components/Basic/CopyTextBlock/CopyTextBlock.tsx
  project-base/storefront/components/Pages/ErrorPage/Error500Content.tsx
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/articles/queries/ArticleDetailQuery.graphql
  project-base/storefront/graphql/requests/articlesInterface/blogArticles/queries/BlogArticleDetailQuery.graphql
  project-base/storefront/graphql/requests/blogCategories/queries/BlogCategoryQuery.graphql
  project-base/storefront/graphql/requests/brands/queries/BrandDetailQuery.graphql
  project-base/storefront/graphql/requests/categories/queries/CategoryDetailQuery.graphql
  project-base/storefront/graphql/requests/flags/queries/FlagDetailQuery.graphql
  project-base/storefront/graphql/requests/products/queries/ProductDetailQuery.graphql
  project-base/storefront/graphql/requests/stores/queries/StoreDetailQuery.graphql
  project-base/storefront/helpers/errors/handleServerSideErrorResponseForFriendlyUrls.ts
  project-base/storefront/helpers/errors/isWithErrorDebugging.ts
  project-base/storefront/helpers/errors/mapGraphqlErrorForDevelopment.ts
  project-base/storefront/helpers/toasts.tsx
  project-base/storefront/middleware.ts
  project-base/storefront/next.config.js
  project-base/storefront/pages/_error.tsx
  project-base/storefront/styles/globals.css
  project-base/storefront/urql/errorExchange.ts
  project-base/storefront/urql/exchanges.ts
  project-base/storefront/urql/fetcher.ts
  project-base/storefront/vitest/helpers/urql/createClient.test.tsx
Labels: Enhancement, Design & Appearance, DX & Refactoring

#3006 [project-base] usps are now relevant and only on few products
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/RetrieveCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
Labels: DX & Refactoring

#2751 resolve unwanted links and http iframe in datafixtures
  UPGRADE-14.0.md
  project-base/app/translations/dataFixtures.cs.po
Labels: Bug, In Backlog

#2997 [storefront] added basic Symfony Toolbar for XHR request to easy opening profiler directly from storefront
  UPGRADE-14.0.md
  docs/installation/application-configuration.md
  project-base/storefront/.env
  project-base/storefront/components/Basic/SymfonyDebugToolbar/SymfonyDebugToolbar.tsx
  project-base/storefront/components/Basic/SymfonyDebugToolbar/SymfonyDebugToolbarRequestsTable.tsx
  project-base/storefront/components/Basic/SymfonyDebugToolbar/helpers.tsx
  project-base/storefront/components/Pages/App/AppPageContent.tsx
  project-base/storefront/helpers/errors/logException.ts
  project-base/storefront/helpers/errors/logMessage.ts
  project-base/storefront/helpers/isEnvironment.ts
  project-base/storefront/next.config.js
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  project-base/storefront/public/images/symfony.svg
  project-base/storefront/tsconfig.json
Labels: DX & Refactoring

#3018 [SSP-2100] added more verbose error messages when using logException on SF
  UPGRADE-14.0.md
  docs/storefront/error-handling.md
  project-base/storefront/components/Pages/Order/TransportAndPayment/helpers.ts
  project-base/storefront/helpers/errors/logException.ts
  project-base/storefront/hooks/seznamMap/useSeznamMapLoader.tsx
  project-base/storefront/hooks/useDomainConfig.ts
  project-base/storefront/pages/_app.tsx
  project-base/storefront/pages/_error.tsx
  project-base/storefront/urql/errorExchange.ts
Labels: Enhancement, DX & Refactoring

#3024 [framework] feed modules are now removed if appropriate feed no longer exists
  UPGRADE-14.0.md
  packages/framework/src/Model/Feed/FeedCronModule.php
  packages/framework/src/Model/Feed/FeedModuleFacade.php
  packages/framework/src/Model/Feed/FeedModuleRepository.php
  packages/framework/tests/Unit/Model/Feed/FeedCronModuleTest.php
Labels: DX & Refactoring

#3013 CategoryTreeSorting.init jquery UI performance
  packages/framework/assets/js/admin/components/CategoryTreeSorting.js
Labels: Performance, In Backlog

#2701 FE API Advert.catgories field returns visible categories only
  UPGRADE-14.0.md
  packages/framework/src/Model/Advert/Advert.php
  project-base/app/src/FrontendApi/Model/Category/CategoriesBatchLoader.php
  project-base/app/src/FrontendApi/Model/Category/CategoryFacade.php
  project-base/app/src/FrontendApi/Model/Category/CategoryRepository.php
  project-base/app/src/FrontendApi/Resolver/Advert/AdvertResolverMap.php
Labels: Bug, In Backlog

#3016 [shopsys] unset variant is now automatically exported
  UPGRADE-14.0.md
  packages/framework/src/Model/Product/Product.php
  packages/framework/src/Model/Product/ProductFacade.php
  project-base/app/src/Model/Product/Product.php
Labels: Bug

#3017 [framework] added unique constraint to cart
  UPGRADE-14.0.md
  packages/framework/src/Migrations/Version20240209114704.php
  project-base/app/src/FrontendApi/Model/Cart/MergeCartFacade.php
  project-base/app/src/FrontendApi/Mutation/Cart/CartMutation.php
Labels: Bug

#3028 [shopsys] luigis box product feed now correctly exports all products
  packages/framework/src/Model/Feed/FeedCronModule.php
  packages/product-feed-luigis-box/src/Model/FeedItem/LuigisBoxProductFeedItemFacade.php
  packages/product-feed-luigis-box/src/Model/Product/LuigisBoxProductRepository.php
Labels: Bug

#3036 [project-base] added missing cron instances to deploy-project.sh
  UPGRADE-14.0.md
  project-base/app/deploy/deploy-project.sh
Labels: Bug

#3025 [SSP-2107] removed duplicate update payment mutation call on order payment confirmation page
  UPGRADE-14.0.md
  project-base/storefront/components/Pages/Order/PaymentConfirmation/helpers.ts
Labels: Bug

#3042 [shopsys] hotfix: locked php-cs-fixer in version lower than 3.50 as new version causes errors in tests with current easy-coding-standards
  UPGRADE-14.0.md
  composer.json
  packages/coding-standards/composer.json
  project-base/app/composer.json
Labels: Bug

#3037 [shopsys] rewritten Persoo bundle to Luigi's Box bundle
  .github/monorepo/monorepo_functions.sh
  CHANGELOG-14.0.md
  UPGRADE-14.0.md
  build.xml
  composer.json
  docs/contributing/guidelines-for-writing-upgrade.md
  docs/introduction/monorepo.md
  packages/article-feed-luigis-box/src/Model/LuigisBoxArticleFeedItem.php
  packages/article-feed-luigis-box/src/Model/LuigisBoxArticleFeedItemFactory.php
  packages/article-feed-luigis-box/src/Resources/views/feed.xml.twig
  packages/category-feed-luigis-box/src/Model/FeedItem/LuigisBoxCategoryFeedItem.php
  packages/frontend-api/src/Resources/config/graphql-types/QueryDecorator.types.yaml
  packages/luigis-box/.github/workflows/run-checks-tests.yaml
  packages/luigis-box/.gitignore
  packages/luigis-box/CONTRIBUTING.md
  packages/luigis-box/LICENSE
  packages/luigis-box/README.md
  packages/luigis-box/composer.json
  packages/luigis-box/ecs.php
  packages/luigis-box/phpunit.xml
  packages/luigis-box/src/Component/LuigisBox/Exception/LuigisBoxConfigurationNotSetException.php
  packages/luigis-box/src/Component/LuigisBox/Exception/LuigisBoxIndexNotRecognizedException.php
  packages/luigis-box/src/Component/LuigisBox/Filter/ProductFilterToLuigisBoxFilterMapper.php
  packages/luigis-box/src/Component/LuigisBox/LuigisBoxClient.php
  packages/luigis-box/src/Component/LuigisBox/LuigisBoxResult.php
  packages/luigis-box/src/DependencyInjection/ShopsysLuigisBoxExtension.php
  packages/luigis-box/src/Model/Product/Connection/Exception/LuigisBoxPaginationBackwardsNotSupportedException.php
  packages/luigis-box/src/Model/Product/ProductSearchResultsProvider.php
  packages/luigis-box/src/Resources/config/parameters.yaml
  packages/luigis-box/src/Resources/config/services.yaml
  packages/luigis-box/src/Resources/translations/validators.cs.po
  packages/luigis-box/src/Resources/translations/validators.en.po
  packages/luigis-box/src/ShopsysLuigisBoxBundle.php
  packages/luigis-box/tests/autoload.php
  packages/persoo/src/Component/Persoo/Exception/PersooConfigurationNotSetException.php
  packages/persoo/src/Component/Persoo/Exception/PersooIndexNotRecognizedException.php
  packages/persoo/src/Component/Persoo/Filter/ProductFilterToPersooFilterMapper.php
  packages/persoo/src/Component/Persoo/PersooClient.php
  packages/persoo/src/Model/Product/Connection/Exception/PersooPaginationBackwardsNotSupportedException.php
  packages/persoo/src/Resources/config/parameters.yaml
  packages/persoo/src/Resources/config/services.yaml
  packages/persoo/src/Resources/config/services_test.yaml
  packages/product-feed-luigis-box/src/Model/FeedItem/LuigisBoxProductFeedItem.php
  project-base/app/composer.json
  project-base/app/config/bundles.php
  project-base/app/deploy/deploy-project.sh
  project-base/app/schema.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringOptionsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsSearchTest.php
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSearch.tsx
  project-base/storefront/components/Pages/Search/helpers.ts
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/generated/index.tsx
  project-base/storefront/graphql/requests/products/queries/SearchProductsQuery.graphql
  project-base/storefront/graphql/requests/search/queries/AutocompleteSearchQuery.graphql
  project-base/storefront/graphql/requests/search/queries/SearchQuery.graphql
  project-base/storefront/pages/search.tsx
  project-base/storefront/schema.graphql.json
Labels: Enhancement

#3039 [project-base] fixed promo code mass generation
  UPGRADE-15.0.md
  project-base/app/src/Model/Order/PromoCode/PromoCodeData.php
  project-base/app/src/Model/Order/PromoCode/PromoCodeFacade.php
Labels: Bug

#3040 [project-base] fixed display advert in category
  UPGRADE-15.0.md
  project-base/app/assets/js/admin/advert/advert.js
  project-base/storefront/components/Blocks/Adverts/Adverts.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
Labels: Bug
