Repository shopsys/shopsys, pull requests merged in 2024-10, with the labels that each got.

#3451 [shopsys] changes of banner sliders are propagated immediately
  packages/framework/src/Component/Grid/CleanStorefrontCacheOnSaveOrderingListener.php
  packages/framework/src/Component/Redis/CleanStorefrontCacheFacade.php
  packages/framework/src/Model/Navigation/NavigationSaveOrderingListener.php
  packages/framework/src/Model/Slider/SliderItem.php
  packages/framework/src/Model/Slider/SliderItemFacade.php
  packages/framework/src/Resources/config/services.yaml
  project-base/app/src/Model/Slider/SliderItemFacade.php
  project-base/app/src/Model/Slider/SliderItemRepository.php
  upgrade-notes/backend_20240923_123538.md
Labels: Bug, Enhancement

#3439 [shopsys] added convertim package
  .github/monorepo/monorepo_functions.sh
  CHANGELOG-16.0.md
  build.xml
  composer.json
  docs/contributing/guidelines-for-writing-upgrade.md
  docs/introduction/monorepo.md
  packages/convertim/.github/workflows/run-checks-tests.yaml
  packages/convertim/.gitignore
  packages/convertim/CONTRIBUTING.md
  packages/convertim/LICENSE
  packages/convertim/README.md
  packages/convertim/composer.json
  packages/convertim/phpstan.neon
  packages/convertim/phpunit.xml
  packages/convertim/src/Controller/.gitkeep
  packages/convertim/src/DependencyInjection/ShopsysConvertimExtension.php
  packages/convertim/src/Migrations/.gitkeep
  packages/convertim/src/Resources/config/services.yaml
  packages/convertim/src/Resources/translations/.gitkeep
  packages/convertim/src/Resources/views/.gitkeep
  packages/convertim/src/ShopsysConvertimBundle.php
  packages/convertim/tests/.gitkeep
  packages/framework/src/Resources/config/packages_registry.yaml
  project-base/app/composer.json
  project-base/app/config/bundles.php
Labels: Enhancement

#3446 [project-base] redesigned homepage
  packages/framework/src/Model/Blog/Category/BlogCategoryFacade.php
  packages/frontend-api/src/Model/Resolver/Settings/MainBlogCategoryData.php
  packages/frontend-api/src/Model/Resolver/Settings/MainBlogCategoryDataQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Blog/Category/MainBlogCategoryDataDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Settings/SettingsDecorator.types.yaml
  project-base/app/config/graphql/types/ModelType/Blog/Category/MainBlogCategoryData.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/ImageDataFixture.php
  project-base/app/src/DataFixtures/resources/images/blogCategory/500.jpg
  project-base/app/tests/FrontendApiBundle/Functional/Settings/MainBlogCategoryDataSettingsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Settings/graphql/MainBlogCategoryDataSettingsQuery.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Settings/graphql/MainBlogCategoryUrlSettingsQuery.graphql
  project-base/storefront/components/Basic/Flag/Flag.tsx
  project-base/storefront/components/Basic/Icon/UpsFifthIcon.tsx
  project-base/storefront/components/Basic/Icon/UpsFirstIcon.tsx
  project-base/storefront/components/Basic/Icon/UpsFourthIcon.tsx
  project-base/storefront/components/Basic/Icon/UpsSecondIcon.tsx
  project-base/storefront/components/Basic/Icon/UpsThirdIcon.tsx
  project-base/storefront/components/Blocks/Banners/BannerImage.tsx
  project-base/storefront/components/Blocks/Banners/Banners.tsx
  project-base/storefront/components/Blocks/Banners/BannersDot.tsx
  project-base/storefront/components/Blocks/Banners/BannersSlider.tsx
  project-base/storefront/components/Blocks/Banners/bannersUtils.ts
  project-base/storefront/components/Blocks/BlogPreview/BlogPreview.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewMain.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewPlaceholder.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewSide.tsx
  project-base/storefront/components/Blocks/BlogPreview/DeferredBlogPreview.tsx
  project-base/storefront/components/Blocks/Categories/PromotedCategories.tsx
  project-base/storefront/components/Blocks/Categories/PromotedCategoriesContent.tsx
  project-base/storefront/components/Blocks/Product/DeferredPromotedProducts.tsx
  project-base/storefront/components/Blocks/Product/LastVisitedProducts/LastVisitedProducts.tsx
  project-base/storefront/components/Blocks/Product/ProductsSlider.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModulePromotedCategories.tsx
  project-base/storefront/components/Blocks/UpsList/UpsList.tsx
  project-base/storefront/components/Blocks/UpsList/UpsListItem.tsx
  project-base/storefront/components/Pages/HomePage/HomePageContent.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/login.cy.ts/should login from header and then log out (after login).png
  project-base/storefront/cypress/snapshots/e2e/authentication/login.cy.ts/should login from header and then log out (after logout).png
  project-base/storefront/cypress/snapshots/e2e/authentication/login.cy.ts/should login from login page and then log out (after login).png
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/should disallow registration with empty registration form, but then allow after filling (after valid try).png
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/should disallow registration with invalid info, but then allow after correction (after valid try).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/should remove products from cart using cart in header and then display empty cart message (after first remove).png
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/should remove products from cart using cart in header and then display empty cart message (after second remove).png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/should add product to cart from promoted products on homepage (add to cart popup).png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/homepage visit with screenshot (homepage).png
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/settings/queries/SettingsQuery.generated.tsx
  project-base/storefront/graphql/requests/settings/queries/SettingsQuery.graphql
  project-base/storefront/graphql/types.ts
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/utils/ui/isWholeElementVisible.ts
  upgrade-notes/backend_20240920_170120.md
  upgrade-notes/storefront_20240919_115821.md
  upgrade-notes/storefront_20240920_170120.md
Labels: Design & Appearance

#3467 [project-base] prevent white page after deploy
  project-base/storefront/middleware.ts
  upgrade-notes/storefront_20241002_121047.md
Labels: Bug

#3434 [project-base] demo images for complaints
  project-base/app/src/DataFixtures/Demo/ComplaintDataFixture.php
  project-base/app/src/DataFixtures/resources/images/complaint/400.jpg
  project-base/app/src/DataFixtures/resources/images/complaint/401.jpg
  project-base/app/src/DataFixtures/resources/images/complaint/402.jpg
  project-base/app/src/DataFixtures/resources/images/complaint/403.jpg
  upgrade-notes/backend_20240913_112707.md
Labels: Enhancement

#3472 [project-base] fixed complaints search
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Homepage] (homepage) homepage visit with screenshot.png
  project-base/storefront/pages/customer/complaints.tsx
  project-base/storefront/pages/customer/new-complaint.tsx
  upgrade-notes/storefront_20241003_123203.md
Labels: Bug

#3471 [project-base] unified date format based on localization
  project-base/storefront/components/Blocks/OpeningHours/OpeningHours.tsx
  project-base/storefront/components/Pages/Article/ArticleDetailContent.tsx
  project-base/storefront/components/Pages/Customer/ComplaintDetail/ComplaintDetailBasicInfo.tsx
  project-base/storefront/components/Pages/Customer/Complaints/ComplaintItem.tsx
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailBasicInfo.tsx
  project-base/storefront/components/Pages/Customer/Orders/OrderItem.tsx
  project-base/storefront/components/Pages/PersonalData/Detail/PersonalDataDetailContent.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/login.cy.ts/[Header] (after login) login from header and then log out.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/lastOrderTransportAndPayment.cy.ts/[Change T&P And Preserve On Refresh] (after second change and refresh) change preselected transport and payment from last order for logged-in user and keep the new selection after refresh.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/[Personal Collection] (after selecting) select personal pickup transport.png
  project-base/storefront/utils/formaters/formatDate.ts
  project-base/storefront/utils/formatting/useFormatDate.ts
  upgrade-notes/storefront_20241003_113606.md
Labels: Bug, Design & Appearance

#3477 [framework] fixed owner of complaint sequences
  docs/cookbook/adding-a-new-order-item-type.md
  packages/framework/src/Migrations/Version20241008072724.php
  packages/framework/src/Model/Complaint/Complaint.php
  packages/framework/src/Model/Complaint/ComplaintItem.php
Labels: Bug

#3476 [project-base] removed link of hide product in order detail
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailOrderItem.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/login.cy.ts/[Header] (after login) login from header and then log out.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Homepage] (homepage) homepage visit with screenshot.png
  upgrade-notes/storefront_20241004_121326.md
Labels: Bug

#3475 [shopsys] FE API: blog category now can return main image
  packages/frontend-api/src/Model/Resolver/Image/BlogCategoryImagesQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Blog/Category/BlogCategoryDecorator.types.yaml
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/BlogArticleDataFixture.php
  project-base/app/src/DataFixtures/Demo/ImageDataFixture.php
  project-base/app/src/DataFixtures/resources/images/blogArticle/600.jpg
  project-base/app/src/DataFixtures/resources/images/blogArticle/601.jpg
  project-base/app/src/DataFixtures/resources/images/blogArticle/602.jpg
  project-base/app/src/DataFixtures/resources/images/blogCategory/501.jpg
  project-base/app/tests/FrontendApiBundle/Functional/Blog/Article/BlogArticleTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Blog/Category/BlogCategoryTest.php
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Blog Detail] (blog article detail) blog article detail visit with screenshot.png
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
Labels: Enhancement

#3487 [docs] lost documentation from Commerce Cloud has returned
  docs/administration/admin-rights.md
  docs/administration/disabling-form-fields.md
  docs/administration/index.md
  docs/administration/navigation.yml
  docs/introduction/index.md
  docs/introduction/navigation.yml
  docs/introduction/phpstorm-settings.md
  docs/introduction/postman-settings.md
Labels: Documentation

#3470 [project-base] added cart skeleton loader
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewMain.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewSide.tsx
  project-base/storefront/components/Blocks/Popup/AddToCartPopup.tsx
  project-base/storefront/components/Blocks/Popup/NotAddedProductsPopup.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageCart.tsx
  project-base/storefront/components/Layout/Header/Cart/CartInHeader.tsx
  project-base/storefront/components/Pages/BlogCategory/BlogArticlesList.tsx
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailOrderItem.tsx
  project-base/storefront/cypress/e2e/cart/cartInHeader.cy.ts
  project-base/storefront/cypress/e2e/visits/simpleVisitsWithScreenshots.cy.ts
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/[Cart Header Remove] (after first remove) remove products from cart using cart in header and then display empty cart message.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Brand Page Add] (add to cart popup) add product to cart from brand page.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Category Page Add] (add to cart popup) add product to cart from category page.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Product Detail Add] (add to cart popup) add product to cart from product detail.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Product Variant Add] (add to cart popup) add variant product to cart from product detail.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Promoted Products Add] (add to cart popup) add product to cart from promoted products on homepage.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/[Search Page Add] (add to cart popup) add product to cart from search results page.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Homepage] (homepage) homepage visit with screenshot.png
  upgrade-notes/storefront_20241003_084133.md
Labels: Bug, Design & Appearance

#3492 [shopsys] docs: add info about necessary Git long paths settings for Windows installation
  docs/installation/application-requirements.md
  docs/installation/installation-using-docker-windows-10.md
  docs/introduction/faq-and-common-issues.md
Labels: Documentation

#3478 [shopsys] upgraded two-factor packages to be compatible with Symfony 6
  composer.json
  packages/framework/composer.json
  packages/framework/src/Controller/Admin/AdministratorController.php
  packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
  packages/framework/src/Model/Administrator/AdministratorTwoFactorAuthenticationFacade.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Administrator/enableTwoFactorAuthenticationByEmail.html.twig
  packages/framework/src/Resources/views/Admin/Content/Administrator/enableTwoFactorAuthenticationByGoogleAuth.html.twig
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/[Cart Header Remove] (after first remove) remove products from cart using cart in header and then display empty cart message.png
Labels: dependencies

#3400 [framework] Remove deprecated title, caption, geo_location, license + lastmod from image sitemap
  packages/framework/src/Model/ImageSitemap/ImageSitemapDumper.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapFacade.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapIndex.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapItemImage.php
  packages/framework/src/Model/ImageSitemap/ImageSitemapListener.php
  project-base/app/tests/App/Functional/Model/ImageSitemap/ImageSitemapTest.php
  upgrade-notes/backend_20240902_060604.md
Labels: Enhancement, Easy Pick

#3498 [shopsys] upgrade doctrine/persistence to ^3.3.3
  composer.json
  packages/article-feed-luigis-box/composer.json
  packages/brand-feed-luigis-box/composer.json
  packages/category-feed-luigis-box/composer.json
  packages/framework/composer.json
  packages/framework/src/Component/EntityExtension/EntityManagerDecorator.php
  packages/product-feed-google/composer.json
  packages/product-feed-heureka/composer.json
  packages/product-feed-luigis-box/composer.json
  packages/product-feed-zbozi/composer.json
  project-base/app/composer.json
  upgrade-notes/backend_20241011_131118.md
Labels: dependencies

#3468 [shopsys] logged user is not allowed to change their email in cart
  packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/SetCustomerUserMiddleware.php
  packages/framework/tests/Unit/Model/Order/Processing/OrderProcessorMiddleware/SetCustomerUserMiddlewareTest.php
  packages/frontend-api/src/Model/Mutation/Order/CreateOrderMutation.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Order/Input/OrderInputDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Order/MinimalOrderAsAuthenticatedCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/RequiredFieldsTest.php
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationEmail.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/contactInformationUtils.ts
  project-base/storefront/connectors/customer/CurrentCustomer.ts
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/types.ts
  project-base/storefront/pages/customer/edit-profile.tsx
  upgrade-notes/backend_20241010_150127.md
  upgrade-notes/storefront_20241002_131825.md
Labels: Enhancement

#3488 [shopsys] SSP-2670 - Fix ordering in FE internal search
  packages/frontend-api/src/Model/Resolver/Products/ProductOrderingModeProvider.php
  packages/frontend-api/src/Model/Resolver/Products/Search/ProductSearchResultsProvider.php
  project-base/app/src/FrontendApi/Mutation/Order/CreateOrderMutation.php
  project-base/storefront/components/Pages/Search/SearchProducts.tsx
  upgrade-notes/storefront_20241009_094528.md
Labels: Bug

#3501 [framework] SSP-2751 - Set default ordering by last/first name in getCustomerUsersQueryBuilder
  packages/framework/src/Model/Customer/CustomerRepository.php
  project-base/storefront/components/Pages/Customer/Users/CustomerUsersTable.tsx
Labels: Enhancement

#3463 [project-base] added browser sync for product lists
  project-base/storefront/cypress/snapshots/e2e/authentication/login.cy.ts/[Login Page] (after login) login from login page and then log out.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/[Cart Header Remove] (after first remove) remove products from cart using cart in header and then display empty cart message.png
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/utils/errors/applicationErrors.ts
  project-base/storefront/utils/errors/errorMessageMapper.ts
  project-base/storefront/utils/productLists/useProductList.ts
  upgrade-notes/storefront_20240930_072933.md
Labels: Bug

#3506 [project-base] fixed inverted button responsive
  project-base/storefront/tailwind.config.js
  upgrade-notes/storefront_20241015_065958.md
Labels: Bug, Design & Appearance

#3503 [framework] fix blog category visibility calculation
  packages/framework/src/Migrations/Version20241014125411.php
  packages/framework/src/Model/Blog/Category/BlogCategoryFacade.php
  packages/framework/src/Model/Blog/Category/BlogCategoryRepository.php
  packages/frontend-api/src/Model/Blog/Article/BlogArticleResolverMap.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Blog/Article/BlogArticleDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/types.ts
Labels: Bug

#3509 [project-base] stable feed hash for alpha branch
  project-base/.gitlab-ci.yml
Labels: DX & Refactoring

#3502 [project-base] hidden user section for non company user
  project-base/storefront/utils/auth/useCurrentCustomerUserPermissions.ts
  upgrade-notes/storefront_20241014_095514.md
Labels: Bug

#3525 [shopsys] upgrade shopsys/deployment package
  composer.json
  project-base/.gitlab-ci.yml
  project-base/app/composer.json
  upgrade-notes/backend_20241021_135521.md
Labels: Infrastructure

#3526 [shopsys] update directories yaml file
  docs/introduction/directories.md
Labels: Documentation

#3521 [project-base] Fix blurry text in popup (4k monitor)
  project-base/storefront/components/Layout/Popup/Popup.tsx
  project-base/storefront/utils/useWindowDimensions.ts
  upgrade-notes/storefront_20241022_104017.md
Labels: Bug

#3474 [SSP-2495] edited required logic for form inputs: deliveryStreet, deliveryCity, deliveryPostcode
  project-base/storefront/components/Pages/Order/ContactInformation/contactInformationFormMeta.ts
Labels: Bug

#3495 [project-base] fixed gtm order create status sent twice
  .github/workflows/docker-build.yaml
  docker/conf/docker-compose.github-actions.review.simplified.yml.dist
  docker/conf/docker-compose.github-actions.review.yml.dist
  project-base/storefront/.env.development
  project-base/storefront/components/Pages/Order/PaymentConfirmation/paymentConfirmationUtils.ts
  upgrade-notes/storefront_20241011_101618.md
Labels: Bug

#3497 [framework] SSP-2718 - extend CustomerFileNotFoundException for frontend 404 page
  packages/framework/src/Component/CustomerUploadedFile/Exception/CustomerFileException.php
  packages/framework/src/Component/CustomerUploadedFile/Exception/CustomerFileNotFoundException.php
  packages/framework/src/Component/Error/ErrorPagesFacade.php
  packages/framework/src/Controller/Admin/ErrorController.php
  packages/framework/src/Model/Breadcrumb/ErrorPageBreadcrumbGenerator.php
  packages/framework/src/Resources/config/routing.yaml
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Error/error.css.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error.js.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error.json.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error.txt.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error.xml.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error4xx.html.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error500.html.twig
  packages/framework/src/Resources/views/Admin/Content/Superadmin/errors.html.twig
  packages/framework/src/Resources/views/Admin/Layout/errorLayout.html.twig
  project-base/app/config/packages/framework.yaml
  project-base/app/config/routes/shopsys_framework.yaml
  project-base/app/config/services.yaml
  project-base/app/src/Controller/Admin/ErrorController.php
  project-base/app/src/Model/Breadcrumb/ErrorPageBreadcrumbGenerator.php
  project-base/app/templates/bundles/ShopsysFrameworkBundle/Admin/Content/Superadmin/errors.html.twig
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  upgrade-notes/backend_20241016_115618.md
Labels: Bug

#3524 [project-base] unified form messages
  project-base/storefront/components/Blocks/Popup/ManageCustomerUserPopup.tsx
  upgrade-notes/storefront_20241021_125820.md
Labels: DX & Refactoring

#3522 [project-base] showed category image just on first page
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
  upgrade-notes/storefront_20241021_115025.md
Labels: Bug, Design & Appearance

#3490 [frontend-api] add variantsCount to MainVariant type
  packages/frontend-api/src/Model/Product/BatchLoad/ProductsBatchLoader.php
  packages/frontend-api/src/Model/Resolver/Products/DataMapper/ProductArrayFieldMapper.php
  packages/frontend-api/src/Model/Resolver/Products/DataMapper/ProductEntityFieldMapper.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Product/MainVariantDecorator.types.yaml
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/app/config/packages/overblog_dataloader.yaml
  project-base/app/config/services_frontend_api.yaml
  project-base/app/schema.graphql
  project-base/app/src/FrontendApi/Resolver/Products/DataMapper/ProductArrayFieldMapper.php
  project-base/app/src/FrontendApi/Resolver/Products/DataMapper/ProductEntityFieldMapper.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductVariantTest.php
  project-base/storefront/components/Basic/Icon/VariantIcon.tsx
  project-base/storefront/components/Basic/UserText/GrapesJsProducts.tsx
  project-base/storefront/components/Blocks/Product/LastVisitedProducts/LastVisitedProductsContent.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItem.tsx
  project-base/storefront/components/Blocks/Product/ProductsSlider.tsx
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSearchPopup.tsx
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSearchProductsResult.tsx
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSkeleton.tsx
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Blog Detail] (blog article detail) blog article detail visit with screenshot.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Homepage] (homepage) homepage visit with screenshot.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/[Product Detail] (product detail) product detail visit with screenshot.png
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/categories/fragments/CategoryDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/categories/queries/CategoryDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/productLists/fragments/ProductInProductListFragment.generated.tsx
  project-base/storefront/graphql/requests/productLists/fragments/ProductListFragment.generated.tsx
  project-base/storefront/graphql/requests/productLists/mutations/AddProductToListMutation.generated.tsx
  project-base/storefront/graphql/requests/productLists/mutations/RemoveProductFromListMutation.generated.tsx
  project-base/storefront/graphql/requests/productLists/queries/ProductListQuery.generated.tsx
  project-base/storefront/graphql/requests/products/fragments/ListedProductConnectionFragment.generated.tsx
  project-base/storefront/graphql/requests/products/fragments/ListedProductFragment.generated.tsx
  project-base/storefront/graphql/requests/products/fragments/ListedProductFragment.graphql
  project-base/storefront/graphql/requests/products/fragments/MainVariantDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/products/fragments/ProductDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/products/fragments/ProductDetailInterfaceFragment.generated.tsx
  project-base/storefront/graphql/requests/products/queries/BrandProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/CategoryProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/FlagProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/ProductDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/ProductsByCatnumsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/PromotedProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/RecommendedProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/AutocompleteSearchQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/SearchProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/search/queries/SearchQuery.generated.tsx
  project-base/storefront/graphql/requests/slugs/queries/slugQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/schema-compressed.graphql.json
  upgrade-notes/backend_20241023_110643.md
  upgrade-notes/storefront_20241011_075157.md
Labels: Enhancement, Performance

#3513 [framework] Activation of CSRF protection for the deleteConfirm actions in admin
  packages/framework/src/Controller/Admin/ArticleController.php
  packages/framework/src/Controller/Admin/BlogArticleController.php
  packages/framework/src/Controller/Admin/ComplaintStatusController.php
  packages/framework/src/Controller/Admin/CurrencyController.php
  packages/framework/src/Controller/Admin/OrderStatusController.php
  packages/framework/src/Controller/Admin/PricingGroupController.php
  packages/framework/src/Controller/Admin/SalesRepresentativeController.php
  packages/framework/src/Controller/Admin/SeoPageController.php
  packages/framework/src/Controller/Admin/UnitController.php
  packages/framework/src/Controller/Admin/VatController.php
  project-base/app/tests/App/Smoke/Http/RouteConfigCustomization.php
Labels: Bug

#3531 [project-base] removed filter panel rerender on search page
  project-base/storefront/components/Blocks/Product/Filter/FilterSelectedParameters.tsx
  project-base/storefront/components/Pages/Search/SearchProducts.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/login.cy.ts/[Login Page] (after login) login from login page and then log out.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/[Cart Header Remove] (after first remove) remove products from cart using cart in header and then display empty cart message.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/[Cart Header Remove] (after second remove) remove products from cart using cart in header and then display empty cart message.png
  upgrade-notes/storefront_20241023_075039.md
Labels: Bug

#3520 [projcet-base] Add Luigi's box recommender identifier
  packages/luigis-box/src/Component/LuigisBox/LuigisBoxClient.php
  packages/luigis-box/src/FrontendApi/Resolver/Recommendation/RecommendationQuery.php
  packages/luigis-box/src/Model/Batch/LuigisBoxBatchLoadData.php
  packages/luigis-box/src/Model/Batch/LuigisBoxBatchLoadDataFactory.php
  packages/luigis-box/src/Model/Batch/LuigisBoxRecommendationBatchLoadData.php
  packages/luigis-box/src/Resources/config/graphql-types/RecommendationQuery.types.yaml
  project-base/app/schema.graphql
  project-base/storefront/components/Blocks/Product/DeferredRecommendedProducts.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/products/queries/RecommendedProductsQuery.generated.tsx
  project-base/storefront/graphql/requests/products/queries/RecommendedProductsQuery.graphql
  project-base/storefront/graphql/types.ts
  project-base/storefront/pages/index.tsx
  project-base/storefront/pages/products/[productSlug].tsx
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/utils/recommender/getRecommenderClientIdentifier.ts
  upgrade-notes/storefront_20241023_082558.md
Labels: Bug

#3516 [shopsys] fix builds on version branches
  .github/workflows/docker-build.yaml
Labels: Infrastructure

#3540 [project-base] fixed asset loading in helios-ag/fm-elfinder-bundle 12.6
  project-base/app/config/packages/fm_elfinder.yaml
  upgrade-notes/backend_20241029_105727.md
Labels: Bug

#3517 [project-base] Fix unknown errors messages
  project-base/storefront/components/Blocks/OpeningHours/OpeningHours.tsx
  project-base/storefront/components/Pages/Customer/EditProfileContent.tsx
  project-base/storefront/cypress/e2e/cart/cartInHeader.cy.ts
  project-base/storefront/cypress/e2e/cart/cartSupport.ts
  project-base/storefront/cypress/e2e/transportAndPayment/lastOrderTransportAndPayment.cy.ts
  project-base/storefront/cypress/e2e/transportAndPayment/transportAndPaymentSupport.ts
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/[Cart Header Remove] (after first remove) remove products from cart using cart in header and then display empty cart message.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/[Cart Header Remove] (after second remove) remove products from cart using cart in header and then display empty cart message.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/lastOrderTransportAndPayment.cy.ts/[Change T&P And Preserve On Refresh] (after second change and refresh) change preselected transport and payment from last order for logged-in user and keep the new selection after refresh.png
  project-base/storefront/cypress/tids.ts
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/utils/errors/applicationErrors.ts
  project-base/storefront/utils/errors/errorMessageMapper.ts
  upgrade-notes/storefront_20241018_140905.md
Labels: Bug

#3529 [project-base] fixed order detail skeleton
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleCustomerComplaintDetail.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleCustomerOrderDetail.tsx
  upgrade-notes/storefront_20241023_061200.md
Labels: Bug

#3527 [project-base] disabled fields in cart for B2B customers
  project-base/storefront/components/Blocks/Popup/ManageCustomerUserPopup.tsx
  project-base/storefront/components/Forms/Lib/LabelWrapper.tsx
  project-base/storefront/components/Forms/Select/Select.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuMyAccountList.tsx
  project-base/storefront/components/Pages/Customer/CustomerContent.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/BillingAddress.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/CompanyCustomer.tsx
  project-base/storefront/components/Pages/Customer/Users/CustomerUsersTable.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationAddress.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationCompany.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationCustomer.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationEmail.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/contactInformationFormMeta.ts
  project-base/storefront/pages/customer/users.tsx
  project-base/storefront/styles/globals.css
  project-base/storefront/utils/auth/useUserPermissions.ts
  project-base/storefront/utils/user/useUserMenuItems.ts
  upgrade-notes/storefront_20241022_075722.md
Labels: Enhancement, Design & Appearance

#3537 [project-base] Fix wrong redirect after refresh
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleCustomerUsers.tsx
  project-base/storefront/pages/customer/users.tsx
  project-base/storefront/utils/auth/useUserPermissions.ts
  upgrade-notes/storefront_20241030_204736.md
Labels: Bug

#3530 [project-base] added form validation delay
  project-base/storefront/components/Layout/Footer/NewsletterForm/newsletterFormMeta.tsx
  project-base/storefront/cypress/e2e/authentication/login.cy.ts
  project-base/storefront/utils/forms/useShopsysForm.ts
  upgrade-notes/storefront_20241023_071213.md
Labels: Enhancement

#3553 dependabot: ignore major version changes
  .github/dependabot.yml
Labels: DX & Refactoring
