Repository shopsys/shopsys, pull requests merged in 2025-06, with the labels that each got.

#3971 Improve middleware security
  project-base/storefront/middleware.ts
  upgrade-notes/storefront_20250509_132321.md
Labels: Security

#3998 ensure that GrapesJS content is always editable
  packages/framework/src/Component/GrapesJs/EnsureCorrectGrapesJsFormatHelper.php
  packages/framework/src/Model/Article/ArticleDataFactory.php
  packages/framework/src/Model/Blog/Article/BlogArticleDataFactory.php
  packages/framework/src/Model/Mail/MailTemplateDataFactory.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  project-base/app/assets/js/admin/grapesjs/initGrapesJs.js
  upgrade-notes/backend_20250528_145603.md
Labels: Bug

#4001 Re-render and recalculations optimalization
  project-base/storefront/components/Basic/RangeSlider/RangeSlider.tsx
  project-base/storefront/components/Blocks/Adverts/Adverts.tsx
  project-base/storefront/components/Blocks/CollapsibleDescriptionWithImage/CollapsibleDescriptionWithImage.tsx
  project-base/storefront/components/Blocks/OrderItemProductCard/OrderItemProductCard.tsx
  project-base/storefront/components/Blocks/Product/Filter/FilterSelectedParameters.tsx
  project-base/storefront/components/Blocks/SimpleNavigation/SimpleNavigation.tsx
  project-base/storefront/components/Blocks/SortingBar/SortingBar.tsx
  project-base/storefront/components/Blocks/UserMenu/UserMenu.tsx
  project-base/storefront/components/Pages/CategoryDetail/AdvancedSeoCategories.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryBestsellers/CategoryBestsellers.tsx
  project-base/storefront/components/Pages/OrderConfirmation/OrderConfirmationSummary.tsx
  upgrade-notes/storefront_20250529_081236.md
Labels: Enhancement, DX & Refactoring, coderabbit

#4023 fixed standards
  packages/administration/src/Component/Config/CrudConfig.php
  packages/framework/src/Command/CheckAccessControlRulesCommand.php
  packages/framework/src/Component/Grid/Grid.php
  project-base/app/src/Component/DataBridge/Transfer/DummyImportTransferFacade.php
  upgrade-notes/backend_20250604_072209.md
Labels: Bug

#4040 fixed price range slider
  project-base/storefront/components/Basic/RangeSlider/RangeSlider.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  upgrade-notes/storefront_20250613_061644.md
Labels: Bug

#4030 mailer does not try to send message to non-existing email
  packages/framework/src/Model/Mail/EventListener/EnvelopeListener.php
  packages/framework/tests/Unit/Model/Mail/EnvelopeListenerTest.php
Labels: Bug, Easy Pick

#4045 fixed responsive signpost zindex
  project-base/storefront/components/Blocks/BlogSignpost/BlogSignpost.tsx
  upgrade-notes/storefront_20250616_122304.md
Labels: Bug

#4033 MultidomainType: multidomain options are correctly merged with domain options
  packages/form-types-bundle/src/MultidomainType.php
  packages/framework/src/Resources/translations/messages.cs.po
Labels: Bug

#4041 Updated meaningful parameters to sliders
  .gitignore
  CLAUDE.md
  ecs.php
  project-base/app/ecs-skip-rules.php
  project-base/app/src/DataFixtures/Demo/CategoryParameterDataFixture.php
  project-base/app/src/DataFixtures/Demo/ParameterDataFixture.php
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/app/src/DataFixtures/Demo/ReadyCategorySeoDataFixture.php
  project-base/app/src/DataFixtures/Demo/UnitDataFixture.php
  project-base/app/tests/App/Functional/Model/Product/Filter/ParameterFilterChoiceRepositoryTest.php
  project-base/app/tests/App/Functional/Model/Product/ProductOnCurrentDomainElasticFacadeCountDataTest.php
  project-base/app/tests/App/Functional/Model/Product/Search/FilterQueryTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/RetrieveCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringOptionsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/storefront/components/Pages/ProductDetail/ProductDetailTabs/ProductDetailTabs.tsx
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  upgrade-notes/backend_20250613_113952.md
Labels: Enhancement

#4039 Refactored Spinbox component & Spinbox Test cover
  project-base/storefront/components/Forms/Spinbox/Spinbox.tsx
  project-base/storefront/components/Forms/validationConstants.ts
  project-base/storefront/cypress/e2e/cart/cartPage.cy.ts
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  project-base/storefront/vitest.config.js
  project-base/storefront/vitest/components/ExtendedNextLink/snap-2.test.tsx.snap
  project-base/storefront/vitest/components/ExtendedNextLink/snap-3.test.tsx.snap
  project-base/storefront/vitest/components/ExtendedNextLink/snap-4.test.tsx.snap
  project-base/storefront/vitest/components/Spinbox/Spinbox.test.tsx
  project-base/storefront/vitest/setup.ts
  upgrade-notes/storefront_20250613_093520.md
Labels: coderabbit

#4046 Fix `LoaderWithOverlay` component
  docs/introduction/friendly-url.md
  docs/storefront/component-deferring.md
  docs/storefront/debugging.md
  project-base/storefront/components/Basic/Loader/LoaderWithOverlay.tsx
  project-base/storefront/components/Blocks/OrderItemProductCard/OrderItemProductCard.tsx
  project-base/storefront/components/Blocks/OrderSummary/OrderSummary.tsx
  project-base/storefront/components/Layout/Header/Cart/CartInHeaderList.tsx
  project-base/storefront/components/Pages/Cart/CartList/CartList.tsx
  project-base/storefront/components/Pages/Cart/CartList/CartListItem.tsx
  project-base/storefront/components/Pages/Cart/CartPreview.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelect.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelectItemLabel.tsx
  project-base/storefront/pages/_feedback.tsx
  upgrade-notes/backend_20250113_134103.md
  upgrade-notes/storefront_20250513_175616.md
  upgrade-notes/storefront_20250602_170234.md
  upgrade-notes/storefront_20250619_073842.md
Labels: Bug

#4049 AddRoundingMiddleware now correctly uses OrderPriceCalculation::calculateOrderRoundingPrice as it was supposed to
  build.xml
  packages/framework/build.xml
  packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/AddRoundingMiddleware.php
  packages/framework/tests/Unit/Model/Order/Processing/OrderProcessorMiddleware/AddRoundingMiddlewareTest.php
Labels: DX & Refactoring, coderabbit
