Repository shopsys/shopsys, pull requests merged in 2025-07, with the labels that each got.

#4053 GoPay: improve logging of failed payment creation + add docs
  docs/index.md
  docs/integration/index.md
  docs/integration/navigation.yml
  docs/integration/payment-gateways.md
  packages/framework/src/Model/GoPay/GoPayFacade.php
  project-base/app/deploy/deploy-project.sh
Labels: Documentation, DX & Refactoring

#4067 updated grapes js and list styles
  project-base/app/assets/js/admin/grapesjs/initGrapesJs.js
  project-base/app/assets/styles/admin/grapesjs.less
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-13 transport and payment page with non-free options after applying promocode.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-4 blog article detail.png
  project-base/storefront/styles/user-text.css
  upgrade-notes/storefront_20250709_113100.md
Labels: Bug, Design & Appearance

#4066 updated complaint item image size
  project-base/storefront/components/Pages/Customer/Complaints/ComplaintItem.tsx
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailOrderItem.tsx
  upgrade-notes/storefront_20250709_064218.md
Labels: Bug

#4055 addFieldsByOrderItemType now correctly sets Product for OrderItem of type product
  packages/framework/src/Model/Order/Item/OrderItemDataFactory.php
Labels: Bug, Easy Pick

#4080 added opening hours voice over logic and format time
  project-base/storefront/components/Basic/Flag/Flag.tsx
  project-base/storefront/components/Basic/Infobox/Infobox.tsx
  project-base/storefront/components/Blocks/OpeningHours/OpeningHours.tsx
  project-base/storefront/components/Blocks/OpeningHours/OpeningHoursToday.tsx
  project-base/storefront/components/Blocks/OpeningHours/OpeningStatus.tsx
  project-base/storefront/components/Blocks/StoreList/StoreListItem.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-13 transport and payment page with non-free options after applying promocode.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/paymentSelect.cy.ts/4-1-4 after selecting.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-3 stores page.png
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/utils/accessibility/formatAccessibleTime.ts
  project-base/storefront/utils/openingHours/openingHoursHelper.tsx
  upgrade-notes/storefront_20250717_102230.md
Labels: Bug, Design & Appearance, coderabbit

#4110 OrderItemData::createFromOrder now sets related items correctly
  packages/framework/src/Model/Order/OrderDataFactory.php
Labels: Bug

#4117 fixed sales representative name without image
  project-base/storefront/components/Layout/Header/MenuIconic/SalesRepresentative.tsx
  upgrade-notes/storefront_20250724_083828.md
Labels: Bug

#4118 fixed product availability popup scrollbars
  project-base/storefront/components/Pages/ProductDetail/ProductDetailAvailability.tsx
  upgrade-notes/storefront_20250724_111618.md
Labels: Bug

#4116 fixed customer info in order detail
  project-base/storefront/components/Blocks/OrderCustomerInfo/OrderCustomerInfo.tsx
  project-base/storefront/utils/user/useCurrentUserContactInformation.ts
  upgrade-notes/storefront_20250724_080631.md
Labels: Bug
