Repository shopsys/shopsys, pull requests merged in 2025-01, with the labels that each got.

#3712 [github-actions] fixed artifact uploading for parallelized cypress tests
  .github/workflows/docker-build.yaml
Labels: Bug

#3680 [administration] fix localization based on admin language for GrapesJS
  packages/framework/assets/styles/admin/components/in/ckeditor.less
  packages/framework/src/Component/CKEditor/CKEditorRendererDecorator.php
  project-base/app/assets/js/admin/grapesjs/initGrapesJs.js
  project-base/app/assets/js/admin/grapesjs/locales/cs.js
  project-base/app/assets/js/admin/grapesjs/locales/en.js
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-mail-template-plugin.js
  project-base/app/package.json
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  upgrade-notes/backend_20241217_163143.md
Labels: Bug, Easy Pick, javascript

#3683 [shopsys] improved administration authentication code
  packages/framework/src/Controller/Admin/AdministratorController.php
  packages/framework/src/Controller/Admin/LoginController.php
  packages/framework/src/Model/Security/Authenticator.php
  packages/framework/src/Model/Security/Exception/LoginFailedException.php
  packages/framework/src/Model/Security/LoginListener.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/views/Admin/Content/Login/loginForm.html.twig
  packages/framework/tests/Unit/Model/Security/AuthenticatorTest.php
  packages/frontend-api/src/Controller/SocialNetworkController.php
  project-base/app/src/Controller/Admin/AdministratorController.php
  project-base/app/tests/App/Functional/Model/Security/AuthenticatorTest.php
  upgrade-notes/backend_20241218_142257.md
Labels: DX & Refactoring

#3729 fix migrations of dates with wrong timezone
  packages/framework/src/Migrations/Version20240111072911.php
  project-base/app/src/Migrations/Version20240111153621.php
Labels: Bug

#3719 order mail: hide total price for customers that are not allowed to see prices
  packages/framework/src/Model/Order/Mail/OrderMail.php
  packages/frontend-api/src/Component/Price/MoneyFormatterHelper.php
  packages/frontend-api/src/Model/Resolver/Query/MoneyResolverMap.php
  project-base/app/src/Model/Order/Mail/OrderMail.php
  project-base/app/tests/App/Functional/Model/Order/Mail/OrderMailTest.php
  upgrade-notes/backend_20250107_162034.md
Labels: Bug

#3730 removed explicitly cleared setting cache
  packages/framework/src/Component/Domain/DomainDataCreator.php
  packages/framework/src/Component/Setting/ClearSettingsCacheDoctrineSubscriber.php
  packages/framework/src/Component/Setting/Setting.php
  packages/framework/src/Resources/config/services.yaml
Labels: Performance

#3716 add email property to Complaint
  packages/framework/src/Form/Admin/Complaint/ComplaintFormType.php
  packages/framework/src/Migrations/Version20250103183756.php
  packages/framework/src/Model/AdvancedSearchComplaint/AdvancedSearchComplaintFacade.php
  packages/framework/src/Model/Complaint/Complaint.php
  packages/framework/src/Model/Complaint/ComplaintData.php
  packages/framework/src/Model/Complaint/ComplaintDataFactory.php
  packages/framework/src/Model/Complaint/Mail/ComplaintMail.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Complaint/quickSearchFormContent.html.twig
  packages/frontend-api/src/Model/Complaint/ComplaintDataApiFactory.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Complaint/ComplaintDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Complaint/Input/ComplaintInputDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/Helper/ComplaintHelper.php
  project-base/app/tests/FrontendApiBundle/Functional/Complaint/ComplaintTestTrait.php
  project-base/app/tests/FrontendApiBundle/Functional/Complaint/CreateComplaintTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Complaint/graphql/CreateComplaintMutation.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Complaint/graphql/GetComplaintQuery.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Complaint/graphql/GetComplaintsQuery.graphql
  project-base/storefront/components/Blocks/Popup/CreateComplaintPopup.tsx
  project-base/storefront/components/Pages/Customer/ComplaintDetail/ComplaintDetailCustomerInfo.tsx
  project-base/storefront/components/Pages/Customer/Complaints/complaintFormMeta.ts
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintDetailFragment.graphql
  project-base/storefront/graphql/requests/complaints/queries/ComplaintQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintsQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/pages/customer/complaints.tsx
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/types/form.ts
  project-base/storefront/utils/complaints/useComplaintsData.ts
  upgrade-notes/storefront_20250107_080713.md
Labels: Enhancement

#3728 updated wrapping required checkbox indicator
  project-base/storefront/components/Basic/Link/Link.tsx
  project-base/storefront/components/Blocks/Product/Watchdog/watchdogFormMeta.tsx
  project-base/storefront/components/Layout/Footer/NewsletterForm/newsletterFormMeta.tsx
  project-base/storefront/components/Pages/Contact/contactFormMeta.tsx
  project-base/storefront/components/Pages/OrderConfirmation/RegistrationAfterOrder.tsx
  project-base/storefront/components/Pages/Registration/RegistrationContent.tsx
  project-base/storefront/components/Pages/Registration/registrationFormMeta.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-0 filled registration form.png
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-2 after invalid try.png
  upgrade-notes/storefront_20250109_090726.md
Labels: Bug, Design & Appearance

#3707 removed banner text when there is no description
  project-base/storefront/components/Blocks/Banners/Banner.tsx
  upgrade-notes/storefront_20241231_122219.md
Labels: Design & Appearance

#3685 removed double slash in link after failed payment
  project-base/storefront/components/PaymentsInOrderSelect/paymentInOrderSelectUtils.ts
  upgrade-notes/storefront_20241219_085149.md
Labels: Bug

#3721 added colors to flags demodata
  project-base/app/src/DataFixtures/Demo/FlagDataFixture.php
  project-base/app/src/Migrations/Version20200714071640.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/RetrieveCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/Flag/FlagTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-0 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-3 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-5 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  upgrade-notes/backend_20250107_141310.md
Labels: Design & Appearance

#3612 repository-clean.sh pipeline id for deployments
  project-base/gitlab/scripts/repository-clean.sh
Labels: Bug, In Backlog

#3670 add register form to payment confirmation page
  packages/framework/src/Model/GoPay/GoPayOrderMapper.php
  project-base/storefront/components/Pages/OrderConfirmation/RegistrationAfterOrder.tsx
  project-base/storefront/pages/order-confirmation.tsx
  project-base/storefront/pages/order-payment-confirmation.tsx
  upgrade-notes/storefront_20250114_122253.md
Labels: Design & Appearance

#3641 admin improvements
  docs/administration/grid-data-sources.md
  packages/framework/src/Command/CreateDatabaseCommand.php
  packages/framework/src/Component/Grid/QueryBuilderDataSource.php
  packages/framework/src/Component/Grid/QueryBuilderWithRowManipulatorDataSource.php
  packages/framework/src/Component/Paginator/QueryPaginator.php
  packages/framework/src/Controller/Admin/CustomerController.php
  packages/framework/src/Controller/Admin/OrderController.php
  packages/framework/src/Controller/Admin/ProductController.php
  packages/framework/src/Controller/Admin/ProductPickerController.php
  packages/framework/src/Migrations/Version20241205144230.php
  packages/framework/src/Model/Order/OrderFacade.php
  packages/framework/src/Model/Order/OrderRepository.php
  packages/framework/src/Model/Product/Listing/ProductListAdminRepository.php
  packages/framework/src/Model/Product/ProductGridFactory.php
  packages/framework/src/Model/Product/ProductVisibilityFacade.php
  packages/framework/src/Model/Product/ProductVisibilityRepository.php
  packages/framework/src/Resources/views/Admin/Content/Product/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Content/ProductPicker/listGrid.html.twig
  packages/framework/src/Twig/ProductExtension.php
  packages/framework/tests/Unit/Model/Product/ProductVisibilityFacadeTest.php
  project-base/app/src/Controller/Admin/ProductController.php
  project-base/app/src/Model/Order/OrderFacade.php
  project-base/app/src/Model/Order/OrderRepository.php
  project-base/app/tests/App/Functional/Model/Product/ProductVisibilityFacadeTest.php
  upgrade-notes/backend_20241205_151830.md
Labels: Performance, DX & Refactoring

#3714 redesigned product detail tabs
  project-base/storefront/components/Basic/Icon/DownloadIcon.tsx
  project-base/storefront/components/Basic/Tabs/Tabs.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailTabs/ProductDetailTabs.tsx
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-1 product detail.png
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  upgrade-notes/storefront_20250106_081458.md
Labels: Design & Appearance

#3675 no log sentry error during maintenance on
  project-base/storefront/pages/_error.tsx
  project-base/storefront/urql/errorExchange.ts
  project-base/storefront/urql/fetcher.ts
  project-base/storefront/vitest/utils/urql/fetcher.test.ts
  upgrade-notes/storefront_20241217_094417.md
Labels: Bug, DX & Refactoring

#3747 github actions: review containers now has limited memory
  docker/conf/docker-compose.github-actions.review.simplified.yml.dist
  docker/conf/docker-compose.github-actions.review.yml.dist
Labels: Infrastructure

#3749 doctrine/doctrine-migrations-bundle v3.4.0 is now marked as conflicting
  composer.json
  packages/migrations/composer.json
Labels: Bug

#3739 updated complaints search inputs placeholders
  project-base/storefront/pages/customer/complaints.tsx
  project-base/storefront/pages/customer/new-complaint.tsx
  upgrade-notes/storefront_20250116_135301.md
Labels: Bug

#3740 added stores breadcrumbs skeleton loader
  project-base/storefront/pages/stores/[storeSlug].tsx
  project-base/storefront/types/friendlyUrl.ts
  upgrade-notes/storefront_20250116_140004.md
Labels: Bug

#3741 remove pagination title from first page
  project-base/storefront/components/Pages/BrandDetail/BrandDetailContent.tsx
  project-base/storefront/components/Pages/FlagDetail/FlagDetailContent.tsx
  project-base/storefront/config/constants.ts
  project-base/storefront/pages/blogCategories/[blogCategorySlug].tsx
  project-base/storefront/utils/seo/useSeoTitleWithPagination.ts
  upgrade-notes/storefront_20250116_143527.md
Labels: Bug

#3711 updated email templates
  ecs.php
  packages/framework/src/Form/Admin/Transport/TransportFormType.php
  packages/framework/src/Migrations/Version20241001113136.php
  packages/framework/src/Model/ContactForm/ContactFormFacade.php
  packages/framework/src/Model/Mail/MailTemplateBuilder.php
  packages/framework/src/Model/Mail/MailTemplateConfiguration.php
  packages/framework/src/Model/Order/Mail/OrderMail.php
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Resources/translations/dataFixtures.cs.po
  packages/framework/src/Resources/translations/dataFixtures.en.po
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Mail/Order/addresses.html.twig
  packages/framework/src/Resources/views/Mail/Order/billingAddress.html.twig
  packages/framework/src/Resources/views/Mail/Order/deliveryAddress.html.twig
  packages/framework/src/Resources/views/Mail/Order/note.html.twig
  packages/framework/src/Resources/views/Mail/Order/paymentInfo.html.twig
  packages/framework/src/Resources/views/Mail/Order/paymentInstructions.html.twig
  packages/framework/src/Resources/views/Mail/Order/products.html.twig
  packages/framework/src/Resources/views/Mail/Order/roundingInfo.html.twig
  packages/framework/src/Resources/views/Mail/Order/transportInfo.html.twig
  packages/framework/src/Resources/views/Mail/Order/transportInstructions.html.twig
  packages/framework/src/Twig/MailTemplateExtension.php
  project-base/app/assets/public/frontend/mail/billing-address.png
  project-base/app/assets/public/frontend/mail/delivery-address.png
  project-base/app/ecs-skip-rules.php
  project-base/app/src/DataFixtures/Demo/CompanyOrderDataFixture.php
  project-base/app/src/DataFixtures/Demo/MailTemplateDataFixture.php
  project-base/app/src/DataFixtures/Demo/OrderDataFixture.php
  project-base/app/src/DataFixtures/Demo/PromoCodeDataFixture.php
  project-base/app/src/Model/Order/Mail/OrderMail.php
  project-base/app/tests/App/Functional/Model/Order/Mail/OrderMailTest.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/CustomerUserOwnerTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  upgrade-notes/backend_20250107_121242.md
Labels: Design & Appearance

#3757 close db and redis connections when worker is in idle state
  packages/framework/src/Component/Messenger/CloseIdleConnectionSubscriber.php
  packages/framework/src/Component/Redis/RedisFacade.php
  packages/framework/tests/Unit/Component/Messenger/CloseIdleConnectionSubscriberTest.php
Labels: Performance, Queue

#3687 NoDomainSelectedException is no longer throwed during maintenance page + additional Sentry context
  packages/framework/src/Command/MaintenanceModeCommand.php
  packages/framework/src/Component/AddSentryContextSubscriber.php
  packages/framework/src/Component/Collector/ShopsysFrameworkDataCollector.php
  packages/framework/src/Component/Domain/DomainSubscriber.php
  packages/framework/src/Component/Maintenance/MaintenanceModeFacade.php
  packages/framework/src/Component/Maintenance/MaintenanceModeSubscriber.php
Labels: DX & Refactoring

#3744 set footer to stick to bottom
  project-base/storefront/components/Layout/CommonLayout.tsx
  project-base/storefront/components/Layout/ErrorLayout.tsx
  project-base/storefront/components/Pages/App/AppPageContent.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-0 filled registration form.png
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-1 customer edit page.png
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-2 after invalid try.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-0 cart page after login.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-1 cart page after adding product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-2 cart page after adding product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-3 cart page after adding product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-4 cart page after adding second product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-5 cart page after second login.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-6 cart page after first login.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-0 after increase.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-1 after decrease.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-10 after applying promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-11 after removing product that allows promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-12 cart page with non-free transport after applying promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-2 after increase.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-3 after decrease.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-4 after first removal.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-5 empty cart after second removal.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-6 cart page after applying first promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-8 cart page after removing first promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-9 cart page after removing second promocode.png
  project-base/storefront/cypress/snapshots/e2e/matrix/matrixTest.cy.ts/0-0-0 matrix page.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/3-1-6 customer edit page.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-0 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-1 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-2 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-3 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-4 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-5 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/4-2-8 cart page with enough products.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-0 homepage.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-1 product detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-3 stores page.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-4 blog article detail.png
  upgrade-notes/storefront_20250116_180334.md
Labels: Design & Appearance
