Repository shopsys/shopsys, pull requests merged in 2025-08, with the labels that each got.

#4057 added ability to easily add new item to OrderData that will be persisted after OrderFacade::edit
  packages/framework/src/Model/Order/OrderData.php
  project-base/app/tests/App/Functional/Model/Order/OrderFacadeEditTest.php
  upgrade-notes/backend_20250625_161205.md
Labels: DX & Refactoring

#4128 admin: enhance "Email allowed recipients" page
  packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/MailAllowedRecipient/list.html.twig
Labels: Design & Appearance

#4124 refactor administrator login as user
  packages/framework/src/Controller/Admin/CustomerController.php
  packages/framework/src/Controller/Admin/LoginController.php
  packages/framework/src/Migrations/Version20250722131817.php
  packages/framework/src/Model/Administrator/Administrator.php
  packages/framework/src/Model/Administrator/AdministratorRepository.php
  packages/framework/src/Model/Security/AdministratorLoginFacade.php
  packages/framework/src/Model/Security/LoginAdministratorAsUserUrlProvider.php
  packages/framework/src/Model/Security/LoginListener.php
  packages/framework/src/Model/Security/UniqueLoginInterface.php
  packages/framework/src/Resources/views/Admin/Content/Customer/User/edit.html.twig
  packages/framework/src/Resources/views/Admin/Content/Customer/edit.html.twig
  packages/framework/src/Resources/views/Admin/Content/Customer/loginAsUserLinkMacro.html.twig
  packages/framework/src/Resources/views/Admin/Form/customerUserListFields.html.twig
  packages/framework/src/Twig/CustomerExtensionTwig.php
  packages/frontend-api/src/Controller/Admin/CustomerUserController.php
  packages/frontend-api/src/Controller/SocialNetworkController.php
  packages/frontend-api/src/Migrations/Version20250730125606.php
  packages/frontend-api/src/Model/Mutation/Login/LoginMutation.php
  packages/frontend-api/src/Model/Security/DeleteExpiredExchangeTokensCronModule.php
  packages/frontend-api/src/Model/Security/LoginAdministratorAsUserUrlProvider.php
  packages/frontend-api/src/Model/Security/LoginAsUserExchangeToken.php
  packages/frontend-api/src/Model/Security/LoginAsUserExchangeTokenFacade.php
  packages/frontend-api/src/Model/Security/LoginAsUserExchangeTokenFactory.php
  packages/frontend-api/src/Model/Security/LoginAsUserExchangeTokenRepository.php
  packages/frontend-api/src/Model/Security/LoginAsUserFacade.php
  packages/frontend-api/src/Model/Token/TokenFacade.php
  packages/frontend-api/src/Resources/config/graphql-types/Mutation/MutationDecorator.types.yaml
  packages/frontend-api/src/Resources/views/SocialLogin/loginAsCustomerUser.html.twig
  project-base/app/config/cron.yaml
  project-base/app/schema.graphql
  project-base/app/src/Model/Administrator/AdministratorRepository.php
  project-base/app/tests/App/Functional/Model/Administrator/AdministratorRepositoryTest.php
  project-base/app/tests/App/Smoke/Http/RouteConfigCustomization.php
  project-base/app/tests/FrontendApiBundle/Functional/Login/LoginViaExchangeTokenTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Login/graphql/LoginViaExchangeTokenMutation.graphql
  project-base/storefront/components/Pages/HomePage/ExchangeTokenHandler.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/auth/mutations/LoginViaExchangeTokenMutation.generated.tsx
  project-base/storefront/graphql/requests/auth/mutations/LoginViaExchangeTokenMutation.graphql
  project-base/storefront/graphql/types.ts
  project-base/storefront/pages/index.tsx
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/utils/auth/useLoginViaExchangeToken.tsx
  upgrade-notes/backend_20250801_120040.md
  upgrade-notes/storefront_20250801_120040.md
Labels: Security, DX & Refactoring

#4150 codeception acceptance tests now use pg_restore to dump DB from sql file
  .gitignore
  packages/framework/build.xml
  packages/framework/src/Command/DatabaseDumpCommand.php
  packages/framework/src/Component/Doctrine/DatabaseConnectionCredentialsProvider.php
  project-base/app/tests/App/Acceptance/acceptance.suite.yml
  project-base/app/tests/App/Test/Codeception/Helper/DatabaseHelper.php
  upgrade-notes/backend_20250821_104722.md
  var/cache/.gitkeep
Labels: Bug, DX & Refactoring

#4129 fix product videos association updates
  packages/framework/src/Model/Product/ProductDataFactory.php
  packages/framework/src/Model/ProductVideo/ProductVideoFacade.php
Labels: Bug, DX & Refactoring

#4151 fixed recalculation of deleted regular product
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationFacade.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationRepository.php
  project-base/app/tests/App/Functional/Model/Product/Recalculation/ProductRecalculationRepositoryTest.php
  upgrade-notes/backend_20250821_130824.md
Labels: Bug

#4148 updated gitlab cypress screenshots
  project-base/.gitlab-ci.yml
  project-base/gitlab/docker-compose-ci.yml
  upgrade-notes/storefront_20250819_093922.md
Labels: Enhancement
