Repository shopsys/shopsys, pull requests merged in 2025-02, with the labels that each got.

#3763 elasticsearch on local now has limited resources to prevent excessive memory usage
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose.yml.dist
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
  upgrade-notes/backend_20250129_154324.md
Labels: Infrastructure

#3781 fixed yaml standards checking
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/config/services_test.yaml
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/app/config/packages/overblog_dataloader.yaml
  project-base/app/config/packages/scheb_2fa.yaml
  project-base/app/config/packages/twig.yaml
  project-base/app/yaml-standards.yaml
  upgrade-notes/backend_20250207_095355.md
  yaml-standards.yaml
Labels: Bug

#3775 added margin to info message on comparison page
  project-base/storefront/components/Pages/ProductComparison/ProductComparison.tsx
  upgrade-notes/storefront_20250203_141351.md
Labels: Design & Appearance

#3779 updated email templates for outlook classic
  packages/framework/src/Model/Mail/MailTemplateBuilder.php
  packages/framework/src/Resources/views/Mail/Order/addresses.html.twig
  packages/framework/src/Resources/views/Mail/Order/billingAddress.html.twig
  packages/framework/src/Resources/views/Mail/Order/deliveryAddress.html.twig
  packages/framework/src/Resources/views/Mail/Order/products.html.twig
  upgrade-notes/backend_20250206_084222.md
Labels: Bug

#3777 administrator now can upload files without ROLE_FILES_FULL that is used for separate administration section
  project-base/app/config/packages/security.yaml
  upgrade-notes/backend_20250204_132803.md
Labels: Bug

#3784 manual complaint creation (without order)
  packages/framework/src/Form/Admin/Complaint/ComplaintFormType.php
  packages/framework/src/Form/DisplayOnlyOrderType.php
  packages/framework/src/Migrations/Version20250208081702.php
  packages/framework/src/Migrations/Version20250209123001.php
  packages/framework/src/Model/AdvancedSearchComplaint/AdvancedSearchComplaintFacade.php
  packages/framework/src/Model/Complaint/Complaint.php
  packages/framework/src/Model/Complaint/ComplaintData.php
  packages/framework/src/Model/Complaint/ComplaintDataFactory.php
  packages/framework/src/Model/Complaint/ComplaintItem.php
  packages/framework/src/Model/Complaint/ComplaintRepository.php
  packages/framework/src/Model/Complaint/Mail/ComplaintMail.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Complaint/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Form/displayOnlyOrder.html.twig
  packages/frontend-api/src/Model/Complaint/ComplaintApiFacade.php
  packages/frontend-api/src/Model/Complaint/ComplaintDataApiFactory.php
  packages/frontend-api/src/Model/Complaint/ComplaintItemDataApiFactory.php
  packages/frontend-api/src/Model/Mutation/Complaint/CreateComplaintMutation.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Complaint/ComplaintDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Complaint/ComplaintItemDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Complaint/Input/ComplaintInputDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Complaint/Input/ComplaintItemInputDecorator.types.yaml
  packages/frontend-api/src/Resources/translations/validators.cs.po
  packages/frontend-api/src/Resources/translations/validators.en.po
  packages/frontend-api/src/Voter/CreateComplaintVoter.php
  project-base/app/ecs-skip-rules.php
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/ComplaintDataFixture.php
  project-base/app/src/DataFixtures/Demo/Helper/ComplaintHelper.php
  project-base/app/tests/FrontendApiBundle/Functional/Complaint/CreateComplaintTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Complaint/graphql/CreateComplaintMutation.graphql
  project-base/storefront/components/Blocks/Complaint/CreateComplaintPopupButton.tsx
  project-base/storefront/components/Blocks/Popup/CreateComplaintPopup.tsx
  project-base/storefront/components/Forms/validationConstants.ts
  project-base/storefront/components/Forms/validationRules.ts
  project-base/storefront/components/Pages/Customer/ComplaintDetail/ComplaintDetailBasicInfo.tsx
  project-base/storefront/components/Pages/Customer/ComplaintDetail/ComplaintDetailComplaintItem.tsx
  project-base/storefront/components/Pages/Customer/Complaints/ComplaintItem.tsx
  project-base/storefront/components/Pages/Customer/Complaints/complaintFormMeta.ts
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailOrderItem.tsx
  project-base/storefront/cypress/tids.ts
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintDetailFragment.graphql
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintItemFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintItemFragment.graphql
  project-base/storefront/graphql/requests/complaints/fragments/CreateComplaintFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/mutations/CreateComplaintMutation.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintsQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/pages/customer/complaints.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/types/form.ts
  upgrade-notes/backend_20250209_122624.md
  upgrade-notes/storefront_20250209_122624.md
Labels: Enhancement

#3776 renamed contact page to contact-form page
  project-base/app/src/DataFixtures/Demo/ArticleDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Article/GetArticlesTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/storefront/components/Layout/Footer/FooterPlaceholder.tsx
  project-base/storefront/config/staticRewritePaths.ts
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-0 filled registration form.png
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-1 customer edit page.png
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-2 after invalid try.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-0 cart page after login.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-1 cart page after adding product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-2 cart page after adding product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-3 cart page after adding product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-4 cart page after adding second product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-5 cart page after second login.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-6 cart page after first login.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-0 after increase.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-1 after decrease.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-10 after applying promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-11 after removing product that allows promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-12 cart page with non-free transport after applying promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-2 after increase.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-3 after decrease.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-4 after first removal.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-5 empty cart after second removal.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-6 cart page after applying first promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-8 cart page after removing first promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-9 cart page after removing second promocode.png
  project-base/storefront/cypress/snapshots/e2e/matrix/matrixTest.cy.ts/0-0-0 matrix page.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/3-1-6 customer edit page.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-0 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-1 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-2 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-3 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-4 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-5 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/4-2-8 cart page with enough products.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-0 homepage.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-1 product detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-3 stores page.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-4 blog article detail.png
  project-base/storefront/pages/contact-form.tsx
  upgrade-notes/backend_20250210_073925.md
  upgrade-notes/storefront_20250203_142238.md
Labels: Bug

#3786 fixed url param value with slash
  project-base/storefront/pages/articles/[articleSlug].tsx
  project-base/storefront/pages/blogArticles/[blogArticleSlug].tsx
  project-base/storefront/pages/blogCategories/[blogCategorySlug].tsx
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/flags/[flagSlug].tsx
  project-base/storefront/pages/products/[productSlug].tsx
  project-base/storefront/pages/search.tsx
  project-base/storefront/pages/stores/[storeSlug].tsx
  project-base/storefront/utils/parsing/getSlugFromServerSideUrl.ts
  upgrade-notes/storefront_20250210_072816.md
Labels: Bug

#3782 fix price filtering for products with special prices
  packages/framework/src/Form/Admin/PriceList/PriceListFormType.php
  packages/framework/src/Form/Transformers/CategoriesIdsToCategoriesTransformer.php
  packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
  packages/framework/src/Model/Product/Search/FilterQuery.php
  project-base/app/src/Model/Product/Elasticsearch/ProductExportRepository.php
  project-base/app/src/Resources/definition/product/1.json
  project-base/app/src/Resources/definition/product/2.json
  project-base/app/tests/App/Functional/Model/Product/Search/FilterQueryTest.php
  upgrade-notes/backend_20250207_111605.md
Labels: Bug

#3669 added deduplication for product messages in the queue, including scopes
  docs/asynchronous-processing/product-recalculations.md
  docs/model/navigation.yml
  packages/framework/src/Command/DispatchRecalculationMessageCommand.php
  packages/framework/src/Model/Product/ProductFacade.php
  packages/framework/src/Model/Product/ProductRepository.php
  packages/framework/src/Model/Product/Recalculation/AbstractProductRecalculationMessage.php
  packages/framework/src/Model/Product/Recalculation/DispatchAllProductsMessageHandler.php
  packages/framework/src/Model/Product/Recalculation/DispatchProductIdsBatchMessage.php
  packages/framework/src/Model/Product/Recalculation/DispatchProductIdsBatchMessageHandler.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationDeduplicationFacade.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcher.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationDispatcherExecutor.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationFacade.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationMessageHandler.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationRepository.php
  packages/framework/src/Resources/config/services.yaml
  phpstan.neon
  project-base/app/config/packages/messenger.yaml
  project-base/app/config/packages/snc_redis.yaml
  project-base/app/config/services.yaml
  project-base/app/phpstan.neon
  project-base/app/tests/App/Functional/Component/Redis/RedisFacadeTest.php
  project-base/app/tests/App/Functional/Model/Product/ProductVisibilityFacadeTest.php
  project-base/app/tests/App/Functional/Model/Product/Recalculation/ProductRecalculationDeduplicationFacadeTest.php
  project-base/app/tests/App/Functional/Model/Product/Recalculation/ProductRecalculationRepositoryTest.php
  project-base/app/tests/App/Test/WebTestCase.php
  upgrade-notes/backend_20250206_212223.md
Labels: Enhancement

#3787 added missing translations for collapsible component
  project-base/storefront/components/Basic/CollapsibleText/CollapsibleText.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  upgrade-notes/storefront_20250211_123400.md
Labels: Bug

#3774 redesigned order confirmation
  packages/framework/src/Resources/views/Mail/Order/billingAddress.html.twig
  packages/framework/src/Resources/views/Mail/Order/deliveryAddress.html.twig
  project-base/app/assets/public/frontend/mail/billing-address.png
  project-base/app/assets/public/frontend/mail/delivery-address.png
  project-base/storefront/components/Basic/Icon/BoxPackageHandIcon.tsx
  project-base/storefront/components/Basic/Icon/CheckboxCheckedIcon.tsx
  project-base/storefront/components/Basic/Icon/PackageDeliveredIcon.tsx
  project-base/storefront/components/Basic/Icon/ThumbUp.tsx
  project-base/storefront/components/Basic/Icon/TruckClockIcon.tsx
  project-base/storefront/components/Basic/Icon/UserProfileCardsIcon.tsx
  project-base/storefront/components/Basic/Icon/WalletIcon.tsx
  project-base/storefront/components/Basic/Icon/WarehouseBoxPackageIcon.tsx
  project-base/storefront/components/Basic/Icon/WatchdogIcon.tsx
  project-base/storefront/components/Basic/InformationCard/InformationCard.tsx
  project-base/storefront/components/Blocks/ConfirmationPage/ConfirmationPageContent.tsx
  project-base/storefront/components/Blocks/OrderCustomerInfo/OrderCustomerInfo.tsx
  project-base/storefront/components/Blocks/OrderItemDiscountCard/OrderItemDiscountCard.tsx
  project-base/storefront/components/Blocks/OrderItemProductCard/OrderItemProductCard.tsx
  project-base/storefront/components/Blocks/OrderItemProductCard/OrderItemProductPrice.tsx
  project-base/storefront/components/Blocks/Product/Watchdog/WatchDogButton.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageConfirmation.tsx
  project-base/storefront/components/Pages/Contact/contactFormMeta.tsx
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailContent.tsx
  project-base/storefront/components/Pages/Order/PaymentConfirmation/PaymentFail.tsx
  project-base/storefront/components/Pages/Order/PaymentConfirmation/PaymentStatus.tsx
  project-base/storefront/components/Pages/Order/PaymentConfirmation/PaymentSuccess.tsx
  project-base/storefront/components/Pages/OrderConfirmation/OrderConfirmationProducts.tsx
  project-base/storefront/components/Pages/OrderConfirmation/OrderConfirmationStep.tsx
  project-base/storefront/components/Pages/OrderConfirmation/OrderConfirmationStepper.tsx
  project-base/storefront/components/Pages/OrderConfirmation/OrderConfirmationStepperFlows.ts
  project-base/storefront/components/Pages/OrderConfirmation/OrderConfirmationSummary.tsx
  project-base/storefront/components/Pages/OrderConfirmation/RegistrationAfterOrder.tsx
  project-base/storefront/components/Pages/OrderConfirmation/registrationAfterOrderFormMeta.tsx
  project-base/storefront/components/PaymentsInOrderSelect/PaymentsInOrderSelect.tsx
  project-base/storefront/cypress/e2e/order/createOrder.cy.ts
  project-base/storefront/cypress/e2e/order/orderSupport.ts
  project-base/storefront/cypress/fixtures/demodata.ts
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/ComplaintItemFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/fragments/CreateComplaintFragment.generated.tsx
  project-base/storefront/graphql/requests/complaints/mutations/CreateComplaintMutation.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintsQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/OrderedItemsQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/SearchOrderedItemsQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailItemFragment.generated.tsx
  project-base/storefront/graphql/requests/orders/fragments/OrderDetailItemFragment.graphql
  project-base/storefront/graphql/requests/orders/queries/OrderDetailByHashOrUuidQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrderDetailByHashOrUuidQuery.graphql
  project-base/storefront/graphql/requests/orders/queries/OrderDetailByHashQuery.generated.tsx
  project-base/storefront/graphql/requests/orders/queries/OrderDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/personalData/queries/PersonalDataDetailQuery.generated.tsx
  project-base/storefront/pages/order-confirmation.tsx
  project-base/storefront/pages/order-payment-confirmation.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/types/form.ts
  upgrade-notes/storefront_20250203_135805.md
Labels: Design & Appearance

#3802 framework: add missing symfony/validator dependency
  packages/framework/composer.json
Labels: Bug

#3806 conflicted codeception/codeception 5.2.0
  composer.json
  project-base/app/composer.json
  upgrade-notes/backend_20250217_102248.md
Labels: dependencies

#3793 added overflow scroll to product availability popup
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  upgrade-notes/storefront_20250213_095405.md
Labels: Bug

#3799 fix complaint detail
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageConfirmation.tsx
  project-base/storefront/components/Pages/Customer/ComplaintDetail/ComplaintDetailContent.tsx
  project-base/storefront/components/Pages/Customer/ComplaintDetail/ComplaintDetailCustomerInfo.tsx
  project-base/storefront/components/Pages/Customer/Complaints/ComplaintItem.tsx
  project-base/storefront/components/Pages/Customer/Complaints/ComplaintsContent.tsx
  project-base/storefront/pages/customer/complaints.tsx
  upgrade-notes/storefront_20250214_070837.md
Labels: Bug

#3794 fixed mobile banner slide
  project-base/storefront/components/Blocks/Banners/BannersSlider.tsx
  upgrade-notes/storefront_20250213_102040.md
Labels: Bug

#3792 Fixed all tests to work also with CZK currency and Czech language
  .github/get-build-exit-code.sh
  .github/workflows/docker-build.yaml
  project-base/app/ecs-skip-rules.php
  project-base/app/src/DataFixtures/Demo/ProductDataFixture.php
  project-base/app/src/DataFixtures/Demo/SettingValueDataFixture.php
  project-base/app/tests/App/Functional/Component/EntityLog/EntityLogTest.php
  project-base/app/tests/App/Functional/Model/Product/Availability/ProductAvailabilityFacadeTest.php
  project-base/app/tests/App/Functional/Model/Transport/TransportPriceCalculationTest.php
  project-base/app/tests/App/Functional/PersonalData/PersonalDataExportXmlTest.php
  project-base/app/tests/App/Functional/PersonalData/Resources/test.xml
  project-base/app/tests/App/Functional/Twig/PriceExtensionTest.php
  project-base/app/tests/App/Functional/Twig/Resources/picture.twig
  project-base/app/tests/FrontendApiBundle/Functional/Advert/GetAdvertsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/AddOrderItemsToCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/PriceWithoutDiscountTransportAndPaymentTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/RemainingToFreeTransportCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/RetrieveCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Cart/RoundingPriceInCartTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Order/DeliveryFieldsValidationTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/Flag/FlagTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/MultipleProductsQueryTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductVariantTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringOptionsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/graphql/multipleProductsQuery.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Settings/HeurekaEnabledSettingTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Settings/MainBlogCategoryDataSettingsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/query/TotalPriceWithoutDiscountPaymentAndTransportQuery.graphql
  project-base/app/tests/FrontendApiBundle/Test/GraphQlTestCase.php
  project-base/app/translations/tests.cs.po
  project-base/app/translations/tests.en.po
  upgrade-notes/backend_20250214_100948.md
Labels: Bug

#3800 gitlab security check is now dependent on build of storefront
  project-base/.gitlab-ci.yml
  upgrade-notes/backend_20250214_103903.md
Labels: Bug

#3801 removed no longer necessary command for migrating images to new proxy structure
  packages/framework/build.xml
  packages/framework/src/Command/MigrateImagesCommand.php
  packages/framework/src/Component/Setting/Setting.php
  packages/framework/src/Migrations/Version20250214133657.php
  packages/framework/src/Resources/config/services/commands.yaml
  project-base/app/src/DataFixtures/Demo/SettingValueDataFixture.php
  upgrade-notes/backend_20250214_123809.md
Labels: DX & Refactoring

#3812 administration bundle now uses new bundle directory structure
  packages/administration/config/routing.yaml
  packages/administration/config/services.yaml
  packages/administration/src/DependencyInjection/.gitkeep
  packages/administration/src/DependencyInjection/ShopsysAdministrationExtension.php
  packages/administration/src/Resources/config/services.yaml
  packages/administration/src/ShopsysAdministrationBundle.php
  packages/administration/templates/.gitkeep
  project-base/app/config/routes/shopsys_framework.yaml
  upgrade-notes/backend_20250219_070137.md
Labels: DX & Refactoring

#3788 ROLE_API_CUSTOMER_SELF_MANAGE tweaks
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Customer/DeliveryAddress/DeliveryAddressMutationDecorator.types.yaml
  packages/frontend-api/src/Resources/config/graphql-types/Mutation/MutationDecorator.types.yaml
  packages/frontend-api/src/Voter/CustomerUserVoter.php
  project-base/app/src/DataFixtures/Demo/CustomerUserRoleGroupDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/DeleteDeliveryAddressTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/User/CurrentCustomerUserTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Customer/User/graphql/ChangePersonalAndCompanyDataMutation.graphql
  project-base/app/tests/FrontendApiBundle/Functional/_graphql/mutation/DeleteDeliveryAddressMutation.graphql
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/CustomerUserCatalogUserTest.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/CustomerUserOwnerTest.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/CustomerUserSelfManageTest.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/CustomerUser/Helper/ChangePersonalAndCompanyDataInputProvider.php
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/ChangeCompanyDataMutation.graphql
  project-base/app/tests/FrontendApiBundle/FunctionalB2b/_graphql/ChangePersonalDataMutation.graphql
  project-base/storefront/components/Blocks/Popup/ManageCustomerUserPopup.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItem.tsx
  project-base/storefront/components/Blocks/SortingBar/SortingBar.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemUserAuthenticatedContent.tsx
  project-base/storefront/components/Pages/Cart/CartPreview.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryBestsellers/CategoryBestsellersListItem.tsx
  project-base/storefront/components/Pages/Customer/CustomerContent.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/AddressList.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/BillingAddress.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/CompanyCustomer.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/DeliveryAddress.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/EditProfileContent.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/PersonalData.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationAddress.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationDeliveryAddress.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationSendOrderButton.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/contactInformationUtils.ts
  project-base/storefront/components/Pages/ProductComparison/ProductComparisonHeadItem.tsx
  project-base/storefront/components/providers/AuthorizationProvider.tsx
  project-base/storefront/connectors/customer/CurrentCustomer.ts
  project-base/storefront/gtm/utils/pageViewEvents/productList/useGtmPaginatedProductListViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/productList/useGtmSliderProductListViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmCartViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmContactInformationPageViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmPaymentAndTransportPageViewEvent.ts
  project-base/storefront/gtm/utils/pageViewEvents/useGtmProductDetailViewEvent.ts
  project-base/storefront/pages/customer/edit-profile.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  project-base/storefront/types/customer.ts
  project-base/storefront/utils/cart/useAddToCart.ts
  project-base/storefront/utils/cart/useChangePaymentInCart.ts
  project-base/storefront/utils/cart/useChangeTransportInCart.ts
  project-base/storefront/utils/cart/useRemoveFromCart.ts
  project-base/storefront/utils/user/useUserMenuItems.ts
  project-base/storefront/utils/user/useUserProfileSectionLabel.ts
  upgrade-notes/backend_20250214_171357.md
  upgrade-notes/storefront_20250214_171357.md
Labels: Bug, DX & Refactoring

#3810 fixed editing of unused friendly urls
  packages/framework/src/Component/Grid/Grid.php
Labels: Bug

#3817 fixed gitlab check for commited icons
  project-base/.gitlab-ci.yml
  upgrade-notes/backend_20250131_220504.md
Labels: Bug

#3819 fixed psr-4 compliance
  packages/framework/src/Component/UploadedFile/Config/Exception/DuplicateEntityNameException.php
  packages/framework/src/Model/CategorySeo/Exception/SelectedCategorySeoMixCombinationIsNotValidException.php
Labels: Bug

#3795 added smoth scroll to error fields in complaint form popup
  project-base/storefront/components/Blocks/Popup/CreateComplaintPopup.tsx
  project-base/storefront/components/Blocks/Popup/DeliveryAddressPopup.tsx
  project-base/storefront/components/Blocks/Popup/ErrorPopup.tsx
  project-base/storefront/components/Blocks/Popup/InquiryPopup.tsx
  project-base/storefront/components/Blocks/Popup/ManageCustomerUserPopup.tsx
  project-base/storefront/components/Blocks/Popup/WatchdogPopup.tsx
  project-base/storefront/components/Pages/Customer/EditProfile/EditProfileContent.tsx
  project-base/storefront/components/Pages/Registration/RegistrationContent.tsx
  project-base/storefront/components/Pages/ResetPassword/ResetPasswordContent.tsx
  project-base/storefront/utils/forms/useScrollToFirstError.ts
  upgrade-notes/storefront_20250213_110953.md
Labels: Bug

#3811 shopsys:domains-urls:replace now also marks appropriate entities for export to Elasticsearch
  docs/cookbook/create-asynchronous-notifier.md
  docs/model/elasticsearch.md
  packages/framework/build.xml
  packages/framework/src/Command/ReplaceDomainsUrlsCommand.php
  packages/framework/src/Component/Elasticsearch/AbstractExportScheduler.php
  packages/framework/src/Migrations/MultidomainMigrationTrait.php
  packages/framework/src/Migrations/Version20160129122637.php
  packages/framework/src/Model/Article/ArticleFacade.php
  packages/framework/src/Model/Article/ArticleRepository.php
  packages/framework/src/Model/Article/Elasticsearch/ArticleExportRepository.php
  packages/framework/src/Model/Article/Elasticsearch/ArticleExportScheduler.php
  packages/framework/src/Model/Article/Elasticsearch/ArticleExportSubscriber.php
  packages/framework/src/Model/Article/Messenger/ArticleExportMessage.php
  packages/framework/src/Model/Article/Messenger/ArticleExportMessageDispatcher.php
  packages/framework/src/Model/Article/Messenger/ArticleExportMessageHandler.php
  packages/framework/src/Model/Blog/Article/Elasticsearch/BlogArticleExportRepository.php
  packages/framework/src/Model/Product/Brand/BrandCachedFacade.php
  packages/framework/src/Model/Product/Elasticsearch/ProductExportRepository.php
  packages/framework/src/Model/Product/Elasticsearch/Scope/ProductExportFieldProvider.php
  packages/framework/src/Model/Product/Elasticsearch/Scope/ProductExportScopeConfig.php
  packages/framework/src/Model/Product/Search/ProductElasticsearchConverter.php
  packages/framework/src/Model/Seo/HreflangLink.php
  packages/framework/src/Model/Seo/HreflangLinksFacade.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/tests/Unit/Model/Product/Search/ProductElasticsearchConverterTest.php
  packages/frontend-api/src/Model/Blog/Article/BlogArticleResolverMap.php
  packages/frontend-api/src/Model/Resolver/Products/DataMapper/ProductArrayFieldMapper.php
  packages/frontend-api/src/Model/Resolver/Products/DataMapper/ProductEntityFieldMapper.php
  project-base/app/config/packages/messenger.yaml
  project-base/app/deploy/deploy-project.sh
  project-base/app/docker/php-fpm/consumer-entrypoint.sh
  project-base/app/src/FrontendApi/Resolver/Products/DataMapper/ProductArrayFieldMapper.php
  project-base/app/src/FrontendApi/Resolver/Products/DataMapper/ProductEntityFieldMapper.php
  project-base/app/src/Model/Product/Elasticsearch/ProductExportRepository.php
  project-base/app/src/Model/Product/Elasticsearch/Scope/ProductExportFieldProvider.php
  project-base/app/src/Model/Product/Search/ProductElasticsearchConverter.php
  project-base/app/src/Resources/definition/product/1.json
  project-base/app/src/Resources/definition/product/2.json
  project-base/app/tests/App/Functional/Model/Product/Elasticsearch/ProductExportRepositoryTest.php
  upgrade-notes/backend_20250220_144154.md
Labels: DX & Refactoring

#3821 updated responsive filters based on figma design
  project-base/storefront/components/Blocks/Product/Filter/FilterElements.tsx
  project-base/storefront/components/Blocks/Product/Filter/FilterPanel.tsx
  project-base/storefront/components/Blocks/UserNavigation/UserNavigation.tsx
  project-base/storefront/components/Forms/Button/Button.tsx
  project-base/storefront/components/Forms/Spinbox/Spinbox.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailAddToCart/ProductDetailAddToCart.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideButtons.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-1 customer edit page.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/2-0-0 after first remove.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-0 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-2 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-5 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/3-1-0 filled contact information form.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/3-1-6 customer edit page.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-1 product detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  upgrade-notes/storefront_20250224_085833.md
Labels: Bug

#3815 improve npm asset linking
  .github/workflows/docker-build.yaml
  .gitignore
  build.xml
  composer.json
  docs/frontend/npm-and-webpack.md
  node_modules
  package-lock.json
  package.json
  packages/framework/assets/.eslintrc.json
  packages/framework/assets/package.json
  packages/framework/build.xml
  packages/frontend-api/build.xml
  project-base/app/.eslintignore
  project-base/app/assets/js/bin/helpers/sources.js
  project-base/app/composer.json
  project-base/app/package.json
  project-base/app/webpack.config.js
  upgrade-notes/_layout.md
  upgrade-notes/backend_20250226_145543.md
  utils/link-packages.js
  utils/releaser/config/release-candidate.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ReleaseNewNodeModulePackageVersion.php
Labels: DX & Refactoring
