Repository shopsys/shopsys, pull requests merged in 2025-05, with the labels that each got.

#3960 transport prices are now copied to newly created domain
  packages/framework/src/Model/MultidomainEntityClassProvider.php
Labels: Bug

#3954 changed pagination scroll location
  project-base/storefront/components/Blocks/FilteredProductsWrapper/FilteredProductsWrapper.tsx
  project-base/storefront/components/Blocks/Pagination/Pagination.tsx
  project-base/storefront/components/Blocks/SortingBar/DeferredFilterAndSortingBar.tsx
  project-base/storefront/components/Pages/BrandDetail/BrandDetailContent.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
  project-base/storefront/components/Pages/FlagDetail/FlagDetailContent.tsx
  project-base/storefront/components/Pages/Search/SearchProducts.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-0 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-5 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  upgrade-notes/storefront_20250429_085607.md
Labels: Design & Appearance

#3967 bump codeception versions
  composer.json
  project-base/app/composer.json
  upgrade-notes/backend_20250507_113220.md
Labels: Bug

#3956 added input type numeric to postcode
  project-base/storefront/components/Blocks/Popup/CreateComplaintPopup.tsx
  project-base/storefront/components/Blocks/Popup/DeliveryAddressPopup.tsx
  project-base/storefront/components/Forms/TextInput/TextInput.tsx
  project-base/storefront/components/Forms/TextInput/TextInputControlled.tsx
  project-base/storefront/components/Forms/validationRules.ts
  project-base/storefront/components/Pages/Customer/EditProfile/BillingAddress.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationAddress.tsx
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationDeliveryAddress.tsx
  project-base/storefront/components/Pages/Registration/RegistrationAddress.tsx
  upgrade-notes/storefront_20250429_114958.md
Labels: Design & Appearance

#3957 fixed long banner button name
  project-base/storefront/components/Blocks/Banners/BannersDot.tsx
  upgrade-notes/storefront_20250429_122139.md
Labels: Bug

#3964 yaml standards: ignore kubernetes config files
  project-base/app/yaml-standards.yaml
  upgrade-notes/backend_20250505_150355.md
Labels: coding standards

#3961 ProductVisibilityFacadeTest is now resistant to added domain without loaded data
  project-base/app/tests/App/Functional/Model/Product/ProductVisibilityFacadeTest.php
  upgrade-notes/backend_20250505_095008.md
Labels: Enhancement

#3965 flag demo data are now created in data fixtures
  packages/framework/src/Migrations/Version20250506081245.php
  project-base/app/src/DataFixtures/Demo/FlagDataFixture.php
  project-base/app/src/Migrations/Version20200221155940.php
  project-base/app/src/Migrations/Version20200714071640.php
  project-base/app/src/Migrations/Version20240702065648.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/Flag/FlagTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/Flag/FlagsTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  upgrade-notes/backend_20250506_082515.md
Labels: DX & Refactoring

#3969 UX icons are now imported within standards-fix(-diff) phing targets
  Makefile
  packages/framework/build.xml
  project-base/Makefile
  upgrade-notes/backend_20250508_134446.md
Labels: DX & Refactoring, coding standards

#3966 little environment cleanup
  composer.json
  packages/framework/build.xml
  project-base/app/composer.json
  upgrade-notes/backend_20250507_095412.md
Labels: DX & Refactoring, dependencies

#3979 updated order of created data fixtures of price lists to ensure correct working of testProperSpecialPriceIsReturnedForMultipleLists
  project-base/app/src/DataFixtures/Demo/PriceListDataFixture.php
  upgrade-notes/backend_20250514_101911.md
Labels: Bug

#3974 fix contact form query
  packages/framework/src/Model/ContactForm/ContactFormSettingsFacade.php
  packages/frontend-api/src/Model/Resolver/Settings/ContactFormMainTextQuery.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Settings/SettingsDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/storefront/components/Pages/Contact/ContactContent.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/settings/queries/SettingsQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
  upgrade-notes/backend_20250512_081202.md
  upgrade-notes/storefront_20250512_081754.md
Labels: Bug

#3986 added docs for easier switching between the projects on MacOS with Mutagen
  .github/workflows/docker-build.yaml
  docs/project/how-to-switch-between-projects-on-macos-with-mutagen.md
  docs/project/index.md
  docs/project/navigation.yml
Labels: Documentation

#3985 administrator without filtered domains will see new domains automatically when added
  packages/framework/src/Controller/Admin/SelectAdminDomainsController.php
  packages/framework/src/Migrations/Version20250516104642.php
  packages/framework/src/Model/Administrator/Administrator.php
  packages/framework/src/Model/Administrator/AdministratorData.php
  packages/framework/src/Model/Administrator/AdministratorDataFactory.php
Labels: Enhancement

#3984 admin enabled domains are now correctly aplied to PriceAndVatTableByDomainsType
  packages/framework/src/Form/PriceAndVatTableByDomainsType.php
  packages/framework/src/Resources/views/Admin/Form/priceandvattableByDomainsFields.html.twig
Labels: Bug

#3983 releaser: PackageProvider now uses version 2 of Packagist.org metadata
  packages/framework/src/Form/Transformers/MailWhitelistTransformer.php
  packages/framework/src/Model/Mail/MailerSettingProvider.php
  packages/framework/src/Model/Seo/SeoSettingFacade.php
  project-base/app/tests/App/Test/Client.php
  project-base/app/tests/App/Unit/Model/Product/Search/ProductElasticsearchConverterTest.php
  project-base/app/tests/FrontendApiBundle/Test/GraphQlTestCase.php
  upgrade-notes/backend_20250515_084909.md
  utils/releaser/src/FileManipulator/ComposerJsonFileManipulator.php
  utils/releaser/src/FilesProvider/PackageNamesProvider.php
  utils/releaser/src/Guzzle/ApiCaller.php
  utils/releaser/src/Packagist/PackageProvider.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ValidateConflictsInComposerJsonReleaseWorker.php
  utils/releaser/src/ReleaseWorker/ReleaseCandidate/ValidateRequireFormatInComposerJsonReleaseWorker.php
Labels: DX & Refactoring

#3982 fixed searching in unused friendly urls
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlRepository.php
Labels: Bug

#3934 stores are ordered by position
  packages/framework/src/Model/Store/StoreRepository.php
Labels: Bug, Easy Pick, In Backlog, Frontend API

#3989 DomainsForDataFixtureProvider loads domains on demand instead of allways
  .github/workflows/docker-build.yaml
  packages/framework/src/Component/DataFixture/DomainsForDataFixtureProvider.php
Labels: Bug

#3992 added deferred accessories to main variant detail
  project-base/storefront/components/Pages/ProductDetail/ProductDetailMainVariantContent.tsx
  upgrade-notes/storefront_20250521_072420.md
Labels: Bug

#3995 fixed related products slider arrows
  project-base/storefront/components/Pages/ProductDetail/ProductDetailTabs/ProductDetailRelatedProductsTab.tsx
  upgrade-notes/storefront_20250521_074738.md
Labels: Bug

#3990 bump phpstan
  composer.json
  packages/administration/composer.json
  packages/administration/src/Component/Action/AbstractAction.php
  packages/coding-standards/composer.json
  packages/coding-standards/extension.neon
  packages/coding-standards/src/Phpstan/GedmoExtension.php
  packages/coding-standards/tests/Unit/PhpStan/GedmoExtensionTest.php
  packages/coding-standards/tests/Unit/PhpStan/GedmoTestEntity.php
  packages/framework/composer.json
  packages/framework/src/Component/Error/ExceptionListener.php
  packages/framework/src/Component/Grid/GridView.php
  packages/framework/src/DependencyInjection/SetterInjectionTrait.php
  packages/framework/src/Form/Constraints/FileAllowedExtensionValidator.php
  packages/framework/src/Form/Constraints/FileExtensionMaxLengthValidator.php
  packages/framework/src/Form/Constraints/MoneyRange.php
  packages/framework/src/Form/Constraints/UniqueCollectionValidator.php
  packages/framework/src/Model/Administrator/AdministratorGridFacade.php
  packages/framework/src/Model/Cart/CartFacade.php
  packages/framework/src/Model/Mail/MailerSettingProvider.php
  packages/framework/tests/Unit/Component/Cron/CronFacadeTest.php
  packages/framework/tests/Unit/Component/Cron/CronModuleExecutorTest.php
  packages/framework/tests/Unit/Component/Doctrine/QueryBuilderExtenderTest.php
  packages/framework/tests/Unit/Component/Elasticsearch/IndexRegistryTest.php
  packages/framework/tests/Unit/Component/Grid/GridTest.php
  packages/framework/tests/Unit/Component/Router/CurrentDomainRouterTest.php
  packages/framework/tests/Unit/Component/Router/Security/RouteCsrfProtectorTest.php
  packages/framework/tests/Unit/Component/Translation/TranslatorTest.php
  packages/framework/tests/Unit/Model/Customer/UserFactoryTest.php
  packages/framework/tests/Unit/Model/Order/Processing/OrderProcessorMiddleware/AddProductsMiddlewareTest.php
  packages/framework/tests/Unit/Model/Order/Processing/OrderProcessorMiddleware/ApplyPercentagePromoCodeMiddlewareTest.php
  packages/frontend-api/composer.json
  packages/frontend-api/src/Component/CustomerUploadedFile/CustomerUploadedFilesBatchLoader.php
  packages/frontend-api/src/Component/Files/FilesBatchLoader.php
  packages/frontend-api/src/Component/Image/FirstImageBatchLoader.php
  packages/frontend-api/src/Component/Image/ImagesBatchLoader.php
  packages/frontend-api/src/Model/Error/ErrorCodeSubscriber.php
  packages/frontend-api/src/Model/Mutation/Login/LoginMutation.php
  packages/frontend-api/src/Model/Resolver/Settings/MaxAllowedPaymentTransactionsQuery.php
  packages/maker/composer.json
  packages/maker/src/EntityConfig/ScalarProperty.php
  packages/product-feed-google/tests/Unit/GoogleFeedItemTest.php
  packages/product-feed-heureka-delivery/tests/Unit/HeurekaDeliveryFeedItemTest.php
  packages/product-feed-heureka/tests/Unit/HeurekaFeedItemTest.php
  packages/product-feed-zbozi/tests/Unit/ZboziFeedItemTest.php
  packages/s3-bridge/composer.json
  phpstan.neon
  project-base/app/composer.json
  project-base/app/phpstan.neon
  project-base/app/src/FrontendApi/Model/Product/Filter/ProductFilterOptionsFactory.php
  project-base/app/src/Model/Product/Brand/BrandDataFactory.php
  project-base/app/src/Model/Product/Search/FilterQuery.php
  project-base/app/tests/App/Functional/Component/Doctrine/SortableNullsWalkerTest.php
  project-base/app/tests/App/Functional/EntityExtension/EntityExtensionTest.php
  project-base/app/tests/App/Functional/PersonalData/PersonalDataExportXmlTest.php
  project-base/app/tests/App/Performance/Feed/PerformanceTestSample.php
  project-base/app/tests/App/Performance/Page/AllPagesTest.php
  project-base/app/tests/App/Test/HttpFoundation/RequestStack.php
  upgrade-notes/backend_20250520_053833.md
Labels: DX & Refactoring

#3963 social login tweaks and fixes
  packages/frontend-api/src/Controller/SocialNetworkController.php
  packages/frontend-api/src/Model/SocialNetwork/SocialNetworkFacade.php
  project-base/app/config/routes/shopsys_front.yaml
  upgrade-notes/backend_20250506_101523.md
Labels: DX & Refactoring

#3988 fixed empty page title suffix
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Seo/SeoSettingDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/settings/fragments/SeoSettingFragment.generated.tsx
  project-base/storefront/graphql/requests/settings/queries/SettingsQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/utils/seo/useSeo.ts
  upgrade-notes/storefront_20250519_095034.md
Labels: Bug

#3994 fixed order confirmation product image size
  project-base/storefront/components/Pages/Customer/OrderDetail/OrderDetailOrderItem.tsx
  upgrade-notes/storefront_20250521_073913.md
Labels: Bug

#3996 fixed contact information address animation
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationDeliveryAddress.tsx
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/3-1-2 filled contact information form.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-0 contact information form before filling.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-10 with default address.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-13 contact information form before filling.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-14 contact information form after refresh.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-15 contact information form before filling.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-16 after checking again.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-17 contact information form before filling.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-18 contact information form after refresh.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-19 contact information form before filling.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-2 contact information form before filling.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-20 after checking again.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-3 contact information form after checking again.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-4 contact information form before filling.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-6 contact information form before filling.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-7 contact information form after checking again.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-8 with default address.png
  upgrade-notes/storefront_20250521_082906.md
Labels: Bug

#3977 Fix load more limit
  project-base/storefront/components/Blocks/Pagination/Pagination.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductsListContent.tsx
  project-base/storefront/components/Pages/BlogCategory/BlogCategoryArticlesWrapper.tsx
  project-base/storefront/components/Pages/BrandDetail/BrandDetailContent.tsx
  project-base/storefront/components/Pages/BrandDetail/BrandDetailProductsWrapper.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailProductsWrapper/CategoryDetailProductsWrapper.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailProductsWrapper/DeferredCategoryDetailProductsWrapper.tsx
  project-base/storefront/components/Pages/Customer/Complaints/ComplaintsContent.tsx
  project-base/storefront/components/Pages/Customer/OrderedItems/OrderedItemsContent.tsx
  project-base/storefront/components/Pages/Customer/Orders/OrdersContent.tsx
  project-base/storefront/components/Pages/FlagDetail/FlagDetailContent.tsx
  project-base/storefront/components/Pages/FlagDetail/FlagDetailProductsWrapper.tsx
  project-base/storefront/components/Pages/Search/SearchProducts.tsx
  project-base/storefront/components/Pages/Search/SearchProductsContent.tsx
  project-base/storefront/components/providers/PaginationProvider.tsx
  project-base/storefront/config/constants.ts
  project-base/storefront/pages/brands/[brandSlug].tsx
  project-base/storefront/pages/categories/[categorySlug].tsx
  project-base/storefront/pages/flags/[flagSlug].tsx
  project-base/storefront/utils/loadMore/getOffsetPage.ts
  project-base/storefront/utils/loadMore/getOffsetPageAndLoadMore.ts
  project-base/storefront/utils/loadMore/getRedirectWithOffsetPage.ts
  project-base/storefront/utils/ui/useScrollRestoration.ts
  project-base/storefront/vitest/utils/pagination/loadMore.test.ts
  upgrade-notes/storefront_20250513_175616.md
Labels: Bug

#3981 added prevention for duplicate parameter values
  packages/framework/src/Model/CategorySeo/ReadyCategorySeoMixFacade.php
  packages/framework/src/Model/Product/Parameter/ParameterFacade.php
  packages/framework/src/Model/Product/Parameter/ParameterRepository.php
  packages/framework/src/Model/Product/Parameter/ProductParameterValueDataFactory.php
  project-base/app/src/DataFixtures/Demo/ReadyCategorySeoDataFixture.php
  project-base/app/tests/App/Functional/Model/Product/Filter/ParameterFilterChoiceRepositoryTest.php
  project-base/app/tests/App/Functional/Model/Product/ProductOnCurrentDomainElasticFacadeCountDataTest.php
  project-base/app/tests/App/Test/ParameterTransactionFunctionalTestCase.php
  project-base/app/tests/FrontendApiBundle/Functional/CategorySeo/CategorySeoTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringOptionsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Product/ProductsFilteringTest.php
  upgrade-notes/backend_20250514_120051.md
Labels: Bug

#4008 DatabaseSearchingHelper::getFullTextLikeSearchString argument is not nullable anymore
  packages/framework/src/Component/String/DatabaseSearchingHelper.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Category/CategoryRepository.php
  project-base/app/src/Model/Category/CategoryFacade.php
  project-base/app/src/Model/Category/CategoryRepository.php
  upgrade-notes/backend_20250528_090023.md
Labels: DX & Refactoring

#4007 ensure order mail can be sent from CLI
  packages/framework/src/Resources/views/Mail/Order/billingAddress.html.twig
  packages/framework/src/Resources/views/Mail/Order/deliveryAddress.html.twig
  packages/framework/src/Resources/views/Mail/Order/paymentInfo.html.twig
  packages/framework/src/Resources/views/Mail/Order/paymentInstructions.html.twig
  packages/framework/src/Resources/views/Mail/Order/products.html.twig
  packages/framework/src/Resources/views/Mail/Order/transportInfo.html.twig
  packages/framework/src/Resources/views/Mail/Order/transportInstructions.html.twig
  packages/framework/src/Twig/ImageExtension.php
Labels: Bug
