Repository shopsys/shopsys, pull requests merged in 2025-04, with the labels that each got.

#3878 Free transport promo code fix
  project-base/storefront/components/Pages/Cart/CartPreview.tsx
  project-base/storefront/components/Pages/PersonalData/Detail/PersonalDataDetailContent.tsx
  project-base/storefront/graphql/requests/personalData/fragments/PersonalDataDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/personalData/fragments/PersonalDataDetailFragment.graphql
  project-base/storefront/graphql/requests/personalData/queries/PersonalDataDetailQuery.generated.tsx
  project-base/storefront/graphql/requests/personalData/queries/PersonalDataDetailQuery.graphql
  project-base/storefront/pages/order-confirmation.tsx
  project-base/storefront/pages/order-payment-confirmation.tsx
  upgrade-notes/storefront_20250325_135324.md
Labels: Bug

#3903 admin menu: "identification" section is available for multidomain projects only
  packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
Labels: Enhancement

#3900 fixed search by catnum exact match
  project-base/app/src/Resources/definition/product/1.json
  project-base/app/src/Resources/definition/product/2.json
  upgrade-notes/backend_20250403_065029.md
Labels: Bug

#3894 fixed notification bar unlimited validTo
  project-base/storefront/utils/useNotificationBarRevalidation.ts
  upgrade-notes/storefront_20250331_021925.md
Labels: Bug

#3892 fixed user information after change
  project-base/storefront/utils/user/useCurrentUserContactInformation.ts
  upgrade-notes/storefront_20250331_012821.md
Labels: Bug

#3889 admin product detail: display main category full path
  packages/framework/src/Form/Admin/Product/ProductFormType.php
  packages/framework/src/Form/CategoriesType.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Category/CategoryRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Form/theme.html.twig
  project-base/app/src/Model/Category/CategoryFacade.php
  project-base/app/src/Model/Category/CategoryRepository.php
  upgrade-notes/backend_20250328_132407.md
Labels: Design & Appearance

#3873 ensure store coordinates are always numeric
  packages/framework/src/Form/Admin/Store/StoreFormType.php
  packages/framework/src/Migrations/Version20250320124625.php
  packages/framework/src/Model/Store/Store.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Store/Input/CoordinatesDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Store/GetFilteredStoresTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Store/GetStoreTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Store/GetStoresTest.php
  project-base/storefront/components/Blocks/StoreList/StoresWrapper.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/types.ts
  upgrade-notes/backend_20250320_124958.md
Labels: Bug

#3901 fixed attempt to login as admin without password
  packages/framework/src/Model/Administrator/AdministratorRepository.php
  packages/framework/src/Model/Administrator/Security/AdministratorUserProvider.php
  project-base/app/src/Model/Administrator/AdministratorRepository.php
Labels: Bug

#3885 simplified conditions in mail templates twig
  packages/framework/src/Migrations/Version20250331122654.php
  packages/framework/src/Resources/views/Mail/Order/paymentInfo.html.twig
  packages/framework/src/Resources/views/Mail/Order/products.html.twig
  packages/framework/src/Resources/views/Mail/Order/transportInfo.html.twig
  upgrade-notes/backend_20250314_114815.md
Labels: DX & Refactoring

#3884 Fix Load more and Show more pluralization
  project-base/storefront/components/Blocks/Pagination/Pagination.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryBestsellers/CategoryBestsellers.tsx
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  upgrade-notes/storefront_20250407_071224.md
Labels: DX & Refactoring

#3880 Fix long product name word break
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItem.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-0 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/matrix/matrixTest.cy.ts/0-0-0 matrix page.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-0 homepage.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-1 product detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-4 blog article detail.png
  upgrade-notes/storefront_20250325_140323.md
Labels: Bug

#3915 category bestseller items use onmouseup event for gtm
  project-base/storefront/components/Pages/CategoryDetail/CategoryBestsellers/CategoryBestsellersListItem.tsx
Labels: Enhancement

#3791 [SSP-3143] - articles layout
  project-base/app/src/DataFixtures/Demo/ArticleDataFixture.php
  project-base/app/src/DataFixtures/Demo/TopCategoryDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/Article/GetArticlesTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Category/PromotedCategoriesTest.php
  project-base/storefront/components/Blocks/BlogPreview/BlogPreview.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewPlaceholder.tsx
  project-base/storefront/components/Blocks/BlogPreview/DeferredBlogPreview.tsx
  project-base/storefront/components/Blocks/Product/ProductsSlider.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonPageArticle.tsx
  project-base/storefront/components/Layout/Webline/Webline.tsx
  project-base/storefront/components/Pages/Article/ArticleDetailContent.tsx
  project-base/storefront/cypress/snapshots/e2e/matrix/matrixTest.cy.ts/0-0-0 matrix page.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-0 homepage.png
  upgrade-notes/storefront_20250212_080332.md
Labels: Bug, Design & Appearance

#3921 fixed product name wrapping
  project-base/storefront/components/Pages/ProductDetail/ProductDetailContent.tsx
Labels: Bug

#3925 updated list of supported currencies by intl library
  packages/framework/src/Model/Localization/IntlCurrencyRepository.php
  upgrade-notes/backend_20250411_093455.md
Labels: Enhancement

#3917 added icons for displaying visibility of categories
  packages/framework/src/Controller/Admin/CategoryController.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Category/CategoryRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Category/list.html.twig
Labels: Enhancement

#3928 polished gallery thumbnails sizes
  project-base/storefront/components/Pages/ProductDetail/ProductDetailGallery.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-1 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-1 product detail.png
  upgrade-notes/storefront_20250414_061233.md
Labels: Bug

#3916 Fixed GrapesJS Text with Image component
  project-base/app/assets/js/admin/grapesjs/plugins/grapesjs-text-with-image-plugin.js
  project-base/app/assets/styles/admin/grapesjs.less
  project-base/storefront/components/Basic/UserText/GrapesJsProducts.tsx
  project-base/storefront/components/Blocks/Product/ProductsSlider.tsx
  project-base/storefront/components/Pages/BlogArticle/BlogArticleDetailContent.tsx
  project-base/storefront/cypress/snapshots/e2e/matrix/matrixTest.cy.ts/0-0-0 matrix page.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-0 homepage.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-1 product detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-4 blog article detail.png
  project-base/storefront/styles/user-text.css
  upgrade-notes/backend_20250408_091057.md
Labels: Bug

#3926 updated tailwind to v4.1
  project-base/storefront/components/Blocks/Banners/Banner.tsx
  project-base/storefront/components/Blocks/Banners/BannersDot.tsx
  project-base/storefront/components/Blocks/Banners/BannersSlider.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailElements.tsx
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  upgrade-notes/storefront_20250411_092711.md
Labels: dependencies

#3936 unified user menu drawer for account page and header
  project-base/storefront/components/Blocks/UserMenu/UserMenu.tsx
  project-base/storefront/components/Blocks/UserNavigation/UserNavigation.tsx
  project-base/storefront/components/Layout/Header/MenuIconic/MenuIconicItemUserAuthenticated.tsx
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/3-1-3 filled contact information form.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-10 with default address.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-11 with changed delivery address.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-12 with changed delivery address after switching back from default.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-13 contact information form before filling.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-14 contact information form after refresh.png
  project-base/storefront/store/slices/createUserMenuSlice.ts
  project-base/storefront/store/useSessionStore.ts
  upgrade-notes/storefront_20250416_114430.md
Labels: Design & Appearance

#3937 updated responsive button in product list and spinbox
  project-base/storefront/components/Blocks/Product/AddToCart.tsx
  project-base/storefront/components/Blocks/Product/ProductAction.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItem.tsx
  project-base/storefront/components/Forms/Spinbox/Spinbox.tsx
  project-base/storefront/components/Pages/Cart/CartList/CartListItem.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailAddToCart/ProductDetailAddToCart.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-0 cart page after login.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-1 cart page after adding product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-2 cart page after adding product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-3 cart page after adding product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-4 cart page after adding second product to cart.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-5 cart page after second login.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartLogin.cy.ts/2-1-6 cart page after first login.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-0 after increase.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-1 after decrease.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-10 after applying promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-11 after removing product that allows promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-12 cart page with non-free transport after applying promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-2 after increase.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-3 after decrease.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-4 after first removal.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-6 cart page after applying first promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-8 cart page after removing first promocode.png
  project-base/storefront/cypress/snapshots/e2e/cart/cartPage.cy.ts/2-2-9 cart page after removing second promocode.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-0 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-1 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-2 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-3 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-4 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/order/orderRepeat.cy.ts/3-3-5 after repeat.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/4-2-8 cart page with enough products.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-1 product detail.png
  upgrade-notes/storefront_20250417_054922.md
Labels: Design & Appearance

#3941 enable adding related products on product creation
  project-base/app/src/Model/Product/Product.php
  upgrade-notes/backend_20250424_130657.md
Labels: Bug

#3942 domain icon edit page is now standard separate page
  packages/framework/assets/js/admin/components/DomainIcon.js
  packages/framework/assets/js/admin/components/index.js
  packages/framework/src/Controller/Admin/DomainController.php
  packages/framework/src/Form/Admin/Domain/DomainFormType.php
  packages/framework/src/Form/DisplayOnlyDomainIconType.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Domain/edit.html.twig
  packages/framework/src/Resources/views/Admin/Content/Domain/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Form/displayOnlyDomainIconFields.html.twig
  upgrade-notes/backend_20250423_111501.md
Labels: DX & Refactoring

#3924 fix disappearing RGB color of parameter values
  packages/framework/src/Form/Transformers/ProductParameterValueToProductParameterValuesLocalizedTransformer.php
  packages/framework/src/Model/Product/Parameter/ParameterFacade.php
  packages/framework/src/Model/Product/Parameter/ParameterRepository.php
  packages/framework/src/Model/Product/Parameter/ParameterValue.php
  packages/framework/src/Model/Product/Parameter/ParameterValueData.php
  packages/framework/src/Model/Product/Parameter/ParameterValueDataFactory.php
  packages/framework/src/Model/Product/Parameter/ProductParameterValueDataFactory.php
  packages/framework/src/Model/Product/Parameter/ProductParameterValuesLocalizedDataFactory.php
  packages/framework/src/Model/Product/ProductFacade.php
  project-base/app/src/Model/Product/Parameter/ParameterRepository.php
  project-base/app/src/Model/Product/ProductFacade.php
  upgrade-notes/backend_20250411_125117.md
Labels: Bug, DX & Refactoring

#3943 fixed luigis box size in cart
  project-base/storefront/components/Pages/Cart/CartContent.tsx
  upgrade-notes/storefront_20250423_064409.md
Labels: Bug

#3950 do not render datagrid without defined or visibled columns
  packages/administration/src/Component/Datagrid/Datagrid.php
Labels: Bug, Easy Pick

#3938 Refactor of Image sizes prop
  project-base/storefront/components/Basic/ModalGallery/ModalGallery.tsx
  project-base/storefront/components/Blocks/Banners/BannerImage.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewMain.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewSide.tsx
  project-base/storefront/components/Blocks/Categories/PromotedCategoriesContent.tsx
  project-base/storefront/components/Blocks/CollapsibleDescriptionWithImage/CollapsibleDescriptionWithImage.tsx
  project-base/storefront/components/Pages/BlogCategory/BlogArticlesList.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailGallery.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailVariantsTable.tsx
  project-base/storefront/cypress/snapshots/e2e/authentication/registration.cy.ts/1-0-1 customer edit page.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-2 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/3-1-3 filled contact information form.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrder.cy.ts/3-1-6 customer edit page.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-10 with default address.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-11 with changed delivery address.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-12 with changed delivery address after switching back from default.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-8 with default address.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-9 changed contact information after refresh.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/4-2-1 after selecting.png
  upgrade-notes/storefront_20250429_090255.md
Labels: coderabbit

#3948 tweaks of code generator
  packages/maker/src/Maker/FrontendApiTypeMaker.php
  packages/maker/src/Utils/EntityChoiceHelper.php
Labels: DX & Refactoring

#3944 removed unnecessary order sent page data fixtures
  packages/framework/src/Migrations/Version20180702111020.php
  packages/framework/src/Resources/translations/dataFixtures.cs.po
  packages/framework/src/Resources/translations/dataFixtures.en.po
  project-base/app/src/DataFixtures/Demo/OrderContentPageSettingValueDataFixture.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  upgrade-notes/backend_20250425_074659.md
Labels: DX & Refactoring

#3946 variants can be set as related products
  project-base/app/src/Form/Admin/ProductFormTypeExtension.php
  upgrade-notes/backend_20250424_180643.md
Labels: Bug

#3869 Improved documentation visual
  .readthedocs.yml
  docker/mkdocs/Dockerfile
  docs/_theme/img/shopsys-logo.svg
  docs/_theme/img/slack.png
  docs/_theme/main.css
  docs/_theme/main.html
  docs/_theme/nav.html
  docs/_theme/versions.html
  docs/contributing/guidelines-for-pull-request.md
  docs/cookbook/modifying-a-template-in-administration.md
  docs/docker/docker-troubleshooting.md
  docs/index.md
  docs/installation/application-configuration.md
  docs/installation/application-requirements.md
  docs/introduction/domain-multidomain-multilanguage.md
  docs/introduction/how-to-set-up-domains-and-locales.md
  docs/introduction/shopsys-framework-on-docker.md
  docs/introduction/start-building-your-application.md
  docs/requirements.txt
  docs/storefront/graphql.md
  docs/storefront/project-structure.md
  mkdocs.yml
Labels: Documentation

#3955 change defer location and z-index
  project-base/storefront/components/Layout/PageDefer.tsx
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-8 with default address.png
  project-base/storefront/cypress/snapshots/e2e/order/createOrderWithDeliveryAddress.cy.ts/3-2-9 changed contact information after refresh.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/paymentSelect.cy.ts/4-1-4 after selecting.png
  project-base/storefront/cypress/snapshots/e2e/transportAndPayment/transportSelect.cy.ts/4-2-1 after selecting.png
  upgrade-notes/storefront_20250429_091624.md
Labels: Bug
