Repository shopsys/shopsys, pull requests merged in 2025-03, with the labels that each got.

#3816 added smoke tests
  .github/get-build-exit-code.sh
  .github/workflows/docker-build.yaml
  Makefile
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose.github-actions.cypress.yml.dist
  docker/conf/docker-compose.yml.dist
  docs/storefront/cypress.md
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
  project-base/storefront/config/routes.ts
  project-base/storefront/config/staticRewritePaths.ts
  project-base/storefront/cypress/cypress.config.ts
  project-base/storefront/cypress/cypress.d.ts
  project-base/storefront/cypress/docker/entrypoint.sh
  project-base/storefront/cypress/fixtures/demodata.ts
  project-base/storefront/cypress/package.json
  project-base/storefront/cypress/smokeTests/smokeTests.cy.ts
  project-base/storefront/cypress/support/api.ts
  project-base/storefront/cypress/support/index.ts
  project-base/storefront/cypress/tids.ts
  project-base/storefront/cypress/tsconfig.json
  project-base/storefront/pages/customer/change-password.tsx
  project-base/storefront/pages/customer/edit-profile.tsx
  project-base/storefront/utils/user/useRedirectOnPermissionsChange.tsx
  upgrade-notes/storefront_20250220_142029.md
Labels: Enhancement

#3809 added support for entity with single domain friendly URL
  docs/introduction/using-form-types.md
  packages/framework/src/Component/Domain/Domain.php
  packages/framework/src/Component/Router/FriendlyUrl/Exception/FriendlyUrlIsNotMultidomainException.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlFactory.php
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrlGeneratorFacade.php
  packages/framework/src/Form/Admin/Article/ArticleFormType.php
  packages/framework/src/Form/Admin/Store/StoreFormType.php
  packages/framework/src/Form/DomainType.php
  packages/framework/src/Form/FriendlyUrlType.php
  packages/framework/src/Form/UrlListType.php
  packages/framework/src/Model/Article/ArticleDataFactory.php
  packages/framework/src/Model/Store/Store.php
  packages/framework/src/Model/Store/StoreDataFactory.php
  packages/framework/tests/Unit/Component/Router/FriendlyUrl/FriendlyUrlFactoryTest.php
  packages/framework/tests/Unit/Component/Router/FriendlyUrl/FriendlyUrlUniqueResultFactoryTest.php
  project-base/app/config/shopsys-routing/routing_friendly_url.yaml
  upgrade-notes/backend_20250224_105239.md
Labels: DX & Refactoring

#3828 cleared search input after submit
  project-base/storefront/components/Layout/Header/AutocompleteSearch/AutocompleteSearch.tsx
  upgrade-notes/storefront_20250227_103530.md
Labels: Bug

#3829 refactored product slider for improved responsiveness
  project-base/storefront/components/Blocks/Product/ProductsSlider.tsx
  project-base/storefront/cypress/snapshots/e2e/matrix/matrixTest.cy.ts/0-0-0 matrix page.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-0 homepage.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-1 product detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-4 blog article detail.png
  upgrade-notes/storefront_20250227_125554.md
Labels: Bug

#3831 controllers are now typed
  packages/framework/src/Controller/Admin/ArticleController.php
  packages/framework/src/Controller/Admin/BestsellingProductController.php
  packages/framework/src/Controller/Admin/BlogCategoryController.php
  packages/framework/src/Controller/Admin/BreadcrumbController.php
  packages/framework/src/Controller/Admin/CategoryController.php
  packages/framework/src/Controller/Admin/ContactFormSettingsController.php
  packages/framework/src/Controller/Admin/CspHeaderController.php
  packages/framework/src/Controller/Admin/CurrencyController.php
  packages/framework/src/Controller/Admin/CustomerController.php
  packages/framework/src/Controller/Admin/DomainController.php
  packages/framework/src/Controller/Admin/FeedController.php
  packages/framework/src/Controller/Admin/FileUploadController.php
  packages/framework/src/Controller/Admin/FlagController.php
  packages/framework/src/Controller/Admin/FlashMessageController.php
  packages/framework/src/Controller/Admin/GridController.php
  packages/framework/src/Controller/Admin/HeurekaController.php
  packages/framework/src/Controller/Admin/NewsletterController.php
  packages/framework/src/Controller/Admin/OrderStatusController.php
  packages/framework/src/Controller/Admin/ParameterValueController.php
  packages/framework/src/Controller/Admin/PaymentController.php
  packages/framework/src/Controller/Admin/PersonalDataController.php
  packages/framework/src/Controller/Admin/PricingGroupController.php
  packages/framework/src/Controller/Admin/ProductController.php
  packages/framework/src/Controller/Admin/ProductPickerController.php
  packages/framework/src/Controller/Admin/PromoCodeController.php
  packages/framework/src/Controller/Admin/SeoController.php
  packages/framework/src/Controller/Admin/SliderController.php
  packages/framework/src/Controller/Admin/SuperadminController.php
  packages/framework/src/Controller/Admin/TopCategoryController.php
  packages/framework/src/Controller/Admin/TopProductController.php
  packages/framework/src/Controller/Admin/TransferIssueController.php
  packages/framework/src/Controller/Admin/TransportAndPaymentController.php
  packages/framework/src/Controller/Admin/TransportController.php
  packages/framework/src/Controller/Admin/UnitController.php
  packages/framework/src/Controller/Admin/VatController.php
Labels: DX & Refactoring

#3837 navigation edit now respects the admin available locales
  packages/framework/src/Form/Admin/Navigation/NavigationItemFormType.php
  packages/framework/src/Model/Category/CategoryFacade.php
  packages/framework/src/Model/Category/CategoryRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  project-base/app/src/Model/Category/CategoryFacade.php
  project-base/app/src/Model/Category/CategoryRepository.php
  upgrade-notes/backend_20250305_064851.md
Labels: Bug

#3835 updated dependencies
  project-base/storefront/components/Pages/OrderConfirmation/OrderConfirmationStepper.tsx
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  upgrade-notes/storefront_20250304_042745.md
Labels: dependencies

#3805 notification bar validity now includes time for more narrow settings
  packages/framework/src/Component/DateTimeHelper/DateTimeHelper.php
  packages/framework/src/Component/Redis/CleanStorefrontCacheFacade.php
  packages/framework/src/Form/Admin/NotificationBar/NotificationBarFormType.php
  packages/framework/src/Model/NotificationBar/NotificationBarFacade.php
  packages/framework/src/Model/NotificationBar/NotificationBarRepository.php
  packages/framework/src/Resources/views/Admin/Content/NotificationBar/listGrid.html.twig
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/NotificationBar/NotificationBarDecorator.types.yaml
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/NotificationBarDataFixture.php
  project-base/app/tests/FrontendApiBundle/Functional/NotificationBar/NotificationBarsTest.php
  project-base/app/tests/FrontendApiBundle/Functional/NotificationBar/graphql/NotificationBarsQuery.graphql
  project-base/storefront/components/Layout/NotificationBars/NotificationBars.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/notificationBars/fragments/NotificationBarsFragment.generated.tsx
  project-base/storefront/graphql/requests/notificationBars/fragments/NotificationBarsFragment.graphql
  project-base/storefront/graphql/requests/notificationBars/queries/NotificationBarsQuery.generated.tsx
  project-base/storefront/graphql/requests/notificationBars/queries/NotificationBarsQuery.graphql
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
  project-base/storefront/utils/useCountdown.ts
  project-base/storefront/utils/useNotificationBarRevalidation.ts
  upgrade-notes/backend_20250217_091404.md
  upgrade-notes/storefront_20250226_180117.md
Labels: Enhancement

#3854 fixed adding non string constant to category data fixture
  project-base/app/src/DataFixtures/Demo/CategoryParameterDataFixture.php
  upgrade-notes/backend_20250312_133647.md
Labels: Bug, Easy Pick

#3855 invalid locale set to admin now defaults to first allowed locale
  packages/framework/src/Model/Localization/LocalizationListener.php
Labels: Bug

#3856 order statuses are now created with domain defined locales
  packages/framework/src/Migrations/Version20180603135341.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
Labels: Enhancement

#3859 ChoiceType values are not translated by default
  packages/framework/src/Form/Admin/Advert/AdvertFormType.php
  packages/framework/src/Form/Admin/Article/ArticleFormType.php
  packages/framework/src/Form/Admin/Category/CategoryFormType.php
  packages/framework/src/Form/Admin/Complaint/ComplaintFormType.php
  packages/framework/src/Form/Admin/Customer/RoleGroup/CustomerUserRoleGroupFormType.php
  packages/framework/src/Form/Admin/PriceList/ImportPriceListFormType.php
  packages/framework/src/Form/Admin/PromoCode/PromoCodeFlagType.php
  packages/framework/src/Form/Admin/PromoCode/PromoCodeFormType.php
  packages/framework/src/Form/ChoiceTypeExtension.php
  upgrade-notes/backend_20250312_144941.md
Labels: DX & Refactoring

#3860 added index to friendly url to cover most used method
  packages/framework/src/Component/Router/FriendlyUrl/FriendlyUrl.php
  packages/framework/src/Migrations/Version20250313074307.php
Labels: Performance

#3827 remove generated error pages
  .github/workflows/docker-build.yaml
  docs/cookbook/basic-data-import.md
  docs/cookbook/working-with-multiple-cron-instances.md
  docs/installation/installation-using-docker-application-setup.md
  packages/administration/src/ShopsysAdministrationBundle.php
  packages/administration/src/Twig/ErrorIdExtension.php
  packages/administration/templates/bundles/TwigBundle/Exception/error500.html.twig
  packages/framework/build.xml
  packages/framework/phpstan.neon
  packages/framework/src/Command/GenerateErrorPagesCommand.php
  packages/framework/src/Component/AddSentryContextSubscriber.php
  packages/framework/src/Component/Error/BlueScreenErrorRenderer.php
  packages/framework/src/Component/Error/ErrorIdLogProcessor.php
  packages/framework/src/Component/Error/ErrorIdProvider.php
  packages/framework/src/Component/Error/ErrorPageCronModule.php
  packages/framework/src/Component/Error/ErrorPagesFacade.php
  packages/framework/src/Component/Error/Exception/BadErrorPageStatusCodeException.php
  packages/framework/src/Component/Error/Exception/FakeHttpException.php
  packages/framework/src/Component/Error/ExceptionListener.php
  packages/framework/src/Component/Error/NotLogFakeHttpExceptionsErrorListener.php
  packages/framework/src/Controller/Admin/ErrorController.php
  packages/framework/src/Controller/Admin/SuperadminController.php
  packages/framework/src/Migrations/Version20250302234333.php
  packages/framework/src/Model/AdminNavigation/SideMenuBuilder.php
  packages/framework/src/Resources/config/routing.yaml
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Error/error.css.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error.js.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error.json.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error.txt.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error.xml.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error4xx.html.twig
  packages/framework/src/Resources/views/Admin/Content/Error/error500.html.twig
  packages/framework/src/Resources/views/Admin/Content/Superadmin/errors.html.twig
  packages/framework/src/Resources/views/Admin/Layout/errorLayout.html.twig
  project-base/.github/workflows/run-checks-tests.yaml
  project-base/.gitlab-ci.yml
  project-base/app/config/cron.yaml
  project-base/app/config/packages/acc/monolog.yaml
  project-base/app/config/packages/framework.yaml
  project-base/app/config/packages/prod/monolog.yaml
  project-base/app/config/packages/prod/sentry.yaml
  project-base/app/tests/App/Acceptance/acceptance/ErrorHandlingCest.php
  project-base/scripts/install.sh
  upgrade-notes/backend_20250227_040635.md
Labels: DX & Refactoring

#3862 fixed assigning parameter position to category
  packages/framework/src/Form/Admin/Category/CategoryFormType.php
Labels: Bug

#3851 Migrate eslint from v8.56 to v9.22
  docs/storefront/coding-standards.md
  project-base/storefront/.eslintrc.js
  project-base/storefront/.prettierignore
  project-base/storefront/components/Basic/CopyTextBlock/CopyTextBlock.tsx
  project-base/storefront/components/Basic/ExtendedNextLink/ExtendedNextLink.tsx
  project-base/storefront/components/Basic/GoogleMap/GoogleMap.tsx
  project-base/storefront/components/Forms/Button/Button.tsx
  project-base/storefront/eslint.config.mjs
  project-base/storefront/i18n-translator.js
  project-base/storefront/middleware.ts
  project-base/storefront/next.config.js
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
  project-base/storefront/schema-compress.js
  project-base/storefront/store/slices/createPageLoadingStateSlice.ts
  project-base/storefront/tsconfig.json
  project-base/storefront/types/globals.d.ts
  project-base/storefront/utils/requestProtocol.ts
  project-base/storefront/utils/serverSide/initServerSideProps.ts
  upgrade-notes/storefront_20250310_170634.md
Labels: DX & Refactoring

#3865 mail template prices now reflect input price type setting
  docs/introduction/faq-and-common-issues.md
  packages/framework/src/Model/Mail/MailTemplateConfiguration.php
  packages/framework/src/Model/Order/Mail/OrderMail.php
  packages/framework/src/Model/Order/PromoCode/DiscountCalculation.php
  packages/framework/src/Resources/config/parameters_common.yaml
  packages/framework/src/Resources/config/services.yaml
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Mail/Order/paymentInfo.html.twig
  packages/framework/src/Resources/views/Mail/Order/products.html.twig
  packages/framework/src/Resources/views/Mail/Order/transportInfo.html.twig
  project-base/app/config/parameters_common.yaml
  project-base/app/config/services.yaml
  project-base/app/src/DataFixtures/Demo/MailTemplateDataFixture.php
  project-base/app/src/Model/Order/Mail/OrderMail.php
  project-base/app/tests/App/Functional/Model/Order/Mail/OrderMailTest.php
  project-base/app/translations/dataFixtures.cs.po
  project-base/app/translations/dataFixtures.en.po
  upgrade-notes/backend_20250314_114815.md
Labels: Enhancement

#3870 search by catnum is now case insensitive on storefront
  project-base/app/src/Resources/definition/product/1.json
  project-base/app/src/Resources/definition/product/2.json
  upgrade-notes/backend_20250319_112923.md
Labels: Bug

#3861 review cancel is now independent on running container and use proper working dir
  .github/cancel-review.sh
Labels: Infrastructure

#3841 Optional links to social networks for email templates
  packages/framework/src/Controller/Admin/MailController.php
  packages/framework/src/Form/Admin/Mail/MailSettingFormType.php
  packages/framework/src/Model/Mail/MailTemplateBuilder.php
  packages/framework/src/Model/Mail/Setting/MailSetting.php
  packages/framework/src/Model/Mail/Setting/MailSettingFacade.php
Labels: Enhancement

#3843 Filter in the administration for products type upon inquiry
  packages/framework/src/Form/Admin/AdvancedSearch/AdvancedSearchProductFilterTranslation.php
  packages/framework/src/Model/AdvancedSearch/Filter/ProductUponInquiryFilter.php
  packages/framework/src/Model/AdvancedSearch/ProductAdvancedSearchConfig.php
  packages/framework/src/Model/Product/Listing/ProductListAdminRepository.php
  packages/framework/src/Model/Product/ProductGridFactory.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Product/listGrid.html.twig
  packages/framework/src/Resources/views/Admin/Content/ProductPicker/listGrid.html.twig
Labels: Enhancement

#3798 fill delivery address data from existing entity
  packages/framework/src/Model/Country/CountryFacade.php
  packages/framework/src/Model/Country/CountryRepository.php
  packages/frontend-api/src/Model/Country/Exception/CountryNotFoundUserError.php
  packages/frontend-api/src/Model/Mutation/Customer/DeliveryAddress/DeliveryAddressDataApiFactory.php
  packages/frontend-api/src/Model/Mutation/Customer/DeliveryAddress/DeliveryAddressMutation.php
Labels: In Backlog

#3842 Tuning the display of a group of parameters when editing a product
  packages/framework/src/Form/Admin/Product/Parameter/ProductParameterValueFormType.php
  packages/framework/src/Model/Product/Parameter/ParameterRepository.php
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Form/productParameterValue.html.twig
Labels: Design & Appearance

#3830 Improve CLS
  project-base/storefront/components/Basic/CollapsibleText/CollapsibleText.tsx
  project-base/storefront/components/Basic/Image/Image.tsx
  project-base/storefront/components/Blocks/CollapsibleDescriptionWithImage/CollapsibleDescriptionWithImage.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleCartInHeader.tsx
  project-base/storefront/components/Layout/Header/Cart/CartCount.tsx
  project-base/storefront/components/Layout/Header/Cart/CartInHeader.tsx
  project-base/storefront/components/Pages/ProductDetail/ProductDetailGallery.tsx
  project-base/storefront/cypress/snapshots/e2e/cart/cartInHeader.cy.ts/2-0-0 after first remove.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-0 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/cart/productAddToCart.cy.ts/2-3-2 add to cart popup.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  upgrade-notes/storefront_20250321_162300.md
Labels: Performance

#3871 site articles and link articles are now differentiated in the list
  packages/framework/src/Resources/translations/messages.cs.po
  packages/framework/src/Resources/translations/messages.en.po
  packages/framework/src/Resources/views/Admin/Content/Article/listGrid.html.twig
Labels: Enhancement

#3852 fix multiple rerenders of product comparison
  project-base/storefront/components/Pages/ProductComparison/ProductComparisonContent.tsx
  project-base/storefront/components/Pages/ProductComparison/ProductComparisonHeadSticky.tsx
  project-base/storefront/utils/productLists/comparison/useComparisonTable.tsx
  project-base/storefront/utils/ui/useScrollTop.ts
  upgrade-notes/storefront_20250311_073929.md
Labels: Bug, DX & Refactoring, coderabbit

#2368 Doctrine: Migration: added functionality for ignore column from entity by annotation
  docs/extensibility/entity-extension.md
  packages/framework/src/Component/Doctrine/Attribute/RemoveColumn.php
  packages/framework/src/Component/Doctrine/RemoveEntityColumnSubscriber.php
  packages/framework/src/Resources/config/services.yaml
  project-base/app/config/services.yaml
  project-base/app/src/Component/Doctrine/RemoveMappingsSubscriber.php
  upgrade-notes/backend_20250326_125354.md
Labels: Status: on hold, In Backlog

#3822 Fix cart & missing whishlist/comparison products after external login
  packages/frontend-api/src/Controller/CustomerUserController.php
  packages/frontend-api/src/Controller/SocialNetworkController.php
  packages/frontend-api/src/Resources/views/Admin/Content/Login/loginAsCustomerUser.html.twig
  upgrade-notes/backend_20250224_112831.md
Labels: Bug

#3718 remove linked categories on category edit/create from administration
  packages/framework/src/Migrations/Version20250324141622.php
  packages/frontend-api/src/Model/Resolver/Category/CategoryResolverMap.php
  packages/frontend-api/src/Resources/config/graphql-types/ModelType/Category/CategoryDecorator.types.yaml
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/app/config/forms.yaml
  project-base/app/config/packages/overblog_dataloader.yaml
  project-base/app/schema.graphql
  project-base/app/src/DataFixtures/Demo/CategoryDataFixture.php
  project-base/app/src/Form/Admin/CategoryFormTypeExtension.php
  project-base/app/src/FrontendApi/Model/Category/CategoryFacade.php
  project-base/app/src/FrontendApi/Model/Category/CategoryRepository.php
  project-base/app/src/FrontendApi/Model/Category/LinkedCategoriesBatchLoader.php
  project-base/app/src/Migrations/Version20201115140641.php
  project-base/app/src/Model/Category/CategoryData.php
  project-base/app/src/Model/Category/CategoryDataFactory.php
  project-base/app/src/Model/Category/CategoryFacade.php
  project-base/app/src/Model/Category/LinkedCategory/LinkedCategory.php
  project-base/app/src/Model/Category/LinkedCategory/LinkedCategoryFacade.php
  project-base/app/src/Model/Category/LinkedCategory/LinkedCategoryRepository.php
  project-base/app/tests/FrontendApiBundle/Functional/Category/CategoryTest.php
  project-base/app/tests/FrontendApiBundle/Functional/Category/graphql/CategoryQuery.graphql
  project-base/app/tests/FrontendApiBundle/Functional/Category/graphql/PromotedCategoriesQuery.graphql
  project-base/app/tests/FrontendApiBundle/Functional/CategorySeo/CategorySeoTest.php
  project-base/app/tests/FrontendApiBundle/Functional/CategorySeo/graphql/CategorySeoWithLinks.graphql
  project-base/app/translations/messages.cs.po
  project-base/app/translations/messages.en.po
  project-base/storefront/components/Pages/CategoryDetail/CategoryDetailContent.tsx
  project-base/storefront/graphql/docs/schema.md
  project-base/storefront/graphql/requests/categories/fragments/CategoryDetailFragment.generated.tsx
  project-base/storefront/graphql/requests/categories/fragments/CategoryDetailFragment.graphql
  project-base/storefront/graphql/requests/categories/queries/CategoryDetailQuery.generated.tsx
  project-base/storefront/graphql/types.ts
  project-base/storefront/schema-compressed.graphql.json
  upgrade-notes/backend_20250107_141848.md
Labels: Enhancement, regenerate screenshots

#3886 dicsount order items creation tweaks
  packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/ApplyNominalPromoCodeMiddleware.php
  packages/framework/src/Model/Order/Processing/OrderProcessorMiddleware/ApplyPercentagePromoCodeMiddleware.php
  packages/framework/tests/Unit/Model/Order/Processing/OrderProcessorMiddleware/ApplyNominalPromoCodeMiddlewareTest.php
Labels: DX & Refactoring

#3890 project-base: merge services_frontend_api.yaml into services.yaml
  project-base/app/config/services.yaml
  project-base/app/config/services_frontend_api.yaml
  upgrade-notes/backend_20250328_151152.md
Labels: DX & Refactoring

#3690 Improve logging
  docs/cookbook/create-asynchronous-notifier.md
  packages/framework/src/Command/CronCommand.php
  packages/framework/src/Command/Exception/CronIsLockedException.php
  packages/framework/src/Component/Bytes/BytesHelper.php
  packages/framework/src/Component/Console/ConsoleExitCodeSubscriber.php
  packages/framework/src/Component/Cron/CronFacade.php
  packages/framework/src/Component/Cron/CronModuleExecutor.php
  packages/framework/src/Component/Log/SlowLogSubscriber.php
  packages/framework/src/Component/Reflection/ReflectionHelper.php
  packages/framework/src/Model/Product/Recalculation/ProductRecalculationMessageHandler.php
  packages/framework/src/Resources/config/services.yaml
  packages/framework/tests/Unit/Component/Console/ConsoleExitCodeSubscriberTest.php
  packages/frontend-api/src/Resources/config/services.yaml
  project-base/app/config/bundles.php
  project-base/app/config/packages/acc/monolog.yaml
  project-base/app/config/packages/dev/monolog.yaml
  project-base/app/config/packages/monolog.yaml
  project-base/app/config/packages/prod/monolog.yaml
  project-base/app/config/packages/prod/sentry.yaml
  project-base/app/config/packages/sentry.yaml
  project-base/app/config/packages/test/monolog.yaml
  project-base/app/docker/php-fpm/consumer-entrypoint.sh
  project-base/app/docker/php-fpm/production-www.conf
  project-base/app/src/Kernel.php
  upgrade-notes/backend_20250330_221733.md
Labels: Bug, DX & Refactoring, dependencies
