Repository shopsys/shopsys, pull requests merged in 2025-09, with the labels that each got.

#4133 improved link color in mail warning bar
  packages/framework/assets/styles/admin/components/window/fixed-bar.less
Labels: Design & Appearance

#4164 fixed order of registering extended routes
  project-base/app/config/routes/shopsys_admin.yaml
  project-base/app/config/routes/shopsys_framework.yaml
  upgrade-notes/backend_20250829_124729.md
Labels: Bug

#4163 order payment method is now changed if user selected different payment method in GoPay payment gate
  packages/framework/src/Migrations/Version20250819082815.php
  packages/framework/src/Model/GoPay/GoPayFacade.php
  packages/framework/src/Model/GoPay/OrderGoPayStatusUpdateCronModule.php
  packages/framework/src/Model/Order/Order.php
  packages/framework/src/Model/Order/OrderFacade.php
  packages/framework/src/Model/Payment/PaymentFacade.php
  packages/framework/src/Model/Payment/PaymentRepository.php
  packages/framework/src/Model/Payment/Service/PaymentServiceFacade.php
  packages/framework/src/Model/Payment/Transaction/PaymentTransaction.php
  packages/framework/src/Model/Payment/Transaction/PaymentTransactionData.php
  packages/framework/src/Model/Payment/Transaction/PaymentTransactionDataFactory.php
  packages/framework/tests/Unit/Model/Order/OrderFacadeHeurekaTest.php
  packages/frontend-api/src/Model/Mutation/Payment/PaymentMutation.php
  project-base/app/src/Model/Order/OrderFacade.php
  project-base/app/src/Model/Payment/PaymentFacade.php
  project-base/app/src/Model/Payment/PaymentRepository.php
  project-base/app/tests/FrontendApiBundle/Functional/Payment/GoPay/GoPayClient.php
  upgrade-notes/backend_20250819_102019.md
Labels: Enhancement

#4156 added utility for hiding scrollbars
  project-base/storefront/components/Basic/ModalGallery/ModalGalleryCarousel.tsx
  project-base/storefront/components/Blocks/Banners/BannersSlider.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreview.tsx
  project-base/storefront/components/Blocks/BlogPreview/BlogPreviewPlaceholder.tsx
  project-base/storefront/components/Blocks/Categories/PromotedCategoriesContent.tsx
  project-base/storefront/components/Blocks/Product/ProductsSlider.tsx
  project-base/storefront/components/Blocks/Product/ProductsSliderPlaceholder.tsx
  project-base/storefront/components/Blocks/Skeleton/SkeletonModuleProductSlider.tsx
  project-base/storefront/components/Blocks/UpsList/UpsList.tsx
  project-base/storefront/components/Layout/Header/Navigation/Navigation.tsx
  project-base/storefront/styles/utilities.css
  upgrade-notes/storefront_20250822_101415.md
Labels: Bug, Design & Appearance

#4178 remove references to admin bundle in framework tests
  packages/framework/tests/Unit/Form/DataTransformer/RolesGridDataTransformerTest.php
Labels: Bug

#4179 fixed text selection links
  project-base/storefront/components/Basic/ExtendedNextLink/ExtendedNextLink.tsx
  project-base/storefront/components/Blocks/Banners/BannersSlider.tsx
  project-base/storefront/components/Blocks/Product/ProductsList/ProductListItem.tsx
  project-base/storefront/components/Layout/Popup/Popup.tsx
  project-base/storefront/components/Pages/CategoryDetail/CategoryBestsellers/CategoryBestsellersListItem.tsx
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-2 category detail.png
  project-base/storefront/cypress/snapshots/e2e/visits/simpleVisitsWithScreenshots.cy.ts/5-0-3 stores page.png
  upgrade-notes/storefront_20250908_093634.md
Labels: Bug

#4182 Fix SF vulnerabilities
  project-base/storefront/package.json
  project-base/storefront/pnpm-lock.yaml
Labels: Security, dependencies

#4171 updated newsletter gtm
  project-base/storefront/components/Pages/Order/ContactInformation/FormBlocks/ContactInformationSendOrderButton.tsx
  project-base/storefront/gtm/types/objects.ts
  project-base/storefront/gtm/utils/getGtmUserInfo.ts
  project-base/storefront/utils/user/useCurrentUserContactInformation.ts
  upgrade-notes/storefront_20250903_105514.md
Labels: Bug

#4169 fixed pagination scroll + added pagination to complaints
  project-base/storefront/components/Blocks/Pagination/Pagination.tsx
  project-base/storefront/components/Pages/Customer/Complaints/ComplaintsContent.tsx
  project-base/storefront/components/Pages/Customer/OrderedItems/OrderedItemsContent.tsx
  project-base/storefront/components/Pages/Customer/Orders/OrdersContent.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintsQuery.generated.tsx
  project-base/storefront/graphql/requests/complaints/queries/ComplaintsQuery.graphql
  project-base/storefront/pages/customer/complaints.tsx
  project-base/storefront/pages/customer/new-complaint.tsx
  project-base/storefront/utils/complaints/useComplaintsData.ts
  upgrade-notes/storefront_20250902_094156.md
Labels: Bug, Enhancement

#4183 fixed makefile in project-base
  Makefile
  project-base/.gitlab-ci.yml
  project-base/Makefile
  project-base/app/scripts/check-licenses.sh
  project-base/app/symfony.lock
  project-base/storefront/cypress/docker/entrypoint.sh
  upgrade-notes/backend_20250909_112822.md
Labels: Bug

#4167 upgrade rabbitMQ version
  docker/conf/docker-compose-mac.yml.dist
  docker/conf/docker-compose.github-actions.cypress.yml.dist
  docker/conf/docker-compose.github-actions.review.yml.dist
  docker/conf/docker-compose.yml.dist
  project-base/docker/conf/docker-compose-mac.yml.dist
  project-base/docker/conf/docker-compose.yml.dist
  project-base/gitlab/docker-compose-ci.yml
  upgrade-notes/backend_20250831_215537.md
Labels: dependencies

#4154 updated styleguide colors
  Makefile
  project-base/Makefile
  project-base/storefront/components/Pages/ProductDetail/ProductDetailTabs/ProductDetailTabs.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideColors.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideContent.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideIcons.generated.tsx
  project-base/storefront/components/Pages/Styleguide/StyleguideIcons.tsx
  project-base/storefront/pages/styleguide.tsx
  upgrade-notes/storefront_20250821_131748.md
Labels: DX & Refactoring

#4158 added better accessibility for banner slider1
  project-base/storefront/components/Blocks/Banners/BannersDot.tsx
  project-base/storefront/components/Blocks/Banners/BannersSlider.tsx
  project-base/storefront/public/locales/cs/common.json
  project-base/storefront/public/locales/en/common.json
  project-base/storefront/public/locales/sk/common.json
  upgrade-notes/storefront_20250825_094755.md
Labels: Enhancement

#4177 updated transport and payment select for single option
  project-base/storefront/components/Basic/Animations/AnimateCollapseDiv.tsx
  project-base/storefront/components/Pages/Order/TransportAndPayment/TransportAndPaymentSelect/TransportAndPaymentSelect.tsx
  upgrade-notes/storefront_20250908_081304.md
Labels: Bug

#4189 updated scroll above heading in orders and complaints in customer layout
  project-base/storefront/components/Forms/validationRules.ts
  project-base/storefront/components/Layout/CustomerLayout.tsx
  project-base/storefront/components/Pages/Customer/Complaints/ComplaintsContent.tsx
  project-base/storefront/components/Pages/Customer/Orders/OrdersContent.tsx
  project-base/storefront/components/providers/PaginationProvider.tsx
  project-base/storefront/utils/ui/useScrollRestoration.ts
  upgrade-notes/storefront_20250912_063228.md
Labels: Bug

#4184 Add special article page (about) GTM type
  docs/storefront/gtm/objects.md
  project-base/storefront/gtm/enums/GtmPageType.ts
  project-base/storefront/gtm/types/objects.ts
  project-base/storefront/gtm/utils/getGtmPageInfoTypeForFriendlyUrl.ts
  project-base/storefront/gtm/utils/getSpecialArticleGtmTypes.ts
  project-base/storefront/vitest/gtm/specialArticleGtmTypes.test.ts
  upgrade-notes/storefront_20250909_142418.md
Labels: Enhancement

#4197 added check to ensure that upgrade notes include correct PR number and link
  .github/workflows/docker-build.yaml
Labels: DX & Refactoring

#4199 updated filled email in order after log
  project-base/storefront/utils/user/useCurrentUserContactInformation.ts
  upgrade-notes/storefront_20250925_105527.md
Labels: Bug

#4200 fixed not working elfinder with new route access
  packages/administration/src/Component/Security/AccessControl/RouteAccessControlDataProvider.php
Labels: Bug
